import Link from "next/link";
import { ArrowRight, BarChart3, Eye, Scale, ShieldCheck, Sparkles } from "lucide-react";
import { EvidenceLabel, MarketOverview, MarketTerminal } from "@/modules/market-intelligence/components";
import { PUBLIC_ORIGINS } from "@/core/config/public-origins";

export default function MarketPage() {
  const jsonLd={"@context":"https://schema.org","@type":"WebSite",name:"LAEX Market Intelligence",url:`${PUBLIC_ORIGINS.laex}/market`,description:"Plataforma pública de inteligencia y transparencia de mercado."};
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}} />
    <section className="mx-auto w-[min(100%-2rem,92rem)] pb-16 pt-16 lg:pb-24 lg:pt-24"><div className="grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><span className="laex-eyebrow">Market Intelligence · Acceso público</span><h1 className="laex-display mt-7 max-w-4xl text-[clamp(3.4rem,8vw,7.5rem)]">Comprende el mercado. <span className="text-cyan-200">Exige evidencia.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">Precios, liquidez, riesgo y análisis explicables en una experiencia que distingue hechos, evaluación independiente y promoción comercial.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#assets" className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-[#031014]">Explorar mercado</Link><Link href="/promote" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-bold text-slate-200">Promocionar mi token o producto</Link></div></div><div><div className="mb-4 flex flex-wrap gap-2"><EvidenceLabel kind="market"/><span className="rounded-full border border-amber-200/15 bg-amber-300/[.05] px-3 py-1.5 text-[10px] font-bold tracking-[.14em] text-amber-200">DATOS REALES · SOLO LECTURA</span></div><MarketTerminal initialSlug="bitcoin"/></div></div></section>

    <section className="border-y border-white/[.06] bg-black/10 py-7"><div className="mx-auto grid w-[min(100%-2rem,92rem)] gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Análisis independiente","La puntuación no se vende."],[Eye,"Transparencia visible","Fuentes, límites y conflictos."],[Scale,"Separación comercial","Promoción siempre identificada."],[Sparkles,"Inteligencia explicable","Cada señal muestra sus factores."]].map(([Icon,title,text])=><div key={String(title)} className="flex gap-3"><Icon className="mt-1 text-cyan-200" size={18}/><div><b className="text-sm">{String(title)}</b><p className="mt-1 text-sm leading-6 text-slate-400">{String(text)}</p></div></div>)}</div></section>

    <section id="assets" className="mx-auto w-[min(100%-2rem,92rem)] py-20"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="laex-eyebrow">Universo observado</span><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Activos y señales públicas</h2></div><p className="max-w-lg text-sm leading-6 text-slate-500">Identidad por assetId, red y contrato. Nunca solamente por símbolo.</p></div><MarketOverview/></section>

    <section className="mx-auto w-[min(100%-2rem,92rem)] pb-20"><div className="laex-surface-raised overflow-hidden rounded-[2rem] p-7 sm:p-10 lg:p-14"><div className="grid gap-9 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><EvidenceLabel kind="sponsored"/><h2 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-5xl">¿Quieres que tu token, empresa o producto forme parte de LAEX?</h2><p className="mt-6 max-w-3xl text-sm leading-7 text-slate-400 sm:text-base">Solicita una evaluación independiente, crea un perfil verificado o contrata una campaña promocional dentro del ecosistema. La contratación de servicios no garantiza una calificación favorable, una recomendación ni resultados comerciales.</p></div><div className="flex flex-col gap-3"><Link href="/promote" className="flex items-center justify-between rounded-xl bg-cyan-300 px-5 py-4 text-sm font-bold text-[#031014]">Solicitar evaluación <ArrowRight size={16}/></Link><Link href="/promote/packages" className="flex items-center justify-between rounded-xl border border-white/10 px-5 py-4 text-sm font-bold">Conocer los paquetes <ArrowRight size={16}/></Link></div></div></div></section>

    <section className="mx-auto grid w-[min(100%-2rem,92rem)] gap-5 pb-24 md:grid-cols-3">{[[BarChart3,"Datos del mercado","Precio, volumen y liquidez con fuente y actualización."],[ShieldCheck,"Análisis independiente","Puntuaciones explicables, limitaciones e historial."],[Scale,"Publicidad transparente","Patrocinador, periodo y naturaleza comercial visibles."]].map(([Icon,title,text])=><article key={String(title)} className="laex-card rounded-3xl p-6"><Icon size={20} className="text-cyan-200"/><h3 className="mt-5 text-lg font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{String(text)}</p></article>)}</section>
  </main>;
}
