import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import type { ChapterTwoState, ChapterTwoStore } from "../chapter-two/types";
import type { ActorContext, CompanyId } from "../domain/types";

export interface PaymentProviderEvent { eventId:string; paymentId:string; status:"authorized"|"paid"|"rejected"|"cancelled"|"refunded"; occurredAt:string }
export interface CommercePaymentProvider { readonly id:string; verify(rawBody:string,signature:string):PaymentProviderEvent }
export class DisabledCommercePaymentProvider implements CommercePaymentProvider { readonly id="disabled";verify():never{throw new Error("automatic_payment_provider_disabled")} }
export class HmacCommercePaymentProvider implements CommercePaymentProvider { constructor(readonly id:string,private readonly secret:string){}verify(rawBody:string,signature:string){const expected=createHmac("sha256",this.secret).update(rawBody).digest("hex"),left=Buffer.from(expected),right=Buffer.from(signature);if(left.length!==right.length||!timingSafeEqual(left,right))throw new Error("invalid_provider_signature");return JSON.parse(rawBody) as PaymentProviderEvent} }

export class CommercePaymentEngine {
  constructor(private readonly store:ChapterTwoStore,private readonly now=()=>new Date(),private readonly id=()=>randomUUID()){}
  private require(actor:ActorContext,capability:"commerce.order.manage"|"settings.manage"|"cash.operate"){if(!(actor.capabilities as readonly string[]).includes(capability))throw new Error(`capability_denied:${capability}`)}
  private audit(state:ChapterTwoState,actor:ActorContext,action:string,entityId:string){state.audit.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,userId:actor.userId,action,entityId,traceId:actor.traceId,at:this.now().toISOString()})}
  async configure(actor:ActorContext,input:{id?:string;name:string;kind:ChapterTwoState["commercePaymentMethods"][number]["kind"];currency?:string;instructions?:string[];destinationLabel?:string;destinationValue?:string;requiresManualVerification?:boolean;enabled?:boolean}){this.require(actor,"settings.manage");return this.store.transact(state=>{const now=this.now().toISOString(),record=state.commercePaymentMethods.find(item=>item.id===input.id&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId),value={id:record?.id??this.id(),tenantId:actor.tenantId,companyId:actor.companyId,name:input.name.trim(),kind:input.kind,currency:input.currency??"DOP",instructions:input.instructions??[],destinationLabel:input.destinationLabel,destinationValue:input.destinationValue,requiresManualVerification:input.requiresManualVerification??input.kind!=="cash",enabled:input.enabled??true,createdAt:record?.createdAt??now,updatedAt:now};if(!value.name)throw new Error("payment_method_name_required");if(record)Object.assign(record,value);else state.commercePaymentMethods.push(value);this.audit(state,actor,"commerce.payment-method.configured",value.id);return value})}
  async publicMethods(companyId:CompanyId){const state=await this.store.snapshot(),company=state.platformCompanies.find(item=>item.id===companyId);if(!company)return[];return state.commercePaymentMethods.filter(item=>item.tenantId===company.tenantId&&item.companyId===company.id&&item.enabled).map(({id,name,kind,currency,instructions,destinationLabel,destinationValue,requiresManualVerification})=>({id,name,kind,currency,instructions,destinationLabel,destinationValue,requiresManualVerification}))}
  async submit(companyId:CompanyId,key:string,input:{orderId:string;methodId:string;externalReference?:string;receiptReference?:string}){if(!key)throw new Error("idempotency_required");return this.store.transact(state=>{const order=state.commerceOrders.find(item=>item.id===input.orderId&&item.companyId===companyId),company=state.platformCompanies.find(item=>item.id===companyId),method=state.commercePaymentMethods.find(item=>item.id===input.methodId&&item.companyId===companyId&&item.enabled);if(!order||!company||!method)throw new Error("payment_context_not_found");if(order.termsConfirmationRequired||order.status==="pending")throw new Error("commercial_conditions_confirmation_required");if(method.kind==="bank-transfer"&&(!input.externalReference?.trim()||!input.receiptReference?.trim()))throw new Error("transfer_evidence_required");const scoped=`${company.tenantId}:${company.id}:payment:${key}`,prior=state.idempotency[scoped];if(prior)return prior;const payment={id:this.id(),tenantId:company.tenantId,companyId:company.id,orderId:order.id,methodId:method.id,amountMinor:order.totalMinor,currency:method.currency,status:"pending" as const,externalReference:input.externalReference?.trim(),receiptReference:input.receiptReference?.trim(),providerId:method.requiresManualVerification?"manual":"disabled",submittedAt:this.now().toISOString(),idempotencyKey:key};state.commercePayments.push(payment);state.idempotency[scoped]=payment;state.commerceOrderHistory.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,orderId:order.id,status:"payment-pending",at:payment.submittedAt,note:method.name});state.audit.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,userId:"commerce-public" as never,action:"commerce.payment.submitted",entityId:payment.id,traceId:key,at:payment.submittedAt});return payment})}
  async verifyManual(actor:ActorContext,paymentId:string){this.require(actor,"commerce.order.manage");this.require(actor,"cash.operate");return this.store.transact(state=>{const payment=state.commercePayments.find(item=>item.id===paymentId&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId),order=payment&&state.commerceOrders.find(item=>item.id===payment.orderId&&item.companyId===actor.companyId);if(!payment||!order||payment.status!=="pending")throw new Error("payment_not_verifiable");if(order.termsConfirmationRequired||order.status==="pending")throw new Error("commercial_conditions_confirmation_required");const cashSession=state.cashSessions.find(item=>item.companyId===actor.companyId&&item.status==="open");if(!cashSession)throw new Error("cash_session_required");const at=this.now().toISOString();for(const reservation of state.commerceReservations.filter(item=>item.orderId===order.id&&item.status==="active")){const warehouse=state.warehouses.find(item=>item.companyId===actor.companyId);if(!warehouse)throw new Error("warehouse_required");state.inventory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,warehouseId:warehouse.id,productId:reservation.productId,delta:-reservation.quantity,kind:"sale",sourceId:order.id,occurredAt:at,reason:"Pedido Commerce pagado",userId:actor.userId});reservation.status="consumed";}payment.status="paid";payment.verifiedAt=at;payment.verifiedBy=actor.userId;payment.reconciledAt=at;order.paymentStatus="paid";order.status=order.lines.some(line=>line.deliverySnapshot?.mode==="on-order")?"to-acquire":"preparing";order.updatedAt=at;state.cashOperations.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,cashSessionId:cashSession.id,userId:actor.userId,kind:"sale",amountMinor:payment.amountMinor,reason:`Pago Commerce ${order.publicId}`,at});state.commerceOrderHistory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status:"payment-confirmed",at,actorUserId:actor.userId},{id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status:order.status,at,actorUserId:actor.userId});this.audit(state,actor,"commerce.payment.verified",payment.id);return payment})}

  async track(companyId:CompanyId,input:{publicId:string;phone:string}){const state=await this.store.snapshot(),company=state.platformCompanies.find(item=>item.id===companyId),normalized=input.phone.replace(/\D/g,"");if(!company||normalized.length<7)throw new Error("tracking_context_invalid");const order=state.commerceOrders.find(item=>item.tenantId===company.tenantId&&item.companyId===company.id&&item.publicId.toLowerCase()===input.publicId.trim().toLowerCase()&&item.customer.phone.replace(/\D/g,"")===normalized);if(!order)throw new Error("order_not_found");return{publicId:order.publicId,status:order.status,paymentStatus:order.paymentStatus,fulfillment:order.fulfillment,updatedAt:order.updatedAt,lines:order.lines.map(line=>({name:line.publicName,quantity:line.quantity,delivery:line.deliverySnapshot?.estimatedDelivery})),history:state.commerceOrderHistory.filter(item=>item.tenantId===company.tenantId&&item.companyId===company.id&&item.orderId===order.id).sort((a,b)=>a.at.localeCompare(b.at)).map(({status,at,note})=>({status,at,note}))}}
  async applyProviderEvent(actor:ActorContext,provider:CommercePaymentProvider,rawBody:string,signature:string){this.require(actor,"commerce.order.manage");const event=provider.verify(rawBody,signature);return this.store.transact(state=>{const scoped=`${actor.tenantId}:${actor.companyId}:provider-event:${provider.id}:${event.eventId}`,prior=state.idempotency[scoped];if(prior)return prior;const payment=state.commercePayments.find(item=>item.id===event.paymentId&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId);if(!payment)throw new Error("payment_not_found");payment.status=event.status;payment.providerId=provider.id;payment.providerEventId=event.eventId;if(event.status==="paid"){payment.verifiedAt=event.occurredAt;const order=state.commerceOrders.find(item=>item.id===payment.orderId&&item.companyId===actor.companyId);if(order)order.paymentStatus="paid";}state.idempotency[scoped]=payment;this.audit(state,actor,`commerce.payment.${event.status}`,payment.id);return payment})}
}
