import { randomUUID } from "node:crypto";
import type { ChapterTwoState, ChapterTwoStore, CommerceDeliveryPolicy } from "../chapter-two/types";
import type { ActorContext, CompanyId } from "../domain/types";

export interface PaymentProvider { readonly id: string; authorize(): Promise<{ status: "pending" | "authorized" | "paid" | "failed" | "cancelled" | "refunded" }> }
export class DisabledPaymentProvider implements PaymentProvider { readonly id = "disabled"; async authorize() { return { status: "pending" as const }; } }

type PublishImage = { url:string; alt:string; order:number; assetReference?:string; checksum?:string; version?:number; purpose?:"carousel"|"card"|"detail"|"promotion"; tool?:string };
type PublishInput = { productId:string; publicName?:string; publicSku?:string; description?:string; category?:string; compatibility?:string[]; images?:PublishImage[]; features?:string[]; featured?:boolean; promotion?:{priceMinor:number;startsAt:string;endsAt?:string;active:boolean;title?:string;description?:string;eligibilityMode?:"manual";assetReference?:string}; deliveryPolicy?:Partial<CommerceDeliveryPolicy> };

const slugify = (value:string) => value.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const defaultPolicy = ():CommerceDeliveryPolicy => ({ mode:"in-stock", priceType:"fixed", paymentRequirement:"full", estimatedDelivery:"1–2 días" });
const promotionActive = (projection:ChapterTwoState["commerceProjections"][number], now:Date) => Boolean(projection.promotion?.active && new Date(projection.promotion.startsAt) <= now && (!projection.promotion.endsAt || new Date(projection.promotion.endsAt) >= now));
const effectivePrice = (projection:ChapterTwoState["commerceProjections"][number], now:Date) => promotionActive(projection,now) ? projection.promotion!.priceMinor : projection.publicPriceMinor;
const publicAvailability = (policy:CommerceDeliveryPolicy, available:number) => policy.mode === "on-order" ? "Por encargo" as const : policy.mode === "confirm-availability" ? "Consultar disponibilidad" as const : available <= 0 ? "Agotado" as const : available <= 2 ? "Pocas unidades" as const : "Disponible" as const;

export class CommerceEngine {
  constructor(private store:ChapterTwoStore, private now=()=>new Date(), private id=()=>randomUUID(), private media?:{imagesFor(actor:ActorContext,productId:string):Promise<PublishImage[]>}) {}
  private require(actor:ActorContext, capability:string) { if (!(actor.capabilities as readonly string[]).includes(capability)) throw new Error(`capability_denied:${capability}`); }
  private audit(state:ChapterTwoState, actor:ActorContext, action:string, entityId:string) { state.audit.push({ id:this.id(), tenantId:actor.tenantId, companyId:actor.companyId, userId:actor.userId, action, entityId, traceId:actor.traceId, at:this.now().toISOString() }); }
  private policy(input?:Partial<CommerceDeliveryPolicy>, prior?:CommerceDeliveryPolicy) {
    const policy:CommerceDeliveryPolicy = { ...defaultPolicy(), ...prior, ...input };
    if (!(["in-stock","on-order","confirm-availability"] as string[]).includes(policy.mode)) throw new Error("invalid_delivery_mode");
    if (!(["fixed","tentative"] as string[]).includes(policy.priceType)) throw new Error("invalid_price_type");
    if (!(["full","deposit","confirmation"] as string[]).includes(policy.paymentRequirement)) throw new Error("invalid_payment_requirement");
    if (policy.mode === "on-order" && !policy.estimatedDelivery?.trim()) throw new Error("estimated_delivery_required");
    if (policy.priceType === "tentative" && (!policy.tentativePriceValidUntil || new Date(policy.tentativePriceValidUntil) <= this.now())) throw new Error("tentative_price_validity_required");
    if (policy.paymentRequirement === "deposit" && (!policy.depositPercent || policy.depositPercent <= 0 || policy.depositPercent >= 100)) throw new Error("invalid_deposit_percent");
    return policy;
  }

  async publish(actor:ActorContext, input:PublishInput) {
    this.require(actor, "commerce.publish");
    const automated = input.images === undefined && this.media ? await this.media.imagesFor(actor, input.productId) : undefined;
    return this.store.transact(state => {
      const product = state.products.find(item => item.id === input.productId && item.tenantId === actor.tenantId && item.companyId === actor.companyId);
      if (!product) throw new Error("product_not_found");
      if (!product.priceMinor || product.priceMinor < 0) throw new Error("invalid_public_price");
      if (input.promotion && (input.promotion.priceMinor < 0 || input.promotion.priceMinor >= (product.publicPriceMinor ?? product.priceMinor) || (input.promotion.endsAt && new Date(input.promotion.endsAt) <= new Date(input.promotion.startsAt)))) throw new Error("invalid_promotion");
      let projection = state.commerceProjections.find(item => item.productId === product.id && item.tenantId === actor.tenantId && item.companyId === actor.companyId);
      const at = this.now().toISOString(), slug = projection?.slug ?? slugify(input.publicName ?? product.name);
      const images = input.images ?? (automated?.length ? automated : (product.mediaReference && product.imageUrl ? [{ url:product.imageUrl, alt:product.name, order:0, assetReference:product.mediaReference }] : []));
      if (state.commerceProjections.some(item => item.companyId === actor.companyId && item.slug === slug && item.productId !== product.id)) throw new Error("duplicate_slug");
      const promotion = input.promotion ? { ...input.promotion, basePriceMinor:product.publicPriceMinor ?? product.priceMinor, createdAt:at } : projection?.promotion;
      const deliveryPolicy = this.policy(input.deliveryPolicy, projection?.deliveryPolicy);
      const value:ChapterTwoState["commerceProjections"][number] = { id:projection?.id ?? this.id(), tenantId:actor.tenantId, companyId:actor.companyId, productId:product.id, slug, publicName:input.publicName ?? product.name, publicModel:product.model, publicSku:input.publicSku ?? product.sku, publicDescription:input.description ?? product.description ?? "", commercialCategory:input.category ?? product.category ?? "Productos", compatibility:input.compatibility ?? projection?.compatibility ?? [], images, publicPriceMinor:product.publicPriceMinor ?? product.priceMinor, promotion, deliveryPolicy, features:input.features ?? projection?.features ?? [], featured:input.featured ?? projection?.featured ?? false, publicationStatus:"published", seo:{ title:input.publicName ?? product.name, description:input.description ?? product.description ?? "" }, version:(projection?.version ?? 0)+1, synchronizedAt:at };
      if (projection) Object.assign(projection, value); else { state.commerceProjections.push(value); projection = value; }
      product.publishable = true; product.visibility = "visible";
      this.audit(state, actor, "commerce.product.published", projection.id);
      this.audit(state, actor, "commerce.delivery-policy.configured", projection.id);
      if (promotion) this.audit(state, actor, "commerce.promotion.published", projection.id);
      return projection;
    });
  }

  async unpublish(actor:ActorContext, productId:string) { this.require(actor, "commerce.publish"); return this.store.transact(state => { const projection=state.commerceProjections.find(item=>item.productId===productId&&item.companyId===actor.companyId),product=state.products.find(item=>item.id===productId&&item.companyId===actor.companyId); if(!projection||!product)throw new Error("publication_not_found");projection.publicationStatus="unpublished";projection.version++;projection.synchronizedAt=this.now().toISOString();product.publishable=false;product.visibility="hidden";this.audit(state,actor,"commerce.product.unpublished",projection.id);return projection; }); }

  async publicCatalog(companyId:CompanyId) {
    const state=await this.store.snapshot(),company=state.platformCompanies.find(item=>item.id===companyId);
    if(!company||!company.enabledModules.includes("commerce"))return{company:null,products:[]};
    const products=state.commerceProjections.filter(item=>item.companyId===companyId&&item.publicationStatus==="published").map(projection=>{const product=state.products.find(item=>item.id===projection.productId&&item.companyId===companyId)!,stock=state.inventory.filter(item=>item.companyId===companyId&&item.productId===product.id).reduce((sum,item)=>sum+item.delta,0),reserved=state.commerceReservations.filter(item=>item.companyId===companyId&&item.productId===product.id&&item.status==="active"&&new Date(item.expiresAt)>this.now()).reduce((sum,item)=>sum+item.quantity,0),available=Math.max(0,stock-reserved),deliveryPolicy=projection.deliveryPolicy??defaultPolicy();return{slug:projection.slug,name:projection.publicName,description:projection.publicDescription,category:projection.commercialCategory,images:projection.images.filter(image=>!image.hidden).sort((a,b)=>a.order-b.order),priceMinor:effectivePrice(projection,this.now()),promotion:projection.promotion,features:projection.features,featured:projection.featured,availability:publicAvailability(deliveryPolicy,available),availableQuantity:deliveryPolicy.mode==="in-stock"?available:undefined,deliveryPolicy};});
    return{company:{name:company.name,logoUrl:company.logoUrl,primaryColor:company.primaryColor,phone:company.phone,address:company.address},products};
  }

  async checkout(companyId:CompanyId, key:string, input:{lines:Array<{slug:string;quantity:number;clientPriceMinor?:number}>;customer:{name:string;phone:string;email?:string;address?:string};fulfillment:"pickup"|"local-delivery"|"shipping";notes?:string}) {
    if(!key)throw new Error("idempotency_required");
    return this.store.transact(state=>{const company=state.platformCompanies.find(item=>item.id===companyId&&item.enabledModules.includes("commerce"));if(!company)throw new Error("commerce_disabled");const scoped=`${company.tenantId}:${company.id}:commerce:${key}`,prior=state.idempotency[scoped];if(prior)return prior;if(!input.customer.name.trim()||!input.customer.phone.trim()||!input.lines.length)throw new Error("invalid_checkout");const orderId=this.id(),at=this.now().toISOString();
      const lines=input.lines.map(line=>{if(!Number.isInteger(line.quantity)||line.quantity<=0)throw new Error("invalid_quantity");const projection=state.commerceProjections.find(item=>item.companyId===companyId&&item.slug===line.slug&&item.publicationStatus==="published"),product=projection&&state.products.find(item=>item.id===projection.productId&&item.companyId===companyId);if(!projection||!product)throw new Error("product_not_available");const policy=projection.deliveryPolicy??defaultPolicy(),price=effectivePrice(projection,this.now());if(policy.priceType==="tentative"&&policy.tentativePriceValidUntil&&new Date(policy.tentativePriceValidUntil)<this.now())throw new Error("tentative_price_expired");if(line.clientPriceMinor!==undefined&&line.clientPriceMinor!==price)throw new Error("price_manipulation_rejected");if(policy.mode==="in-stock"){const stock=state.inventory.filter(item=>item.companyId===companyId&&item.productId===product.id).reduce((sum,item)=>sum+item.delta,0),reserved=state.commerceReservations.filter(item=>item.companyId===companyId&&item.productId===product.id&&item.status==="active"&&new Date(item.expiresAt)>this.now()).reduce((sum,item)=>sum+item.quantity,0);if(stock-reserved<line.quantity)throw new Error("insufficient_availability");}const base=Math.round(price/(1+(product.taxRate??18)/100)),tax=price-base;return{productId:product.id,publicName:projection.publicName,quantity:line.quantity,unitPriceMinor:price,taxMinor:tax*line.quantity,totalMinor:price*line.quantity,deliverySnapshot:{...policy}};});
      const requiresConfirmation=lines.some(line=>line.deliverySnapshot.priceType==="tentative"||line.deliverySnapshot.mode==="confirm-availability"||line.deliverySnapshot.paymentRequirement==="confirmation"),total=lines.reduce((sum,line)=>sum+line.totalMinor,0),tax=lines.reduce((sum,line)=>sum+line.taxMinor,0),status=requiresConfirmation?"pending" as const:"reserved" as const;
      const order:ChapterTwoState["commerceOrders"][number]={id:orderId,publicId:`WEB-${orderId.slice(0,8).toUpperCase()}`,tenantId:company.tenantId,companyId:company.id,channel:"WEB",status,customer:input.customer,fulfillment:input.fulfillment,notes:input.notes,lines,subtotalMinor:total-tax,taxMinor:tax,totalMinor:total,paymentStatus:"pending",termsConfirmationRequired:requiresConfirmation,idempotencyKey:key,createdAt:at,updatedAt:at};state.commerceOrders.push(order);state.commerceOrderHistory.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,orderId:order.id,status,at,note:requiresConfirmation?"Condiciones comerciales pendientes":"Reserva creada"});
      if(status==="reserved")for(const line of lines.filter(item=>item.deliverySnapshot.mode==="in-stock"))state.commerceReservations.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,productId:line.productId,orderId,quantity:line.quantity,status:"active",createdAt:at,expiresAt:new Date(this.now().getTime()+15*60_000).toISOString()});
      state.idempotency[scoped]=order;state.audit.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,userId:"commerce-public" as never,action:requiresConfirmation?"commerce.order.conditions-requested":"commerce.order.reserved",entityId:order.id,traceId:key,at});return order;});
  }

  async approveConditions(actor:ActorContext, orderId:string) { this.require(actor,"commerce.order.manage");return this.store.transact(state=>{const order=state.commerceOrders.find(item=>item.id===orderId&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId);if(!order||order.status!=="pending"||!order.termsConfirmationRequired)throw new Error("conditions_not_approvable");const at=this.now().toISOString();order.conditionsConfirmedAt=at;order.termsConfirmationRequired=false;order.status="reserved";order.updatedAt=at;for(const line of order.lines){line.priceConfirmedAt=at;if(line.deliverySnapshot?.mode==="in-stock")state.commerceReservations.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,productId:line.productId,orderId:order.id,quantity:line.quantity,status:"active",createdAt:at,expiresAt:new Date(this.now().getTime()+15*60_000).toISOString()});}state.commerceOrderHistory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status:"conditions-confirmed",at,actorUserId:actor.userId});this.audit(state,actor,"commerce.order.conditions-approved",order.id);return order;}); }

  async confirm(actor:ActorContext, orderId:string) { this.require(actor,"commerce.order.manage");return this.store.transact(state=>{const order=state.commerceOrders.find(item=>item.id===orderId&&item.companyId===actor.companyId);if(!order||order.status!=="reserved")throw new Error(order?.status==="pending"?"conditions_confirmation_required":"order_not_confirmable");const reservations=state.commerceReservations.filter(item=>item.orderId===order.id&&item.status==="active");for(const reservation of reservations){const warehouse=state.warehouses.find(item=>item.companyId===actor.companyId);if(!warehouse)throw new Error("warehouse_required");state.inventory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,warehouseId:warehouse.id,productId:reservation.productId,delta:-reservation.quantity,kind:"sale",sourceId:order.id,occurredAt:this.now().toISOString(),reason:"Pedido WEB confirmado",userId:actor.userId});reservation.status="consumed";}const at=this.now().toISOString();order.status="confirmed";order.updatedAt=at;state.commerceOrderHistory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status:"confirmed",at,actorUserId:actor.userId});this.audit(state,actor,"commerce.order.confirmed",order.id);return order;}); }

  async transition(actor:ActorContext, orderId:string, status:"to-acquire"|"received"|"preparing"|"ready"|"delivered") { this.require(actor,"commerce.order.manage");const allowed:Record<string,string[]>={confirmed:["to-acquire","preparing"],"to-acquire":["received"],received:["preparing"],preparing:["ready"],ready:["delivered"]};return this.store.transact(state=>{const order=state.commerceOrders.find(item=>item.id===orderId&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId);if(!order||!allowed[order.status]?.includes(status))throw new Error("invalid_order_transition");const at=this.now().toISOString();order.status=status;order.updatedAt=at;state.commerceOrderHistory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status,at,actorUserId:actor.userId});this.audit(state,actor,`commerce.order.${status}`,order.id);return order;}); }

  async cancel(actor:ActorContext, orderId:string) { this.require(actor,"commerce.order.manage");return this.store.transact(state=>{const order=state.commerceOrders.find(item=>item.id===orderId&&item.companyId===actor.companyId);if(!order||!["reserved","pending"].includes(order.status))throw new Error("order_not_cancellable");for(const reservation of state.commerceReservations.filter(item=>item.orderId===order.id&&item.status==="active"))reservation.status="released";const at=this.now().toISOString();order.status="cancelled";order.updatedAt=at;state.commerceOrderHistory.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,orderId:order.id,status:"cancelled",at,actorUserId:actor.userId});this.audit(state,actor,"commerce.order.cancelled",order.id);return order;}); }
}
