interface MarketChartProps { points: number[]; positive?: boolean; }

export default function MarketChart({ points, positive = true }: MarketChartProps) {
  const width = 800, height = 240, max = Math.max(...points, 1), min = Math.min(...points, 0), span = Math.max(max - min, 1);
  const line = points.map((point, index) => `${(index/(points.length-1))*width},${height-((point-min)/span)*(height-24)-12}`).join(" ");
  const area = `0,${height} ${line} ${width},${height}`;
  const color = positive ? "#37d8ee" : "#fb7185";
  return <div className="relative overflow-hidden rounded-3xl border border-white/[.08] bg-[#07101b]/90 p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-[.2em] text-slate-500">Precio · Volumen sincronizado</span><p className="mt-1 text-xs text-amber-200">Datos simulados · sin ejecución de operaciones</p></div><div className="flex gap-1">{["1D","7D","1M","3M","1A"].map((range,i)=><span key={range} className={`rounded-lg px-3 py-1.5 text-[11px] font-bold ${i===1?"bg-cyan-300/10 text-cyan-200":"text-slate-600"}`}>{range}</span>)}</div></div><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label="Gráfica de mercado simulada"><defs><linearGradient id="marketArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient><pattern id="grid" width="80" height="48" patternUnits="userSpaceOnUse"><path d="M 80 0 L 0 0 0 48" fill="none" stroke="rgba(148,163,184,.10)" strokeWidth="1"/></pattern></defs><rect width={width} height={height} fill="url(#grid)"/><polygon points={area} fill="url(#marketArea)"/><polyline points={line} fill="none" stroke={color} strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><div className="mt-3 grid h-12 grid-cols-12 items-end gap-1" aria-label="Volumen simulado">{points.slice(0,12).map((point,index)=><span key={index} className="rounded-t bg-cyan-300/20" style={{height:`${Math.max(15,(point/max)*100)}%`}} />)}</div></div>;
}
