"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { Bot,CheckCircle2,ExternalLink,Layers3,Search,Sparkles,Users } from "lucide-react";
import type { KnowledgeItem } from "../domain/types";
import { filterKnowledge } from "../application/search";
const kinds=[{id:"all",label:"Todo"},{id:"question",label:"Preguntas"},{id:"synthesis",label:"Síntesis"},{id:"signal",label:"Señales"},{id:"resource",label:"Recursos"}];
export function CommunityRadar({items}:{items:KnowledgeItem[]}){const[query,setQuery]=useState("");const[kind,setKind]=useState("all");const results=useMemo(()=>filterKnowledge(items,query,kind),[items,query,kind]);return <>
 <div className="mt-8 flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Buscar conocimiento</span><Search className="absolute left-5 top-1/2 -translate-y-1/2 text-cyan-300" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tema, activo, proyecto o pregunta" className="w-full rounded-2xl border border-cyan-300/20 bg-black/30 py-4 pl-13 pr-5 text-[15px] text-white placeholder:text-slate-400 focus:border-cyan-300/60 focus:outline-none"/></label><div className="scrollbar-hide flex gap-2 overflow-auto">{kinds.map(k=><button key={k.id} onClick={()=>setKind(k.id)} aria-pressed={kind===k.id} className={`shrink-0 rounded-full border px-4 py-2.5 text-[13px] font-semibold ${kind===k.id?"border-cyan-300/50 bg-cyan-300/10 text-cyan-100":"border-white/10 text-slate-300"}`}>{k.label}</button>)}</div></div>
 <div className="mt-5 flex justify-between text-[13px] text-slate-400"><span>{results.length} núcleos de conocimiento</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300"/>IA organizando</span></div>
 <section className="mt-5 grid gap-5 lg:grid-cols-2" aria-live="polite">{results.map(item=><article key={item.id} className="laex-card rounded-3xl p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><span className="flex items-center gap-2 text-[12px] font-bold uppercase tracking-[.16em] text-cyan-200">{item.status==="verified"?<CheckCircle2 size={14}/>:<Bot size={14}/>} {item.status==="verified"?"Verificado":item.status==="open"?"Pregunta abierta":"Organizado por IA"}</span><span className="text-[12px] text-slate-400">{item.ai.confidence}% confianza</span></div><h2 className="mt-5 text-2xl font-semibold tracking-[-.035em]">{item.title}</h2><p className="mt-3 text-[15px] leading-7 text-slate-300">{item.summary}</p><div className="mt-5 rounded-2xl border border-violet-300/10 bg-violet-300/[.04] p-4"><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.17em] text-violet-200"><Sparkles size={13}/> Síntesis IA</p><p className="mt-2 text-[14px] leading-6 text-slate-300">{item.ai.summary}</p></div><div className="mt-5 flex flex-wrap gap-2">{item.entities.map(e=><Link key={`${e.type}-${e.id}`} href={e.href} className="rounded-full border border-white/10 px-3 py-1.5 text-[12px] text-slate-300 hover:border-cyan-300/30 hover:text-white">{e.label} <ExternalLink className="ml-1 inline" size={10}/></Link>)}</div><div className="mt-6 flex flex-wrap items-center gap-4 border-t border-white/[.07] pt-5 text-[12px] text-slate-400"><span className="flex items-center gap-1.5"><Users size={13}/>{item.contributors} aportes</span><span className="flex items-center gap-1.5"><Layers3 size={13}/>{item.ai.duplicates} duplicados agrupados</span><span>{item.evidence.length} evidencias</span></div></article>)}</section>
 </>}
