import { NextResponse } from "next/server";
import { z } from "zod";
import { getBusinessRuntime } from "@/modules/business-engine/server/runtime";
import { checkExperienceAvailability, submitExperienceReservation } from "@/modules/company-experience/engine";

const reservationSchema = z.object({ catalogItemSlug: z.string().min(1).max(100), startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), name: z.string().min(2).max(100), phone: z.string().min(7).max(30), notes: z.string().max(500).optional() }).strict();
const availabilitySchema = z.object({ startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), passengers: z.coerce.number().int().min(1).max(100).optional() });
const errorResponse = (error: unknown) => { const message = error instanceof Error ? error.message : "invalid_request"; const status = message.includes("not_found") ? 404 : message === "vehicle_unavailable_for_dates" ? 409 : 400; return NextResponse.json({ error: message }, { status }); };
export async function GET(request: Request, { params }: { params: Promise<{ company: string }> }) { try { const url = new URL(request.url), query = availabilitySchema.parse(Object.fromEntries(url.searchParams)); return NextResponse.json(await checkExperienceAvailability(getBusinessRuntime().store, (await params).company, query)); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request, { params }: { params: Promise<{ company: string }> }) { try { const payload = reservationSchema.parse(await request.json()), key = request.headers.get("idempotency-key") ?? ""; const result = await submitExperienceReservation(getBusinessRuntime().store, (await params).company, key, payload); return NextResponse.json(result, { status: 201 }); } catch (error) { return errorResponse(error); } }