"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft,CheckCircle2,ExternalLink,LoaderCircle,ShieldCheck,XCircle } from "lucide-react";

type Status={provider:string;connected:boolean;configured?:boolean;expiresAt?:string;scopes:string[];canvaUserId?:string;updatedAt?:string};
export default function CanvaConnectionPage(){const[status,setStatus]=useState<Status|null>(null);const[error,setError]=useState(false);useEffect(()=>{fetch('/api/integrations/canva/status',{cache:'no-store'}).then(response=>response.json()).then(setStatus).catch(()=>setError(true));},[]);return <main className="min-h-screen bg-[#02060b] px-5 py-16 text-white"><section className="mx-auto max-w-2xl"><Link href="/configuracion" className="inline-flex items-center gap-2 text-xs text-slate-400 hover:text-white"><ArrowLeft size={14}/> Configuración</Link><div className="mt-8 overflow-hidden rounded-[2rem] border border-white/10 bg-[#07111b] shadow-[0_30px_100px_rgba(0,0,0,.45)]"><div className="border-b border-white/10 p-7 sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 text-black"><ShieldCheck/></span><p className="mt-6 text-[10px] font-black uppercase tracking-[.22em] text-cyan-300">Composición comercial</p><h1 className="mt-2 text-3xl font-black">Canva Connect</h1><p className="mt-3 text-sm leading-6 text-slate-400">Conexión OAuth segura entre Canva Negocios y LAEX. Esta fase no carga activos ni genera diseños.</p></div><div className="p-7 sm:p-9">{!status&&!error?<div className="flex items-center gap-3 text-sm text-slate-400"><LoaderCircle className="animate-spin"/> Verificando conexión…</div>:error?<State icon={XCircle} tone="text-rose-300" title="No se pudo consultar" body="Revisa que el servidor LAEX esté disponible."/>:status?.connected?<><State icon={CheckCircle2} tone="text-emerald-300" title="Conectado" body="Los tokens están cifrados y almacenados exclusivamente en el servidor."/><dl className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-5 text-xs sm:grid-cols-2"><Info label="Proveedor" value="Canva"/><Info label="Usuario" value={status.canvaUserId??"Verificado"}/><Info label="Expira" value={status.expiresAt?new Date(status.expiresAt).toLocaleString('es'):"Renovación automática"}/><Info label="Permisos" value={`${status.scopes.length} scopes autorizados`}/></dl></>:<><State icon={XCircle} tone="text-amber-300" title={status?.configured===false?"Configuración pendiente":"No conectado"} body={status?.configured===false?"Faltan variables server-side de Canva.":"Autoriza a LAEX desde la pantalla oficial de Canva."}/><a href="/api/integrations/canva/authorize?returnTo=/configuracion/canva" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-xs font-black text-black transition hover:bg-cyan-200">Conectar con Canva <ExternalLink size={15}/></a></>}</div></div></section></main>}
function State({icon:Icon,tone,title,body}:{icon:typeof CheckCircle2;tone:string;title:string;body:string}){return <div className="flex gap-4"><Icon className={tone}/><div><h2 className="font-black">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{body}</p></div></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 break-all font-bold text-slate-200">{value}</dd></div>}
