import { randomUUID } from "node:crypto";
import type { ActorContext, Capability, UserId } from "../domain/types";
import type { ChapterTwoStore } from "../chapter-two/types";
import type { BusinessIdentity } from "../server/BusinessIdentity";
import { ROLE_POLICIES, type BusinessRoleName } from "./RolePolicy";

export class ChapterFiveService {
  constructor(private readonly store: ChapterTwoStore, private readonly identity: BusinessIdentity, private readonly now: () => Date = () => new Date(), private readonly id: () => string = randomUUID, private readonly media?:{associate(actor:ActorContext,productId:string):Promise<unknown>}) {}
  private require(actor: ActorContext, capability: Capability) { if (!actor.capabilities.includes(capability)) throw new Error(`capability_denied:${capability}`); }
  private audit(state: Awaited<ReturnType<ChapterTwoStore["snapshot"]>>, actor: ActorContext, action: string, entityId: string) { state.audit.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, action, entityId, traceId: actor.traceId, at: this.now().toISOString() }); }

  async overview(actor: ActorContext) {
    const state = await this.store.snapshot(), own = <T extends { companyId: string }>(items: T[]) => items.filter(i => i.companyId === actor.companyId);
    return { company: state.platformCompanies.find(c=>c.id===actor.companyId), actor: { userId: actor.userId, capabilities: actor.capabilities }, users: own(state.memberships).map(m => ({ ...m, user: state.users.find(u => u.id === m.userId), role: state.roles.find(r => r.id === m.roleId) })), roles: own(state.roles), sessions: own(state.businessSessions), cashSessions: own(state.cashSessions), cashOperations: own(state.cashOperations), branches: own(state.branches), warehouses: own(state.warehouses), products: own(state.products).map(product=>actor.capabilities.includes("product.cost.read")?product:({...product,costMinor:undefined})), backups: state.backupRecords.filter(b=>b.companyId===actor.companyId), support: own(state.supportGrants) };
  }
  async createProduct(actor: ActorContext, input: { sku: string; barcode?: string; name: string; description?: string; category?: string; brand?: string; model?: string; costMinor?: number; priceMinor: number; taxRate?: number; taxIncluded?: boolean; unit?: string; minimumStock?: number; supplierId?: string; imageUrl?: string }) {
    this.require(actor, "product.manage"); const product=await this.store.transact(state => { const normalized=input.name.trim().toLowerCase(); if(state.products.some(p=>p.companyId===actor.companyId&&(p.sku.toLowerCase()===input.sku.toLowerCase()||(input.barcode&&p.barcode===input.barcode)||p.name.trim().toLowerCase()===normalized))) throw new Error("duplicate_product"); const created={ id:this.id(), tenantId:actor.tenantId, companyId:actor.companyId, sku:input.sku.trim(), barcode:input.barcode?.trim(), name:input.name.trim(), priceMinor:input.priceMinor, description:input.description, category:input.category, brand:input.brand, model:input.model, costMinor:input.costMinor, taxRate:input.taxRate??18, taxIncluded:input.taxIncluded??true, unit:input.unit??"unidad", minimumStock:input.minimumStock??0, supplierId:input.supplierId, imageUrl:input.imageUrl, status:"active" as const, publishable:false, visibility:"hidden" as const, commerceStatus:"available" as const, publicPriceMinor:input.priceMinor }; state.products.push(created); this.audit(state,actor,"product.created",created.id); return created; });
    if(this.media)await this.media.associate(actor,product.id);
    return (await this.store.snapshot()).products.find(item=>item.id===product.id&&item.companyId===actor.companyId)??product;
  }
  async updateProduct(actor: ActorContext, input: { productId: string; changes: Record<string, unknown> }) { this.require(actor,"product.manage"); return this.store.transact(state=>{const p=state.products.find(x=>x.id===input.productId&&x.companyId===actor.companyId);if(!p)throw new Error("product_not_found"); const allowed=["sku","barcode","name","description","category","brand","model","costMinor","priceMinor","taxRate","taxIncluded","unit","minimumStock","supplierId","imageUrl","status","publishable","visibility","commerceStatus","publicPriceMinor","mediaReference"]; for(const key of allowed)if(key in input.changes)(p as unknown as Record<string,unknown>)[key]=input.changes[key];this.audit(state,actor,"product.updated",p.id);return p;}); }
  async bulkReceive(actor:ActorContext,input:{warehouseId:string;confirmMissing:boolean;rows:Array<{sku:string;barcode?:string;name:string;quantity:number;costMinor:number;priceMinor:number;description?:string;category?:string;brand?:string;model?:string}>}){
    this.require(actor,"inventory.receive");
    if(!input.rows.length)throw new Error("bulk_rows_required");
    const snapshot=await this.store.snapshot(),warehouse=snapshot.warehouses.find(item=>item.id===input.warehouseId&&item.tenantId===actor.tenantId&&item.companyId===actor.companyId);
    if(!warehouse)throw new Error("access_denied");
    const missing=input.rows.filter(row=>!snapshot.products.some(p=>p.companyId===actor.companyId&&(p.sku.toLowerCase()===row.sku.toLowerCase()||(row.barcode&&p.barcode===row.barcode)||p.name.trim().toLowerCase()===row.name.trim().toLowerCase())));
    if(missing.length&&!input.confirmMissing)return{requiresConfirmation:true,missing};
    if(missing.length)this.require(actor,"product.manage");
    const result=await this.store.transact(state=>{const movements=[],createdProductIds:string[]=[];for(const row of input.rows){if(!row.sku.trim()||!row.name.trim()||!Number.isInteger(row.quantity)||row.quantity<0||row.costMinor<0||row.priceMinor<0)throw new Error("invalid_bulk_row");let product=state.products.find(p=>p.companyId===actor.companyId&&(p.sku.toLowerCase()===row.sku.toLowerCase()||(row.barcode&&p.barcode===row.barcode)||p.name.trim().toLowerCase()===row.name.trim().toLowerCase()));if(!product){product={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,sku:row.sku.trim(),barcode:row.barcode?.trim(),name:row.name.trim(),description:row.description?.trim(),category:row.category?.trim(),brand:row.brand?.trim(),model:row.model?.trim(),priceMinor:row.priceMinor,costMinor:row.costMinor,taxRate:18,taxIncluded:true,unit:"unidad",status:"active",publishable:false,visibility:"hidden",commerceStatus:"available",publicPriceMinor:row.priceMinor};state.products.push(product);createdProductIds.push(product.id);}const movement={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,warehouseId:warehouse.id,productId:product.id,delta:row.quantity,kind:"purchase" as const,sourceId:`bulk:${this.id()}`,occurredAt:this.now().toISOString(),reason:"Entrada masiva autorizada",unitCostMinor:row.costMinor,userId:actor.userId};state.inventory.push(movement);movements.push(movement);}this.audit(state,actor,"inventory.bulk_received",movements[0]?.sourceId??this.id());return{requiresConfirmation:false as const,movements,createdProductIds};});
    if(this.media)for(const productId of result.createdProductIds)await this.media.associate(actor,productId);
    return result;
  }
  async createSupplier(actor:ActorContext,input:{name:string;taxId?:string;phone?:string;email?:string;address?:string}){this.require(actor,"supplier.manage");return this.store.transact(state=>{const duplicate=state.suppliers.find(s=>s.companyId===actor.companyId&&(s.name.trim().toLowerCase()===input.name.trim().toLowerCase()||(input.taxId&&s.taxId===input.taxId)));if(duplicate)return duplicate;const supplier={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,...input,status:"active" as const};state.suppliers.push(supplier);this.audit(state,actor,"supplier.created",supplier.id);return supplier;});}
  async updateCompany(actor:ActorContext,input:Record<string,unknown>){this.require(actor,"settings.manage");return this.store.transact(state=>{const company=state.platformCompanies.find(c=>c.id===actor.companyId);if(!company)throw new Error("company_not_found");for(const key of ["name","legalName","taxId","address","phone","email","currency","timezone","primaryColor","logoUrl","printFormat","enabledModules"])if(key in input)(company as unknown as Record<string,unknown>)[key]=input[key];this.audit(state,actor,"company.updated",company.id);return company;});}
  async createLocation(actor:ActorContext,input:{branchName:string;branchAddress?:string;warehouseName:string}){this.require(actor,"settings.manage");return this.store.transact(state=>{const branch={id:`branch-${this.id()}`,tenantId:actor.tenantId,companyId:actor.companyId,name:input.branchName,address:input.branchAddress,status:"active" as const},warehouse={id:`warehouse-${this.id()}` as never,tenantId:actor.tenantId,companyId:actor.companyId,branchId:branch.id,name:input.warehouseName,status:"active" as const};state.branches.push(branch);state.warehouses.push(warehouse);this.audit(state,actor,"location.created",branch.id);return{branch,warehouse};});}
  async advanceWorkshop(actor:ActorContext,input:{workOrderId:string;status:"pending_diagnosis"|"pending_authorization"|"authorized"|"repairing"|"quality_control"|"completed";diagnosis?:string}){this.require(actor,input.status==="quality_control"?"workshop.supervise":"workshop.complete");return this.store.transact(state=>{const order=state.workOrders.find(w=>w.id===input.workOrderId&&w.companyId===actor.companyId);if(!order)throw new Error("work_order_not_found");order.status=input.status;if(input.diagnosis)order.diagnosis=input.diagnosis;if(input.status==="authorized")order.authorizedAt=this.now().toISOString();if(input.status==="quality_control")order.qualityControlAt=this.now().toISOString();this.audit(state,actor,"workshop.status_changed",order.id);return order;});}
  async adjustInventory(actor: ActorContext,input:{productId:string;warehouseId:string;quantityDelta:number;reason:string}){this.require(actor,"inventory.adjust");if(!input.quantityDelta||!input.reason.trim())throw new Error("invalid_adjustment");return this.store.transact(state=>{const p=state.products.find(x=>x.id===input.productId&&x.companyId===actor.companyId);const w=state.warehouses.find(x=>x.id===input.warehouseId&&x.companyId===actor.companyId);if(!p||!w)throw new Error("access_denied");const movement={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,warehouseId:w.id,productId:p.id,delta:input.quantityDelta,kind:"purchase" as const,sourceId:`adjustment:${this.id()}`};state.inventory.push(movement);this.audit(state,actor,"inventory.adjusted",movement.id);return movement;});}
  async createCustomer(actor:ActorContext,input:{name:string;phone?:string;email?:string;taxId?:string;address?:string;creditLimitMinor?:number}){this.require(actor,"customer.create");return this.store.transact(state=>{const norm=input.name.trim().toLowerCase(),phone=input.phone?.replace(/\D/g,"");const duplicate=state.customers.find(c=>c.companyId===actor.companyId&&(c.normalizedName===norm||(phone&&c.phone?.replace(/\D/g,"")===phone)||(input.taxId&&c.taxId===input.taxId)));if(duplicate)return duplicate;const c={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,name:input.name.trim(),phone:input.phone,email:input.email,taxId:input.taxId,address:input.address,creditLimitMinor:input.creditLimitMinor??0,balanceMinor:0,status:"active" as const,normalizedName:norm};state.customers.push(c);this.audit(state,actor,"customer.created",c.id);return c;});}
  async updateCustomer(actor:ActorContext,input:{customerId:string;changes:{name?:string;phone?:string;email?:string;taxId?:string;address?:string;status?:"active"|"disabled"}}){this.require(actor,"customer.update");return this.store.transact(state=>{const customer=state.customers.find(item=>item.id===input.customerId&&item.companyId===actor.companyId);if(!customer)throw new Error("customer_not_found");const name=input.changes.name?.trim()??customer.name,phone=input.changes.phone?.replace(/\D/g,"");const duplicate=state.customers.find(item=>item.id!==customer.id&&item.companyId===actor.companyId&&(item.normalizedName===name.toLowerCase()||(phone&&item.phone?.replace(/\D/g,"")===phone)||(input.changes.taxId&&item.taxId===input.changes.taxId)));if(duplicate)throw new Error("duplicate_customer");Object.assign(customer,input.changes,{name,normalizedName:name.toLowerCase()});this.audit(state,actor,"customer.updated",customer.id);return customer})}
  async createUser(actor:ActorContext,input:{name:string;email:string;password:string;roleName:BusinessRoleName;branchIds?:string[]}){this.require(actor,"user.manage");const state=await this.store.snapshot();let role=state.roles.find(r=>r.companyId===actor.companyId&&r.name===input.roleName);if(!role){role={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,name:input.roleName,capabilities:ROLE_POLICIES[input.roleName],system:true,status:"active"};await this.store.transact(s=>s.roles.push(role!));}await this.identity.provisionAccount({email:input.email,password:input.password,tenantId:actor.tenantId,companyId:actor.companyId,capabilities:role.capabilities,name:input.name,roleId:role.id,branchIds:input.branchIds});return {created:true,email:input.email,role:input.roleName};}
  async updateMembership(actor:ActorContext,input:{userId:UserId;status?:"active"|"disabled";roleName?:BusinessRoleName;branchIds?:string[]}){this.require(actor,"user.manage");return this.store.transact(state=>{const m=state.memberships.find(x=>x.companyId===actor.companyId&&x.userId===input.userId);if(!m)throw new Error("membership_not_found");if(input.status)m.status=input.status;if(input.roleName){const role=state.roles.find(r=>r.companyId===actor.companyId&&r.name===input.roleName);if(!role)throw new Error("role_not_found");m.roleId=role.id;m.capabilities=role.capabilities;}if(input.branchIds)m.branchIds=input.branchIds;this.audit(state,actor,"membership.updated",input.userId);return m;});}
  async revokeSession(actor:ActorContext,sessionId:string){this.require(actor,"user.manage");return this.identity.revokeSession(sessionId,actor.companyId,actor.userId,"company_administrator");}
  async openCash(actor:ActorContext,input:{branchId:string;openingMinor:number}){this.require(actor,"cash.open");return this.store.transact(state=>{if(state.cashSessions.some(s=>s.companyId===actor.companyId&&s.userId===actor.userId&&s.status==="open"))throw new Error("cash_session_already_open");const s={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,branchId:input.branchId,userId:actor.userId,openedAt:this.now().toISOString(),openingMinor:input.openingMinor,status:"open" as const};state.cashSessions.push(s);this.audit(state,actor,"cash.opened",s.id);return s;});}
  async cashOperation(actor:ActorContext,input:{cashSessionId:string;kind:"entry"|"withdrawal"|"refund";amountMinor:number;reason:string}){this.require(actor,"cash.operate");return this.store.transact(state=>{const s=state.cashSessions.find(x=>x.id===input.cashSessionId&&x.companyId===actor.companyId&&x.status==="open");if(!s||s.userId!==actor.userId)throw new Error("cash_session_not_available");const op={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,cashSessionId:s.id,userId:actor.userId,kind:input.kind,amountMinor:input.amountMinor,reason:input.reason,at:this.now().toISOString()};state.cashOperations.push(op);this.audit(state,actor,`cash.${input.kind}`,op.id);return op;});}
  async closeCash(actor:ActorContext,input:{cashSessionId:string;countedMinor:number;supervisorUserId?:UserId}){this.require(actor,"cash.close");return this.store.transact(state=>{const s=state.cashSessions.find(x=>x.id===input.cashSessionId&&x.companyId===actor.companyId&&x.status==="open");if(!s)throw new Error("cash_session_not_available");const ops=state.cashOperations.filter(o=>o.cashSessionId===s.id).reduce((n,o)=>n+(o.kind==="withdrawal"||o.kind==="refund"?-o.amountMinor:o.amountMinor),0);s.expectedMinor=s.openingMinor+ops;s.countedMinor=input.countedMinor;s.differenceMinor=input.countedMinor-s.expectedMinor;s.closedAt=this.now().toISOString();s.status="closed";s.supervisorUserId=input.supervisorUserId;this.audit(state,actor,"cash.closed",s.id);return s;});}
  async updateOnboarding(actor:ActorContext,input:{step:string;values:Record<string,unknown>}){this.require(actor,"settings.manage");return this.store.transact(state=>{const company=state.platformCompanies.find(c=>c.id===actor.companyId);if(!company)throw new Error("company_not_found");const record=company as unknown as Record<string,unknown>,allowed=["name","legalName","taxId","address","phone","whatsapp","email","currency","timezone","logoUrl","operatingStartDate","printFormat"];for(const key of allowed)if(key in input.values)record[key]=input.values[key];if(input.step==="fiscal")record.fiscalStatus=input.values.taxId?"configured":"pending";record.dgiiIntegrationStatus="disabled";const onboarding=(record.onboarding??{currentStep:"identity",completedSteps:[]}) as {currentStep:string;completedSteps:string[];completedAt?:string};if(!onboarding.completedSteps.includes(input.step))onboarding.completedSteps.push(input.step);onboarding.currentStep=String(input.values.nextStep??input.step);record.onboarding=onboarding;this.audit(state,actor,"onboarding.step.completed",`${company.id}:${input.step}`);return{company,onboarding}})}
  async openingInventory(actor:ActorContext,input:{productId:string;warehouseId:string;quantity:number;unitCostMinor?:number;cutoffDate:string;reason:string;reference:string}){this.require(actor,"inventory.adjust");if(!Number.isInteger(input.quantity)||input.quantity<0||!input.cutoffDate||!input.reason.trim()||!input.reference.trim())throw new Error("invalid_opening_inventory");return this.store.transact(state=>{const product=state.products.find(p=>p.id===input.productId&&p.companyId===actor.companyId),warehouse=state.warehouses.find(w=>w.id===input.warehouseId&&w.companyId===actor.companyId);if(!product||!warehouse)throw new Error("access_denied");if(state.inventory.some(m=>m.companyId===actor.companyId&&m.productId===product.id&&m.warehouseId===warehouse.id))throw new Error("opening_inventory_already_declared");const movement={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,warehouseId:warehouse.id,productId:product.id,delta:input.quantity,kind:"purchase" as const,sourceId:`opening:${input.reference}`,occurredAt:new Date(`${input.cutoffDate}T00:00:00.000Z`).toISOString(),reason:input.reason,reference:input.reference,unitCostMinor:input.unitCostMinor,userId:actor.userId};state.inventory.push(movement);this.audit(state,actor,"inventory.opening.recorded",movement.id);return movement})}
}
