import type { Capability } from "../domain/types";

export const ROLE_POLICIES = {
  Propietario: ["dashboard.view","customer.read","customer.create","customer.update","customer.credit","inventory.read","inventory.receive","inventory.adjust","product.manage","product.cost.read","supplier.manage","purchase.receive","purchase.manage","quote.convert","invoice.read","invoice.void","invoice.return","pos.sell","pos.discount","pos.discount.override","cash.open","cash.operate","cash.close","cash.read","workorder.create","workshop.read","workshop.complete","workshop.supervise","audit.read","assistant.use","user.manage","role.manage","settings.manage","branch.select","backup.manage","report.sales","report.inventory","report.expenses","report.fiscal.prepare","expense.read","expense.create","fiscal.profile.read","fiscal.profile.manage","fiscal.document.read","fiscal.document.prepare","fiscal.sequence.manage","fiscal.reconcile","commerce.read","commerce.publish","commerce.order.manage"],
  Administrador: ["dashboard.view","customer.read","customer.create","customer.update","inventory.read","inventory.receive","inventory.adjust","product.manage","product.cost.read","supplier.manage","purchase.receive","purchase.manage","quote.convert","invoice.read","invoice.void","invoice.return","pos.sell","pos.discount","pos.discount.override","cash.open","cash.operate","cash.close","cash.read","workorder.create","workshop.read","workshop.complete","workshop.supervise","audit.read","assistant.use","user.manage","role.manage","settings.manage","branch.select","report.sales","report.inventory","report.expenses","expense.read","expense.create","fiscal.profile.read","fiscal.profile.manage","fiscal.document.read","fiscal.document.prepare","fiscal.sequence.manage","fiscal.reconcile"],
  Supervisor: ["dashboard.view","customer.read","customer.create","customer.update","inventory.read","inventory.receive","product.cost.read","purchase.receive","quote.convert","invoice.read","invoice.void","invoice.return","pos.sell","pos.discount","pos.discount.override","cash.open","cash.operate","cash.close","cash.read","workorder.create","workshop.read","workshop.complete","workshop.supervise","audit.read","assistant.use","branch.select"],
  Cajero: ["dashboard.view","customer.read","customer.create","pos.sell","pos.discount","cash.open","cash.operate","cash.close","cash.read","invoice.read"],
  Ventas: ["dashboard.view","customer.read","customer.create","customer.update","inventory.read","quote.convert","invoice.read","pos.sell","pos.discount","assistant.use"],
  Inventario: ["dashboard.view","inventory.read","inventory.receive","inventory.adjust","product.manage","product.cost.read","supplier.manage","purchase.receive","purchase.manage","audit.read","assistant.use","branch.select"],
  Compras: ["dashboard.view","inventory.read","inventory.receive","product.cost.read","supplier.manage","purchase.receive","purchase.manage","audit.read","branch.select"],
  Taller: ["dashboard.view","customer.read","customer.create","inventory.read","workorder.create","workshop.read","workshop.complete","assistant.use","branch.select"],
  Contabilidad: ["dashboard.view","customer.read","customer.credit","purchase.manage","invoice.read","cash.read","audit.read","report.sales","report.inventory","report.expenses","report.fiscal.prepare","expense.read","expense.create","assistant.use","fiscal.profile.read","fiscal.document.read","fiscal.document.prepare","fiscal.reconcile"],
  Consulta: ["dashboard.view","customer.read","inventory.read","invoice.read","workshop.read"],
  Auditor: ["dashboard.view","customer.read","inventory.read","invoice.read","cash.read","workshop.read","audit.read","report.sales","report.inventory","report.expenses","expense.read"],
} as const satisfies Record<string, readonly Capability[]>;

export type BusinessRoleName = keyof typeof ROLE_POLICIES;
export const roleCapabilities = (name: BusinessRoleName): readonly Capability[] => ROLE_POLICIES[name];
export const hasCapability = (capabilities: readonly Capability[], required: Capability) => capabilities.includes(required);
