import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { can, type WorkspaceRole } from "@/modules/media-intelligence/domain/permissions";
import type { MediaProductState, ProductWorkspace } from "@/modules/media-intelligence/domain/product";
import { updateLocalProductState } from "@/modules/media-intelligence/infrastructure/local/LocalProductStore";
import { requireControlledDevelopmentActor } from "@/modules/media-intelligence/server/controlled-session";
export const runtime = "nodejs";
const unavailable = () => NextResponse.json({ error: "not_available" }, { status: 404 });
function auth(workspace: ProductWorkspace, userId: string, capability: Parameters<typeof can>[1]) { const member = workspace.members.find((item)=>item.id===userId&&item.status==="active"); if(!member) throw new Error("workspace_access_denied"); const override=member.overrides[capability]; if(override===false||(override!==true&&!can(member.role,capability))) throw new Error("capability_denied"); return member; }
function log(workspace: ProductWorkspace, actorId: string, action: string, resource: string, detail?: string) { workspace.audit.unshift({id:randomUUID(),workspaceId:workspace.id,actorId,action,resource,outcome:"success",at:new Date().toISOString(),detail}); }
function fail(error: unknown) { const code=error instanceof Error?error.message:"operation_failed"; return NextResponse.json({error:code},{status:code==="revision_conflict"?409:code.endsWith("denied")?403:400}); }
export async function POST(request: NextRequest) {
  if(process.env.NODE_ENV!=="development") return unavailable();
  try { const actor=await requireControlledDevelopmentActor(); const body=await request.json() as {revision:number;workspaceId:string;action:string;payload?:Record<string,unknown>}; const next=await updateLocalProductState(body.revision,(state:MediaProductState)=>{
    const workspace=state.workspaces.find((item)=>item.id===body.workspaceId); if(!workspace) throw new Error("workspace_access_denied"); const payload=body.payload??{};
    if(body.action==="member.invite"){auth(workspace,actor.userId,"members.invite");const email=String(payload.email??"").trim().toLowerCase();if(!email.includes("@"))throw new Error("invalid_email");workspace.invitations.push({id:`inv_${randomUUID()}`,email,role:String(payload.role??"viewer") as Exclude<WorkspaceRole,"owner">,status:"pending",expiresAt:new Date(Date.now()+604800000).toISOString()});log(workspace,actor.userId,"member.invited",email);return;}
    if(body.action.startsWith("invitation.")){auth(workspace,actor.userId,"members.manage");const invitation=workspace.invitations.find((item)=>item.id===payload.id);if(!invitation)throw new Error("invitation_not_found");const target=body.action.split(".")[1];if(target==="accept"){if(new Date(invitation.expiresAt)<=new Date())throw new Error("invitation_expired");invitation.status="accepted";workspace.members.push({id:`sim_${randomUUID()}`,name:invitation.email.split("@")[0],email:invitation.email,role:invitation.role,status:"active",overrides:{}});}else invitation.status=target==="reject"?"revoked":"revoked";log(workspace,actor.userId,body.action,invitation.email);return;}
    if(body.action.startsWith("member.")){auth(workspace,actor.userId,"members.manage");const member=workspace.members.find((item)=>item.id===payload.id);if(!member)throw new Error("member_not_found");const operation=body.action.split(".")[1];if(member.role==="owner"&&operation!=="transfer")throw new Error("last_owner_required");if(operation==="suspend")member.status="suspended";if(operation==="reactivate")member.status="active";if(operation==="override")member.overrides[String(payload.capability) as keyof typeof member.overrides]=Boolean(payload.value);if(operation==="transfer"){const current=workspace.members.find((item)=>item.id===actor.userId);if(!current||current.role!=="owner"||member.status!=="active")throw new Error("ownership_transfer_denied");current.role="admin";member.role="owner";}log(workspace,actor.userId,body.action,member.id);return;}
    if(body.action==="content.edit"){auth(workspace,actor.userId,"content.edit");const content=workspace.contents.find((item)=>item.id===payload.id);if(!content)throw new Error("content_not_found");const previous=content.versions.at(-1);content.title=String(payload.title??content.title);content.versions.push({number:(previous?.number??0)+1,title:content.title,body:String(payload.body??previous?.body??""),author:actor.name,createdAt:new Date().toISOString(),note:String(payload.note??"Edición")});content.approvedVersion=null;content.status="draft";content.updatedAt=new Date().toISOString();log(workspace,actor.userId,"content.versioned",content.id);return;}
    if(body.action==="content.generate"){auth(workspace,actor.userId,"content.edit");const content=workspace.contents.find((item)=>item.id===payload.id);if(!content)throw new Error("content_not_found");const scenario=String(payload.scenario??"success");if(scenario==="error"||scenario==="timeout"){content.status="generation_error";content.risks=[scenario==="timeout"?"La simulación agotó el tiempo de espera":"La simulación devolvió un error explícito"]; }else{content.status="generated";content.confidence=scenario==="low"?42:scenario==="partial"?61:91;content.risks=scenario==="partial"?["Resultado parcial: faltan formatos"]:scenario==="low"?["Confianza baja: requiere revisión"]:[];}content.updatedAt=new Date().toISOString();log(workspace,actor.userId,`simulation.${scenario}`,content.id);return;}
    if(body.action==="campaign.create"){auth(workspace,actor.userId,"campaign.manage");const title=String(payload.title??"").trim();if(!title)throw new Error("invalid_title");workspace.campaigns.unshift({id:`campaign_${randomUUID()}`,title,objective:String(payload.objective??"Alcance"),audience:String(payload.audience??workspace.audience),contentIds:Array.isArray(payload.contentIds)?payload.contentIds.map(String):[],platforms:["instagram"],status:"draft",scheduledAt:null,publicationStatus:"idle",idempotencyKey:null});log(workspace,actor.userId,"campaign.created",title);return;}
    if(body.action.startsWith("campaign.")){auth(workspace,actor.userId,"campaign.manage");const campaign=workspace.campaigns.find((item)=>item.id===payload.id);if(!campaign)throw new Error("campaign_not_found");const operation=body.action.split(".")[1];if(operation==="approve")campaign.status="approved";if(operation==="reject")campaign.status="rejected";if(operation==="archive")campaign.status="archived";if(operation==="recover")campaign.status="draft";if(operation==="schedule"){if(campaign.status!=="approved")throw new Error("approval_required");campaign.status="scheduled";campaign.scheduledAt=String(payload.at??new Date(Date.now()+86400000).toISOString());}if(operation==="publish"){if(campaign.status!=="scheduled")throw new Error("schedule_required");const key=String(payload.key??campaign.id);if(campaign.idempotencyKey!==key){campaign.idempotencyKey=key;campaign.publicationStatus=String(payload.scenario??"success") as typeof campaign.publicationStatus;}}if(operation==="duplicate"){workspace.campaigns.unshift({...campaign,id:`campaign_${randomUUID()}`,title:`${campaign.title} · Copia`,status:"draft",scheduledAt:null,publicationStatus:"idle",idempotencyKey:null});}log(workspace,actor.userId,body.action,campaign.id);return;}
    throw new Error("unsupported_action");
  }); return NextResponse.json(next); } catch(error){return fail(error);}
}
