"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import type { PublicCompanyExperienceDTO, VehicleOperationalStatus } from "../types";

type Availability = { slug: string; available: boolean; operationalStatus: VehicleOperationalStatus; statusLabel: string };
const labels: Record<VehicleOperationalStatus, string> = { available: "Disponible", reserved: "Reservado", rented: "Alquilado", maintenance: "No disponible · Mantenimiento" };
export function AvailabilityExplorer({ company, catalog }: { company: string; catalog: PublicCompanyExperienceDTO["catalog"] }) {
  const [dates, setDates] = useState<{ startDate: string; endDate: string; passengers: string } | null>(null), [results, setResults] = useState<Availability[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget), query = { startDate: String(form.get("startDate")), endDate: String(form.get("endDate")), passengers: String(form.get("passengers")) }; const response = await fetch(`/api/company-experience/${company}/reservations?${new URLSearchParams(query)}`); const body = await response.json(); if (response.ok) { setDates(query); setResults(body.vehicles); } else setError(body.error === "invalid_reservation_dates" ? "Revisa el período seleccionado." : "No pudimos consultar disponibilidad."); setBusy(false); }
  const visible = useMemo(() => { const allowed = dates ? new Set(results.map((item) => item.slug)) : null; return catalog.filter((item) => !allowed || allowed.has(item.slug)).slice().sort((a, b) => Number(results.find((item) => item.slug === b.slug)?.available) - Number(results.find((item) => item.slug === a.slug)?.available)); }, [catalog, dates, results]);
  return <><form className="ce-search" onSubmit={search}><div><span className="ce-eyebrow">DISPONIBILIDAD DEMO</span><h3>¿Cuándo quieres viajar?</h3></div><label>Fecha de recogida<input name="startDate" type="date" required /></label><label>Fecha de devolución<input name="endDate" type="date" required /></label><label>Pasajeros<select name="passengers" defaultValue="1"><option value="1">1 pasajero</option><option value="2">2 pasajeros</option><option value="5">5 pasajeros</option><option value="8">8 pasajeros</option><option value="18">18 pasajeros</option></select></label><button disabled={busy}>{busy ? "BUSCANDO…" : "BUSCAR"}</button>{error && <p role="alert">{error}</p>}</form>{dates && <p className="ce-search-summary">Resultados demo para {dates.startDate} → {dates.endDate}. La reserva se valida nuevamente en el servidor.</p>}<div className="ce-grid">{visible.map((item) => { const result = results.find((candidate) => candidate.slug === item.slug), available = result?.available ?? item.operationalStatus === "available", label = dates ? available ? "Disponible para tus fechas" : "No disponible para esas fechas" : labels[item.operationalStatus ?? "available"], href = `/empresas/${company}/catalogo/${item.slug}${dates ? `?startDate=${dates.startDate}&endDate=${dates.endDate}` : ""}`; return <article className="ce-card" key={item.id}><Link href={href} className="ce-card-image"><Image src={item.image} alt={item.imageAlt} fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw" /></Link><div className="ce-card-body"><div className="ce-card-meta"><span>{item.year}</span><span>{item.passengers} pasajeros</span><span>{item.transmission}</span></div><span className={`ce-availability ${available ? "is-available" : "is-unavailable"}`}>{label}</span><h3>{item.name}</h3><p>{item.summary}</p><strong>{item.priceLabel}</strong><Link className="ce-card-link" href={href}>{available ? "VER FICHA Y RESERVAR →" : "VER FICHA →"}</Link></div></article>; })}</div></>;
}