import type { Capability } from "../domain/types";
import type { AssistantToolName } from "../assistant/ConversationalProvider";

export type AgentName="LIA"|"ALAN"|"ETHAN";export type ToolRisk="read"|"prepare"|"operational"|"financial-fiscal"|"critical";
export type ToolDefinition={name:AssistantToolName;agents:AgentName[];capability?:Capability;risk:ToolRisk;confirmation:"never"|"required"};
export const TOOL_REGISTRY:readonly ToolDefinition[]=[
{name:"customer.search",agents:["LIA"],capability:"customer.read",risk:"read",confirmation:"never"},{name:"customer.create",agents:["LIA"],capability:"customer.create",risk:"operational",confirmation:"required"},{name:"customer.update",agents:["LIA"],capability:"customer.update",risk:"operational",confirmation:"required"},{name:"reception.create",agents:["LIA"],capability:"workorder.create",risk:"operational",confirmation:"required"},{name:"product.create",agents:["LIA"],capability:"product.manage",risk:"operational",confirmation:"required"},{name:"catalog.bulk",agents:["LIA"],capability:"product.manage",risk:"operational",confirmation:"required"},{name:"inventory.read",agents:["LIA","ETHAN"],capability:"inventory.read",risk:"read",confirmation:"never"},{name:"inventory.move",agents:["LIA"],capability:"inventory.adjust",risk:"operational",confirmation:"required"},{name:"quote.prepare",agents:["LIA"],capability:"quote.convert",risk:"prepare",confirmation:"required"},{name:"invoice.read",agents:["LIA"],capability:"invoice.read",risk:"read",confirmation:"never"},{name:"cash.read",agents:["LIA","ETHAN"],capability:"cash.read",risk:"read",confirmation:"never"},{name:"workshop.read",agents:["ALAN"],capability:"workshop.read",risk:"read",confirmation:"never"},{name:"report.sales",agents:["LIA","ETHAN"],capability:"report.sales",risk:"read",confirmation:"never"},{name:"report.inventory",agents:["LIA","ETHAN"],capability:"report.inventory",risk:"read",confirmation:"never"},{name:"report.expenses",agents:["LIA","ETHAN"],capability:"report.expenses",risk:"read",confirmation:"never"},{name:"report.fiscal.prepare",agents:["LIA"],capability:"report.fiscal.prepare",risk:"financial-fiscal",confirmation:"required"},{name:"navigation.help",agents:["LIA","ALAN","ETHAN"],risk:"read",confirmation:"never"}];
export function toolsFor(agent:AgentName,capabilities:readonly Capability[]){return TOOL_REGISTRY.filter(tool=>tool.agents.includes(agent)&&(!tool.capability||capabilities.includes(tool.capability)||(tool.name==="workshop.read"&&capabilities.includes("workorder.create")))).map(tool=>tool.name)}
export function toolDefinition(name:AssistantToolName){return TOOL_REGISTRY.find(tool=>tool.name===name)}
