import { NextRequest,NextResponse } from "next/server";
import { CompanyResolver } from "@/modules/business-engine/platform/CompanyResolver";
import { BUSINESS_SESSION_COOKIE,getBusinessRuntime } from "@/modules/business-engine/server/runtime";
import { requireBusinessActor } from "@/modules/business-engine/server/BusinessRequestHandlers";
export const runtime="nodejs";
const local=(request:NextRequest)=>["localhost","127.0.0.1","::1"].includes(request.nextUrl.hostname);
export async function POST(request:NextRequest,{params}:{params:Promise<{company:string}>}){try{const runtime=getBusinessRuntime(),company=await new CompanyResolver(runtime.store).bySlugOrHost((await params).company),body=await request.json() as {email?:string;password?:string};const token=await runtime.businessIdentity.login(body.email??"",body.password??"",company.id),response=NextResponse.json({authenticated:true,company:{id:company.id,name:company.name,slug:company.slug,primaryColor:company.primaryColor}});response.cookies.set(BUSINESS_SESSION_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production"&&!local(request),sameSite:"strict",path:"/",maxAge:28800,priority:"high"});return response}catch{return NextResponse.json({error:"invalid_credentials"},{status:401})}}
export async function DELETE(request:NextRequest){await getBusinessRuntime().businessIdentity.logout(request.cookies.get(BUSINESS_SESSION_COOKIE)?.value);const response=NextResponse.json({authenticated:false});response.cookies.set(BUSINESS_SESSION_COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production"&&!local(request),expires:new Date(0),path:"/",sameSite:"strict"});return response}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{company:string}>}){try{const runtime=getBusinessRuntime(),company=await new CompanyResolver(runtime.store).bySlugOrHost((await params).company),actor=await requireBusinessActor(request,company.id),body=await request.json() as {currentPassword?:string;newPassword?:string};await runtime.businessIdentity.changePassword(actor,body.currentPassword??"",body.newPassword??"");const response=NextResponse.json({changed:true,reauthenticationRequired:true});response.cookies.set(BUSINESS_SESSION_COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production"&&!local(request),expires:new Date(0),path:"/",sameSite:"strict"});return response}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"password_change_failed"},{status:400})}}
export async function PUT(request:NextRequest,{params}:{params:Promise<{company:string}>}){try{const runtime=getBusinessRuntime(),company=await new CompanyResolver(runtime.store).bySlugOrHost((await params).company),body=await request.json() as {token?:string;newPassword?:string};return NextResponse.json(await runtime.businessIdentity.consumePasswordToken(company.id,body.token??"",body.newPassword??""))}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"activation_failed"},{status:400})}}
