import 'server-only';
import { z } from 'zod';

const jobSchema=z.object({job:z.object({id:z.string(),status:z.enum(['in_progress','success','failed']),error:z.object({code:z.string().optional(),message:z.string().optional()}).optional()}).passthrough()});
export type CanvaBrandTemplate={id:string;title:string};
export class CanvaApiClient{
  constructor(private readonly accessToken:string,private readonly request:typeof fetch=fetch){}
  async listBrandTemplates(){const data=await this.json('/brand-templates?limit=100');const raw=(data.items??data.brand_templates??[]) as Record<string,unknown>[];return raw.map(item=>({id:String(item.id??item.brand_template_id),title:String(item.title??item.name??'Sin título')})).filter(item=>item.id&&item.id!=='undefined');}
  async brandTemplateDataset(id:string){const data=await this.json(`/brand-templates/${encodeURIComponent(id)}/dataset`);return (data.dataset??{}) as Record<string,{type:string}>;}
  async uploadAsset(bytes:Uint8Array,name:string){const body=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const response=await this.call('/asset-uploads',{method:'POST',headers:{'content-type':'application/octet-stream','asset-upload-metadata':JSON.stringify({name_base64:Buffer.from(name).toString('base64')})},body});const created=jobSchema.parse(await response.json());const completed=await this.poll(`/asset-uploads/${created.job.id}`);const asset=(completed.job as Record<string,unknown>).asset as {id?:string}|undefined;if(!asset?.id)throw new Error('Canva no devolvió el Asset ID de la carga.');return{assetId:asset.id,jobId:created.job.id};}
  async createAutofill(templateId:string,data:Record<string,{type:'text';text:string}|{type:'image';asset_id:string}>){const response=await this.call('/autofills',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'create_from_brand_template',brand_template_id:templateId,data})});const created=jobSchema.parse(await response.json()),completed=await this.poll(`/autofills/${created.job.id}`),result=(completed.job as Record<string,unknown>).result as {design?:{id?:string}}|undefined;if(!result?.design?.id)throw new Error('Canva no devolvió el Design ID de Autofill.');return{designId:result.design.id,jobId:created.job.id};}
  async exportPng(designId:string){const response=await this.call('/exports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({design_id:designId,format:{type:'png',lossless:true,transparent_background:false}})});const created=jobSchema.parse(await response.json()),completed=await this.poll(`/exports/${created.job.id}`),urls=(completed.job as Record<string,unknown>).urls as string[]|undefined;if(!urls?.[0])throw new Error('Canva no devolvió una URL de exportación.');return{url:urls[0],jobId:created.job.id};}
  async downloadExport(value:string){const url=new URL(value);if(url.protocol!=='https:'||!(url.hostname==='canva.com'||url.hostname.endsWith('.canva.com')))throw new Error('Canva devolvió una URL de exportación no autorizada.');const response=await this.request(url,{headers:{accept:'image/png'},cache:'no-store',signal:AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`Descarga Canva falló (${response.status}).`);const type=(response.headers.get('content-type')??'').split(';')[0];if(type!=='image/png')throw new Error(`Canva devolvió ${type||'un tipo desconocido'} en lugar de PNG.`);return new Uint8Array(await response.arrayBuffer());}
  private async poll(path:string){for(let attempt=0;attempt<10;attempt++){const parsed=jobSchema.parse(await this.json(path));if(parsed.job.status==='success')return parsed;if(parsed.job.status==='failed')throw new Error(`Trabajo Canva falló: ${parsed.job.error?.code??'unknown'}.`);await new Promise(resolve=>setTimeout(resolve,Math.min(500*2**attempt,4000)));}throw new Error('Tiempo de espera agotado para el trabajo Canva.');}
  private async json(path:string){const response=await this.call(path,{method:'GET'});return await response.json() as Record<string,unknown>;}
  private async call(path:string,init:RequestInit){const response=await this.request(`https://api.canva.com/rest/v1${path}`,{...init,headers:{authorization:`Bearer ${this.accessToken}`,accept:'application/json',...init.headers},cache:'no-store',signal:AbortSignal.timeout(20_000)});if(!response.ok){const requestId=response.headers.get('x-request-id');throw new Error(`Canva API rechazó la solicitud (${response.status})${requestId?` [${requestId}]`:''}.`);}return response;}
}
