"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { BarChart3, Bot, Boxes, ClipboardList, FileText, History, Landmark, Store, LayoutDashboard, LogOut, PackagePlus, ReceiptText, ShieldCheck, ShoppingCart, MessageCircle, Settings, Users, WalletCards, Wrench } from "lucide-react";
import "./chapter-two-audit.css";
import { PosPanelFinal } from "./PosPanelFinal";
import { AssistantCenter } from "./AssistantCenter";
import { OperationsPanel } from "./OperationsPanel";
import { ReportsCenter } from "./ReportsCenter";
import { IdentitySecurityPanel } from "./IdentitySecurityPanel";
import { CustomerDirectory } from "./CustomerDirectory";
import { FiscalCenter } from "./FiscalCenter";
import { CommerceCenter } from "./CommerceCenter";
import { announceCommerceChange } from "@/modules/lf-printer/infrastructure/commerce-events";

type View = "dashboard" | "assistants" | "reports" | "fiscal" | "commerce" | "pos" | "customers" | "reception" | "workshop" | "inventory" | "purchases" | "quotes" | "invoices" | "cash" | "delivery" | "history" | "settings";
type State = {
  customers: Array<{ id: string; name: string; phone?: string }>;
  equipment: Array<{ id: string; customerId: string; brand: string; model: string; serial?: string; physicalStatus: string }>;
  workOrders: Array<{ id: string; equipmentId: string; status: string; diagnosis: string; invoiceId?: string }>;
  products: Array<{ id: string; sku: string; name: string; priceMinor: number }>;
  inventory: Array<{ id: string; productId: string; delta: number; kind: string; sourceId: string }>;
  suppliers: Array<{ id: string; name: string }>;
  purchases: Array<{ id: string; supplierId: string; status: string; totalMinor: number }>;
  quotes: Array<{ id: string; customerId: string; status: string; totalMinor: number; invoiceId: string }>;
  invoices: Array<{ id: string; customerId: string; sourceType: string; sourceId: string; totalMinor: number; paidMinor: number; status: string }>;
  payments: Array<{ id: string; invoiceId: string; amountMinor: number; method: string }>;
  cashMovements: Array<{ id: string; paymentId: string; amountMinor: number }>;
  history: Array<{ id: string; entityType: string; entityId: string; event: string; at: string }>;
  events: Array<{ id: string; name: string; aggregateId: string; occurredAt: string }>;
  audit: Array<{ id: string; action: string; entityId: string; at: string }>;
};

const emptyState: State = { customers: [], equipment: [], workOrders: [], products: [], inventory: [], suppliers: [], purchases: [], quotes: [], invoices: [], payments: [], cashMovements: [], history: [], events: [], audit: [] };
const navigation = [
  ["dashboard", "Dashboard", LayoutDashboard], ["assistants", "Centro de Asistentes", Bot], ["reports", "Reportes / Contabilidad", BarChart3], ["fiscal", "Centro Fiscal", Landmark], ["commerce", "Commerce / Tienda", Store], ["pos", "Punto de Venta", ShoppingCart], ["customers", "Clientes", Users], ["reception", "Recepción", ClipboardList], ["workshop", "Taller", Wrench], ["inventory", "Inventario", Boxes], ["purchases", "Compras", PackagePlus], ["quotes", "Cotización", FileText], ["invoices", "Factura", ReceiptText], ["cash", "Pago / Caja", WalletCards], ["delivery", "Entrega", ShoppingCart], ["history", "Historial", History], ["settings", "Configuración", Settings],
] as const;

const money = (value: number) => new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" }).format(value / 100);
const label = (value: string) => ({ closed: "Cerrada", completed: "Completada", delivered: "Entregado", paid: "Pagada", converted: "Convertida", received: "Recibida", purchase: "Entrada por compra", workshop: "Consumo en taller", cash: "Efectivo", transfer: "Transferencia" }[value] ?? value.replaceAll("_", " "));
const short = (id?: string) => id ? `LAEX-${id.slice(-6).toUpperCase()}` : "—";

export function BusinessWorkspace({ apiBase, companyName, companyLogoUrl, warehouseId, mode = "business", autoLogin, credentials, enabledModules, actor, loginUrl }: { apiBase: string; companyName: string; companyLogoUrl?: string; warehouseId: string; mode?: "business" | "laboratory"; autoLogin?: boolean; credentials?: { email: string; password: string }; enabledModules?: string[]; actor?: { name: string; role: string; capabilities: string[]; supportGrantId?: string }; loginUrl?: string }) {
  const [view, setView] = useState<View>("dashboard"); const [state, setState] = useState<State>(emptyState); const [busy, setBusy] = useState(true); const [notice, setNotice] = useState("Preparando empresa piloto…"); const [technical, setTechnical] = useState(false);
  const [reception, setReception] = useState({ customerName: "Juan Martínez", phone: "849-526-1212", brand: "Epson", model: "L3250", serial: "", diagnosis: "Servicio básico y sustitución de tinta", quantity: 1, service: 1500, paymentMethod: "cash" });
  const [purchase, setPurchase] = useState({ supplierName: "Distribuidora Epson Demo", quantity: 10, unitCost: 400 });
  const [quote, setQuote] = useState({ customerId: "", quantity: 2, paymentMethod: "transfer" });

  const request = useCallback(async (path: string, init?: RequestInit) => { const response = await fetch(path, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No fue posible completar la operación"); return data; }, []);
  const refresh = useCallback(async () => { const data = await request(apiBase); setState(data); setQuote((current) => ({ ...current, customerId: current.customerId || data.customers[0]?.id || "" })); }, [apiBase, request]);
  useEffect(() => { void (async () => { try { if (autoLogin && credentials) await request(`${apiBase}/session`, { method: "POST", body: JSON.stringify(credentials) }); await refresh(); setNotice(`${mode === "laboratory" ? "Sesión demo" : "Sesión empresarial"} activa · ${companyName}`); } catch (error) { setNotice(error instanceof Error ? error.message : "Error de acceso"); } finally { setBusy(false); } })(); }, [apiBase, autoLogin, companyName, credentials, mode, refresh, request]);

  const required:Record<View,string[]>={dashboard:["dashboard.view"],assistants:["assistant.use"],reports:["report.sales","report.inventory","report.expenses","report.fiscal.prepare"],fiscal:["fiscal.profile.read","fiscal.document.read"],commerce:["commerce.read","commerce.publish","settings.manage"],pos:["pos.sell"],customers:["customer.read","customer.create"],reception:["workorder.create"],workshop:["workshop.read","workshop.complete"],inventory:["inventory.read"],purchases:["purchase.receive","purchase.manage"],quotes:["quote.convert"],invoices:["invoice.read"],cash:["cash.read","cash.open"],delivery:["workshop.read"],history:["audit.read"],settings:["user.manage","settings.manage"]};
  const allowed=(id:View)=>!actor||required[id].some(cap=>actor.capabilities.includes(cap));
  const visibleNavigation = navigation.filter(([id]) => allowed(id) && (id === "dashboard" || id === "reports" || id === "fiscal" || id === "commerce" || !enabledModules?.length || enabledModules.includes(id)));
  const product = state.products[0]; const customerName = (id: string) => state.customers.find((item) => item.id === id)?.name ?? "Cliente"; const supplierName = (id: string) => state.suppliers.find((item) => item.id === id)?.name ?? "Proveedor"; const equipmentName = (id: string) => { const item = state.equipment.find((equipment) => equipment.id === id); return item ? `${item.brand} ${item.model}` : "Equipo"; };
  const stock = useMemo(() => state.inventory.reduce((total, movement) => total + movement.delta, 0), [state.inventory]);
  async function execute(action: string, input: unknown, success: string, next: View) { setBusy(true); try { await request(apiBase, { method: "POST", body: JSON.stringify({ action, idempotencyKey: crypto.randomUUID(), input }) }); await refresh(); if (["workshop", "purchase"].includes(action)) announceCommerceChange(apiBase.split("/").filter(Boolean).at(-1) ?? ""); setNotice(success); setView(next); } catch (error) { setNotice(error instanceof Error ? error.message : "Operación rechazada"); } finally { setBusy(false); } }
  function submitReception(event: FormEvent) { event.preventDefault(); if (!product) return; void execute("workshop", { customer: { name: reception.customerName, phone: reception.phone }, equipment: { type: "printer", brand: reception.brand, model: reception.model, serial: reception.serial || `AUD-${Date.now()}` }, diagnosis: reception.diagnosis, warehouseId, parts: [{ productId: product.id, quantity: reception.quantity }], serviceTotalMinor: Math.round(reception.service * 100), paymentMethod: reception.paymentMethod }, "Recepción procesada, facturada, pagada y entregada correctamente.", "workshop"); }
  function submitPurchase(event: FormEvent) { event.preventDefault(); if (!product) return; void execute("purchase", { supplierName: purchase.supplierName, warehouseId, lines: [{ productId: product.id, quantity: purchase.quantity, unitCostMinor: Math.round(purchase.unitCost * 100) }] }, "Compra recibida; el inventario fue actualizado.", "inventory"); }
  function submitQuote(event: FormEvent) { event.preventDefault(); if (!product || !quote.customerId) return; void execute("quote", { customerId: quote.customerId, lines: [{ productId: product.id, quantity: quote.quantity }], paymentMethod: quote.paymentMethod }, "Cotización convertida en factura y pagada.", "invoices"); }
  async function advanceWorkshop(workOrderId:string,status:string){setBusy(true);try{await request(`${apiBase}/operations`,{method:"POST",body:JSON.stringify({action:"workshop.advance",input:{workOrderId,status}})});await refresh();setNotice("Estado de taller actualizado y auditado.");}catch(error){setNotice(error instanceof Error?error.message:"Cambio rechazado");}finally{setBusy(false)}}
  async function logout(){if(!loginUrl||busy)return;setBusy(true);setNotice("Cerrando sesión empresarial…");try{const response=await fetch(`${apiBase}/session`,{method:"DELETE"});if(!response.ok)throw new Error("No fue posible cerrar la sesión");window.location.assign(loginUrl);}catch(error){setNotice(error instanceof Error?error.message:"No fue posible cerrar la sesión");setBusy(false)}}

  return <main className={`audit-shell ${allowed("assistants")?"":"assistants-hidden"}`}>
    <aside className="audit-sidebar"><div className="audit-brand"><span>LB</span><div><strong>LAEX Business</strong><small>{mode === "laboratory" ? "Laboratorio · Auditoría" : "Business Platform"}</small></div></div><nav aria-label="Módulos del Business Engine">{visibleNavigation.map(([id, name, Icon]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="audit-security"><ShieldCheck size={18}/><div><strong>Entorno seguro</strong><small>{companyName}</small></div></div></aside>
    <section className="audit-workspace">{actor?.supportGrantId&&<div className="support-banner"><ShieldCheck size={18}/><strong>Soporte LAEX activo</strong><span>Acceso temporal de diagnóstico. Acciones financieras y fiscales deshabilitadas.</span></div>}<header className="audit-topbar"><div><p>{mode === "laboratory" ? "Empresa piloto" : `${actor?.role??"Empresa activa"} · ${actor?.name??companyName}`}</p><h1>{visibleNavigation.find(([id]) => id === view)?.[1]}</h1></div><div className="audit-topbar-actions"><div className="audit-session"><span className={busy ? "pulse" : ""}/><div><strong>{busy ? "Procesando…" : "Operativo"}</strong><small>{notice}</small></div></div>{mode === "business" && loginUrl && <button className="audit-logout" type="button" onClick={() => void logout()} disabled={busy} aria-label={`Cerrar sesión de ${actor?.name ?? companyName}`}><LogOut size={17}/><span>Cerrar sesión</span></button>}</div></header>
      <div className="audit-content">
        {view === "assistants" && <AssistantCenter apiBase={apiBase} companyName={companyName} onBusinessChange={() => void refresh()}/>}
        {view === "reports" && <ReportsCenter apiBase={apiBase} capabilities={actor?.capabilities??[]}/>} 
        {view === "fiscal" && <FiscalCenter apiBase={apiBase} capabilities={actor?.capabilities??[]}/>} 
        {view === "commerce" && <CommerceCenter apiBase={apiBase} onBusinessChange={() => void refresh()}/>} 
        {view === "pos" && <PosPanelFinal apiBase={apiBase} companyName={companyName} companyLogoUrl={companyLogoUrl} warehouseId={warehouseId} actorName={actor?.name} capabilities={actor?.capabilities} onBusinessChange={() => void refresh()}/>} 
        {view === "dashboard" && <><div className="audit-hero"><div><span>Business Engine conectado</span><h2>La operación completa, en un solo lugar.</h2><p>Estado técnico: operativo. Estado comercial: se administra por separado desde LAEX Control Plane.</p></div><button onClick={() => setView("reception")}>Nueva recepción <ClipboardList size={18}/></button></div><section className="lia-dashboard-card"><div className="lia-dashboard-avatar"><Image src="/images/lia/lia-avatar-v1.png" alt="LIA, Asistente Administrativa Inteligente" width={78} height={78} priority/></div><div className="lia-dashboard-copy"><span>ASISTENTE ADMINISTRATIVA INTELIGENTE · PROVEEDOR LOCAL</span><h3>LIA trabaja contigo dentro de LAEX Business</h3><p>Interpreta solicitudes compatibles con herramientas autorizadas, pide confirmación para cambios y nunca escribe directamente en la base de datos.</p></div><button onClick={() => setView("assistants")}><MessageCircle size={18}/> Hablar con LIA</button></section><div className="metric-grid"><Metric title="Productos" value={state.products.length} note="Catálogo activo"/><Metric title="Unidades disponibles" value={stock} note="Suma de movimientos"/><Metric title="Taller pendiente" value={state.workOrders.filter(item => !["closed","completed"].includes(item.status)).length} note="Órdenes por atender"/><Metric title="Facturado" value={money(state.invoices.reduce((sum, item) => sum + item.totalMinor, 0))} note={`${state.invoices.length} documentos`}/></div><Panel title="Continuidad empresarial" subtitle="Cada etapa reutiliza la información anterior."><div className="flow-strip">{["Recepción","Cliente","Equipo","Taller","Inventario","Factura","Pago","Entrega","Historial"].map((item, index) => <div key={item}><span>{index + 1}</span><strong>{item}</strong></div>)}</div></Panel><Panel title="Actividad reciente" subtitle="Eventos publicados por el Business Engine."><EventList events={state.events.slice(-6).reverse()}/></Panel></>}
        {view === "customers" && <><OperationsPanel mode="customers" apiBase={apiBase} warehouseId={warehouseId} capabilities={actor?.capabilities??["customer.create"]} onChange={()=>void refresh()}/><CustomerDirectory apiBase={apiBase} canUpdate={actor?.capabilities.includes("customer.update")??false} onChange={()=>void refresh()}/></>}
        {view === "reception" && <div className="split-grid"><Panel title="Nueva recepción inteligente" subtitle="Una sola captura crea cliente, equipo, orden, factura, pago, entrega e historial."><form className="audit-form" onSubmit={submitReception}><Field label="Nombre del cliente"><input required value={reception.customerName} onChange={(e) => setReception({...reception, customerName:e.target.value})}/></Field><Field label="Teléfono"><input required value={reception.phone} onChange={(e) => setReception({...reception, phone:e.target.value})}/></Field><div className="form-row"><Field label="Marca"><input required value={reception.brand} onChange={(e) => setReception({...reception, brand:e.target.value})}/></Field><Field label="Modelo"><input required value={reception.model} onChange={(e) => setReception({...reception, model:e.target.value})}/></Field></div><Field label="Número de serie"><input placeholder="Se genera uno demo si queda vacío" value={reception.serial} onChange={(e) => setReception({...reception, serial:e.target.value})}/></Field><Field label="Diagnóstico / trabajo realizado"><textarea required value={reception.diagnosis} onChange={(e) => setReception({...reception, diagnosis:e.target.value})}/></Field><div className="form-row"><Field label={`${product?.name ?? "Producto"} · cantidad`}><input type="number" min="1" max={stock} value={reception.quantity} onChange={(e) => setReception({...reception, quantity:Number(e.target.value)})}/></Field><Field label="Servicio (RD$)"><input type="number" min="0" value={reception.service} onChange={(e) => setReception({...reception, service:Number(e.target.value)})}/></Field></div><Field label="Método de pago"><select value={reception.paymentMethod} onChange={(e) => setReception({...reception, paymentMethod:e.target.value})}><option value="cash">Efectivo</option><option value="transfer">Transferencia</option></select></Field><button className="primary-action" disabled={busy || !product}>Procesar recepción completa</button></form></Panel><Panel title="Resumen antes de confirmar" subtitle="El motor validará existencias y consistencia."><ReceiptSummary customer={reception.customerName} concept={`${reception.brand} ${reception.model}`} product={`${reception.quantity} × ${product?.name ?? "producto"}`} total={money((product?.priceMinor ?? 0) * reception.quantity + reception.service * 100)}/></Panel></div>}
        {view === "workshop" && <Panel title="Órdenes de taller" subtitle="Recepción → diagnóstico → autorización → reparación → control de calidad → factura → entrega."><DataTable headers={["Orden","Equipo","Diagnóstico","Estado","Factura","Gestionar"]} rows={state.workOrders.map((item) => [short(item.id), equipmentName(item.equipmentId), item.diagnosis, <Status key={item.id} value={item.status}/>, short(item.invoiceId), actor?.capabilities.some(cap=>cap==="workshop.complete"||cap==="workshop.supervise")?<select key={`${item.id}-stage`} value={item.status} onChange={e=>void advanceWorkshop(item.id,e.target.value)}><option value="pending_diagnosis">Diagnóstico</option><option value="pending_authorization">Esperando autorización</option><option value="authorized">Autorizada</option><option value="repairing">Reparación</option><option value="quality_control">Control de calidad</option><option value="completed">Completada</option></select>:"Sólo consulta"])} empty="No hay órdenes de trabajo."/></Panel>}
        {view === "inventory" && <><OperationsPanel mode="inventory" apiBase={apiBase} warehouseId={warehouseId} capabilities={actor?.capabilities??["product.manage","inventory.adjust"]} onChange={()=>void refresh()}/><div className="metric-grid compact"><Metric title={product?.name ?? "Producto"} value={stock} note={`SKU ${product?.sku ?? "—"}`}/><Metric title="Precio de venta" value={money(product?.priceMinor ?? 0)} note="Configuración empresarial"/><Metric title="Movimientos" value={state.inventory.length} note="Libro de existencias"/></div><Panel title="Movimientos de inventario" subtitle="La existencia nunca se modifica directamente."><DataTable headers={["Movimiento","Producto","Tipo","Cantidad","Origen"]} rows={state.inventory.slice().reverse().map((item) => [short(item.id), state.products.find((p) => p.id === item.productId)?.name ?? "Producto", label(item.kind), <strong className={item.delta > 0 ? "positive" : "negative"} key={item.id}>{item.delta > 0 ? "+" : ""}{item.delta}</strong>, short(item.sourceId)])} empty="Sin movimientos." action={allowed("purchases")?<button onClick={() => setView("purchases")}>Recibir mercancía</button>:undefined}/></Panel></>}
        {view === "purchases" && <div className="split-grid"><Panel title="Recibir compra" subtitle="Proveedor → compra → recepción → inventario."><form className="audit-form" onSubmit={submitPurchase}><Field label="Proveedor"><input required value={purchase.supplierName} onChange={(e) => setPurchase({...purchase, supplierName:e.target.value})}/></Field><Field label="Producto"><input disabled value={`${product?.name ?? "Sin producto"} · ${product?.sku ?? ""}`}/></Field><div className="form-row"><Field label="Cantidad recibida"><input required type="number" min="1" value={purchase.quantity} onChange={(e) => setPurchase({...purchase, quantity:Number(e.target.value)})}/></Field><Field label="Costo unitario (RD$)"><input required type="number" min="0" value={purchase.unitCost} onChange={(e) => setPurchase({...purchase, unitCost:Number(e.target.value)})}/></Field></div><button className="primary-action" disabled={busy || !product}>Confirmar recepción</button></form></Panel><Panel title="Compras recibidas" subtitle="Documentos que ya aumentaron inventario."><DataTable headers={["Compra","Proveedor","Total","Estado"]} rows={state.purchases.map((item) => [short(item.id), supplierName(item.supplierId), money(item.totalMinor), <Status key={item.id} value={item.status}/>])} empty="Aún no hay compras."/></Panel></div>}
        {view === "quotes" && <div className="split-grid"><Panel title="Nueva cotización" subtitle="Reutiliza cliente, producto y precio oficial."><form className="audit-form" onSubmit={submitQuote}><Field label="Cliente"><select required value={quote.customerId} onChange={(e) => setQuote({...quote, customerId:e.target.value})}><option value="">Seleccionar cliente</option>{state.customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Producto"><input disabled value={`${product?.name ?? "Sin producto"} · ${money(product?.priceMinor ?? 0)}`}/></Field><Field label="Cantidad"><input required type="number" min="1" value={quote.quantity} onChange={(e) => setQuote({...quote, quantity:Number(e.target.value)})}/></Field><Field label="Pago al convertir"><select value={quote.paymentMethod} onChange={(e) => setQuote({...quote, paymentMethod:e.target.value})}><option value="transfer">Transferencia</option><option value="cash">Efectivo</option></select></Field><button className="primary-action" disabled={busy || !quote.customerId || !product}>Cotizar, convertir y pagar</button></form></Panel><Panel title="Cotizaciones convertidas" subtitle="Sin volver a escribir cliente ni producto."><DataTable headers={["Cotización","Cliente","Total","Estado"]} rows={state.quotes.map((item) => [short(item.id), customerName(item.customerId), money(item.totalMinor), <Status key={item.id} value={item.status}/>])} empty="No hay cotizaciones."/></Panel></div>}
        {view === "invoices" && <Panel title="Facturas" subtitle="Documentos vinculados a taller o cotización."><div className="document-grid">{state.invoices.map((item) => <article className="invoice-card" key={item.id}><div><span>FACTURA</span><strong>{short(item.id)}</strong></div><h3>{customerName(item.customerId)}</h3><p>Origen: {item.sourceType === "work_order" ? "Orden de taller" : "Cotización"} {short(item.sourceId)}</p><dl><div><dt>Total</dt><dd>{money(item.totalMinor)}</dd></div><div><dt>Pagado</dt><dd>{money(item.paidMinor)}</dd></div></dl><Status value={item.status}/></article>)}</div>{!state.invoices.length && <Empty text="Aún no existen facturas."/>}</Panel>}
        {view === "cash" && <><OperationsPanel mode="cash" apiBase={apiBase} warehouseId={warehouseId} capabilities={actor?.capabilities??["cash.open","cash.close"]} onChange={()=>void refresh()}/><div className="metric-grid compact"><Metric title="Cobrado" value={money(state.payments.reduce((sum, item) => sum + item.amountMinor, 0))} note="Pagos registrados"/><Metric title="Movimientos de caja" value={state.cashMovements.length} note="Trazables a pagos"/></div><Panel title="Pagos y caja" subtitle="Cada cobro conserva su factura y método."><DataTable headers={["Pago","Factura","Método","Monto","Caja"]} rows={state.payments.map((item) => [short(item.id), short(item.invoiceId), label(item.method), money(item.amountMinor), state.cashMovements.some((cash) => cash.paymentId === item.id) ? "Registrado" : "Pendiente"])} empty="No hay pagos."/></Panel></>}
        {view === "delivery" && <Panel title="Entregas confirmadas" subtitle="Facturar no entrega físicamente el equipo; este estado se confirma por separado."><DataTable headers={["Equipo","Cliente","Serie","Estado físico","Orden"]} rows={state.equipment.map((item) => [equipmentName(item.id), customerName(item.customerId), item.serial ?? "Sin serie", <Status key={item.id} value={item.physicalStatus}/>, short(state.workOrders.find((order) => order.equipmentId === item.id)?.id)])} empty="No hay equipos recibidos."/></Panel>}
        {view === "settings" && <><OperationsPanel mode="access" apiBase={apiBase} warehouseId={warehouseId} capabilities={actor?.capabilities??["user.manage"]} onChange={()=>void refresh()}/><IdentitySecurityPanel apiBase={apiBase} capabilities={actor?.capabilities??[]} loginUrl={loginUrl}/><Panel title="Configuración empresarial" subtitle="Identidad, usuarios, roles y módulos pertenecen exclusivamente a esta empresa."><div className="receipt-summary"><div><span>Empresa</span><strong>{companyName}</strong></div><div><span>Almacén activo</span><strong>{warehouseId}</strong></div><div><span>Módulos habilitados</span><strong>{enabledModules?.length ?? visibleNavigation.length}</strong></div><p>La administración de capacidades se valida en servidor. El propietario no puede modificar políticas globales de LAEX.</p></div></Panel></>}
        {view === "history" && <Panel title="Historial y auditoría" subtitle="Evidencia transversal de operaciones y eventos."><div className="timeline">{state.audit.slice().reverse().map((item) => <div key={item.id}><span/><div><strong>{label(item.action)}</strong><p>Documento {short(item.entityId)} · {new Date(item.at).toLocaleString("es-DO")}</p></div></div>)}</div>{!state.audit.length && <Empty text="Aún no hay actividad auditada."/>}<button className="diagnostic-toggle" onClick={() => setTechnical(!technical)}>{technical ? "Ocultar" : "Mostrar"} diagnóstico técnico</button>{technical && <pre className="diagnostic-json">{JSON.stringify(state, null, 2)}</pre>}</Panel>}
      </div>
    </section>
  </main>;
}

function Panel({ title, subtitle, children, action }: { title: string; subtitle: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="audit-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</header>{children}</section>; }
function Metric({ title, value, note }: { title: string; value: string | number; note: string }) { return <article className="metric-card"><span>{title}</span><strong>{value}</strong><small>{note}</small></article>; }
function Field({ label: title, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{title}</span>{children}</label>; }
function Status({ value }: { value: string }) { return <span className="status-pill">{label(value)}</span>; }
function Empty({ text }: { text: string }) { return <div className="empty-state"><Boxes size={28}/><p>{text}</p></div>; }
function DataTable({ headers, rows, empty, action }: { headers: string[]; rows: React.ReactNode[][]; empty: string; action?: React.ReactNode }) { return <>{action && <div className="table-action">{action}</div>}<div className="table-wrap"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>{!rows.length && <Empty text={empty}/>}</>; }
function EventList({ events }: { events: State["events"] }) { return <div className="event-list">{events.map((event) => <div key={event.id}><span/><div><strong>{label(event.name)}</strong><small>{new Date(event.occurredAt).toLocaleString("es-DO")}</small></div><em>{short(event.aggregateId)}</em></div>)}{!events.length && <Empty text="Las operaciones aparecerán aquí."/>}</div>; }
function ReceiptSummary({ customer, concept, product, total }: { customer: string; concept: string; product: string; total: string }) { return <div className="receipt-summary"><div><span>Cliente</span><strong>{customer}</strong></div><div><span>Equipo</span><strong>{concept}</strong></div><div><span>Repuesto</span><strong>{product}</strong></div><div className="receipt-total"><span>Total estimado</span><strong>{total}</strong></div><p>Al confirmar, el sistema validará permisos, existencia e idempotencia y registrará auditoría.</p></div>; }








