"use client";

import { useCallback, useEffect, useState } from "react";
import { announceCommerceChange } from "@/modules/lf-printer/infrastructure/commerce-events";
import type { CommerceDeliveryPolicy } from "../chapter-two/types";
import "./commerce-center.css";

type Product={id:string;name:string;sku:string;priceMinor:number};
type Projection={productId:string;publicationStatus:string;deliveryPolicy?:CommerceDeliveryPolicy};
type Order={id:string;publicId:string;status:string;customer:{name:string};totalMinor:number;termsConfirmationRequired?:boolean;lines:Array<{deliverySnapshot?:CommerceDeliveryPolicy}>};
type PaymentMethod={id:string;name:string;kind:string;currency:string;destinationLabel?:string;destinationValue?:string;enabled:boolean};
type CommercePayment={id:string;orderId:string;status:string;amountMinor:number;externalReference?:string};
type Data={products:Product[];projections:Projection[];orders:Order[];paymentMethods:PaymentMethod[];commercePayments:CommercePayment[];storefront:string;paymentProvider:string};
const defaults:CommerceDeliveryPolicy={mode:"in-stock",estimatedDelivery:"1–2 días",priceType:"fixed",paymentRequirement:"full"};
const money=new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"});

export function CommerceCenter({apiBase,onBusinessChange}:{apiBase:string;onBusinessChange?:()=>void}){
  const[data,setData]=useState<Data|null>(null),[notice,setNotice]=useState(""),[policies,setPolicies]=useState<Record<string,CommerceDeliveryPolicy>>({});
  const[method,setMethod]=useState({name:"",kind:"bank-transfer",destinationLabel:"Cuenta DOP",destinationValue:"",currency:"DOP"});
  const companySlug=apiBase.split("/").filter(Boolean).at(-1)??"";
  const load=useCallback(()=>fetch(`${apiBase}/commerce`,{cache:"no-store"}).then(response=>response.json()).then((next:Data)=>{setData(next);setPolicies(current=>{const copy={...current};for(const product of next.products){const stored=next.projections.find(item=>item.productId===product.id)?.deliveryPolicy;copy[product.id]=copy[product.id]??stored??{...defaults};}return copy;});}),[apiBase]);
  useEffect(()=>{void load()},[load]);
  async function act(action:string,payload:object){const response=await fetch(`${apiBase}/commerce`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await response.json();setNotice(response.ok?"Operación Commerce completada, auditada y sincronizada.":body.error);if(response.ok){await load();onBusinessChange?.();announceCommerceChange(companySlug)}}
  function update(productId:string,patch:Partial<CommerceDeliveryPolicy>){setPolicies(current=>({...current,[productId]:{...(current[productId]??defaults),...patch}}))}
  return <div className="split-grid">
    <section className="audit-panel"><header><div><h2>Publicación Commerce</h2><p>Configura la condición comercial antes de publicar.</p></div></header>
      {data?.products.map(product=>{const projection=data.projections.find(item=>item.productId===product.id),published=projection?.publicationStatus==="published",policy=policies[product.id]??defaults;return <article key={product.id} className="receipt-summary"><div><span>{product.sku}</span><strong>{product.name}</strong><small>{money.format(product.priceMinor/100)}</small></div><div className="commerce-policy-form"><label>Modalidad<select value={policy.mode} onChange={event=>update(product.id,{mode:event.target.value as CommerceDeliveryPolicy["mode"]})}><option value="in-stock">En existencia</option><option value="on-order">Por encargo</option><option value="confirm-availability">Consultar disponibilidad</option></select></label><label>Plazo estimado<input value={policy.estimatedDelivery??""} onChange={event=>update(product.id,{estimatedDelivery:event.target.value})} placeholder="Ej.: 5–7 días"/></label><label>Precio<select value={policy.priceType} onChange={event=>update(product.id,{priceType:event.target.value as CommerceDeliveryPolicy["priceType"]})}><option value="fixed">Fijo</option><option value="tentative">Tentativo</option></select></label><label>Condición de pago<select value={policy.paymentRequirement} onChange={event=>update(product.id,{paymentRequirement:event.target.value as CommerceDeliveryPolicy["paymentRequirement"]})}><option value="full">Pago completo</option><option value="deposit">Adelanto</option><option value="confirmation">Confirmación previa</option></select></label>{policy.paymentRequirement==="deposit"&&<label>Adelanto (%)<input type="number" min="1" max="99" value={policy.depositPercent??50} onChange={event=>update(product.id,{depositPercent:Number(event.target.value)})}/></label>}{policy.priceType==="tentative"&&<label>Vigencia<input type="datetime-local" value={policy.tentativePriceValidUntil?.slice(0,16)??""} onChange={event=>update(product.id,{tentativePriceValidUntil:event.target.value?new Date(event.target.value).toISOString():undefined})}/></label>}<label className="policy-note">Nota visible<input value={policy.customerNote??""} onChange={event=>update(product.id,{customerNote:event.target.value})} placeholder="Información para el cliente"/></label></div><div><button onClick={()=>void act("publish",{input:{productId:product.id,deliveryPolicy:policy}})} className="primary-action">{published?"Actualizar condiciones":"Publicar en tienda"}</button>{published&&<button onClick={()=>void act("unpublish",{productId:product.id})}>Despublicar</button>}</div></article>})}
      {!data?.products.length&&<p>Todavía no hay productos empresariales.</p>}
    </section>
    <section className="audit-panel"><header><div><h2>Pedidos WEB</h2><p>PaymentProvider: {data?.paymentProvider}</p></div>{data?.storefront&&<a href={data.storefront} target="_blank" rel="noreferrer">Abrir Showroom</a>}</header>
      <div className="commerce-payment-config"><h3>Métodos de pago</h3><p>Las cuentas se configuran por empresa; no se publican desde código.</p><div><input value={method.name} onChange={event=>setMethod(current=>({...current,name:event.target.value}))} placeholder="Ej.: Banco Popular"/><select value={method.kind} onChange={event=>setMethod(current=>({...current,kind:event.target.value}))}><option value="bank-transfer">Transferencia bancaria</option><option value="cash">Efectivo</option><option value="token">Token configurado</option><option value="crypto">Cripto configurada</option></select><input value={method.destinationValue} onChange={event=>setMethod(current=>({...current,destinationValue:event.target.value}))} placeholder="Instrucción o cuenta autorizada"/><button disabled={!method.name.trim()} onClick={()=>void act("payment-method.configure",{input:{...method,instructions:["Incluye el número de pedido en la referencia."],requiresManualVerification:method.kind!=="cash"}})} className="primary-action">Agregar método</button></div>{data?.paymentMethods.map(item=><small key={item.id}>{item.name} · {item.currency} · {item.enabled?"Activo":"Inactivo"}</small>)}</div>
      {data?.orders.map(order=><article key={order.id} className="receipt-summary"><div><span>{order.publicId} · {order.status}</span><strong>{order.customer.name}</strong><small>{order.lines.map(line=>line.deliverySnapshot?.mode??"histórico").join(" · ")}</small></div><div><span>Total</span><strong>{money.format(order.totalMinor/100)}</strong></div><div>{order.status==="pending"&&order.termsConfirmationRequired&&<button className="primary-action" onClick={()=>void act("approve-conditions",{orderId:order.id})}>Confirmar precio/disponibilidad</button>}{order.status==="reserved"&&<><button onClick={()=>void act("cancel",{orderId:order.id})}>Cancelar y liberar</button><button className="primary-action" onClick={()=>void act("confirm",{orderId:order.id})}>Confirmar pedido</button></>}{order.status==="confirmed"&&<><button onClick={()=>void act("transition",{orderId:order.id,status:"preparing"})}>Preparando</button>{order.lines.some(line=>line.deliverySnapshot?.mode==="on-order")&&<button className="primary-action" onClick={()=>void act("transition",{orderId:order.id,status:"to-acquire"})}>Por adquirir</button>}</>}{order.status==="to-acquire"&&<button className="primary-action" onClick={()=>void act("transition",{orderId:order.id,status:"received"})}>Marcar recibido</button>}{order.status==="received"&&<button className="primary-action" onClick={()=>void act("transition",{orderId:order.id,status:"preparing"})}>Preparando</button>}{order.status==="preparing"&&<button className="primary-action" onClick={()=>void act("transition",{orderId:order.id,status:"ready"})}>Listo para entrega</button>}{order.status==="ready"&&<button className="primary-action" onClick={()=>void act("transition",{orderId:order.id,status:"delivered"})}>Entregado</button>}</div></article>)}
      {data?.commercePayments.map(payment=><article key={payment.id} className="receipt-summary"><div><span>Pago · {payment.status}</span><strong>{money.format(payment.amountMinor/100)}</strong></div>{payment.status==="pending"&&<button className="primary-action" onClick={()=>void act("payment.verify",{paymentId:payment.id})}>Verificar ingreso y registrar caja</button>}</article>)}
      {notice&&<p role="status">{notice}</p>}
    </section>
  </div>
}
