"use client";
import { useState, type FormEvent } from "react";
import { BarChart3, Download, FileWarning, Info, PlusCircle } from "lucide-react";
import "./reports.css";

type ReportType = "sales" | "inventory" | "expenses" | "dgii-606" | "dgii-607" | "dgii-it1";
type ReportResult = { type: string; status?: string; notice?: string; rows?: Array<Record<string, unknown>>; canonicalData?: { rows?: Array<Record<string, unknown>> }; totals?: Record<string, number>; dateQuality?: string };
const today = new Date().toISOString().slice(0, 10), first = `${today.slice(0, 8)}01`;
const money = (minor: number) => new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" }).format(minor / 100);
export function ReportsCenter({ apiBase, capabilities }: { apiBase: string; capabilities: string[] }) {
  const [type, setType] = useState<ReportType>("sales"), [from, setFrom] = useState(first), [to, setTo] = useState(today), [result, setResult] = useState<ReportResult | null>(null), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [expense, setExpense] = useState({ category: "Operación", description: "", amount: "0", tax: "0", occurredAt: today, documentReference: "", paymentMethod: "cash" });
  const allowed = (value: ReportType) => value === "sales" ? capabilities.includes("report.sales") : value === "inventory" ? capabilities.includes("report.inventory") : value === "expenses" ? capabilities.includes("report.expenses") : capabilities.includes("report.fiscal.prepare");
  async function generate(exported = false) { setBusy(true); setNotice(""); try { const response = await fetch(`${apiBase}/reports?type=${type}&from=${from}&to=${to}${exported ? "&export=true" : ""}`), data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); setNotice(exported ? "Exportación JSON canónica generada y auditada." : "Reporte generado y auditado."); if (exported) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }), link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${type}-${from}-${to}.json`; link.click(); URL.revokeObjectURL(link.href); } } catch (error) { setNotice(error instanceof Error ? error.message : "No fue posible generar el reporte."); } finally { setBusy(false); } }
  async function createExpense(event: FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch(`${apiBase}/reports`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "expense.create", input: { ...expense, amountMinor: Math.round(Number(expense.amount) * 100), taxMinor: Math.round(Number(expense.tax) * 100), occurredAt: `${expense.occurredAt}T12:00:00.000Z` } }) }), data = await response.json(); setNotice(response.ok ? "Gasto registrado con auditoría." : data.error); if (response.ok) { setExpense({ ...expense, description: "", amount: "0", tax: "0", documentReference: "" }); if (type === "expenses") await generate(); } setBusy(false); }
  const rows = result?.rows ?? result?.canonicalData?.rows ?? [];
  return <section className="reports-center"><header><div><span><BarChart3 size={16} /> CENTRO OFICIAL</span><h2>Reportes y Contabilidad</h2><p>Datos canónicos separados de adaptadores fiscales. Cada consulta queda auditada.</p></div><div className="reports-boundary"><FileWarning size={18} /><strong>DGII desconectada</strong><small>Sin transmisión ni declaración fiscal.</small></div></header>
    <div className="report-controls"><label>Reporte<select value={type} onChange={event => setType(event.target.value as ReportType)}>{(["sales", "inventory", "expenses", "dgii-606", "dgii-607", "dgii-it1"] as ReportType[]).filter(allowed).map(value => <option key={value} value={value}>{({ sales: "Ventas por fecha", inventory: "Inventario a una fecha", expenses: "Gastos por fecha", "dgii-606": "Preparación 606", "dgii-607": "Preparación 607", "dgii-it1": "Preparación IT-1" })[value]}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>Hasta / fecha de corte<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label><button disabled={busy || !allowed(type)} onClick={() => void generate()}>{busy ? "Procesando…" : "Generar"}</button><button className="report-export" disabled={!result || busy} onClick={() => void generate(true)}><Download size={16} /> Exportar JSON</button></div>
    {notice && <div className="report-notice" role="status">{notice}</div>}
    {result && <article className="report-result"><header><div><strong>{result.type}</strong><small>{from} → {to} · {rows.length} registros</small></div>{result.status && <span>{result.status}</span>}</header>{result.notice && <p className="fiscal-notice"><Info size={16} />{result.notice}</p>}<div className="report-summary">{result.totals && Object.entries(result.totals).map(([key, value]) => <div key={key}><span>{key.replace("Minor", "")}</span><strong>{money(value)}</strong></div>)}{result.dateQuality && <div><span>Calidad temporal</span><strong>{result.dateQuality === "exact" ? "Fechas exactas" : "Incluye movimientos heredados"}</strong></div>}</div><div className="report-table"><table><thead><tr>{rows[0] && Object.keys(rows[0]).slice(0, 7).map(key => <th key={key}>{key}</th>)}</tr></thead><tbody>{rows.slice(0, 100).map((row, index) => <tr key={String(row.id ?? row.invoiceId ?? row.productId ?? index)}>{Object.values(row).slice(0, 7).map((value, cell) => <td key={cell}>{typeof value === "number" && Object.keys(row)[cell]?.endsWith("Minor") ? money(value) : String(value ?? "—")}</td>)}</tr>)}</tbody></table>{!rows.length && <p>No hay registros en este período. Ajusta las fechas o registra operaciones.</p>}</div></article>}
    {capabilities.includes("expense.create") && <form className="expense-form" onSubmit={createExpense}><header><PlusCircle size={18} /><div><h3>Registrar gasto empresarial</h3><p>Crea un asiento operativo auditable; no constituye un comprobante DGII.</p></div></header><label>Categoría <span title="Agrupa el gasto en reportes. Ejemplo: Servicios, Transporte u Operación.">ⓘ</span><input required value={expense.category} onChange={event => setExpense({ ...expense, category: event.target.value })} /></label><label>Descripción <span title="Explica claramente qué se pagó y por qué.">ⓘ</span><input required value={expense.description} onChange={event => setExpense({ ...expense, description: event.target.value })} placeholder="Ej.: mantenimiento del local" /></label><label>Monto RD$<input required type="number" min="0.01" step=".01" value={expense.amount} onChange={event => setExpense({ ...expense, amount: event.target.value })} /></label><label>ITBIS identificado RD$<input type="number" min="0" step=".01" value={expense.tax} onChange={event => setExpense({ ...expense, tax: event.target.value })} /></label><label>Fecha<input required type="date" value={expense.occurredAt} onChange={event => setExpense({ ...expense, occurredAt: event.target.value })} /></label><label>Referencia documental<input value={expense.documentReference} onChange={event => setExpense({ ...expense, documentReference: event.target.value })} placeholder="Factura o referencia interna" /></label><button disabled={busy}>Registrar gasto</button></form>}
  </section>;
}
