import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";
import { CommercePaymentEngine, HmacCommercePaymentProvider } from "../../modules/business-engine/commerce/CommercePaymentEngine";
import { SqliteChapterTwoStore } from "../../modules/business-engine/infrastructure/sqlite/SqliteChapterTwoStore";
import type { ActorContext, CompanyId, TenantId, UserId } from "../../modules/business-engine/domain/types";

const root=mkdtempSync(join(tmpdir(),"laex-payments-")),tenant="tenant-pay" as TenantId,company="company-pay" as CompanyId,other="company-other" as CompanyId,user="user-pay" as UserId;let store:SqliteChapterTwoStore,payments:CommercePaymentEngine,actor:ActorContext;
before(async()=>{store=new SqliteChapterTwoStore(join(root,"payment.sqlite"));payments=new CommercePaymentEngine(store,()=>new Date("2026-08-14T14:00:00Z"),(()=>{let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,"0")}`})());actor={tenantId:tenant,companyId:company,userId:user,traceId:"payment",capabilities:["settings.manage","commerce.order.manage","cash.operate"]};await store.transact(state=>{state.platformCompanies.push({id:company,tenantId:tenant,slug:"pay",name:"Pay",legalName:"Pay",currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#000",enabledModules:["commerce"],status:"active",createdAt:"2026-08-14T00:00:00Z"},{id:other,tenantId:tenant,slug:"other",name:"Other",legalName:"Other",currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#000",enabledModules:["commerce"],status:"active",createdAt:"2026-08-14T00:00:00Z"});state.cashSessions.push({id:"cash",tenantId:tenant,companyId:company,branchId:"branch",userId:user,openedAt:"2026-08-14T08:00:00Z",openingMinor:0,status:"open"});state.commerceOrders.push({id:"order",publicId:"WEB-ORDER",tenantId:tenant,companyId:company,channel:"WEB",status:"reserved",customer:{name:"Ana",phone:"8090000000"},fulfillment:"pickup",lines:[],subtotalMinor:100000,taxMinor:18000,totalMinor:118000,paymentStatus:"pending",termsConfirmationRequired:false,idempotencyKey:"order",createdAt:"2026-08-14T12:00:00Z",updatedAt:"2026-08-14T12:00:00Z"},{id:"pending",publicId:"WEB-PENDING",tenantId:tenant,companyId:company,channel:"WEB",status:"pending",customer:{name:"Eva",phone:"8091111111"},fulfillment:"pickup",lines:[],subtotalMinor:100000,taxMinor:18000,totalMinor:118000,paymentStatus:"pending",termsConfirmationRequired:true,idempotencyKey:"pending",createdAt:"2026-08-14T12:00:00Z",updatedAt:"2026-08-14T12:00:00Z"});});});after(()=>{store.close();rmSync(root,{recursive:true,force:true})});

describe("Chapter 12 Commerce Payment Engine",()=>{
  it("configures tenant-scoped bank methods without hardcoding the storefront",async()=>{const method=await payments.configure(actor,{name:"Banco Popular",kind:"bank-transfer",destinationLabel:"Cuenta DOP",destinationValue:"Configurada por Business",instructions:["Usa el número de pedido"]});assert.equal((await payments.publicMethods(company))[0].name,"Banco Popular");assert.equal((await payments.publicMethods(other)).length,0);assert.equal(method.requiresManualVerification,true)});
  it("blocks payment while tentative commercial conditions remain pending",async()=>{const method=(await payments.publicMethods(company))[0];await assert.rejects(payments.submit(company,"blocked",{orderId:"pending",methodId:method.id,externalReference:"REF",receiptReference:"receipt"}),/commercial_conditions_confirmation_required/)});
  it("keeps transfer pending until an authorized manual verification records cash",async()=>{const method=(await payments.publicMethods(company))[0],first=await payments.submit(company,"transfer-once",{orderId:"order",methodId:method.id,externalReference:"BANK-123",receiptReference:"receipt://123"}) as {id:string;status:string},again=await payments.submit(company,"transfer-once",{orderId:"order",methodId:method.id,externalReference:"BANK-123",receiptReference:"receipt://123"}) as {id:string};assert.equal(first.id,again.id);assert.equal(first.status,"pending");await payments.verifyManual(actor,first.id);const state=await store.snapshot(),order=state.commerceOrders.find(item=>item.id==="order")!;assert.equal(order.paymentStatus,"paid");assert.equal(state.cashOperations.length,1);assert.ok(state.audit.some(item=>item.action==="commerce.payment.verified"))});
  it("exposes only a phone-verified, tenant-scoped customer timeline",async()=>{const result=await payments.track(company,{publicId:"WEB-ORDER",phone:"809-000-0000"});assert.equal(result.publicId,"WEB-ORDER");assert.ok(result.history.some(item=>item.status==="payment-confirmed"));await assert.rejects(payments.track(company,{publicId:"WEB-ORDER",phone:"8099999999"}),/order_not_found/);await assert.rejects(payments.track(other,{publicId:"WEB-ORDER",phone:"8090000000"}),/order_not_found/)});
  it("verifies signed provider events and rejects an invalid signature",()=>{const provider=new HmacCommercePaymentProvider("future-provider","secret"),body=JSON.stringify({eventId:"evt-1",paymentId:"pay-1",status:"paid",occurredAt:"2026-08-14T14:00:00Z"}),signature=createHmac("sha256","secret").update(body).digest("hex");assert.equal(provider.verify(body,signature).eventId,"evt-1");assert.throws(()=>provider.verify(body,"bad"),/invalid_provider_signature/)});
});
