import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";
import { CommerceEngine } from "../../modules/business-engine/commerce/CommerceEngine";
import { SqliteChapterTwoStore } from "../../modules/business-engine/infrastructure/sqlite/SqliteChapterTwoStore";
import type { ActorContext, CompanyId, TenantId, UserId, WarehouseId } from "../../modules/business-engine/domain/types";

const root=mkdtempSync(join(tmpdir(),"laex-delivery-policy-")),tenant="tenant-policy" as TenantId,company="company-policy" as CompanyId,other="company-policy-other" as CompanyId,user="user-policy" as UserId,warehouse="warehouse-policy" as WarehouseId;
let store:SqliteChapterTwoStore,engine:CommerceEngine,actor:ActorContext;
before(async()=>{store=new SqliteChapterTwoStore(join(root,"policy.sqlite"));engine=new CommerceEngine(store,()=>new Date("2026-08-14T12:00:00Z"));actor={tenantId:tenant,companyId:company,userId:user,traceId:"policy",capabilities:["commerce.publish","commerce.order.manage"]};await store.transact(state=>{for(const [id,slug] of [[company,"policy"],[other,"policy-other"]] as const)state.platformCompanies.push({id,tenantId:tenant,slug,name:slug,legalName:slug,currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#000",enabledModules:["commerce"],status:"active",createdAt:"2026-08-14T00:00:00Z"});state.warehouses.push({id:warehouse,tenantId:tenant,companyId:company,branchId:"branch",name:"Principal",status:"active"});state.products.push({id:"stock",tenantId:tenant,companyId:company,sku:"STOCK",name:"En existencia",priceMinor:10000,taxRate:18},{id:"order",tenantId:tenant,companyId:company,sku:"ORDER",name:"Por encargo",priceMinor:20000,taxRate:18},{id:"private",tenantId:tenant,companyId:other,sku:"PRIVATE",name:"Privado",priceMinor:30000});state.inventory.push({id:"opening",tenantId:tenant,companyId:company,warehouseId:warehouse,productId:"stock",delta:2,kind:"opening",sourceId:"opening"});});});
after(()=>{store.close();rmSync(root,{recursive:true,force:true})});

describe("Chapter 11 delivery and tentative-price policy",()=>{
  it("publishes in-stock delivery terms and freezes them in the order",async()=>{await engine.publish(actor,{productId:"stock",deliveryPolicy:{mode:"in-stock",estimatedDelivery:"1–2 días",priceType:"fixed",paymentRequirement:"full"}});const catalog=await engine.publicCatalog(company);assert.equal(catalog.products[0].deliveryPolicy.estimatedDelivery,"1–2 días");const order=await engine.checkout(company,"stock-order",{customer:{name:"Ana",phone:"8090000000"},fulfillment:"pickup",lines:[{slug:"en-existencia",quantity:1}]}) as {status:string;lines:Array<{deliverySnapshot:{mode:string;estimatedDelivery?:string}}>};assert.equal(order.status,"reserved");assert.deepEqual(order.lines[0].deliverySnapshot,{mode:"in-stock",estimatedDelivery:"1–2 días",priceType:"fixed",paymentRequirement:"full"});});
  it("allows on-order without physical stock and preserves its fulfillment history",async()=>{await engine.publish(actor,{productId:"order",deliveryPolicy:{mode:"on-order",estimatedDelivery:"5–7 días después de confirmar",priceType:"fixed",paymentRequirement:"full",customerNote:"Se adquiere después de confirmar."}});const product=(await engine.publicCatalog(company)).products.find(item=>item.slug==="por-encargo")!;assert.equal(product.availability,"Por encargo");const order=await engine.checkout(company,"on-order",{customer:{name:"Luis",phone:"8091111111"},fulfillment:"pickup",lines:[{slug:"por-encargo",quantity:1}]}) as {id:string;status:string};assert.equal(order.status,"reserved");await engine.confirm(actor,order.id);await engine.transition(actor,order.id,"to-acquire");await engine.transition(actor,order.id,"received");const stored=(await store.snapshot()).commerceOrders.find(item=>item.id===order.id)!;assert.equal(stored.status,"received");assert.equal(stored.lines[0].deliverySnapshot?.estimatedDelivery,"5–7 días después de confirmar");});
  it("blocks tentative price from definitive confirmation until audited approval",async()=>{await engine.publish(actor,{productId:"order",deliveryPolicy:{mode:"on-order",estimatedDelivery:"7–10 días",priceType:"tentative",paymentRequirement:"confirmation",tentativePriceValidUntil:"2026-08-20T00:00:00Z"}});const order=await engine.checkout(company,"tentative",{customer:{name:"Eva",phone:"8092222222"},fulfillment:"pickup",lines:[{slug:"por-encargo",quantity:1}]}) as {id:string;status:string};assert.equal(order.status,"pending");await assert.rejects(engine.confirm(actor,order.id),/conditions_confirmation_required/);await engine.approveConditions(actor,order.id);await engine.confirm(actor,order.id);const state=await store.snapshot(),stored=state.commerceOrders.find(item=>item.id===order.id)!;assert.ok(stored.conditionsConfirmedAt);assert.ok(stored.lines[0].priceConfirmedAt);assert.ok(state.audit.some(item=>item.action==="commerce.order.conditions-approved"&&item.entityId===order.id));});
  it("keeps delivery policies isolated by tenant and company",async()=>{assert.equal((await engine.publicCatalog(other)).products.length,0);const state=await store.snapshot();assert.equal(state.commerceProjections.filter(item=>item.companyId===other).length,0);});
});
