import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after,before,describe,it } from "node:test";
import { ChapterFiveService } from "../../modules/business-engine/chapter-five/ChapterFiveService";
import { ROLE_POLICIES } from "../../modules/business-engine/chapter-five/RolePolicy";
import { PosEngine } from "../../modules/business-engine/chapter-two/PosEngine";
import { SqliteChapterTwoStore } from "../../modules/business-engine/infrastructure/sqlite/SqliteChapterTwoStore";
import { CompanyProvisioningService } from "../../modules/business-engine/platform/CompanyProvisioningService";
import { PlatformOperationsService } from "../../modules/business-engine/platform/PlatformOperationsService";
import { BusinessIdentity } from "../../modules/business-engine/server/BusinessIdentity";
import type { ActorContext,CompanyId,WarehouseId } from "../../modules/business-engine/domain/types";

const root=mkdtempSync(join(tmpdir(),"laex-ch5-")),database=join(root,"chapter5.sqlite"),previousPath=process.env.BUSINESS_DATABASE_PATH;let store:SqliteChapterTwoStore,identity:BusinessIdentity,service:ChapterFiveService,platform:PlatformOperationsService,owner:ActorContext,cashier:ActorContext,companyId:CompanyId,warehouseId:WarehouseId;
before(async()=>{process.env.BUSINESS_DATABASE_PATH=database;store=new SqliteChapterTwoStore(database);identity=new BusinessIdentity(store,"chapter-five-test-secret-longer-than-thirty-two");const provisioned=await new CompanyProvisioningService(store,identity).provision({name:"Capítulo 5",legalName:"Capítulo 5 SRL",slug:"chapter-five",hostname:"chapter-five.test",ownerEmail:"owner@chapter5.test",ownerPassword:"Owner-Chapter5-2026!",enabledModules:["dashboard","inventory","pos","cash","settings"]});companyId=provisioned.companyId;warehouseId=provisioned.warehouseId;service=new ChapterFiveService(store,identity);platform=new PlatformOperationsService(store,identity);owner=await identity.requireActor(await identity.login("owner@chapter5.test","Owner-Chapter5-2026!",companyId));await service.createProduct(owner,{sku:"SKU-1",name:"Producto operativo",costMinor:5000,priceMinor:10000});await service.createUser(owner,{name:"Caja",email:"cashier@chapter5.test",password:"Cashier-Chapter5-2026!",roleName:"Cajero"});cashier=await identity.requireActor(await identity.login("cashier@chapter5.test","Cashier-Chapter5-2026!",companyId));});
after(()=>{store.close();if(previousPath===undefined)delete process.env.BUSINESS_DATABASE_PATH;else process.env.BUSINESS_DATABASE_PATH=previousPath;rmSync(root,{recursive:true,force:true});});
describe("Chapter 5 operational controls",()=>{
it("assigns least-privilege cashier capabilities",()=>{const cashierCapabilities=ROLE_POLICIES.Cajero as readonly string[];assert.ok(cashierCapabilities.includes("pos.sell"));assert.ok(!cashierCapabilities.includes("product.manage"));assert.ok(!cashierCapabilities.includes("user.manage"));});
it("protects product management and inventory adjustments",async()=>{await assert.rejects(service.createProduct(cashier,{sku:"NO",name:"No permitido",costMinor:1,priceMinor:2}),/capability_denied/);const product=(await store.snapshot()).products[0];await service.adjustInventory(owner,{productId:product.id,warehouseId,quantityDelta:10,reason:"Entrada inicial autorizada"});assert.equal((await store.snapshot()).inventory.reduce((n,m)=>n+m.delta,0),10);});
it("requires an open cash shift and supervisor override above five percent",async()=>{const product=(await store.snapshot()).products[0],pos=new PosEngine(store);const input={customerType:"consumer_final",warehouseId,lines:[{productId:product.id,quantity:1}],discountMinor:1000,taxRate:.18,taxMode:"included" as const,payments:[{method:"cash",amountMinor:9000,receivedMinor:10000}]};await assert.rejects(pos.confirmSale(cashier,"no-shift",input),/active cash session/);const branch=(await store.snapshot()).branches[0];await service.openCash(cashier,{branchId:branch.id,openingMinor:20000});await assert.rejects(pos.confirmSale(cashier,"excess-discount",input),/pos.discount.override/);const allowed={...input,discountMinor:500,payments:[{method:"cash",amountMinor:9500,receivedMinor:10000}]};assert.equal((await pos.confirmSale(cashier,"allowed-sale",allowed)).status,"paid");});
it("closes cash with expected and counted difference",async()=>{const open=(await store.snapshot()).cashSessions.find(s=>s.userId===cashier.userId&&s.status==="open")!;const closed=await service.closeCash(cashier,{cashSessionId:open.id,countedMinor:29500});assert.equal(closed.expectedMinor,29500);assert.equal(closed.differenceMinor,0);});
it("revokes a registered business session",async()=>{const token=await identity.login("cashier@chapter5.test","Cashier-Chapter5-2026!",companyId),actor=await identity.requireActor(token),session=(await store.snapshot()).businessSessions.find(s=>s.id===actor.sessionId)!;await service.revokeSession(owner,session.id);await assert.rejects(identity.requireActor(token),/authentication_required/);});
it("creates multi-branch resources and scoped membership context",async()=>{const location=await service.createLocation(owner,{branchName:"Sucursal Norte",warehouseName:"Almacén Norte"});assert.equal(location.warehouse.branchId,location.branch.id);const state=await store.snapshot();assert.equal(state.branches.filter(b=>b.companyId===companyId).length,2);});
it("issues and revokes restricted support and creates a non-destructive backup",async()=>{const issued=await platform.issueSupport(companyId,{reason:"Diagnóstico solicitado",durationMinutes:15,issuedBy:"laex-admin"});const support=await identity.requireActor(issued.token);assert.deepEqual(support.capabilities,["dashboard.view","support.diagnose"]);await platform.revokeSupport(issued.grant.id,"laex-admin");await assert.rejects(identity.requireActor(issued.token));const backup=await platform.createBackup(companyId);assert.equal(backup.status,"completed");});
});
