import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { Pool } from "pg";
import { PostgresChapterTwoStore } from "../../modules/business-engine/infrastructure/postgres/PostgresChapterTwoStore";
import type { CompanyId,TenantId } from "../../modules/business-engine/domain/types";

const url=process.env.BUSINESS_DATABASE_URL;
if(!url)throw new Error("BUSINESS_DATABASE_URL required for Chapter 6 tests");
const store=PostgresChapterTwoStore.fromUrl(url),pool=new Pool({connectionString:url,max:1,application_name:"laex-chapter-six-tests"});
const tenantA="tenant-pg-a" as TenantId,tenantB="tenant-pg-b" as TenantId,companyA="company-pg-a" as CompanyId,companyB="company-pg-b" as CompanyId;

describe("Chapter 6 PostgreSQL production gate",()=>{
  const clean=()=>store.transact(state=>{for(const key of Object.keys(state)as Array<keyof typeof state>){const value=state[key];if(Array.isArray(value))(state[key]as unknown[])=value.filter((item:unknown)=>{if(!item||typeof item!=="object")return true;const record=item as{tenantId?:string;companyId?:string;id?:string};return ![tenantA,tenantB].includes(record.tenantId as TenantId)&&![companyA,companyB].includes(record.companyId as CompanyId)&&![tenantA,tenantB,companyA,companyB].includes(record.id as never)})as never}for(const key of Object.keys(state.idempotency))if(key.startsWith(`${tenantA}:`)||key.startsWith(`${tenantB}:`))delete state.idempotency[key]});
  before(clean);
  after(async()=>{await clean();await store.close();await pool.end()});
  it("persists normalized tenant/company records and survives a fresh snapshot",async()=>{await store.transact(state=>{const at=new Date().toISOString();state.platformTenants.push({id:tenantA,name:"A",status:"active",createdAt:at},{id:tenantB,name:"B",status:"active",createdAt:at});state.platformCompanies.push({id:companyA,tenantId:tenantA,slug:"pg-a",name:"A",legalName:"A",currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#000",enabledModules:[],status:"active",createdAt:at},{id:companyB,tenantId:tenantB,slug:"pg-b",name:"B",legalName:"B",currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#000",enabledModules:[],status:"active",createdAt:at});state.products.push({id:"same-sku-a",tenantId:tenantA,companyId:companyA,sku:"SAME",name:"A product",priceMinor:100},{id:"same-sku-b",tenantId:tenantB,companyId:companyB,sku:"SAME",name:"B product",priceMinor:200});state.fiscalConfigurations.push({tenantId:tenantA,companyId:companyA,enabled:false,environment:"disabled",rnc:"101000001",obligationsCurrent:false,authorizedElectronicIssuer:false,softwareCertified:false,certificateReference:null,credentialReference:null,sequenceVaultReference:null},{tenantId:tenantB,companyId:companyB,enabled:false,environment:"disabled",rnc:"101000002",obligationsCurrent:false,authorizedElectronicIssuer:false,softwareCertified:false,certificateReference:null,credentialReference:null,sequenceVaultReference:null})});const state=await store.snapshot();assert.equal(state.platformCompanies.filter(item=>[companyA,companyB].includes(item.id)).length,2);assert.equal(state.products.filter(item=>[companyA,companyB].includes(item.companyId)).length,2)});
  it("rolls back the whole business transaction on failure",async()=>{await assert.rejects(store.transact(state=>{state.customers.push({id:"must-rollback",tenantId:tenantA,companyId:companyA,name:"Rollback"});throw new Error("expected_failure")}),/expected_failure/);assert.equal((await store.snapshot()).customers.some(c=>c.id==="must-rollback"),false)});
  it("enforces tenant/company RLS even when record ids and SKUs are known",async()=>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('laex.tenant_id',$1,true),set_config('laex.company_id',$2,true)",[tenantA,companyA]);const own=await client.query("SELECT payload->>'name' name FROM business_records WHERE bucket='products' ORDER BY record_key"),fiscal=await client.query("SELECT rnc FROM business_fiscal_profiles");assert.deepEqual(own.rows,[{name:"A product"}]);assert.deepEqual(fiscal.rows,[{rnc:"101000001"}]);await client.query("ROLLBACK")}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});
  it("loads a platform-authorized company snapshot without crossing the RLS boundary",async()=>{const scoped=await store.snapshotForCompany(tenantA,companyA,["platformCompanies","products"]);assert.deepEqual(scoped.products.map(product=>product.name),["A product"]);assert.equal(scoped.products.some(product=>product.companyId===companyB),false);assert.equal(scoped.platformCompanies.some(company=>company.id===companyB),false)});
  it("forces RLS on the normalized Commerce payment tables",async()=>{const result=await pool.query("SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname = ANY($1::text[]) ORDER BY relname",[["commerce_order_history","commerce_payment_methods","commerce_payments"]]);assert.deepEqual(result.rows.map(row=>[row.relname,row.relrowsecurity,row.relforcerowsecurity]),[["commerce_order_history",true,true],["commerce_payment_methods",true,true],["commerce_payments",true,true]])});
  it("records migration checksums exactly once",async()=>{const result=await pool.query("SELECT version,count(*)::int count,length(checksum) checksum_length FROM laex_schema_migrations GROUP BY version,checksum ORDER BY version");assert.deepEqual(result.rows.map(r=>[r.version,r.count,r.checksum_length]),[["0001_saas_core",1,64],["0002_operational_control",1,64],["0003_security_invariants",1,64],["0004_chapter_eight_accounting_identity",1,64],["0005_dominican_fiscal_engine",1,64],["0006_ai_engine_governance",1,64],["0007_commerce_publication_engine",1,64],["0008_commerce_payment_engine",1,64]])});
});
