import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { DisabledElectronicInvoicingProvider, ElectronicInvoicingService, classifyPosCustomerType } from "../../modules/business-engine/electronic-invoicing";
import type { ElectronicInvoicingProvider, FiscalTenantConfiguration } from "../../modules/business-engine/electronic-invoicing";
import type { CompanyId, TenantId, UserId } from "../../modules/business-engine/domain/types";

const tenantId = "tenant-ecf" as TenantId, companyId = "company-ecf" as CompanyId, userId = "user-ecf" as UserId;
const ready: FiscalTenantConfiguration = { tenantId, companyId, enabled: true, environment: "certification", rnc: "101000001", obligationsCurrent: true, authorizedElectronicIssuer: true, softwareCertified: true, certificateReference: "vault://tenant-ecf/certificate", credentialReference: "vault://tenant-ecf/credential", sequenceVaultReference: "vault://tenant-ecf/sequences" };
const provider: ElectronicInvoicingProvider = { provider: "certification-fake", version: "test", async sign() { return { status: "signed", occurredAt: "2026-08-08T17:00:00.000Z" }; }, async submit() { return { status: "accepted", eNcf: "E320000000001", acknowledgementId: "ACK-1", dgiiStatus: "accepted", occurredAt: "2026-08-08T17:01:00.000Z" }; }, async queryStatus() { return { status: "accepted", occurredAt: "2026-08-08T17:01:00.000Z" }; }, async printableRepresentation() { return { mimeType: "text/html", content: "demo" }; } };

describe("Electronic invoicing preparation", () => {
  it("maps POS fiscal selections without consuming an official sequence", () => { assert.equal(classifyPosCustomerType("consumer_final"), "E32"); assert.equal(classifyPosCustomerType("fiscal_credit"), "E31"); assert.equal(classifyPosCustomerType("government"), "E45"); assert.equal(classifyPosCustomerType("special_regime"), "E44"); const record = new ElectronicInvoicingService(new DisabledElectronicInvoicingProvider(), () => "ecf-1", () => new Date("2026-08-08T17:00:00.000Z")).prepareDraft({ tenantId, companyId, invoiceId: "invoice-1", type: "E32", userId, idempotencyKey: "key-1" }); assert.equal(record.status, "draft"); assert.equal(record.eNcf, null); });
  it("keeps real signing disabled without company certification", async () => { const service = new ElectronicInvoicingService(new DisabledElectronicInvoicingProvider()); const record = service.prepareDraft({ tenantId, companyId, invoiceId: "invoice-1", type: "E31", userId, idempotencyKey: "key-2" }); await assert.rejects(service.sign(record, { ...ready, enabled: false, environment: "disabled" }), /disabled/); assert.equal(record.status, "draft"); });
  it("supports the future signature and submission state machine", async () => { const service = new ElectronicInvoicingService(provider); const record = service.prepareDraft({ tenantId, companyId, invoiceId: "invoice-2", type: "E32", userId, idempotencyKey: "key-3" }); await service.sign(record, ready); assert.equal(record.status, "signed"); await service.submit(record, ready); assert.equal(record.status, "accepted"); assert.equal(record.eNcf, "E320000000001"); assert.equal(record.acknowledgementId, "ACK-1"); });
  it("requires an original same-company e-CF for credit and debit notes", () => { const service = new ElectronicInvoicingService(provider); assert.throws(() => service.prepareDraft({ tenantId, companyId, invoiceId: "note", type: "E34", userId, idempotencyKey: "note-1" }), /original/); const original = service.prepareDraft({ tenantId, companyId, invoiceId: "invoice", type: "E31", userId, idempotencyKey: "original" }); const note = service.prepareDraft({ tenantId, companyId, invoiceId: "note", type: "E34", userId, idempotencyKey: "note-2", original }); assert.equal(note.originalElectronicInvoiceId, original.id); });
});
