"use client";

import { ArrowUpRight, Blocks, Bot, Radio, ShieldCheck } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { Project } from "@/core/types/project";
import { ONE_MILLION_MINERS_LAUNCH } from "@/core/projects/onemillionminers/launch";
import OneMillionMinersCountdown from "./OneMillionMinersCountdown";

type Props={project:Project;index:number};
export default function OneMillionMinersProjectCard({project,index}:Props){
  return <article data-launch-source={ONE_MILLION_MINERS_LAUNCH.sourcePage} data-launch-at={ONE_MILLION_MINERS_LAUNCH.targetIso} className="group relative flex min-h-[470px] min-w-0 flex-col overflow-hidden rounded-[28px] border border-amber-300/35 bg-[linear-gradient(160deg,#110d04,#050a11_58%,#02060b)] p-4 shadow-[0_24px_75px_rgba(0,0,0,.48),0_0_28px_rgba(245,183,31,.08)] transition duration-500 hover:-translate-y-1.5 hover:border-amber-200/65 hover:shadow-[0_34px_95px_rgba(0,0,0,.6),0_0_42px_rgba(245,183,31,.16)] sm:p-5">
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(251,191,36,.2),transparent_35%),radial-gradient(circle_at_100%_38%,rgba(34,211,238,.1),transparent_32%)]"/><div className="pointer-events-none absolute inset-px rounded-[27px] border border-white/[.045]"/>
    <section className="relative h-[172px] overflow-hidden rounded-[20px] border border-amber-200/20 bg-black"><Image src={project.banner} alt="Presentación oficial OneMillionMiners" fill sizes="(max-width:767px) calc(100vw - 3rem),25vw" className="object-cover opacity-70 saturate-[1.12] transition duration-700 group-hover:scale-[1.045] group-hover:opacity-85"/><div className="absolute inset-0 bg-[linear-gradient(to_top,#090b0c_2%,transparent_60%),radial-gradient(circle_at_50%_15%,transparent,rgba(0,0,0,.42))]"/><span className="absolute left-3 top-3 rounded-full border border-cyan-300/35 bg-[#04111b]/85 px-2.5 py-1 font-mono text-[8px] tracking-[.17em] text-cyan-200 backdrop-blur">PRJ-{String(index+1).padStart(2,"0")}</span><span className="absolute right-3 top-3 inline-flex items-center gap-1.5 rounded-full border border-amber-300/35 bg-black/65 px-2.5 py-1 text-[7px] font-black uppercase tracking-[.13em] text-amber-200 backdrop-blur"><Radio size={9} className="animate-pulse"/> Contador oficial</span><div className="absolute inset-x-0 bottom-3 flex items-end justify-between gap-3 px-3"><div className="grid size-14 place-items-center overflow-hidden rounded-2xl border border-amber-200/35 bg-[#080b0e]/90 p-1.5 shadow-[0_0_24px_rgba(245,183,31,.25)]"><Image src={project.logo} alt="Logo OneMillionMiners" width={52} height={52} className="size-full object-contain"/></div><div className="text-right"><p className="text-[8px] font-black uppercase tracking-[.18em] text-amber-300">Lanzamiento oficial</p><h2 className="mt-1 text-lg font-black tracking-[-.035em] text-white">OneMillionMiners</h2></div></div></section>
    <section className="relative mt-3 rounded-2xl border border-amber-300/20 bg-black/25 p-3"><div className="flex items-center justify-between gap-3"><p className="text-[8px] font-black uppercase tracking-[.16em] text-slate-400">Faltan para el lanzamiento</p><span className="text-[7px] font-bold text-emerald-300">UTC · FUENTE VERIFICADA</span></div><div className="mt-3"><OneMillionMinersCountdown /></div><time dateTime={ONE_MILLION_MINERS_LAUNCH.targetIso} className="mt-2 block text-center text-[7px] text-slate-600">29 AGO 2026 · 14:00 UTC</time></section>
    <section className="relative mt-3 grid grid-cols-3 gap-1.5 text-center"><div className="rounded-xl border border-white/[.07] bg-white/[.025] p-2"><Bot className="mx-auto text-amber-300" size={13}/><span className="mt-1 block text-[6px] font-bold uppercase tracking-[.08em] text-slate-400">Minería inteligente</span></div><div className="rounded-xl border border-white/[.07] bg-white/[.025] p-2"><Blocks className="mx-auto text-cyan-300" size={13}/><span className="mt-1 block text-[6px] font-bold uppercase tracking-[.08em] text-slate-400">Blockchain</span></div><div className="rounded-xl border border-white/[.07] bg-white/[.025] p-2"><ShieldCheck className="mx-auto text-emerald-300" size={13}/><span className="mt-1 block text-[6px] font-bold uppercase tracking-[.08em] text-slate-400">Fuente oficial</span></div></section>
    <Link href="/proyectos/onemillionminers" className="relative mt-auto flex min-h-11 items-center justify-between border-t border-amber-300/15 pt-4 text-[9px] font-black uppercase tracking-[.14em] text-amber-200 transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300/70" aria-label="Explorar OneMillionMiners">Explorar proyecto<span className="grid size-8 place-items-center rounded-full border border-amber-300/40 bg-amber-300/[.08] transition group-hover:bg-amber-300/[.16]"><ArrowUpRight size={13}/></span></Link>
  </article>
}
