import { randomUUID } from "node:crypto";
import { AccessDeniedError, CapabilityDeniedError } from "../domain/errors";
import type { ActorContext } from "../domain/types";
import type { ChapterTwoEngine } from "./ChapterTwoEngine";
import type { ReceptionEngine } from "./ReceptionEngine";
import type { ChapterTwoState, ChapterTwoStore } from "./types";
import { type AssistantToolName, type ConversationalProvider } from "../assistant/ConversationalProvider";
import type { ReportingService } from "../reporting/ReportingService";
import type { AIProvider } from "../ai/AIProvider";
import { DeterministicAIProvider } from "../ai/DeterministicAIProvider";
import { toolsFor } from "../ai/ToolRegistry";
import { redactForProvider } from "../ai/ContextSecurity";
import type { ChapterFiveService } from "../chapter-five/ChapterFiveService";

export type AssistantAgent = "LIA" | "ALAN" | "ETHAN";
export class LocalAssistantOrchestrator {
  private readonly reporting?:ReportingService;private readonly provider:ConversationalProvider|AIProvider;private readonly now:()=>Date;private readonly id:()=>string;
  constructor(private readonly store: ChapterTwoStore, private readonly business: ChapterTwoEngine, private readonly reception: ReceptionEngine, reportingOrNow?: ReportingService|(()=>Date), provider: ConversationalProvider|AIProvider = new DeterministicAIProvider(), now: () => Date = () => new Date(), id: () => string = randomUUID,private readonly operations?:ChapterFiveService) {if(typeof reportingOrNow==="function"){this.now=reportingOrNow;this.reporting=undefined}else{this.reporting=reportingOrNow;this.now=now}this.provider=provider;this.id=id}
  private require(actor: ActorContext) { if (!(actor.capabilities as readonly string[]).includes("assistant.use")) throw new CapabilityDeniedError("assistant.use"); }
  private own<T extends { tenantId: string; companyId: string; userId: string }>(actor: ActorContext, value: T) { if (value.tenantId !== actor.tenantId || value.companyId !== actor.companyId || value.userId !== actor.userId) throw new AccessDeniedError(); return value; }
  async history(actor: ActorContext, agent?: AssistantAgent) { this.require(actor); const state = await this.store.snapshot(); return state.assistantMessages.filter((m) => m.tenantId === actor.tenantId && m.companyId === actor.companyId && m.userId === actor.userId && (!agent || m.agent === agent)); }
  async ask(actor: ActorContext, agent: AssistantAgent, text: string) {
    this.require(actor); if (!text.trim()) throw new Error("message_required"); text=redactForProvider(text);
    const snapshot = await this.business.snapshot(actor), history = await this.history(actor, agent), tools = toolsFor(agent,actor.capabilities) as AssistantToolName[];
    const providerInput={actor,agent,message:text,history:history.slice(-12).map(item=>({role:item.role,text:item.text,at:item.at})),availableTools:tools};const interpretation=await this.provider.interpret(providerInput);let answer = "Necesito que me indiques qué deseas consultar o preparar. No completaré datos que no hayas proporcionado."; let proposal: ChapterTwoState["assistantProposals"][number] | undefined;
    const lower = text.toLocaleLowerCase();if(interpretation.intent==="unsupported")answer="No puedo seguir instrucciones que intenten omitir permisos o revelar información fuera de tu alcance. Puedo ayudarte con una tarea empresarial autorizada.";
    if (interpretation.intent==="report.sales"&&this.reporting) {const date=this.now().toISOString().slice(0,10),report=await this.reporting.sales(actor,{from:date,to:date});answer=`Ventas del ${date}: ${new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(report.totals.totalMinor/100)} en ${report.rows.length} factura${report.rows.length===1?"":"s"}.`;}
    else if (interpretation.intent==="report.inventory"&&this.reporting) {const date=this.now().toISOString().slice(0,10),report=await this.reporting.inventory(actor,date);answer=`Inventario al ${date}: ${report.rows.reduce((sum,row)=>sum+row.quantity,0)} unidades en ${report.rows.length} productos.`;}
    else if (interpretation.intent==="report.expenses"&&this.reporting) {const date=this.now().toISOString().slice(0,10),report=await this.reporting.expenses(actor,{from:date,to:date});answer=`Gastos del ${date}: ${new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(report.totals.amountMinor/100)} en ${report.rows.length} registros.`;}
    else if (interpretation.intent==="report.fiscal.prepare"&&this.reporting) {const date=this.now().toISOString().slice(0,10),report=await this.reporting.fiscalPreparation(actor,"dgii-it1",{from:date,to:date});answer=`Preparación fiscal del ${date} generada con reglas ${report.ruleVersion}. Es una vista no transmisible y debe revisarse antes de cualquier uso fiscal.`;}
    else if(agent==="LIA"&&interpretation.intent==="catalog.bulk"){
      const fullState=await this.store.snapshot(),warehouse=fullState.warehouses.find(item=>item.tenantId===actor.tenantId&&item.companyId===actor.companyId&&item.status==="active"),rows=text.split(/\r?\n/).filter(line=>line.includes(",")).filter(line=>!line.trim().toLowerCase().startsWith("sku,")).map(line=>{const[sku,name,quantity,cost,price,barcode,brand,model,category,description]=line.split(",").map(value=>value.trim());return{sku,name,quantity:Number(quantity),costMinor:Math.round(Number(cost)*100),priceMinor:Math.round(Number(price)*100),barcode:barcode||undefined,brand:brand||undefined,model:model||undefined,category:category||undefined,description:description||undefined}}).filter(row=>row.sku&&row.name&&Number.isInteger(row.quantity)&&row.quantity>=0&&row.costMinor>=0&&row.priceMinor>=0);
      if(!warehouse)answer="No existe un almacén activo. Configúralo antes de preparar la carga.";else if(!rows.length)answer="Pega las filas CSV debajo de la instrucción con: SKU, nombre, cantidad, costo, precio, código, marca, modelo, categoría y descripción. No crearé productos incompletos.";else{proposal={id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,userId:actor.userId,agent:"LIA",command:"catalog.bulk",payload:{warehouseId:warehouse.id,rows},summary:`Registrar ${rows.length} producto${rows.length===1?"":"s"} y sus movimientos en ${warehouse.name}.`,status:"pending",createdAt:this.now().toISOString()};answer=`Preparé una vista previa de ${rows.length} producto${rows.length===1?"":"s"}. Revísala y confirma; todavía no se ha modificado inventario.`}
    }
    else if (agent === "LIA" && interpretation.intent==="reception.create") {
      const customerName = text.match(/(?:lia[, ]*)?([\p{L}]+(?:\s+[\p{L}]+){1,3})\s+trajo/iu)?.[1]?.trim() ?? text.match(/\bde\s+([\p{L}]+(?:\s+[\p{L}]+){0,3})[.!]?$/iu)?.[1] ?? "Cliente por confirmar";
      const equipment = text.match(/\b(Epson|Canon|HP|Brother)\s+([A-Z0-9-]+)/i);
      const brand = equipment?.[1] ?? "", model = equipment?.[2] ?? "",phone=text.match(/\b(?:\+?1[- ]?)?(\d{3}[- ]?\d{3}[- ]?\d{4})\b/)?.[1],problem=text.match(/(?:porque|problema[: ]+)\s*([^.;]+)/i)?.[1]?.trim();const matches=snapshot.customers.filter(item=>item.name.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase()===customerName.normalize("NFD").replace(/\p{Diacritic}/gu,"").toLowerCase());
      if(!brand||!model||customerName==="Cliente por confirmar"){answer=`Necesito ${customerName==="Cliente por confirmar"?"el nombre del cliente, ":""}${!brand||!model?"la marca y el modelo exactos del equipo":""} antes de preparar la recepción.`}
      else if(matches.length>1&&!phone){answer=`Encontré ${matches.length} clientes llamados ${customerName}. Indica el teléfono para seleccionar el registro correcto; no elegiré uno arbitrariamente.`}
      else{proposal = { id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, agent, command: "reception.create", payload: { customerName, brand, model,phone,problem }, summary: `Recibir ${brand} ${model} de ${customerName}${phone?` · teléfono ${phone}`:""}${problem?` · síntoma: ${problem}`:""} y crear orden pendiente de diagnóstico.`, status: "pending", createdAt: this.now().toISOString() };answer = "Preparé la recepción con los datos identificados. Revísala y confirma antes de que el Business Engine modifique clientes, equipos u órdenes.";}
    } else if (agent === "LIA" && /cotiza|cotización|cotizacion/.test(lower)) {
      answer = `Encontré ${snapshot.products.length} producto disponible. Para crear la cotización necesito el modelo exacto y el cliente; todavía no modificaré ningún documento.`;
    } else if (agent === "ALAN" && interpretation.intent==="workshop.read") {
      const pending = snapshot.workOrders.filter((o) => o.status === "pending_diagnosis");
      answer = pending.length ? `Hay ${pending.length} orden${pending.length === 1 ? "" : "es"} pendiente${pending.length === 1 ? "" : "s"} de diagnóstico: ${pending.map((o) => { const e = snapshot.equipment.find((x) => x.id === o.equipmentId); return e ? `${e.brand} ${e.model}` : "equipo"; }).join(", ")}.` : "No hay órdenes pendientes de diagnóstico.";
    } else if (agent === "ETHAN" && /(vendimos|ventas|factur)/.test(lower)) {
      const today = this.now().toISOString().slice(0, 10); const invoiceIds = new Set(snapshot.events.filter((e) => e.name === "InvoiceIssued" && e.occurredAt.startsWith(today)).map((e) => e.aggregateId));
      const total = snapshot.invoices.filter((i) => invoiceIds.has(i.id)).reduce((sum, i) => sum + i.totalMinor, 0);
      answer = `Las ventas registradas hoy son ${new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" }).format(total / 100)} en ${invoiceIds.size} factura${invoiceIds.size === 1 ? "" : "s"}.`;
    } else if(/inventario|costo|margen|ventas|gasto|fiscal|606|607|it-?1/i.test(text)&&!tools.some(tool=>tool.startsWith("report.")||tool==="inventory.read")){answer="No tienes permisos para consultar esa información mediante LIA. Solicita al administrador la capacidad correspondiente.";}
    const at = this.now().toISOString();
    await this.store.transact((state) => { state.assistantMessages.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, agent, role: "user", text, at }); if (proposal) state.assistantProposals.push(proposal); state.assistantMessages.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, agent, role: "assistant", text: answer, proposalId: proposal?.id, at });const enriched=interpretation as typeof interpretation&{usage?:{inputUnits:number;outputUnits:number;estimatedCostUsdMicros:number};dataCategories?:string[]},usage=enriched.usage??{inputUnits:text.length,outputUnits:answer.length,estimatedCostUsdMicros:0};state.aiActivity.push({id:this.id(),tenantId:actor.tenantId,companyId:actor.companyId,userId:actor.userId,sessionId:actor.sessionId,agent,provider:this.provider.id,model:"model"in this.provider?this.provider.model:this.provider.id,intent:interpretation.intent,tools:interpretation.intent==="clarification"||interpretation.intent==="unsupported"?[]:[interpretation.intent],result:proposal?"proposed":interpretation.intent==="clarification"?"clarification":answer.startsWith("No tienes")?"denied":"answered",dataCategories:enriched.dataCategories??["user_instruction"],inputUnits:usage.inputUnits,outputUnits:usage.outputUnits||answer.length,estimatedCostUsdMicros:usage.estimatedCostUsdMicros,createdAt:at}); });
    return { answer, proposal };
  }
  async confirm(actor: ActorContext, proposalId: string) {
    this.require(actor); const state = await this.store.snapshot(); const proposal = this.own(actor, state.assistantProposals.find((p) => p.id === proposalId) ?? (() => { throw new AccessDeniedError(); })());
    if (proposal.status === "cancelled") throw new Error("proposal_cancelled");
    const result = proposal.command==="catalog.bulk"?(this.operations?await this.operations.bulkReceive(actor,{...proposal.payload,confirmMissing:true}):(()=>{throw new Error("catalog_bulk_unavailable")})()):await this.reception.receive(actor, `assistant-proposal:${proposal.id}`, proposal.payload);
    await this.store.transact((draft) => { const current = draft.assistantProposals.find((p) => p.id === proposal.id); if (current) { current.status = "confirmed"; current.confirmedAt = this.now().toISOString(); } draft.assistantMessages.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, agent: proposal.agent, role: "assistant", text: proposal.command==="catalog.bulk"?"Acción confirmada. Los productos y movimientos fueron registrados mediante Business Engine.":"Acción confirmada. La recepción fue registrada y la orden quedó pendiente de diagnóstico.", at: this.now().toISOString() }); });
    return result;
  }
  async cancel(actor: ActorContext, proposalId: string) { this.require(actor); return this.store.transact((state) => { const proposal = this.own(actor, state.assistantProposals.find((p) => p.id === proposalId) ?? (() => { throw new AccessDeniedError(); })()); if (proposal.status === "pending") proposal.status = "cancelled"; return { status: proposal.status }; }); }
}

