"use client";

import Image from "next/image";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Menu, Minus, PackageSearch, Plus, Search, ShoppingCart, Sparkles, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { createPortal } from "react-dom";
import { LiaAvatar } from "@/modules/shared/components/LiaAvatar";
import type { PublicCommerceCatalog, PublicCommerceProduct } from "../infrastructure/commerce-presentation";
import { announceCommerceChange } from "../infrastructure/commerce-events";
import { CommerceServicesDock } from "./CommerceServicesDock";
import { LiaQuickPanel } from "./LiaQuickPanel";
import { OfficialBrandMark } from "./OfficialBrandMark";
import { OneMillionMinersPromoCard } from "./OneMillionMinersPromoCard";
import { PrinterVisual } from "./PrinterVisual";
import { LF_PRINTER_PAYMENT_OPTIONS, LFPrinterCommerceFooter } from "./LFPrinterCommerceFooter";
import { orderWhatsappUrl, type PublicOrderForWhatsapp } from "../infrastructure/order-whatsapp";
import "./commerce-three-zone.css";

const money = new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" });
const checkoutLabels = ["Carrito", "Datos y opciones"];
const paymentMethodOrder = ["OMD", "OMDB", "USDT", "Banco BHD", "Banreservas"];
const policyOf = (product:PublicCommerceProduct) => product.deliveryPolicy ?? { mode:"in-stock" as const, priceType:"fixed" as const, paymentRequirement:"full" as const, estimatedDelivery:"1–2 días" };
const modeLabel = (product:PublicCommerceProduct) => ({ "in-stock":"En existencia", "on-order":"Por encargo", "confirm-availability":"Consultar disponibilidad" })[policyOf(product).mode];
type CartLine = { product: PublicCommerceProduct; quantity: number };
type Drawer = "cart" | "lia" | null;
type CatalogMenuSection = { title:string; items:{ label:string; href?:string; action?:"lia"; category?:string; disabled?:boolean }[] };
const catalogMenuSections:CatalogMenuSection[]=[
  {title:"Cuenta",items:[{label:"Iniciar sesión / Mi cuenta",href:"/login"},{label:"Mis pedidos",href:"/proyectos/lf-printer/seguimiento"},{label:"Seguimiento",href:"/proyectos/lf-printer/seguimiento"}]},
  {title:"Comprar en LF-PRINTER",items:[{label:"Impresoras",category:"Impresoras"},{label:"Tintas y consumibles",category:"Tintas y consumibles"},{label:"Repuestos",category:"Repuestos"},{label:"Ofertas",disabled:true},{label:"Nuevos productos",disabled:true},{label:"Más vendidos",disabled:true}]},
  {title:"Servicios LF-PRINTER",items:[{label:"Taller LF-PRINTER",href:"#taller"},{label:"Seguimiento de reparación",href:"/proyectos/lf-printer/seguimiento"},{label:"Soporte / WhatsApp",href:"https://wa.me/18493581132"},{label:"Hablar con Lía",action:"lia"}]},
  {title:"Ecosistema LAEX",items:[{label:"Conoce LAEX",href:"/"},{label:"Proyectos LAEX",href:"/proyectos"},{label:"OMD",disabled:true},{label:"OMDB",disabled:true},{label:"OneMillionMiners",href:"/proyectos/onemillionminers"},{label:"Proyectos futuros",disabled:true}]},
];
type PublicPaymentMethod={id:string;name:string;kind:string;currency:string;instructions:string[];destinationLabel?:string;destinationValue?:string;requiresManualVerification:boolean};

export function CommerceCatalog({ companySlug, initial, onCatalogChange }: { companySlug: string; initial: PublicCommerceCatalog; onCatalogChange?: (catalog: PublicCommerceCatalog) => void }) {
  const [data, setData] = useState(initial), [query, setQuery] = useState(""), [category, setCategory] = useState(""), [page, setPage] = useState(1);
  const [cart, setCart] = useState<Record<string, CartLine>>({}), [customer, setCustomer] = useState({ name: "", phone: "" });
  const [loading, setLoading] = useState(false), [submitting, setSubmitting] = useState(false), [notice, setNotice] = useState(""), [drawer, setDrawer] = useState<Drawer>(null), [menuOpen,setMenuOpen]=useState(false), [checkoutStep, setCheckoutStep] = useState(0);
  const[lastOrder,setLastOrder]=useState<PublicOrderForWhatsapp|null>(null),[lastOrderPublicId,setLastOrderPublicId]=useState(""),[lastOrderWhatsappUrl,setLastOrderWhatsappUrl]=useState("");
  const portalReady=useSyncExternalStore(()=>()=>{},()=>true,()=>false);
  const[paymentMethods,setPaymentMethods]=useState<PublicPaymentMethod[]>([]),[paymentMethodId,setPaymentMethodId]=useState(""),[fulfillment,setFulfillment]=useState<"pickup"|"local-delivery">("pickup");
  const resultsRef = useRef<HTMLElement>(null);
  const load = useCallback(async (signal?: AbortSignal) => { const params = new URLSearchParams({ page: String(page), pageSize: "24" }); if (query.trim()) params.set("q", query.trim()); if (category) params.set("category", category); const response = await fetch(`/api/commerce/${companySlug}/search?${params}`, { signal, cache: "no-store" }); if (!response.ok) throw new Error("No pudimos actualizar los productos."); const next = await response.json() as PublicCommerceCatalog; setData(next); onCatalogChange?.(next); return next; }, [category, companySlug, onCatalogChange, page, query]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); try { await load(controller.signal); if (query.trim()) resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); } catch (error) { if (!controller.signal.aborted) setNotice(error instanceof Error ? error.message : "No fue posible buscar."); } finally { if (!controller.signal.aborted) setLoading(false); } }, 180); return () => { clearTimeout(timer); controller.abort(); }; }, [load, query]);
  useEffect(() => { document.body.style.overflow = drawer||menuOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [drawer,menuOpen]);
  useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenuOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[menuOpen]);
  useEffect(()=>{void fetch(`/api/commerce/${companySlug}/payments`,{cache:"no-store"}).then(response=>response.ok?response.json():{methods:[]}).then((body:{methods:PublicPaymentMethod[]})=>{const methods=body.methods.length?body.methods:LF_PRINTER_PAYMENT_OPTIONS.map((method,index)=>({id:`coordination-${index}`,name:method.name,kind:method.name==="OMD"||method.name==="OMDB"?"token":method.name==="USDT"?"crypto":"bank-transfer",currency:method.name==="USDT"?"USDT":"DOP",instructions:["Coordinar los datos de pago por WhatsApp."],requiresManualVerification:true}));setPaymentMethods(methods);setPaymentMethodId(current=>current||methods[0]?.id||"")})},[companySlug]);
  const lines = useMemo(() => Object.values(cart).filter(line => line.quantity > 0), [cart]);
  const itemCount = lines.reduce((sum, line) => sum + line.quantity, 0), total = lines.reduce((sum, line) => sum + line.product.priceMinor * line.quantity, 0), pages = Math.max(1, Math.ceil((data.total ?? data.products.length) / (data.pageSize ?? 24)));
  function change(product: PublicCommerceProduct, quantity: number) { setCart(current => ({ ...current, [product.slug]: { product, quantity: Math.max(0, Math.min(quantity, product.availableQuantity ?? Number.MAX_SAFE_INTEGER)) } })); setCheckoutStep(0); setNotice(""); }
  function selectCategory(value: string) { setCategory(value); setPage(1); resultsRef.current?.scrollIntoView({ behavior: "smooth" }); }
  function advanceCheckout() { if (!lines.length) return; setNotice(""); setCheckoutStep(1); }
  async function checkout() {
    if(!customer.name.trim()||!customer.phone.trim()){setCheckoutStep(1);setNotice("Indica tu nombre y teléfono para reservar.");return}
    const selected=paymentMethods.find(method=>method.id===paymentMethodId);
    if(!selected){setNotice("Selecciona cómo deseas pagar para continuar.");return}
    setSubmitting(true);
    const whatsappWindow=window.open("about:blank","_blank");
    try{const response=await fetch(`/api/commerce/${companySlug}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({customer,fulfillment,lines:lines.map(line=>({slug:line.product.slug,quantity:line.quantity}))})}),body=await response.json() as PublicOrderForWhatsapp&{id?:string;status?:string;message?:string};if(!response.ok)throw new Error(body.message||"No pudimos reservar el pedido.");const whatsappUrl=orderWhatsappUrl(body,selected.name);setLastOrder(body);setLastOrderPublicId(body.publicId);setLastOrderWhatsappUrl(whatsappUrl);if(whatsappWindow)whatsappWindow.location.href=whatsappUrl;setCart({});setCheckoutStep(0);await load();announceCommerceChange(companySlug);setNotice(`Pedido ${body.publicId} creado. Continúa en WhatsApp; LF-PRINTER verificará el pago antes de marcarlo como pagado.`)}catch(error){whatsappWindow?.close();setNotice(error instanceof Error?error.message:"No pudimos reservar el pedido.")}finally{setSubmitting(false)}
  }

  const cartPanel = <div className="flex h-full min-h-0 flex-col"><CartTermsSummary lines={lines}/><CartPanel lines={lines} itemCount={itemCount} total={total} customer={customer} notice={notice} submitting={submitting} step={checkoutStep} onStep={setCheckoutStep} onCustomer={setCustomer} onChange={change} onAdvance={advanceCheckout} onCheckout={() => void checkout()} fulfillment={fulfillment} onFulfillment={setFulfillment} paymentMethods={paymentMethods} paymentMethodId={paymentMethodId} onPaymentMethod={setPaymentMethodId}/>{lastOrderPublicId&&lastOrderWhatsappUrl&&<a href={lastOrderWhatsappUrl} target="_blank" rel="noreferrer" className="m-3 mt-0 rounded-lg bg-emerald-500 px-3 py-3 text-center text-xs font-black text-emerald-950">Procesar pago por WhatsApp · {lastOrderPublicId}</a>}</div>;
  const fixedHeader=
    <div className="commerce-fixed-header">
    <div className="catalog-quick-nav" aria-label="Accesos rápidos LF-PRINTER"><div className="catalog-quick-nav__inner"><button className="catalog-quick-nav__all" onClick={()=>setMenuOpen(true)} aria-expanded={menuOpen} aria-controls="lf-catalog-menu"><Menu size={15}/> Todo</button><button onClick={()=>selectCategory("Impresoras")}>Impresoras</button><button onClick={()=>selectCategory("Tintas y consumibles")}>Tintas y consumibles</button><button onClick={()=>selectCategory("Repuestos")}>Repuestos</button><button disabled title="Próximamente">Ofertas</button><button disabled title="Próximamente">Nuevos productos</button><button disabled title="Próximamente">Más vendidos</button><a href="#taller">Taller</a><Link href="/proyectos/lf-printer/seguimiento">Seguimiento</Link><Link href="/proyectos">Proyectos LAEX</Link></div></div>
    <header id="inicio" className="commerce-header sticky top-0 z-40 border-b border-white/10 bg-[#080a0d]/95 text-white backdrop-blur-xl"><div className="mx-auto flex h-[4.75rem] w-[min(100%-1rem,110rem)] items-center gap-2 sm:gap-4 xl:grid xl:grid-cols-[12.75rem_minmax(0,1fr)_16.5rem] xl:gap-0"><Link href="/proyectos/lf-printer" aria-label="Inicio LF-PRINTER" className="flex shrink-0 justify-center"><OfficialBrandMark compact/></Link><label className="relative min-w-0 flex-1 xl:mx-4"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><span className="sr-only">Buscar productos</span><input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="Buscar impresora, tinta, repuesto o modelo..." className="h-11 w-full rounded-lg border-2 border-transparent bg-white pl-10 pr-3 text-sm text-slate-950 outline-none focus:border-[#ffd600]"/></label><button onClick={() => setDrawer("lia")} className="flex h-11 items-center gap-2 rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 text-xs font-black text-emerald-200 xl:hidden"><Sparkles size={17}/><span className="hidden sm:inline">Lía</span></button><button onClick={() => setDrawer("cart")} className="flex h-11 shrink-0 items-center justify-center gap-2 rounded-lg bg-[#ffd600] px-3 text-sm font-black text-black xl:mx-2"><ShoppingCart size={18}/><span className="hidden sm:inline">Carrito</span><b className="grid size-6 place-items-center rounded-full bg-black text-[11px] text-white">{itemCount}</b></button></div><nav aria-label="Categorías" className="mx-auto flex h-11 w-[min(100%-1rem,110rem)] gap-1.5 overflow-x-auto pb-3 text-xs font-bold xl:pl-[13.75rem] xl:pr-[17.5rem]">{["", ...(data.categories ?? [])].map(item => <button key={item || "all"} onClick={() => selectCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 ${category === item ? "bg-[#ffd600] text-black" : "bg-white/5 text-slate-300"}`}>{item || "Todos"}</button>)}<button onClick={() => setDrawer("lia")} className="whitespace-nowrap rounded-full bg-white/5 px-4 py-2 text-slate-300 xl:hidden">Taller</button></nav></header>

    </div>;
  return <>
    {portalReady?createPortal(fixedHeader,document.body):fixedHeader}
    <div className="commerce-shell mx-auto grid w-[min(100%-1rem,110rem)] items-start xl:grid-cols-[12.75rem_minmax(0,1fr)_16.5rem]">
      <aside id="lia-aside" className="hidden border-r border-slate-200 bg-white xl:block"><div className="p-4"><LiaAvatar size={56} state="assistance"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Lía · Asesora LF-PRINTER</p><h2 className="mt-2 text-base font-black text-slate-950">¿Necesitas ayuda para elegir?</h2><p className="mt-2 text-xs leading-5 text-slate-500">Consulta el catálogo real sin interrumpir tu compra.</p><button onClick={() => setDrawer("lia")} className="mt-4 w-full rounded-lg bg-emerald-500 px-3 py-3 text-xs font-black text-emerald-950">Hablar con Lía</button></div><OneMillionMinersPromoCard/><div id="taller"><CommerceServicesDock/></div></aside>

      <section ref={resultsRef} id="catalogo" className="min-w-0 scroll-mt-28 px-4 py-6 lg:px-5"><div className="flex items-end justify-between gap-3 border-b border-slate-200 pb-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-600">Catálogo LF-PRINTER</p><h1 className="mt-1 text-xl font-black text-slate-950 sm:text-2xl">{query ? `Resultados para “${query}”` : "Productos publicados"}</h1></div><span aria-live="polite" className="shrink-0 text-xs text-slate-500">{loading ? "Buscando…" : `${data.total ?? data.products.length} productos`}</span></div>{!data.products.length ? <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Search className="mx-auto text-slate-400"/><h3 className="mt-3 font-black">No encontramos ese producto.</h3><button onClick={() => setQuery("")} className="mt-4 text-sm font-bold text-amber-700">Limpiar búsqueda</button></div> : <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.products.map(product => <CatalogCard key={product.projectionId ?? product.slug} product={product} quantity={cart[product.slug]?.quantity ?? 0} add={() => change(product, (cart[product.slug]?.quantity ?? 0) + 1)}/>)}</div>}{pages > 1 && <nav aria-label="Paginación" className="mt-8 flex items-center justify-center gap-3"><button disabled={page === 1} onClick={() => setPage(value => Math.max(1, value - 1))} className="grid size-9 place-items-center rounded-full border border-slate-300 bg-white disabled:opacity-30"><ChevronLeft/></button><span className="text-xs text-slate-500">Página {page} de {pages}</span><button disabled={page === pages} onClick={() => setPage(value => Math.min(pages, value + 1))} className="grid size-9 place-items-center rounded-full border border-slate-300 bg-white disabled:opacity-30"><ChevronRight/></button></nav>}</section>

      <aside id="pedido-aside" className="hidden overflow-hidden border-l border-slate-200 bg-white xl:flex xl:flex-col">{cartPanel}</aside>
    </div>
    <LFPrinterCommerceFooter order={lastOrder??undefined} onOrderRequired={()=>{setNotice("Primero agrega el producto y crea la reserva. Luego podrás elegir el método y continuar por WhatsApp.");setDrawer("cart")}}/>

    {menuOpen&&<CatalogNavigationMenu onClose={()=>setMenuOpen(false)} onCategory={value=>{selectCategory(value);setMenuOpen(false)}} onLia={()=>{setMenuOpen(false);setDrawer("lia")}}/>}
    {drawer && <div className="fixed inset-0 z-[80] bg-black/60" onMouseDown={event => { if (event.target === event.currentTarget) setDrawer(null); }}><aside role="dialog" aria-modal="true" aria-label={drawer === "cart" ? "Carrito" : "Lía, asesora LF-PRINTER"} className={`relative ml-auto h-full w-[min(100%,30rem)] overflow-hidden shadow-2xl ${drawer === "cart" ? "bg-white text-slate-950" : "overflow-y-auto bg-[#0c1015] text-white"}`}><button aria-label="Cerrar panel" onClick={() => setDrawer(null)} className="absolute right-3 top-3 z-20 grid size-9 place-items-center rounded-full bg-slate-950/10 shadow backdrop-blur"><X size={18}/></button>{drawer === "cart" ? cartPanel : <><LiaQuickPanel companySlug={companySlug}/><CommerceServicesDock/></>}</aside></div>}
  </>;
}

function CatalogNavigationMenu({onClose,onCategory,onLia}:{onClose:()=>void;onCategory:(value:string)=>void;onLia:()=>void}){
  return <div className="fixed inset-0 z-[90] bg-slate-950/70 backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside id="lf-catalog-menu" role="dialog" aria-modal="true" aria-label="Menú completo LF-PRINTER" className="h-full w-[min(92vw,25rem)] overflow-y-auto bg-white text-slate-950 shadow-2xl"><header className="sticky top-0 z-10 flex items-center gap-3 border-b border-slate-200 bg-[#0b1016] p-4 text-white"><OfficialBrandMark compact/><div><b className="block text-sm">Explora LF-PRINTER</b><small className="text-slate-400">Catálogo, servicios y ecosistema LAEX</small></div><button autoFocus onClick={onClose} aria-label="Cerrar menú" className="ml-auto grid size-10 place-items-center rounded-full bg-white/10"><X/></button></header>{catalogMenuSections.map(section=><section key={section.title} className="border-b border-slate-200 p-4"><h2 className="mb-2 text-xs font-black uppercase tracking-[.16em] text-slate-500">{section.title}</h2><div className="grid gap-1">{section.items.map(item=>{const content=<><span>{item.label}</span>{item.disabled?<small className="ml-auto rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-500">Próximamente</small>:<ChevronRight className="ml-auto" size={15}/>}</>;const className="flex min-h-11 items-center rounded-lg px-3 text-sm font-semibold transition hover:bg-amber-50 disabled:cursor-not-allowed disabled:text-slate-400";if(item.disabled)return <button key={item.label} disabled className={className}>{content}</button>;if(item.category)return <button key={item.label} onClick={()=>onCategory(item.category!)} className={className}>{content}</button>;if(item.action==="lia")return <button key={item.label} onClick={onLia} className={className}>{content}</button>;return <Link key={item.label} href={item.href!} onClick={onClose} target={item.href?.startsWith("http")?"_blank":undefined} rel={item.href?.startsWith("http")?"noreferrer":undefined} className={className}>{content}</Link>})}</div></section>)}<section aria-label="Promociones futuras" data-commerce-promotion-slots="offers benefits featured-projects lf-printer-laex" className="m-4 rounded-xl border border-dashed border-amber-300 bg-amber-50 p-4"><div className="flex items-center gap-2 text-amber-900"><PackageSearch size={18}/><b className="text-sm">Beneficios y proyectos destacados</b></div><p className="mt-2 text-xs leading-5 text-amber-800">Espacio preparado para promociones autorizadas por Commerce. No hay beneficios automáticos activos.</p></section></aside></div>
}

function CartPanel({ lines, itemCount, total, customer, notice, submitting, step, onStep, onCustomer, onChange, onAdvance, onCheckout, fulfillment, onFulfillment, paymentMethods, paymentMethodId, onPaymentMethod }: { lines: CartLine[]; itemCount: number; total: number; customer: { name: string; phone: string }; notice: string; submitting: boolean; step: number; onStep: (value: number) => void; onCustomer: (value: { name: string; phone: string }) => void; onChange: (product: PublicCommerceProduct, quantity: number) => void; onAdvance: () => void; onCheckout: () => void; fulfillment:"pickup"|"local-delivery"; onFulfillment:(value:"pickup"|"local-delivery")=>void; paymentMethods:PublicPaymentMethod[]; paymentMethodId:string; onPaymentMethod:(value:string)=>void }) {
  return <>
    <header className="border-b border-slate-200 p-4"><div className="flex items-center gap-2"><ShoppingCart size={18}/><h2 className="font-black">Carrito</h2><b className="ml-auto rounded-full bg-[#ffd600] px-2 py-1 text-[10px]">{itemCount}</b></div><p className="mt-1 text-[10px] text-slate-500">Reserva disponible durante 15 minutos</p></header>
    {step > 0 && <ol aria-label="Progreso del checkout" className="checkout-progress">{checkoutLabels.map((label,index)=><li key={label} className={index<=step?"is-active":""}><span>{index+1}</span><small>{label}</small></li>)}</ol>}
    <div className="min-h-0 flex-1 overflow-y-auto p-3">
      {step===0&&(!lines.length?<p className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center text-xs text-slate-500">Agrega un producto. El carrito seguirá visible mientras exploras.</p>:<div className="grid gap-2">{lines.map(line=><CartProduct key={line.product.slug} line={line} onChange={onChange}/>)}</div>)}
      {step===1&&<div className="checkout-stage"><h3>Completa y envía por WhatsApp</h3><p>Solo necesitamos tus datos, entrega y forma de pago.</p><label>Nombre<input autoFocus value={customer.name} onChange={event=>onCustomer({...customer,name:event.target.value})}/></label><label>Teléfono<input value={customer.phone} inputMode="tel" onChange={event=>onCustomer({...customer,phone:event.target.value})}/></label><fieldset><legend className="mb-2 text-xs font-black">¿Cómo lo recibirás?</legend><div className="grid grid-cols-2 gap-2">{([{id:"pickup",label:"Retiro en tienda",note:"Coordinar recogida"},{id:"local-delivery",label:"Envío",note:"Coordinar dirección"}] as const).map(option=><label key={option.id} className={`checkout-choice cursor-pointer ${fulfillment===option.id?"is-selected":""}`}><input type="radio" name="fulfillment" className="sr-only" checked={fulfillment===option.id} onChange={()=>onFulfillment(option.id)}/><b>{option.label}</b><small>{option.note}</small></label>)}</div></fieldset><fieldset><legend className="mb-2 text-xs font-black">¿Cómo deseas pagar?</legend><div className="grid grid-cols-2 gap-2">{[...paymentMethods].sort((a,b)=>paymentMethodOrder.indexOf(a.name)-paymentMethodOrder.indexOf(b.name)).map(method=>{const visual=LF_PRINTER_PAYMENT_OPTIONS.find(option=>option.name===method.name);return <label key={method.id} className={`checkout-choice checkout-payment-choice cursor-pointer ${paymentMethodId===method.id?"is-selected":""}`}><input type="radio" name="payment-method" className="sr-only" checked={paymentMethodId===method.id} onChange={()=>onPaymentMethod(method.id)}/>{visual?.image&&<span className="relative h-8 w-12 shrink-0"><Image src={visual.image} alt="" fill sizes="48px" className="object-contain"/></span>}<b>{method.name}</b></label>})}</div><p className="mt-2 text-[10px] leading-4 text-slate-500">El pago se coordina y verifica con LF-PRINTER mediante WhatsApp.</p></fieldset></div>}
    </div>
    <footer className="sticky bottom-0 z-10 shrink-0 border-t border-slate-200 bg-slate-50 p-4 shadow-[0_-8px_20px_rgba(15,23,42,.06)]"><div className="flex justify-between text-xs text-slate-500"><span>Artículos</span><b>{itemCount}</b></div><div className="mt-2 flex justify-between text-base"><b>Subtotal</b><b>{money.format(total/100)}</b></div>{lines.length>0&&(step===0?<button onClick={onAdvance} className="mt-4 w-full rounded-lg bg-[#ffd600] px-3 py-3 text-xs font-black text-black">Continuar</button>:<div className="mt-4 grid grid-cols-[auto_1fr] gap-2"><button onClick={()=>onStep(0)} className="rounded-lg border border-slate-300 bg-white px-3 py-3 text-xs font-bold">Atrás</button><button disabled={submitting} onClick={onCheckout} className="rounded-lg bg-emerald-500 px-3 py-3 text-xs font-black text-emerald-950 disabled:opacity-40">{submitting?"Creando pedido…":"Reservar y abrir WhatsApp"}</button></div>)}{notice&&<p role="status" className="mt-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">{notice}</p>}</footer>
  </>;
}

function CartProduct({ line, onChange }: { line: CartLine; onChange: (product: PublicCommerceProduct, quantity: number) => void }) {
  const image=line.product.images.find(item=>item.purpose==="card")??line.product.images[0],policy=policyOf(line.product);
  return <article className="grid grid-cols-[3.25rem_1fr] gap-2 rounded-xl border border-slate-200 p-2"><div className="aspect-square overflow-hidden rounded-lg border border-slate-100"><PrinterVisual compact src={image?.url} alt={image?.alt||line.product.name}/></div><div className="min-w-0"><strong className="line-clamp-2 text-[11px] leading-4">{line.product.model||line.product.name}</strong><small className="mt-1 block text-[9px] font-bold text-amber-700">{modeLabel(line.product)}{policy.estimatedDelivery?` · ${policy.estimatedDelivery}`:""}</small><b className="mt-1 block text-xs">{money.format(line.product.priceMinor*line.quantity/100)}{policy.priceType==="tentative"&&<em className="ml-1 text-[9px] font-normal text-rose-600">tentativo</em>}</b><div className="mt-2 flex items-center gap-2"><button aria-label="Restar" onClick={()=>onChange(line.product,line.quantity-1)}><Minus size={13}/></button><span className="text-xs">{line.quantity}</span><button aria-label="Agregar" disabled={line.quantity>=(line.product.availableQuantity??Infinity)} onClick={()=>onChange(line.product,line.quantity+1)}><Plus size={13}/></button><button className="ml-auto text-slate-400 hover:text-rose-600" aria-label="Eliminar" onClick={()=>onChange(line.product,0)}><Trash2 size={13}/></button></div></div></article>;
}

function CartTermsSummary({lines}:{lines:CartLine[]}){
  if(!lines.length)return null;
  const requiresConfirmation=lines.some(line=>{const policy=policyOf(line.product);return policy.priceType==="tentative"||policy.mode==="confirm-availability"||policy.paymentRequirement==="confirmation"});
  return <div className={`mx-3 mt-3 rounded-lg px-3 py-2 text-[10px] leading-4 ${requiresConfirmation?"bg-rose-50 text-rose-800":"bg-amber-50 text-amber-900"}`}><b className="block">Condiciones del pedido</b>{lines.map(line=><span key={line.product.slug} className="block">{modeLabel(line.product)}{policyOf(line.product).estimatedDelivery?` · ${policyOf(line.product).estimatedDelivery}`:""}{policyOf(line.product).priceType==="tentative"?" · Precio tentativo":""}</span>)}{requiresConfirmation&&<strong className="mt-1 block">Se requiere confirmación empresarial antes de cualquier cobro definitivo.</strong>}</div>;
}

function CatalogCard({ product, quantity, add }: { product: PublicCommerceProduct; quantity: number; add: () => void }) {
  const image=product.images.find(item=>item.purpose==="card")??product.images[0],policy=policyOf(product);
  return <article className="group flex flex-col overflow-hidden rounded-[1.35rem] border border-slate-200/90 bg-white shadow-[0_8px_28px_rgba(15,23,42,.07)] transition duration-300 hover:-translate-y-1 hover:border-amber-300 hover:shadow-[0_22px_48px_rgba(15,23,42,.13)]">
    <Link href={product.url??`/proyectos/lf-printer/productos/${product.slug}`} className="relative block aspect-[4/3] overflow-hidden bg-[radial-gradient(circle_at_50%_35%,#263441_0%,#0b1118_48%,#020407_100%)] before:absolute before:inset-x-[18%] before:bottom-[8%] before:h-[10%] before:rounded-full before:bg-cyan-300/10 before:blur-xl">
      <div className="absolute inset-4 transition duration-500 group-hover:scale-[1.045]"><PrinterVisual src={image?.url} alt={image?.alt||product.name} stage="dark"/></div>
      {product.promotion?.active&&<span className="absolute left-4 top-4 rounded-full bg-[#ffd600] px-3 py-1.5 text-[9px] font-black uppercase tracking-[.1em] text-slate-950 shadow-sm">Exclusivo LAEX + OMM</span>}
    </Link>
    <div className="flex flex-1 flex-col border-t border-slate-100 p-5">
      <div className="flex items-start justify-between gap-3"><span className="text-[11px] font-black uppercase tracking-[.16em] text-cyan-700">{product.model||product.category}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${product.availability==="Agotado"?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{product.availability}</span></div>
      <Link href={product.url??`/proyectos/lf-printer/productos/${product.slug}`}><h2 className="mt-3 line-clamp-2 min-h-12 text-[1.05rem] font-black leading-6 tracking-[-.02em] text-slate-950 transition group-hover:text-amber-700">{product.name}</h2></Link>
      {product.promotion?.active&&<p className="mt-3 text-xs font-extrabold uppercase tracking-[.06em] text-rose-600">{product.promotion.title??"Promoción"}</p>}
      <div className="mt-1 flex flex-wrap items-baseline gap-x-3 gap-y-1"><strong className="text-[1.65rem] font-black tracking-[-.04em] text-slate-950">{money.format(product.priceMinor/100)}</strong>{product.promotion?.active&&product.promotion.basePriceMinor&&<del className="text-sm font-semibold text-slate-400">{money.format(product.promotion.basePriceMinor/100)}</del>}</div>
      <p className="mt-3 text-xs font-semibold text-slate-600">{modeLabel(product)}{policy.estimatedDelivery?` · ${policy.estimatedDelivery}`:" · Confirmación previa"}</p>
      <div className="mt-auto grid grid-cols-2 gap-2.5 pt-5"><Link href={product.url??`/proyectos/lf-printer/productos/${product.slug}`} className="rounded-xl border border-slate-300 px-3 py-3 text-center text-xs font-extrabold text-slate-800 transition hover:border-slate-950">Ver producto</Link><button disabled={product.availability==="Agotado"||quantity>=(product.availableQuantity??Infinity)} onClick={add} className="rounded-xl bg-[#ffd600] px-3 py-3 text-xs font-black text-slate-950 transition hover:bg-amber-400 disabled:opacity-40">{quantity?`Agregar (${quantity})`:"Agregar"}</button></div>
    </div>
  </article>;
}
