"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Tracking={publicId:string;status:string;paymentStatus:string;updatedAt:string;lines:Array<{name:string;quantity:number;delivery?:string}>;history:Array<{status:string;at:string;note?:string}>};
const labels:Record<string,string>={pending:"Pago o condiciones pendientes",reserved:"Reserva creada",confirmed:"Confirmado","payment-pending":"Pago pendiente","payment-confirmed":"Pago confirmado","to-acquire":"Por adquirir",received:"Recibido",preparing:"Preparando",ready:"Listo para entrega",delivered:"Entregado",cancelled:"Cancelado"};

export function OrderTracking({companySlug}:{companySlug:string}){
  const[publicId,setPublicId]=useState(""),[phone,setPhone]=useState(""),[result,setResult]=useState<Tracking|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch(`/api/commerce/${companySlug}/tracking`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicId,phone})}),body=await response.json() as Tracking&{message?:string};if(!response.ok)throw new Error(body.message??"No encontramos el pedido con esos datos.");setResult(body)}catch(reason){setResult(null);setError(reason instanceof Error?reason.message:"No fue posible consultar.")}finally{setLoading(false)}}
  return <main className="min-h-screen bg-slate-950 px-4 py-12 text-white"><section className="mx-auto max-w-2xl"><Link href="/proyectos/lf-printer" className="text-sm font-bold text-amber-300">← Volver a la tienda</Link><h1 className="mt-8 text-3xl font-black">Seguimiento de pedido</h1><p className="mt-2 text-sm text-slate-400">Consulta únicamente con el número del pedido y el teléfono usado al reservar.</p><form onSubmit={submit} className="mt-8 grid gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 sm:grid-cols-2"><label className="text-xs font-bold">Número de pedido<input required value={publicId} onChange={event=>setPublicId(event.target.value)} placeholder="WEB-XXXXXXXX" className="mt-2 w-full rounded-lg bg-white p-3 text-slate-950"/></label><label className="text-xs font-bold">Teléfono<input required value={phone} onChange={event=>setPhone(event.target.value)} inputMode="tel" className="mt-2 w-full rounded-lg bg-white p-3 text-slate-950"/></label><button disabled={loading} className="rounded-lg bg-[#ffd600] p-3 font-black text-black sm:col-span-2">{loading?"Consultando…":"Consultar estado"}</button>{error&&<p role="alert" className="text-sm text-rose-300 sm:col-span-2">{error}</p>}</form>{result&&<section className="mt-6 rounded-2xl bg-white p-6 text-slate-950"><p className="text-xs font-black uppercase tracking-widest text-amber-700">{result.publicId}</p><h2 className="mt-2 text-2xl font-black">{labels[result.status]??result.status}</h2><p className="mt-1 text-sm text-slate-500">Pago: {labels[result.paymentStatus]??result.paymentStatus}</p><div className="mt-6 grid gap-2">{result.lines.map((line,index)=><p key={`${line.name}-${index}`} className="text-sm"><b>{line.quantity} ×</b> {line.name}{line.delivery?` · ${line.delivery}`:""}</p>)}</div><ol className="mt-6 border-l-2 border-amber-300 pl-5">{result.history.map((item,index)=><li key={`${item.at}-${index}`} className="mb-5"><b className="block text-sm">{labels[item.status]??item.status}</b><time className="text-xs text-slate-500">{new Date(item.at).toLocaleString("es-DO")}</time>{item.note&&<p className="text-xs text-slate-600">{item.note}</p>}</li>)}</ol></section>}</section></main>
}
