"use client";

import Link from "next/link";
import { Check, ChevronLeft, ChevronRight, Minus, Plus, ShieldCheck, ShoppingBag, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import type { PublicCommerceProduct } from "../infrastructure/commerce-presentation";
import { announceCommerceChange } from "../infrastructure/commerce-events";
import { LiaQuickPanel } from "./LiaQuickPanel";
import { PrinterVisual } from "./PrinterVisual";
import { LFPrinterCommerceFooter } from "./LFPrinterCommerceFooter";
import { orderWhatsappUrl, type PublicOrderForWhatsapp } from "../infrastructure/order-whatsapp";

const money = new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP" });

export function ProductCommerceDetail({ companySlug, product: initialProduct, related }: { companySlug: string; product: PublicCommerceProduct; related: PublicCommerceProduct[] }) {
  const [product, setProduct] = useState(initialProduct);
  const images = product.images.length ? [...product.images].sort((a,b)=>(a.purpose==='detail'?-1:b.purpose==='detail'?1:a.order-b.order)) : [{ url: "", alt: `${product.name} · Imagen pendiente`, order: 0 }];
  const [selected, setSelected] = useState(0), [quantity, setQuantity] = useState(1), [customer, setCustomer] = useState({ name: "", phone: "" }), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [liaOpen, setLiaOpen] = useState(false), [available, setAvailable] = useState(initialProduct.availableQuantity ?? (initialProduct.deliveryPolicy?.mode === "in-stock" || !initialProduct.deliveryPolicy ? 0 : 99)), [whatsappUrl, setWhatsappUrl] = useState("");
  const availability = product.deliveryPolicy?.mode === "in-stock" || !product.deliveryPolicy ? (available <= 0 ? "Agotado" : available <= 2 ? "Pocas unidades" : "Disponible") : product.availability, canReserve = availability !== "Agotado";
  const deliveryPolicy=product.deliveryPolicy??{mode:"in-stock" as const,priceType:"fixed" as const,paymentRequirement:"full" as const,estimatedDelivery:"1–2 días"},deliveryLabel={"in-stock":"En existencia","on-order":"Por encargo","confirm-availability":"Consultar disponibilidad"}[deliveryPolicy.mode];
  const activeImage = images[Math.min(selected, images.length - 1)], total = useMemo(() => product.priceMinor * quantity, [product.priceMinor, quantity]);
  async function reserve() {
    if (!customer.name.trim() || !customer.phone.trim()) { setNotice("Indica tu nombre y teléfono para reservar."); return; }
    setBusy(true); setNotice("");
    try { const response = await fetch(`/api/commerce/${companySlug}`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ customer, fulfillment: "pickup", lines: [{ slug: product.slug, quantity }] }) }); const body = await response.json() as PublicOrderForWhatsapp & { status?:string; message?: string }; if (!response.ok) throw new Error(body.message || "No pudimos reservar este producto."); setWhatsappUrl(orderWhatsappUrl(body)); const refreshed = await fetch(`/api/commerce/${companySlug}/search?q=${encodeURIComponent(product.model || product.name)}`, { cache: "no-store" }); if (refreshed.ok) { const catalog = await refreshed.json() as { products: PublicCommerceProduct[] }; const current = catalog.products.find(item => item.slug === product.slug); if (current) { setAvailable(current.availableQuantity ?? 0); setProduct(current); } } setQuantity(1); setNotice(body.status==="pending"?`Solicitud ${body.publicId} recibida. Confirmaremos precio y disponibilidad antes de cualquier pago.`:`Reserva ${body.publicId} confirmada. La disponibilidad ya está actualizada.`); announceCommerceChange(companySlug); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos reservar este producto."); } finally { setBusy(false); }
  }
  return <>
    {product.promotion?.active&&<section className="border-b border-rose-200 bg-rose-50"><div className="mx-auto flex w-[min(100%-2rem,92rem)] flex-wrap items-center gap-x-5 gap-y-1 py-3 text-sm text-rose-950"><b>{product.promotion.title??"Promoción"}</b><strong>{money.format(product.priceMinor/100)}</strong>{product.promotion.basePriceMinor&&<del className="text-slate-500">Antes {money.format(product.promotion.basePriceMinor/100)}</del>}{product.promotion.description&&<span className="w-full text-xs leading-5">{product.promotion.description}</span>}</div></section>}
    <section className="border-b border-amber-200 bg-amber-50"><div className="mx-auto flex w-[min(100%-2rem,92rem)] flex-wrap items-center gap-x-6 gap-y-2 py-3 text-xs text-amber-950"><b>{deliveryLabel}</b>{deliveryPolicy.estimatedDelivery&&<span>Entrega estimada: {deliveryPolicy.estimatedDelivery}</span>}{deliveryPolicy.priceType==="tentative"&&<strong className="text-rose-700">Precio tentativo · sujeto a confirmación antes del pago</strong>}{deliveryPolicy.customerNote&&<span>{deliveryPolicy.customerNote}</span>}</div></section>
    <section className="mx-auto grid w-[min(100%-2rem,92rem)] gap-8 py-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,.9fr)_22rem] lg:py-12">
      <div><div className="relative aspect-square overflow-hidden rounded-3xl border border-slate-200 bg-white"><PrinterVisual src={activeImage.url || undefined} alt={activeImage.alt || product.name} priority/><button aria-label="Imagen anterior" disabled={selected === 0} onClick={() => setSelected(value => value - 1)} className="absolute left-4 top-1/2 grid size-10 -translate-y-1/2 place-items-center rounded-full bg-white/90 shadow disabled:hidden"><ChevronLeft/></button><button aria-label="Imagen siguiente" disabled={selected === images.length - 1} onClick={() => setSelected(value => value + 1)} className="absolute right-4 top-1/2 grid size-10 -translate-y-1/2 place-items-center rounded-full bg-white/90 shadow disabled:hidden"><ChevronRight/></button></div>{images.length > 1 && <div className="mt-3 flex gap-3 overflow-x-auto">{images.map((image, index) => <button key={`${image.url}-${index}`} onClick={() => setSelected(index)} className={`relative size-20 shrink-0 overflow-hidden rounded-xl border bg-white ${selected === index ? "border-cyan-500 ring-2 ring-cyan-200" : "border-slate-200"}`}><PrinterVisual src={image.url || undefined} alt={image.alt || product.name} compact/></button>)}</div>}</div>
      <div className="py-2"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-700">{product.category}</p><h1 className="mt-4 text-3xl font-black leading-tight tracking-[-.035em] sm:text-5xl">{product.name}</h1>{product.model && <p className="mt-3 text-sm font-bold text-slate-500">Modelo {product.model}</p>}<p className="mt-6 text-base leading-8 text-slate-600">{product.description || "Consulta las características publicadas y confirma disponibilidad antes de reservar."}</p>{product.features.length > 0 && <div className="mt-7"><h2 className="text-sm font-black">Características publicadas</h2><ul className="mt-4 space-y-3">{product.features.map(feature => <li key={feature} className="flex gap-3 text-sm leading-6 text-slate-700"><Check className="mt-1 shrink-0 text-emerald-600" size={16}/>{feature}</li>)}</ul></div>}{(product.compatibility?.length ?? 0) > 0 && <div className="mt-7"><h2 className="text-sm font-black">Compatibilidad</h2><div className="mt-3 flex flex-wrap gap-2">{product.compatibility!.map(item => <span key={item} className="rounded-full bg-slate-100 px-3 py-2 text-xs text-slate-700">{item}</span>)}</div></div>}<button onClick={() => setLiaOpen(value => !value)} className="mt-8 flex items-center gap-3 rounded-2xl border border-violet-200 bg-violet-50 px-5 py-4 text-left text-sm text-violet-950"><Sparkles className="text-violet-600"/><span><b className="block">¿No sabes si te conviene?</b> Pregúntale a Lía sobre este producto.</span></button></div>
      <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_18px_60px_rgba(15,23,42,.08)] lg:sticky lg:top-6"><strong className="text-3xl">{money.format(product.priceMinor / 100)}</strong><p className={`mt-4 text-sm font-black ${canReserve ? "text-emerald-700" : "text-rose-700"}`}>{product.availability}{product.availableQuantity !== undefined ? ` · ${product.availableQuantity} unidades` : ""}</p><p className="mt-3 flex gap-2 text-xs leading-5 text-slate-500"><ShieldCheck size={16} className="shrink-0 text-cyan-700"/>Precio y disponibilidad validados por el sistema empresarial.</p><div className="mt-6 flex items-center justify-between rounded-xl border border-slate-200 p-2"><span className="pl-2 text-sm font-bold">Cantidad</span><div className="flex items-center gap-3"><button aria-label="Restar" disabled={quantity <= 1} onClick={() => setQuantity(value => Math.max(1, value - 1))} className="grid size-9 place-items-center rounded-lg bg-slate-100 disabled:opacity-30"><Minus size={15}/></button><b>{quantity}</b><button aria-label="Agregar" disabled={quantity >= available} onClick={() => setQuantity(value => Math.min(available, value + 1))} className="grid size-9 place-items-center rounded-lg bg-slate-100 disabled:opacity-30"><Plus size={15}/></button></div></div><div className="mt-5 flex justify-between border-t border-slate-100 pt-5"><span className="text-sm text-slate-500">Total</span><b>{money.format(total / 100)}</b></div><label className="mt-5 block text-xs font-bold text-slate-600">Nombre<input value={customer.name} onChange={event => setCustomer(current => ({ ...current, name: event.target.value }))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-cyan-500"/></label><label className="mt-4 block text-xs font-bold text-slate-600">Teléfono<input value={customer.phone} onChange={event => setCustomer(current => ({ ...current, phone: event.target.value }))} inputMode="tel" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-cyan-500"/></label><button disabled={!canReserve || busy} onClick={() => void reserve()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-4 text-sm font-black text-slate-950 disabled:opacity-40"><ShoppingBag size={17}/>{busy ? "Reservando…" : "Reservar producto"}</button>{notice && <p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-xs leading-5 text-slate-700">{notice}</p>}<p className="mt-4 text-center text-[11px] leading-5 text-slate-400">La reserva mantiene la mercancía durante 15 minutos. No se realiza un cobro en línea.</p></aside>
    </section>
    {whatsappUrl&&<section className="mx-auto -mt-5 mb-10 w-[min(100%-2rem,92rem)]"><a href={whatsappUrl} target="_blank" rel="noreferrer" className="ml-auto flex w-full max-w-[22rem] items-center justify-center rounded-xl bg-emerald-500 px-4 py-4 text-sm font-black text-emerald-950 shadow-lg">Continuar pago por WhatsApp</a></section>}
    {liaOpen && <section id="lia-producto" className="mx-auto mb-12 grid w-[min(100%-2rem,92rem)] overflow-hidden rounded-3xl bg-[#090b18] text-white lg:grid-cols-[.8fr_1.2fr]"><div className="p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-300">Lía · Asesora de compra</p><h2 className="mt-4 text-3xl font-black">Pregunta por {product.model || product.name}.</h2><p className="mt-4 text-sm leading-7 text-slate-300">Lía responderá usando solamente información pública del catálogo.</p></div><LiaQuickPanel companySlug={companySlug}/></section>}
    {related.length > 0 && <section className="border-t border-slate-200 bg-slate-50 py-14"><div className="mx-auto w-[min(100%-2rem,92rem)]"><h2 className="text-2xl font-black">También puedes explorar</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{related.map(item => <Link key={item.slug} href={item.url ?? `/proyectos/lf-printer/productos/${item.slug}`} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-cyan-400"><span className="text-xs font-bold text-cyan-700">{item.category}</span><strong className="mt-2 block leading-6">{item.name}</strong><b className="mt-4 block">{money.format(item.priceMinor / 100)}</b></Link>)}</div></div></section>}
    <LFPrinterCommerceFooter/>
  </>;
}
