import { randomUUID } from "node:crypto";
import { CapabilityDeniedError } from "../domain/errors";
import type { ActorContext, Capability } from "../domain/types";
import type { ChapterTwoState, ChapterTwoStore } from "../chapter-two/types";
import { selectFiscalTreatment } from "../fiscal/FiscalRuleRegistry";

export type ReportType = ChapterTwoState["reportRuns"][number]["reportType"];
export type ReportPeriod = { from: string; to: string };

export class ReportingService {
  constructor(private readonly store: ChapterTwoStore, private readonly now: () => Date = () => new Date(), private readonly id: () => string = randomUUID) {}
  private require(actor: ActorContext, capability: Capability) { if (!actor.capabilities.includes(capability)) throw new CapabilityDeniedError(capability); }
  private period(input: ReportPeriod) { const from = new Date(`${input.from}T00:00:00.000Z`), to = new Date(`${input.to}T23:59:59.999Z`); if (!input.from || !input.to || Number.isNaN(from.getTime()) || Number.isNaN(to.getTime()) || from > to) throw new Error("invalid_report_period"); return { from, to }; }
  private own<T extends { tenantId: string; companyId: string }>(actor: ActorContext, values: T[]) { return values.filter(value => value.tenantId === actor.tenantId && value.companyId === actor.companyId); }
  private async record(actor: ActorContext, reportType: ReportType, period: ReportPeriod, resultCount: number, exported = false) { await this.store.transact(state => { state.reportRuns.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, reportType, periodFrom: period.from, periodTo: period.to, resultCount, exported, createdAt: this.now().toISOString() }); state.audit.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, action: exported ? "report.exported" : "report.generated", entityId: reportType, traceId: actor.traceId, at: this.now().toISOString() }); }); }
  async sales(actor: ActorContext, period: ReportPeriod, exported = false) { this.require(actor, "report.sales"); const range = this.period(period), state = await this.store.snapshot(), events = this.own(actor, state.events); const dateOf = (id: string, explicit?: string) => explicit ?? events.find(event => event.aggregateId === id && event.name === "InvoiceIssued")?.occurredAt; const rows = this.own(actor, state.invoices).map(invoice => ({ ...invoice, occurredAt: dateOf(invoice.id, invoice.createdAt) })).filter(row => row.occurredAt && new Date(row.occurredAt) >= range.from && new Date(row.occurredAt) <= range.to).map(row => ({ invoiceId: row.id, occurredAt: row.occurredAt!, customerId: row.customerId, sourceType: row.sourceType, subtotalMinor: row.subtotalMinor ?? row.totalMinor, discountMinor: row.discountMinor ?? 0, taxableBaseMinor: row.taxableBaseMinor ?? Math.max(0, row.totalMinor - (row.taxMinor ?? 0)), taxMinor: row.taxMinor ?? 0, totalMinor: row.totalMinor, paidMinor: row.paidMinor, status: row.status })); await this.record(actor, "sales", period, rows.length, exported); return { type: "sales", period, rows, totals: rows.reduce((sum, row) => ({ subtotalMinor: sum.subtotalMinor + row.subtotalMinor, taxMinor: sum.taxMinor + row.taxMinor, totalMinor: sum.totalMinor + row.totalMinor, paidMinor: sum.paidMinor + row.paidMinor }), { subtotalMinor: 0, taxMinor: 0, totalMinor: 0, paidMinor: 0 }) }; }
  async inventory(actor: ActorContext, asOf: string, exported = false) { this.require(actor, "report.inventory"); const period = { from: asOf, to: asOf }, range = this.period(period), state = await this.store.snapshot(), company = state.platformCompanies.find(item => item.id === actor.companyId), fallback = company?.createdAt ?? "1970-01-01T00:00:00.000Z"; const movements = this.own(actor, state.inventory).filter(item => new Date(item.occurredAt ?? fallback) <= range.to); const rows = this.own(actor, state.products).map(product => { const related = movements.filter(item => item.productId === product.id); const quantity = related.reduce((sum, item) => sum + item.delta, 0); return { productId: product.id, sku: product.sku, name: product.name, quantity, costMinor: actor.capabilities.includes("product.cost.read") ? product.costMinor ?? null : null, valueMinor: actor.capabilities.includes("product.cost.read") ? quantity * (product.costMinor ?? 0) : null, movementCount: related.length }; }); await this.record(actor, "inventory", period, rows.length, exported); return { type: "inventory", asOf, rows, dateQuality: movements.some(item => !item.occurredAt) ? "legacy-fallback" : "exact" }; }
  async expenses(actor: ActorContext, period: ReportPeriod, exported = false) { this.require(actor, "report.expenses"); const range = this.period(period), rows = this.own(actor, (await this.store.snapshot()).expenses).filter(item => new Date(item.occurredAt) >= range.from && new Date(item.occurredAt) <= range.to); await this.record(actor, "expenses", period, rows.length, exported); return { type: "expenses", period, rows, totals: rows.reduce((sum, row) => ({ amountMinor: sum.amountMinor + row.amountMinor, taxMinor: sum.taxMinor + row.taxMinor }), { amountMinor: 0, taxMinor: 0 }) }; }
  async fiscalPreparation(actor: ActorContext, type: "dgii-606" | "dgii-607" | "dgii-it1", period: ReportPeriod) { this.require(actor, "report.fiscal.prepare"); this.period(period); const state = await this.store.snapshot(), profile = state.fiscalConfigurations.find(item => item.tenantId === actor.tenantId && item.companyId === actor.companyId), treatment = selectFiscalTreatment(profile?.taxRegime ?? "traditional", type); const canonical = type === "dgii-606" ? await this.expenses(actor, period) : await this.sales(actor, period); await this.record(actor, type, period, canonical.rows.length); return { type, period, status: "official-adapter-disabled", ...treatment, officialFields: null, canonicalData: canonical, notice: "Datos canónicos preparados para revisión. No constituyen declaración ni transmisión a DGII." }; }
  async createExpense(actor: ActorContext, input: { category: string; description: string; amountMinor: number; taxMinor?: number; occurredAt: string; supplierId?: string; documentReference?: string; paymentMethod?: string }) { this.require(actor, "expense.create"); if (!input.category.trim() || !input.description.trim() || !Number.isInteger(input.amountMinor) || input.amountMinor <= 0 || !input.occurredAt) throw new Error("invalid_expense"); return this.store.transact(state => { if (input.supplierId && !state.suppliers.some(item => item.id === input.supplierId && item.companyId === actor.companyId)) throw new Error("access_denied"); const expense = { id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, supplierId: input.supplierId, category: input.category.trim(), description: input.description.trim(), amountMinor: input.amountMinor, taxMinor: input.taxMinor ?? 0, occurredAt: new Date(input.occurredAt).toISOString(), documentReference: input.documentReference, paymentMethod: input.paymentMethod, createdBy: actor.userId, createdAt: this.now().toISOString() }; state.expenses.push(expense); state.audit.push({ id: this.id(), tenantId: actor.tenantId, companyId: actor.companyId, userId: actor.userId, action: "expense.created", entityId: expense.id, traceId: actor.traceId, at: this.now().toISOString() }); return expense; }); }
}
