import { createHash, createHmac, randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import type { ActorContext, CompanyId, TenantId, UserId } from "../domain/types";
import type { ChapterTwoStore } from "../chapter-two/types";

interface SessionPayload { sessionId: string; userId: UserId; tenantId: TenantId; companyId: CompanyId; expiresAt: number; sessionVersion: number }
export class BusinessIdentity {
  constructor(private readonly store: ChapterTwoStore, private readonly secret: string) { if (secret.length < 32) throw new Error("BUSINESS_SESSION_SECRET must contain at least 32 characters"); }
  async provisionAccount(input: { email: string; password: string; tenantId: TenantId; companyId: CompanyId; userId?: UserId; capabilities: ActorContext["capabilities"]; name?: string; roleId?: string; branchIds?: string[] }) {
    const salt = randomBytes(16).toString("hex"), requestedUserId = input.userId ?? randomUUID() as UserId;
    await this.store.transact(state => { let user=state.users.find(item=>item.email===input.email.toLowerCase());if(!user){user={id:requestedUserId,email:input.email.toLowerCase(),salt,passwordHash:this.hash(input.password,salt),status:"active",name:input.name,sessionVersion:0};state.users.push(user);}const membership=state.memberships.find(m=>m.userId===user!.id&&m.tenantId===input.tenantId&&m.companyId===input.companyId);if(!membership)state.memberships.push({tenantId:input.tenantId,companyId:input.companyId,userId:user.id,capabilities:input.capabilities,status:"active",roleId:input.roleId,branchIds:input.branchIds});else{membership.capabilities=input.capabilities;if(input.roleId)membership.roleId=input.roleId;if(input.branchIds)membership.branchIds=input.branchIds;}});
  }
  async availableCompanies(email:string,password:string){const{state,user}=await this.authenticate(email,password);return state.memberships.filter(m=>m.userId===user.id&&m.status==="active").map(m=>({tenantId:m.tenantId,companyId:m.companyId,name:state.platformCompanies.find(c=>c.id===m.companyId)?.name??m.companyId}));}
  async login(email:string,password:string,requestedCompanyId?:CompanyId){const{state,user}=await this.authenticate(email,password);const memberships=state.memberships.filter(item=>item.userId===user.id&&item.status==="active");if(!memberships.length)throw new Error("access_denied");const membership=requestedCompanyId?memberships.find(m=>m.companyId===requestedCompanyId):memberships.length===1?memberships[0]:undefined;if(!membership)throw new Error(requestedCompanyId?"access_denied":"company_selection_required");const company=state.platformCompanies.find(c=>c.id===membership.companyId);if(company&&company.status!=="active"&&company.status!=="trial")throw new Error("company_suspended");const sessionId=randomUUID(),expiresAt=Date.now()+8*60*60*1000,now=new Date().toISOString(),sessionVersion=user.sessionVersion??0;await this.store.transact(s=>{s.businessSessions.push({id:sessionId,tenantId:membership.tenantId,companyId:membership.companyId,userId:user.id,branchId:membership.branchIds?.[0],issuedAt:now,expiresAt:new Date(expiresAt).toISOString(),lastSeenAt:now,status:"active"});const stored=s.users.find(u=>u.id===user.id);if(stored)stored.lastAccessAt=now;const storedCompany=s.platformCompanies.find(c=>c.id===membership.companyId);if(storedCompany)storedCompany.lastAccessAt=now;});return this.seal({sessionId,userId:user.id,tenantId:membership.tenantId,companyId:membership.companyId,expiresAt,sessionVersion});}
  async requireActor(token:string|undefined,traceId:string=randomUUID()):Promise<ActorContext>{const payload=this.open(token),state=await this.store.snapshot(),user=state.users.find(u=>u.id===payload.userId&&u.status==="active");if(!user||(user.sessionVersion??0)!==payload.sessionVersion)throw new Error("authentication_required");const session=state.businessSessions.find(s=>s.id===payload.sessionId&&s.status==="active"&&new Date(s.expiresAt).getTime()>Date.now());if(!session)throw new Error("authentication_required");if(session.supportGrantId){const grant=state.supportGrants.find(g=>g.id===session.supportGrantId&&g.status==="active"&&new Date(g.expiresAt).getTime()>Date.now());if(!grant)throw new Error("support_grant_expired");}const membership=state.memberships.find(item=>item.userId===payload.userId&&item.tenantId===payload.tenantId&&item.companyId===payload.companyId&&item.status==="active");if(!membership)throw new Error("authentication_required");const company=state.platformCompanies.find(c=>c.id===payload.companyId);if(company&&company.status!=="active"&&company.status!=="trial")throw new Error("company_suspended");return{userId:payload.userId,tenantId:payload.tenantId,companyId:payload.companyId,capabilities:membership.capabilities,traceId,sessionId:session.id,branchId:session.branchId,supportGrantId:session.supportGrantId};}
  async issueSupportSession(input:{tenantId:TenantId;companyId:CompanyId;grantId:string;expiresAt:string}){const userId=`laex-support-${input.companyId}` as UserId,sessionId=randomUUID(),now=new Date().toISOString(),capabilities=["dashboard.view","support.diagnose"] as const;await this.store.transact(state=>{let user=state.users.find(u=>u.id===userId);if(!user){const salt=randomBytes(16).toString("hex");user={id:userId,email:`support+${input.companyId}@laex.local`,name:"Soporte LAEX",salt,passwordHash:this.hash(randomBytes(32).toString("hex"),salt),status:"active",sessionVersion:0};state.users.push(user);}const membership=state.memberships.find(m=>m.userId===userId&&m.companyId===input.companyId);if(!membership)state.memberships.push({tenantId:input.tenantId,companyId:input.companyId,userId,capabilities,status:"active"});else{membership.capabilities=capabilities;membership.status="active";}state.businessSessions.push({id:sessionId,tenantId:input.tenantId,companyId:input.companyId,userId,issuedAt:now,expiresAt:input.expiresAt,lastSeenAt:now,status:"active",supportGrantId:input.grantId});});return this.seal({sessionId,userId,tenantId:input.tenantId,companyId:input.companyId,expiresAt:new Date(input.expiresAt).getTime(),sessionVersion:0});}
  async revokeSession(sessionId:string,companyId:CompanyId,revokedBy:string,reason:string){return this.store.transact(state=>{const session=state.businessSessions.find(s=>s.id===sessionId&&s.companyId===companyId);if(!session)throw new Error("session_not_found");session.status="revoked";session.revokedAt=new Date().toISOString();session.revokedBy=revokedBy;session.revokeReason=reason;state.audit.push({id:randomUUID(),tenantId:session.tenantId,companyId:session.companyId,userId:revokedBy as UserId,action:"session.revoked",entityId:session.id,traceId:randomUUID(),at:new Date().toISOString()});return{revoked:true};});}
  async revokeCompanySessions(companyId:CompanyId,revokedBy:string,reason:string){return this.store.transact(state=>{let count=0;for(const session of state.businessSessions)if(session.companyId===companyId&&session.status==="active"){session.status="revoked";session.revokedAt=new Date().toISOString();session.revokedBy=revokedBy;session.revokeReason=reason;count++;}const company=state.platformCompanies.find(c=>c.id===companyId);if(company)state.audit.push({id:randomUUID(),tenantId:company.tenantId,companyId,userId:revokedBy as UserId,action:"company.sessions.revoked",entityId:companyId,traceId:randomUUID(),at:new Date().toISOString()});return{revoked:count};});}
  async logout(token?:string){try{const payload=this.open(token);await this.store.transact(state=>{const session=state.businessSessions.find(s=>s.id===payload.sessionId);if(session&&session.status==="active"){session.status="revoked";session.revokedAt=new Date().toISOString();session.revokedBy=payload.userId;session.revokeReason="logout";}});}catch{/* Clearing an invalid cookie remains safe. */}}
  async changePassword(actor:ActorContext,currentPassword:string,newPassword:string){if(newPassword.length<12)throw new Error("password_too_short");return this.store.transact(state=>{const user=state.users.find(item=>item.id===actor.userId&&item.status==="active");if(!user||!this.equal(user.passwordHash,this.hash(currentPassword,user.salt)))throw new Error("invalid_credentials");const salt=randomBytes(16).toString("hex");user.salt=salt;user.passwordHash=this.hash(newPassword,salt);user.passwordChangedAt=new Date().toISOString();user.mustChangePassword=false;user.sessionVersion=(user.sessionVersion??0)+1;for(const session of state.businessSessions)if(session.userId===user.id&&session.status==="active"){session.status="revoked";session.revokedAt=new Date().toISOString();session.revokedBy=user.id;session.revokeReason="password_changed";}state.audit.push({id:randomUUID(),tenantId:actor.tenantId,companyId:actor.companyId,userId:actor.userId,action:"identity.password.changed",entityId:user.id,traceId:actor.traceId,at:new Date().toISOString()});return{changed:true}})}
  async issuePasswordToken(actor:ActorContext,userId:UserId,purpose:"activation"|"recovery"){if(!(actor.capabilities as readonly string[]).includes("user.manage"))throw new Error("capability_denied:user.manage");const token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),now=Date.now();await this.store.transact(state=>{const user=state.users.find(item=>item.id===userId),membership=state.memberships.find(item=>item.userId===userId&&item.companyId===actor.companyId&&item.status==="active");if(!user||!membership)throw new Error("access_denied");for(const existing of state.passwordTokens)if(existing.userId===userId&&existing.purpose===purpose&&!existing.usedAt)existing.usedAt=new Date().toISOString();state.passwordTokens.push({id:randomUUID(),tenantId:actor.tenantId,companyId:actor.companyId,userId,tokenHash,purpose,expiresAt:new Date(now+30*60*1000).toISOString(),createdBy:actor.userId,createdAt:new Date(now).toISOString()});state.audit.push({id:randomUUID(),tenantId:actor.tenantId,companyId:actor.companyId,userId:actor.userId,action:`identity.${purpose}.issued`,entityId:userId,traceId:actor.traceId,at:new Date(now).toISOString()})});return{token,expiresAt:new Date(now+30*60*1000).toISOString()}}
  async consumePasswordToken(companyId:CompanyId,token:string,newPassword:string){if(newPassword.length<12)throw new Error("password_too_short");const tokenHash=createHash("sha256").update(token).digest("hex");return this.store.transact(state=>{const record=state.passwordTokens.find(item=>item.companyId===companyId&&item.tokenHash===tokenHash&&!item.usedAt&&new Date(item.expiresAt).getTime()>Date.now()),user=record&&state.users.find(item=>item.id===record.userId);if(!record||!user)throw new Error("invalid_or_expired_token");const salt=randomBytes(16).toString("hex");user.salt=salt;user.passwordHash=this.hash(newPassword,salt);user.passwordChangedAt=new Date().toISOString();user.mustChangePassword=false;user.sessionVersion=(user.sessionVersion??0)+1;record.usedAt=new Date().toISOString();for(const session of state.businessSessions)if(session.userId===user.id&&session.status==="active"){session.status="revoked";session.revokedAt=new Date().toISOString();session.revokedBy=user.id;session.revokeReason=`${record.purpose}_completed`;}state.audit.push({id:randomUUID(),tenantId:record.tenantId,companyId:record.companyId,userId:user.id,action:`identity.${record.purpose}.completed`,entityId:user.id,traceId:randomUUID(),at:new Date().toISOString()});return{changed:true}})}
  private async authenticate(email:string,password:string){const state=await this.store.snapshot(),user=state.users.find(item=>item.email===email.toLowerCase()&&item.status==="active");if(!user||!this.equal(user.passwordHash,this.hash(password,user.salt)))throw new Error("invalid_credentials");return{state,user};}
  private seal(payload:SessionPayload){const body=Buffer.from(JSON.stringify(payload)).toString("base64url");return`${body}.${createHmac("sha256",this.secret).update(body).digest("base64url")}`;}
  private open(token?:string):SessionPayload{try{if(!token)throw new Error();const[body,signature]=token.split("."),expected=createHmac("sha256",this.secret).update(body).digest(),supplied=Buffer.from(signature,"base64url");if(expected.length!==supplied.length||!timingSafeEqual(expected,supplied))throw new Error();const payload=JSON.parse(Buffer.from(body,"base64url").toString("utf8"))as SessionPayload;if(payload.expiresAt<=Date.now()||!payload.sessionId)throw new Error();return payload;}catch{throw new Error("authentication_required");}}
  private hash(password:string,salt:string){return scryptSync(password,salt,64).toString("hex");}
  private equal(left:string,right:string){const a=Buffer.from(left,"hex"),b=Buffer.from(right,"hex");return a.length===b.length&&timingSafeEqual(a,b);}
}
