import type { MarketAsset, PromotionPackage } from "./domain";

const base = { updatedAt: "2026-08-02T12:00:00-04:00", source: "Dataset LAEX de demostración", simulated: true as const };
const score = (value: number, interpretation: string, confidence: number, factors: [string, number, string][], limitations: string[] = ["Datos simulados; no usar para decisiones financieras."]) => ({ value, interpretation, confidence, factors: factors.map(([label, factorValue, explanation]) => ({ label, value: factorValue, explanation, source: "Metodología LAEX v0.1" })), limitations, assessedAt: base.updatedAt, methodologyVersion: "LAEX-MI-0.1" });

export const assets: MarketAsset[] = [
  { assetId:"asset_btc_mainnet", slug:"bitcoin", symbol:"BTC", name:"Bitcoin", blockchain:"Bitcoin", contractAddress:null, providerId:"bitcoin", pairs:["BTC/USDT","BTC/USD"], markets:["Mercado global agregado"], verification:"contract-verified", listingStatus:"covered", coverage:"continuous", presence:"public-coverage", sponsored:false, summary:"Activo digital descentralizado con alta profundidad de mercado y cobertura editorial pública.", metric:{...base,price:64218.42,change1h:0.31,change24h:2.46,change7d:-1.18,high24h:65102,low24h:61980,volume24h:28400000000,marketCap:1267000000000,liquidity:910000000,circulatingSupply:19720000,totalSupply:21000000}, trust:score(88,"Señales sólidas con riesgo de volatilidad",94,[["Liquidez",96,"Profundidad amplia en múltiples mercados"],["Transparencia",86,"Datos públicos y red auditable"],["Concentración",72,"Distribución relevante en grandes tenedores"]]), risk:score(34,"Riesgo moderado",92,[["Volatilidad",58,"Variaciones significativas continúan siendo posibles"],["Actividad",89,"Mercado activo y observable"]]), liquidityScore:score(96,"Liquidez profunda",96,[["Spread",95,"Diferencial simulado reducido"],["Profundidad",97,"Órdenes distribuidas en ambos lados"]]), conflicts:{ecosystemLinked:false,laexHoldsAsset:false,activeCampaign:false,analystRelationship:false,statement:"Sin relación comercial declarada. Cobertura editorial pública."}, chart:[42,44,43,46,49,48,52,55,53,57,60,58,62,65,64,68,70,67,72,74]},
  { assetId:"asset_eth_mainnet", slug:"ethereum", symbol:"ETH", name:"Ethereum", blockchain:"Ethereum", contractAddress:null, providerId:"ethereum", pairs:["ETH/USDT","ETH/USD"], markets:["Mercado global agregado"], verification:"contract-verified", listingStatus:"covered", coverage:"continuous", presence:"public-coverage", sponsored:false, summary:"Infraestructura programable de referencia con actividad de red y liquidez elevadas.", metric:{...base,price:3184.22,change1h:-0.12,change24h:1.72,change7d:3.84,high24h:3240,low24h:3098,volume24h:14200000000,marketCap:382000000000,liquidity:530000000,circulatingSupply:120100000,totalSupply:null}, trust:score(84,"Fortaleza alta con complejidad operativa",91,[["Liquidez",91,"Mercados profundos"],["Actividad",88,"Ecosistema ampliamente utilizado"],["Estabilidad",72,"Sensibilidad a ciclos de mercado"]]), risk:score(39,"Riesgo moderado",89,[["Volatilidad",55,"Exposición a ciclos"],["Calidad de información",91,"Fuentes múltiples disponibles"]]), liquidityScore:score(91,"Liquidez alta",93,[["Spread",92,"Diferencial simulado contenido"],["Profundidad",90,"Profundidad consistente"]]), conflicts:{ecosystemLinked:false,laexHoldsAsset:false,activeCampaign:false,analystRelationship:false,statement:"Sin relación comercial declarada. Cobertura editorial pública."}, chart:[39,41,43,42,45,49,47,51,54,52,55,58,60,59,63,62,66,69,71,73]},
  { assetId:"asset_omd_bsc_0x01", slug:"omd", symbol:"OMD", name:"OMD Token", blockchain:"BNB Smart Chain", contractAddress:"0x01...OMD-DEMO", providerId:"omd-demo", pairs:["OMD/USDT"], markets:["Mercado simulado LAEX"], verification:"identity-verified", listingStatus:"review", coverage:"standard", presence:"verified", sponsored:false, summary:"Caso de estudio del ecosistema con información institucional verificada y señales de mercado todavía limitadas.", metric:{...base,price:0.0842,change1h:1.2,change24h:-4.8,change7d:12.4,high24h:0.091,low24h:0.078,volume24h:184000,marketCap:8420000,liquidity:410000,circulatingSupply:100000000,totalSupply:500000000}, trust:score(62,"Información verificada; mercado en desarrollo",78,[["Transparencia",76,"Identidad y documentación básica revisadas"],["Liquidez",48,"Profundidad limitada"],["Comunidad",71,"Actividad emergente"]]), risk:score(68,"Riesgo elevado",82,[["Concentración",71,"Distribución requiere vigilancia"],["Volatilidad",76,"Movimientos amplios con volumen limitado"]]), liquidityScore:score(48,"Liquidez limitada",80,[["Spread",44,"Diferencial simulado amplio"],["Profundidad",51,"Capacidad limitada para órdenes grandes"]]), conflicts:{ecosystemLinked:true,laexHoldsAsset:false,activeCampaign:false,analystRelationship:false,statement:"Activo vinculado al ecosistema LAEX. La evaluación utiliza la misma metodología y no recibe ajustes preferenciales."}, chart:[22,28,25,34,31,38,44,41,49,46,55,51,61,57,66,60,70,64,74,69]},
  { assetId:"asset_laex_planned", slug:"laex", symbol:"LAEX", name:"LAEX Token (concepto)", blockchain:"LAEX Network (planned)", contractAddress:null, providerId:"not-issued", pairs:[], markets:[], verification:"unverified", listingStatus:"review", coverage:"essential", presence:"claimed", sponsored:false, summary:"Ejemplo conceptual. El token LAEX no existe como activo negociable en este laboratorio.", metric:{...base,price:0,change1h:0,change24h:0,change7d:0,high24h:0,low24h:0,volume24h:0,marketCap:null,liquidity:0,circulatingSupply:null,totalSupply:null}, trust:score(0,"No evaluable: activo no emitido",100,[["Disponibilidad",0,"No existe mercado ni contrato aprobado"]],["No hay datos de mercado ni activo real."]), risk:score(100,"No apto para evaluación de mercado",100,[["Existencia",0,"Activo exclusivamente conceptual"]]), liquidityScore:score(0,"Sin mercado disponible",100,[["Liquidez",0,"No existen pares ni mercados"]]), conflicts:{ecosystemLinked:true,laexHoldsAsset:false,activeCampaign:false,analystRelationship:false,statement:"Activo vinculado al ecosistema LAEX y claramente identificado como concepto futuro. No está a la venta."}, chart:[0,0,0,0,0,0,0,0,0,0,0,0]},
];

export const packages: PromotionPackage[] = [
  {id:"evaluation",name:"Solicitud de evaluación",category:"evaluation",currency:null,taxPolicy:null,duration:null,scope:["Verificación inicial","Revisión documental","Ficha y análisis","Derecho de respuesta"],exclusions:["Puntuación favorable","Promoción","Publicación automática"],configurable:true},
  {id:"verified",name:"Perfil verificado",category:"verification",currency:null,taxPolicy:null,duration:null,scope:["Identidad y contrato","Enlaces oficiales","Documentación ampliada","Panel del representante"],exclusions:["Recomendación financiera","Garantía de calidad"],configurable:true},
  {id:"continuous",name:"Inteligencia continua",category:"monitoring",currency:null,taxPolicy:null,duration:null,scope:["Monitoreo","Alertas","Informes periódicos","Actualización de indicadores"],exclusions:["Evolución positiva garantizada"],configurable:true},
  {id:"promotion",name:"Promoción dentro de LAEX",category:"promotion",currency:null,taxPolicy:null,duration:null,scope:["Espacios identificados","Periodo de campaña","Divulgación obligatoria"],exclusions:["Edición del análisis","Ocultar riesgos"],configurable:true},
  {id:"distribution",name:"Distribución en redes",category:"distribution",currency:null,taxPolicy:null,duration:null,scope:["Canales oficiales autorizados","Publicaciones identificadas"],exclusions:["Resultados o conversiones garantizadas"],configurable:true},
  {id:"production",name:"Producción audiovisual",category:"production",currency:null,taxPolicy:null,duration:null,scope:["Video","Short/Reel","Guion","Edición y miniatura"],exclusions:["Presentación de publicidad como análisis"],configurable:true},
  {id:"launch",name:"Lanzamiento integral",category:"launch",currency:null,taxPolicy:null,duration:null,scope:["Evaluación","Perfil","Contenido","Campaña","Analytics"],exclusions:["Puntuación negociable","Garantía comercial"],configurable:true},
];
