"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_test_1 = require("node:test");
const MarketDataOrchestrator_1 = require("../../modules/market-intelligence/application/MarketDataOrchestrator");
const MarketNarrative_1 = require("../../modules/market-intelligence/application/MarketNarrative");
const catalog_1 = require("../../modules/market-intelligence/domain/catalog");
const bitcoin = (0, catalog_1.findMarketAsset)("bitcoin");
function data(asset, provider, price = 100) { const at = new Date().toISOString(); return { identity: asset, quote: { assetId: asset.assetId, price, change24h: 2, volume24h: 1000, marketCap: 10000, high24h: 105, low24h: 95, circulatingSupply: 100, totalSupply: 200, observedAt: at, provider, state: "live", staleAfterSeconds: 60 }, candles: [{ timestamp: 1, open: 99, high: 102, low: 98, close: 100, volume: 10 }], venues: [{ name: "Venue A", pair: "BTC/USD", price, volume: 10, spread: .1, observedAt: at, quality: "high", provider }], provenance: [`${provider}:quote`], generatedAt: at }; }
class FakeProvider {
    constructor(id, behavior) {
        this.id = id;
        this.behavior = behavior;
        this.calls = 0;
    }
    supports() { return true; }
    async fetchBundle(asset, _interval, _signal) { this.calls++; const result = this.behavior(asset); if (result instanceof Error)
        throw result; return result; }
}
(0, node_test_1.describe)("identidad y catálogo", () => { (0, node_test_1.it)("usa identidades internas únicas y no depende del símbolo", () => { var _a; strict_1.default.equal(new Set(catalog_1.marketCatalog.map(a => a.assetId)).size, catalog_1.marketCatalog.length); strict_1.default.ok(catalog_1.marketCatalog.every(a => a.assetId && a.networkId && a.symbol)); strict_1.default.equal((_a = (0, catalog_1.findMarketAsset)("solana")) === null || _a === void 0 ? void 0 : _a.providerId, "solana"); }); (0, node_test_1.it)("mantiene OMD pendiente y LAEX conceptual", () => { var _a, _b; strict_1.default.equal((_a = (0, catalog_1.findMarketAsset)("omd")) === null || _a === void 0 ? void 0 : _a.status, "identity-pending"); strict_1.default.equal((_b = (0, catalog_1.findMarketAsset)("laex")) === null || _b === void 0 ? void 0 : _b.status, "conceptual"); }); });
(0, node_test_1.describe)("orquestación resiliente", () => { (0, node_test_1.it)("cachea y deduplica lecturas", async () => { const provider = new FakeProvider("primary", asset => data(asset, "primary")), service = new MarketDataOrchestrator_1.MarketDataOrchestrator([provider], 10000); const [first, second] = await Promise.all([service.get(bitcoin, "1h"), service.get(bitcoin, "1h")]); strict_1.default.equal(provider.calls, 1); strict_1.default.equal(first.quote.price, second.quote.price); strict_1.default.equal((await service.get(bitcoin, "1h")).cache, "hit"); }); (0, node_test_1.it)("activa proveedor secundario sin mezclar procedencia", async () => { const primary = new FakeProvider("primary", () => new Error("down")), secondary = new FakeProvider("secondary", asset => data(asset, "secondary", 101)), service = new MarketDataOrchestrator_1.MarketDataOrchestrator([primary, secondary]); const result = await service.get(bitcoin, "1h"); strict_1.default.equal(result.fallbackUsed, true); strict_1.default.equal(result.quote.provider, "secondary"); strict_1.default.deepEqual(result.provenance, ["secondary:quote"]); }); (0, node_test_1.it)("sirve caché retrasada cuando todos fallan", async () => { let fail = false; const provider = new FakeProvider("primary", asset => fail ? new Error("down") : data(asset, "primary")), service = new MarketDataOrchestrator_1.MarketDataOrchestrator([provider], 0, 60000); await service.get(bitcoin, "1h"); fail = true; const result = await service.get(bitcoin, "1h"); strict_1.default.equal(result.cache, "stale"); strict_1.default.equal(result.quote.state, "delayed"); }); (0, node_test_1.it)("abre el circuito después de fallos repetidos", async () => { const provider = new FakeProvider("primary", () => new Error("down")), service = new MarketDataOrchestrator_1.MarketDataOrchestrator([provider]); await service.get(bitcoin, "1h"); await service.get(bitcoin, "1h"); await service.get(bitcoin, "1h"); await service.get(bitcoin, "1h"); strict_1.default.equal(provider.calls, 6); }); });
(0, node_test_1.describe)("narrativa", () => { (0, node_test_1.it)("reduce confianza cuando no hay datos", () => { const unavailable = Object.assign(Object.assign({}, data(bitcoin, "none")), { quote: Object.assign(Object.assign({}, data(bitcoin, "none").quote), { price: null, state: "unavailable" }), venues: [], cache: "miss", fallbackUsed: false, errors: ["down"] }); const story = (0, MarketNarrative_1.buildMarketNarrative)(unavailable, "1h"); strict_1.default.equal(story.confidence, 0); strict_1.default.match(story.text, /No evaluable/); }); (0, node_test_1.it)("describe divergencia como inferencia y no causalidad", () => { const base = data(bitcoin, "primary"), bundle = Object.assign(Object.assign({}, base), { venues: [...base.venues, Object.assign(Object.assign({}, base.venues[0]), { name: "Venue B", price: 103 })], cache: "miss", fallbackUsed: false, errors: [] }); const story = (0, MarketNarrative_1.buildMarketNarrative)(bundle, "1h"); strict_1.default.match(story.text, /puede relacionarse/i); strict_1.default.match(story.text, /no permiten afirmar causalidad/i); }); });
