"use client";

import {
  Activity, BarChart3, Bell, BookOpen, Bot, Boxes, BrainCircuit,
  Check, ChevronDown, CircleHelp, FileStack, GraduationCap,
  Hash, LayoutDashboard, Menu, MessageSquareText, MoreHorizontal,
  Play, Plus, RadioTower, Search, ShieldCheck, Sparkles, Target,
  Users, WandSparkles, X,
} from "lucide-react";
import Image from "next/image";
import { useMemo, useState } from "react";

import { can } from "../domain/permissions";
import type { MediaWorkspace } from "../domain/types";
import { demoCampaigns, demoChannels, demoIdentity, demoWorkspaces, learningTopics, useCases } from "../application/demo-data";

type View = "overview" | "content" | "campaigns" | "channels" | "analytics" | "learn";

const navigation = [
  { id: "overview" as const, label: "Centro", icon: LayoutDashboard },
  { id: "content" as const, label: "Contenido", icon: FileStack },
  { id: "campaigns" as const, label: "Campañas", icon: Target },
  { id: "channels" as const, label: "Canales", icon: RadioTower },
  { id: "analytics" as const, label: "Analytics", icon: BarChart3 },
  { id: "learn" as const, label: "Aprender", icon: GraduationCap },
];

const help: Record<View, { title: string; body: string; tips: string[] }> = {
  overview: { title: "Centro de operaciones", body: "Resume lo que requiere atención dentro del workspace activo.", tips: ["Revisa primero las decisiones pendientes.", "Cambia de workspace sin mezclar datos."] },
  content: { title: "Contenido", body: "Reúne las piezas detectadas y los formatos creados por IA.", tips: ["La procedencia acompaña cada activo.", "Editar invalida aprobaciones anteriores."] },
  campaigns: { title: "Campañas", body: "Agrupa contenido, audiencias, destinos, programación y aprobaciones.", tips: ["Una campaña nunca publica sin permiso.", "Usa estados para coordinar al equipo."] },
  channels: { title: "Canales", body: "Representa las futuras conexiones externas mediante plugins aislados.", tips: ["El núcleo nunca habla directamente con una API.", "Los tokens pertenecerán al workspace."] },
  analytics: { title: "Analytics", body: "Normaliza resultados sin ocultar la métrica original de cada plataforma.", tips: ["Compara tendencias, no solo volumen.", "Las cifras actuales son demostrativas."] },
  learn: { title: "Centro de Aprendizaje", body: "Enseña Media Intelligence sin obligarte a salir de LAEX.", tips: ["Repite el recorrido cuando quieras.", "Elige un caso de uso parecido al tuyo."] },
};

function Surface({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`rounded-[22px] border border-white/[0.08] bg-[#0A111C]/88 shadow-[inset_0_1px_0_rgba(255,255,255,.045),0_22px_70px_rgba(0,0,0,.28)] backdrop-blur-xl ${className}`}>{children}</div>;
}

function Signal({ children, tone = "cyan" }: { children: React.ReactNode; tone?: "cyan" | "green" | "amber" | "violet" }) {
  const styles = { cyan: "border-cyan-300/20 bg-cyan-300/[0.07] text-cyan-200", green: "border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-300", amber: "border-amber-300/20 bg-amber-300/[0.07] text-amber-200", violet: "border-violet-300/20 bg-violet-300/[0.07] text-violet-200" };
  return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.16em] ${styles[tone]}`}>{children}</span>;
}

function WorkspaceSwitcher({ current, onChange }: { current: MediaWorkspace; onChange: (workspace: MediaWorkspace) => void }) {
  const [open, setOpen] = useState(false);
  return <div className="relative">
    <button onClick={() => setOpen(!open)} className="flex min-w-[230px] items-center gap-3 rounded-2xl border border-white/[0.09] bg-white/[0.035] px-3.5 py-2.5 text-left transition hover:border-cyan-300/25">
      <span className="grid h-9 w-9 place-items-center rounded-xl text-xs font-bold text-slate-950" style={{ background: current.color }}>{current.name.slice(0, 2).toUpperCase()}</span>
      <span className="min-w-0 flex-1"><small className="block text-[8px] font-bold uppercase tracking-[.2em] text-slate-600">Workspace activo</small><b className="block truncate text-xs text-white">{current.name}</b></span><ChevronDown size={14} className="text-slate-500" />
    </button>
    {open && <Surface className="absolute left-0 top-[calc(100%+.6rem)] z-40 w-[290px] overflow-hidden p-2">
      {demoWorkspaces.map((workspace) => <button key={workspace.id} onClick={() => { onChange(workspace); setOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${workspace.id === current.id ? "bg-cyan-300/[0.08]" : "hover:bg-white/[0.04]"}`}><span className="h-2.5 w-2.5 rounded-full" style={{ background: workspace.color }} /><span className="flex-1"><b className="block text-xs text-slate-200">{workspace.name}</b><small className="text-[9px] text-slate-600">{workspace.channelCount} canales · {workspace.role}</small></span>{workspace.id === current.id && <Check size={14} className="text-cyan-300" />}</button>)}
      <button className="mt-1 flex w-full items-center gap-3 border-t border-white/[0.06] px-3 py-3 text-[10px] font-semibold text-cyan-300"><Plus size={14} /> Crear workspace</button>
    </Surface>}
  </div>;
}

export default function MediaIntelligenceApp() {
  const [view, setView] = useState<View>("overview");
  const [workspace, setWorkspace] = useState(demoWorkspaces[0]);
  const [sidebar, setSidebar] = useState(false);
  const [helpOpen, setHelpOpen] = useState(false);
  const [tourStep, setTourStep] = useState<number | null>(0);
  const [toast, setToast] = useState("");
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const context = useMemo(() => ({ ...demoIdentity, workspaceId: workspace.id, role: workspace.role, version: "v1" as const }), [workspace]);

  return <div className="min-h-screen bg-[#04070C] text-slate-100">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_0%,rgba(34,211,238,.09),transparent_30rem),radial-gradient(circle_at_90%_20%,rgba(99,102,241,.08),transparent_34rem)]" />
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[248px] flex-col border-r border-white/[0.07] bg-[#060B12]/96 px-4 py-5 backdrop-blur-2xl transition lg:translate-x-0 ${sidebar ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center gap-3 px-2 pb-7"><Image src="/brand/logo/logo-mark.png" alt="LAEX" width={40} height={40} className="h-10 w-10 object-contain" /><div><b className="block text-sm tracking-[.16em]">MEDIA</b><small className="text-[8px] font-bold tracking-[.26em] text-cyan-300">INTELLIGENCE</small></div><button onClick={() => setSidebar(false)} className="ml-auto text-slate-600 lg:hidden"><X size={18} /></button></div>
      <div className="mb-5"><WorkspaceSwitcher current={workspace} onChange={setWorkspace} /></div>
      <nav className="space-y-1.5" aria-label="Media Intelligence">{navigation.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setView(id); setSidebar(false); }} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-semibold transition ${view === id ? "bg-gradient-to-r from-cyan-300/[0.12] to-transparent text-white shadow-[inset_2px_0_0_#67e8f9]" : "text-slate-500 hover:bg-white/[0.035] hover:text-slate-200"}`}><Icon size={16} className={view === id ? "text-cyan-300" : "text-slate-600 group-hover:text-cyan-300"} />{label}{id === "campaigns" && <span className="ml-auto rounded-full bg-violet-400/10 px-2 py-0.5 text-[8px] text-violet-300">3</span>}</button>)}</nav>
      <div className="mt-auto space-y-2 border-t border-white/[0.07] pt-4"><button onClick={() => { setView("learn"); setTourStep(0); }} className="flex w-full items-center gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.045] px-3 py-3 text-left text-[10px] font-semibold text-cyan-200"><BookOpen size={15} /> Centro de Aprendizaje</button><div className="flex items-center gap-3 px-3 py-2"><div className="grid h-8 w-8 place-items-center rounded-full border border-white/10 bg-white/[0.05] text-[9px] font-bold">CEO</div><div><b className="block text-[10px]">{demoIdentity.displayName}</b><small className="text-[8px] text-emerald-300">Tenant aislado · v1</small></div></div></div>
    </aside>

    <div className="relative lg:pl-[248px]"><header className="sticky top-0 z-30 flex h-[82px] items-center gap-4 border-b border-white/[0.06] bg-[#04070C]/78 px-4 backdrop-blur-2xl md:px-7"><button onClick={() => setSidebar(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 text-slate-300 lg:hidden"><Menu size={18} /></button><div className="min-w-0 flex-1"><small className="block truncate text-[8px] font-bold uppercase tracking-[.22em] text-slate-600">LAEX / MEDIA INTELLIGENCE / {workspace.name}</small><h1 className="mt-1 truncate text-sm font-semibold text-white">{navigation.find((item) => item.id === view)?.label}</h1></div><div className="hidden items-center gap-2 md:flex"><Signal tone="green"><span className="mr-1.5 h-1.5 w-1.5 rounded-full bg-emerald-300" />Core operativo</Signal><Signal tone="violet">v1</Signal></div><button className="grid h-10 w-10 place-items-center rounded-xl border border-white/[0.08] bg-white/[0.03] text-slate-500"><Bell size={16} /></button><button onClick={() => setHelpOpen(true)} className="flex h-10 items-center gap-2 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.045] px-3 text-[10px] font-semibold text-cyan-200"><CircleHelp size={15} /> <span className="hidden sm:inline">Ayuda</span></button></header>
      <main className="mx-auto w-full max-w-[1500px] px-4 py-6 md:px-7 md:py-8">
        {view === "overview" && <Overview workspace={workspace} onNavigate={setView} onToast={showToast} />}
        {view === "content" && <ContentView onToast={showToast} />}
        {view === "campaigns" && <CampaignsView onToast={showToast} canApprove={can(context.role, "content.approve")} />}
        {view === "channels" && <ChannelsView onToast={showToast} canManage={can(context.role, "channel.connect")} />}
        {view === "analytics" && <AnalyticsView />}
        {view === "learn" && <LearningView onTour={() => setTourStep(0)} />}
      </main>
    </div>

    {helpOpen && <><button aria-label="Cerrar ayuda" onClick={() => setHelpOpen(false)} className="fixed inset-0 z-40 bg-black/55 backdrop-blur-sm" /><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-[410px] border-l border-white/[0.09] bg-[#080E17] p-6 shadow-2xl"><div className="flex items-center justify-between"><Signal>Ayuda contextual</Signal><button onClick={() => setHelpOpen(false)} className="text-slate-500"><X /></button></div><div className="mt-12 grid h-14 w-14 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.08] text-cyan-300"><CircleHelp /></div><h2 className="mt-6 text-2xl font-semibold">{help[view].title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{help[view].body}</p><div className="mt-8 space-y-3">{help[view].tips.map((tip) => <div key={tip} className="flex gap-3 rounded-xl border border-white/[0.07] bg-white/[0.025] p-4 text-xs text-slate-300"><Sparkles size={15} className="shrink-0 text-cyan-300" />{tip}</div>)}</div><button onClick={() => { setHelpOpen(false); setView("learn"); }} className="mt-8 w-full rounded-xl bg-gradient-to-r from-cyan-300 to-indigo-400 px-4 py-3 text-xs font-bold text-slate-950">Abrir Centro de Aprendizaje</button></aside></>}
    {tourStep !== null && <GuidedTour step={tourStep} onNext={() => tourStep >= 4 ? setTourStep(null) : setTourStep(tourStep + 1)} onClose={() => setTourStep(null)} />}
    {toast && <div className="fixed bottom-6 right-6 z-[70] rounded-xl border border-cyan-300/20 bg-[#E8FAFF] px-4 py-3 text-xs font-semibold text-[#09202A] shadow-2xl">{toast}</div>}
  </div>;
}

function Overview({ workspace, onNavigate, onToast }: { workspace: MediaWorkspace; onNavigate: (view: View) => void; onToast: (message: string) => void }) {
  return <><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Signal>Workspace independiente</Signal><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Dirige el conocimiento.<br/><span className="bg-gradient-to-r from-cyan-200 to-violet-300 bg-clip-text text-transparent">La IA prepara el terreno.</span></h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500">{workspace.name} mantiene canales, campañas, permisos y métricas completamente aislados de tus demás espacios.</p></div><button onClick={() => onToast("Nueva campaña preparada · Demostración")} className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-indigo-400 px-5 py-3 text-xs font-bold text-slate-950"><Plus size={16} /> Nueva campaña</button></div>
  <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Señales nuevas","03","+2 hoy"],["En análisis","01","Comprendiendo"],["Pendientes","16","Decisión humana"],["Programadas","08","Próximos 7 días"],["Salud editorial","94%","Estable"]].map(([label,value,note],i)=><Surface key={label} className="p-5"><span className="text-[8px] font-bold uppercase tracking-[.18em] text-slate-600">{label}</span><b className="mt-2 block text-3xl font-medium">{value}</b><small className={`mt-2 block text-[9px] ${i===4?"text-emerald-300":i===2?"text-violet-300":"text-cyan-300"}`}>{note}</small></Surface>)}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_.75fr]"><Surface className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-4"><div><span className="text-[8px] font-bold uppercase tracking-[.2em] text-slate-600">Prioridad editorial</span><h3 className="mt-1 text-sm font-semibold">Contenido que requiere tu decisión</h3></div><button onClick={() => onNavigate("campaigns")} className="text-[9px] font-bold text-cyan-300">VER CAMPAÑAS →</button></div><div className="divide-y divide-white/[0.055]">{demoCampaigns.map((campaign)=><button key={campaign.id} onClick={()=>onNavigate("campaigns")} className="grid w-full grid-cols-[auto_1fr_auto] items-center gap-4 px-5 py-4 text-left transition hover:bg-white/[0.025]"><span className={`grid h-10 w-10 place-items-center rounded-xl border ${campaign.status==="review"?"border-violet-300/20 bg-violet-300/[0.07] text-violet-300":"border-cyan-300/15 bg-cyan-300/[0.05] text-cyan-300"}`}><Play size={15}/></span><span><b className="block text-xs text-slate-200">{campaign.title}</b><small className="mt-1 block text-[9px] text-slate-600">{campaign.generatedAssets} activos · {campaign.updatedAt}</small></span><span className="text-right"><Signal tone={campaign.status==="review"?"violet":"green"}>{campaign.status}</Signal><small className="mt-1 block text-[8px] text-slate-600">{campaign.confidence}% IA</small></span></button>)}</div></Surface>
  <Surface className="p-5"><div className="flex items-center justify-between"><div><span className="text-[8px] font-bold uppercase tracking-[.2em] text-slate-600">Inteligencia activa</span><h3 className="mt-1 text-sm font-semibold">Pulso del workspace</h3></div><Activity size={18} className="text-cyan-300" /></div><div className="mt-7 flex justify-center"><div className="grid h-36 w-36 place-items-center rounded-full border border-cyan-300/20 bg-[radial-gradient(circle,rgba(34,211,238,.15),transparent_68%)]"><div className="text-center"><b className="text-3xl font-medium">92.4</b><small className="block text-[8px] tracking-[.18em] text-cyan-300">READINESS</small></div></div></div><div className="mt-7 space-y-3">{[["Conectores","4 preparados"],["Aprobaciones","16 pendientes"],["Riesgos","1 requiere atención"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-white/[0.055] pb-3 text-[9px]"><span className="text-slate-600">{a}</span><b className="text-slate-300">{b}</b></div>)}</div></Surface></div></>;
}

function ContentView({ onToast }: { onToast: (message: string) => void }) {
  const formats = ["Resumen ejecutivo","Artículo","Noticia","Guion Short","Guion Reel","Facebook","Instagram","X","LinkedIn","Correo","Miniatura","Etiquetas","Hashtags","Título SEO","Descripción SEO","Palabras clave"];
  return <><PageHeading eyebrow="Biblioteca editorial" title="Cada pieza conserva su procedencia." body="Organiza cada idea, conserva su historia y decide con claridad qué versión está lista para avanzar." action="Importar contenido" onAction={()=>onToast("Importación preparada · Sin conexión externa")} /><Surface className="mt-7 overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/[0.06] p-4 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-white/[0.08] bg-black/20 px-3"><Search size={14} className="text-slate-600"/><input placeholder="Buscar contenido..." className="w-full bg-transparent py-2.5 text-xs outline-none"/></label><button className="rounded-xl border border-white/[0.08] px-4 py-2 text-[9px] font-bold text-slate-400">Todos los estados</button></div><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{formats.map((format,i)=><button key={format} onClick={()=>onToast(`${format}: editor preparado`)} className="group min-h-40 rounded-2xl border border-white/[0.07] bg-white/[0.022] p-4 text-left transition hover:-translate-y-1 hover:border-cyan-300/25"><span className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[0.045] text-cyan-300">{i%3===0?<FileStack size={15}/>:i%3===1?<MessageSquareText size={15}/>:<Hash size={15}/>}</span><Signal tone={i<3?"violet":"cyan"}>{i<3?"Revisión":"Generado"}</Signal><b className="mt-4 block text-xs">{format}</b><small className="mt-2 block text-[9px] text-slate-600">Campaña · Todo comienza con una decisión</small></button>)}</div></Surface></>;
}

function CampaignsView({ onToast, canApprove }: { onToast: (message: string) => void; canApprove: boolean }) {
  return <><PageHeading eyebrow="Orquestación editorial" title="Campañas con control humano." body="Agrupa objetivos, formatos, audiencias y destinos sin publicar automáticamente." action="Crear campaña" onAction={()=>onToast("Nueva campaña iniciada · Demostración")} /><div className="mt-7 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"> <div className="space-y-3">{demoCampaigns.map((campaign,index)=><Surface key={campaign.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl border border-violet-300/15 bg-violet-300/[0.06] text-violet-300"><WandSparkles size={17}/></span><div><Signal tone={index===0?"violet":"green"}>{campaign.status}</Signal><h3 className="mt-2 text-base font-semibold">{campaign.title}</h3><p className="mt-1 text-[9px] text-slate-600">{campaign.sourceType} · {campaign.generatedAssets} activos · {campaign.updatedAt}</p></div></div><div className="text-right"><b className="text-2xl font-medium">{campaign.confidence}%</b><small className="block text-[8px] uppercase tracking-[.15em] text-slate-600">confianza IA</small></div></div><div className="mt-5 flex flex-wrap gap-2 border-t border-white/[0.055] pt-4"><button onClick={()=>onToast("Editor de campaña abierto")} className="rounded-lg border border-white/[0.08] px-3 py-2 text-[9px] font-semibold text-slate-400">Editar</button><button disabled={!canApprove} onClick={()=>onToast(canApprove?"Aprobación registrada · Demostración":"Tu rol no puede aprobar")} className="rounded-lg border border-emerald-300/15 bg-emerald-300/[0.05] px-3 py-2 text-[9px] font-semibold text-emerald-300 disabled:cursor-not-allowed disabled:opacity-35"><ShieldCheck size={12} className="mr-1 inline"/>Aprobar</button><button className="ml-auto text-slate-600"><MoreHorizontal size={18}/></button></div></Surface>)}</div><Surface className="p-5"><span className="text-[8px] font-bold uppercase tracking-[.2em] text-slate-600">Flujo de aprobación</span><h3 className="mt-2 text-lg font-semibold">La IA ayuda.<br/>El creador decide.</h3><div className="mt-7 space-y-1">{[["1","Comprensión","Completo"],["2","Generación","16 activos"],["3","Revisión","En curso"],["4","Aprobación","Pendiente"],["5","Distribución","Bloqueado"]].map(([n,a,b],i)=><div key={n} className="flex items-center gap-3 py-3"><span className={`grid h-8 w-8 place-items-center rounded-full border text-[9px] ${i<2?"border-emerald-300/20 bg-emerald-300/[0.06] text-emerald-300":i===2?"border-cyan-300/25 bg-cyan-300/[0.08] text-cyan-300":"border-white/[0.08] text-slate-700"}`}>{i<2?<Check size={13}/>:n}</span><span className="flex-1"><b className="block text-[10px] text-slate-300">{a}</b><small className="text-[8px] text-slate-600">{b}</small></span></div>)}</div></Surface></div></>;
}

function ChannelsView({ onToast, canManage }: { onToast: (message: string) => void; canManage: boolean }) {
  const planned = ["LinkedIn","Telegram","WhatsApp","X","LAEX News"];
  return <><PageHeading eyebrow="Ecosistema de canales" title="Cada canal listo para crecer contigo." body="Explora cómo se distribuirá tu contenido. Todas las conexiones permanecen seguras y simuladas durante esta etapa." action="Preparar canal" onAction={()=>onToast(canManage?"Asistente de conexión preparado · Sin OAuth real":"Tu rol no puede administrar canales")} /><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{demoChannels.map((channel)=><Surface key={channel.id} className="p-5"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[0.05] text-cyan-300"><RadioTower size={18}/></span><Signal tone={channel.status==="attention"?"amber":"green"}>{channel.status}</Signal></div><h3 className="mt-5 text-sm font-semibold capitalize">{channel.platform}</h3><p className="mt-1 text-[10px] text-slate-500">{channel.label}</p><div className="mt-5 border-t border-white/[0.055] pt-3 text-[8px] text-slate-600">Plugin {channel.pluginVersion} · sin credenciales activas</div></Surface>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{planned.map((platform)=><button key={platform} onClick={()=>onToast(`${platform}: plugin futuro`)} className="rounded-2xl border border-dashed border-white/[0.1] p-5 text-left transition hover:border-violet-300/30"><Plus size={16} className="text-violet-300"/><b className="mt-4 block text-xs text-slate-400">{platform}</b><small className="mt-1 block text-[8px] text-slate-700">Disponible próximamente</small></button>)}</div><Surface className="mt-4 grid gap-5 p-5 md:grid-cols-5">{["Media Core","Orquestador","Cola de tareas","Plugin","API oficial"].map((node,i)=><div key={node} className="relative rounded-xl border border-white/[0.07] bg-white/[0.02] p-4 text-center"><b className="text-[9px] text-slate-300">{node}</b>{i<4&&<span className="absolute -right-4 top-1/2 hidden text-cyan-300 md:block">→</span>}</div>)}</Surface></>;
}

function AnalyticsView() {
  return <><PageHeading eyebrow="Inteligencia posterior" title="Métricas comparables, contexto intacto." body="Comprende el rendimiento proyectado de cada decisión editorial en una sola vista." /><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Alcance","284.9K","+18.4%"],["CTR","6.84%","+1.2 pts"],["Retención","71.2%","00:45"],["Conversión","4.7%","+0.9 pts"],["Registros","386","Simulado"]].map(([a,b,c])=><Surface key={a} className="p-5"><span className="text-[8px] font-bold uppercase tracking-[.16em] text-slate-600">{a}</span><b className="mt-3 block text-3xl font-medium">{b}</b><small className="mt-2 block text-[9px] text-emerald-300">{c}</small></Surface>)}</div><div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_.7fr]"><Surface className="p-5"><div className="flex justify-between"><div><span className="text-[8px] font-bold uppercase tracking-[.18em] text-slate-600">Rendimiento multicanal</span><h3 className="mt-2 text-sm font-semibold">Primeras 24 horas</h3></div><Signal>Simulación</Signal></div><div className="mt-8 flex h-64 items-end justify-around border-b border-white/[0.08] bg-[repeating-linear-gradient(0deg,transparent_0_49px,rgba(255,255,255,.045)_50px)] px-4">{[["YT",82],["IG",68],["FB",49],["TK",76],["IN",43],["WA",35]].map(([name,height])=><div key={name as string} className="flex h-full w-[9%] items-end"><div className="relative w-full rounded-t bg-gradient-to-t from-indigo-500 to-cyan-300" style={{height:`${height}%`}}><span className="absolute -bottom-6 w-full text-center text-[8px] text-slate-600">{name}</span></div></div>)}</div></Surface><Surface className="p-5"><span className="text-[8px] font-bold uppercase tracking-[.18em] text-slate-600">Recomendación IA</span><div className="mt-6 grid h-12 w-12 place-items-center rounded-xl border border-violet-300/20 bg-violet-300/[0.07] text-violet-300"><BrainCircuit/></div><h3 className="mt-5 text-lg font-semibold">Prioriza Instagram a las 20:30</h3><p className="mt-3 text-xs leading-6 text-slate-500">El Reel corto presenta el mayor potencial de retención para esta audiencia.</p><div className="mt-5 rounded-xl border border-amber-300/15 bg-amber-300/[0.04] p-3 text-[9px] text-amber-200">Riesgo: contextualizar cualquier cifra financiera.</div></Surface></div></>;
}

function LearningView({ onTour }: { onTour: () => void }) {
  const [selected, setSelected] = useState(0);
  return <><div className="overflow-hidden rounded-[28px] border border-cyan-300/15 bg-[radial-gradient(circle_at_80%_10%,rgba(99,102,241,.22),transparent_26rem),linear-gradient(120deg,#0D1A27,#080C14)] p-7 md:p-10"><Signal>Centro de Aprendizaje</Signal><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_.7fr]"><div><h2 className="text-3xl font-semibold tracking-[-.04em] md:text-5xl">Entiende Media Intelligence<br/><span className="text-cyan-200">en menos de cinco minutos.</span></h2><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-400">Una plataforma que enseña mientras trabajas: conecta la idea, la función y la decisión correcta sin documentación externa.</p><button onClick={onTour} className="mt-6 flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-bold text-slate-950"><Play size={15}/> Repetir recorrido guiado</button></div><div className="grid place-items-center"><div className="grid h-48 w-48 place-items-center rounded-full border border-cyan-300/20 bg-[radial-gradient(circle,rgba(34,211,238,.16),transparent_68%)]"><div className="text-center"><Bot className="mx-auto text-cyan-300" size={35}/><b className="mt-3 block text-sm">Aprende haciendo</b><small className="text-[8px] tracking-[.18em] text-slate-600">AI-READY KNOWLEDGE</small></div></div></div></div></div>
  <div className="mt-5 grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><Surface className="overflow-hidden p-2">{learningTopics.map((topic,i)=><button key={topic.id} onClick={()=>setSelected(i)} className={`flex w-full gap-3 rounded-xl p-4 text-left transition ${selected===i?"bg-cyan-300/[0.08]":"hover:bg-white/[0.025]"}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border text-[10px] ${selected===i?"border-cyan-300/20 text-cyan-300":"border-white/[0.07] text-slate-700"}`}>0{i+1}</span><span><b className="block text-xs text-slate-200">{topic.title}</b><small className="mt-1 block text-[8px] text-slate-600">{topic.duration}</small></span></button>)}</Surface><Surface className="p-7"><Signal tone="violet">Lección {selected+1}</Signal><h3 className="mt-5 text-2xl font-semibold">{learningTopics[selected].title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{learningTopics[selected].description}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Qué hace","Convierte señales en decisiones editoriales."],["Cuándo usarlo","Cuando una pieza merece múltiples formatos."],["Recomendación","Comienza con un objetivo y audiencia claros."]].map(([a,b])=><div key={a} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-4"><b className="text-[9px] text-cyan-300">{a}</b><p className="mt-2 text-[10px] leading-5 text-slate-500">{b}</p></div>)}</div><button className="mt-7 flex items-center gap-2 text-[10px] font-bold text-cyan-300">Continuar lección <span>→</span></button></Surface></div>
  <div className="mt-8"><span className="text-[8px] font-bold uppercase tracking-[.22em] text-slate-600">Encuentra tu caso de uso</span><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{useCases.map(([title,body])=><Surface key={title} className="p-5"><Users size={17} className="text-violet-300"/><h3 className="mt-4 text-sm font-semibold">{title}</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">{body}</p></Surface>)}</div></div></>;
}

function PageHeading({ eyebrow, title, body, action, onAction }: { eyebrow: string; title: string; body: string; action?: string; onAction?: () => void }) { return <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="text-[8px] font-bold uppercase tracking-[.24em] text-cyan-300">{eyebrow}</span><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{body}</p></div>{action&&<button onClick={onAction} className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-indigo-400 px-5 py-3 text-xs font-bold text-slate-950"><Plus size={15}/>{action}</button>}</div> }

function GuidedTour({ step, onNext, onClose }: { step: number; onNext: () => void; onClose: () => void }) {
  const steps = [
    ["Bienvenido a Media Intelligence", "Aquí convertirás cada pieza en un ecosistema controlado."],
    ["Tus workspaces están aislados", "Administra marcas, clientes o proyectos sin mezclar datos ni permisos."],
    ["La IA analiza y prepara", "Comprende señales, genera formatos y marca riesgos; nunca toma la decisión final."],
    ["Tú apruebas antes de publicar", "El control humano es una regla del producto, no una preferencia visual."],
    ["Aprende del resultado", "Analytics y recomendaciones convierten cada campaña en una próxima acción."],
  ];
  return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#020408]/82 p-4 backdrop-blur-md"><Surface className="relative w-full max-w-[560px] overflow-hidden p-7 md:p-9"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-cyan-300 via-indigo-400 to-violet-400"/><button onClick={onClose} className="absolute right-5 top-5 text-slate-600"><X size={18}/></button><span className="text-[8px] font-bold uppercase tracking-[.2em] text-cyan-300">Recorrido guiado · {step+1}/5</span><div className="mt-7 grid h-14 w-14 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.07] text-cyan-300">{step===0?<Sparkles/>:step===1?<Boxes/>:step===2?<BrainCircuit/>:step===3?<ShieldCheck/>:<BarChart3/>}</div><h2 className="mt-6 text-2xl font-semibold">{steps[step][0]}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{steps[step][1]}</p><div className="mt-8 flex items-center justify-between"><div className="flex gap-1.5">{steps.map((_,i)=><i key={i} className={`h-1.5 rounded-full transition ${i===step?"w-7 bg-cyan-300":"w-1.5 bg-white/10"}`}/>)}</div><button onClick={onNext} className="rounded-xl bg-white px-5 py-2.5 text-[10px] font-bold text-slate-950">{step===4?"Entrar al producto":"Siguiente →"}</button></div></Surface></div>;
}
