"use client";

import { Activity, AlertTriangle, BarChart3, BookOpen, CheckCircle2, FilePlus2, LoaderCircle, Plus, RefreshCw, ShieldCheck, Sparkles, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { MediaProductState, ProductContent, ProductWorkspace } from "../domain/product";

type ApiState = MediaProductState & { actor: { userId: string; name: string }; persistence: string };

const card = "rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.04)]";
const button = "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-xs font-bold transition disabled:cursor-not-allowed disabled:opacity-35";

export default function OperationsApp() {
  const [state, setState] = useState<ApiState | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [workspaceName, setWorkspaceName] = useState(""), [title, setTitle] = useState(""), [body, setBody] = useState("");
  const active = useMemo(() => state?.workspaces.find((item) => item.id === state.activeWorkspaceId) ?? state?.workspaces[0], [state]);
  const load = useCallback(async () => {
    setBusy(true); setError("");
    try {
      let response = await fetch("/api/media-intelligence", { cache: "no-store" });
      if (response.status === 401) { await fetch("/api/media-intelligence/session", { method: "POST" }); response = await fetch("/api/media-intelligence", { cache: "no-store" }); }
      const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No fue posible cargar el entorno local."); setState(data);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Error inesperado"); } finally { setBusy(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function act(action: string, payload: Record<string, unknown> = {}, workspaceId = active?.id) {
    if (!state) return; setBusy(true); setError("");
    try { const response = await fetch("/api/media-intelligence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ revision: state.revision, action, workspaceId, payload }) }); const data = await response.json(); if (!response.ok) { if (response.status === 409) { await load(); throw new Error("Los datos cambiaron; se recargó la revisión más reciente."); } throw new Error(data.error); } setState({ ...data, actor: state.actor, persistence: state.persistence }); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Operación rechazada"); } finally { setBusy(false); }
  }
  if (!state) return <main className="grid min-h-screen place-items-center p-6"><div className="text-center">{busy ? <LoaderCircle className="mx-auto animate-spin text-cyan-300" /> : <AlertTriangle className="mx-auto text-amber-300" />}<p className="mt-4 text-sm text-slate-400">{error || "Inicializando sesión controlada…"}</p>{error && <button onClick={load} className={`${button} mt-4 bg-white text-slate-950`}>Reintentar</button>}</div></main>;
  return <main className="mx-auto min-h-screen max-w-[1500px] px-4 pb-28 pt-24 sm:px-6 md:pt-20">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[.22em] text-cyan-300">Centro de operaciones · revisión {state.revision}</span><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Construye. Analiza. <span className="text-cyan-200">Decide.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Tu trabajo permanece protegido dentro de cada Workspace. La inteligencia asiste el proceso y cada decisión editorial sigue bajo control humano.</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-emerald-300/20 bg-emerald-300/5 px-3 py-2 text-[9px] font-bold text-emerald-300"><ShieldCheck size={12} className="mr-1 inline"/>IDENTIDAD PROTEGIDA</span><span className="rounded-full border border-violet-300/20 bg-violet-300/5 px-3 py-2 text-[9px] font-bold text-violet-200">ENTORNO DE DEMOSTRACIÓN</span></div></header>
    {error && <div role="alert" className="mt-5 flex items-center gap-3 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4 text-xs text-amber-100"><AlertTriangle size={16}/>{error}<button onClick={()=>setError("")} className="ml-auto">Cerrar</button></div>}
    <section aria-labelledby="workspace-heading" className="mt-8 grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><div className={card}><h2 id="workspace-heading" className="flex items-center gap-2 text-sm font-semibold"><Users size={16} className="text-cyan-300"/>Workspaces aislados</h2><div className="mt-4 space-y-2">{state.workspaces.map((workspace)=><button key={workspace.id} disabled={busy} onClick={()=>void act("workspace.activate",{},workspace.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition ${workspace.id===active?.id?"border-cyan-300/25 bg-cyan-300/[0.07]":"border-white/[0.06] hover:bg-white/[0.03]"}`}><i className="h-3 w-3 rounded-full" style={{background:workspace.color}}/><span className="flex-1"><b className="block text-xs">{workspace.name}</b><small className="text-[9px] text-slate-500">{workspace.contents.length} contenidos · {workspace.members.length} miembros</small></span>{workspace.id===active?.id&&<CheckCircle2 size={15} className="text-cyan-300"/>}</button>)}</div><form onSubmit={(event)=>{event.preventDefault(); if(workspaceName.trim()){void act("workspace.create",{name:workspaceName},undefined);setWorkspaceName("");}}} className="mt-4 flex gap-2"><label className="sr-only" htmlFor="workspace-name">Nombre del Workspace</label><input id="workspace-name" value={workspaceName} onChange={(event)=>setWorkspaceName(event.target.value)} placeholder="Nuevo workspace" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-xs outline-none focus:border-cyan-300/40"/><button disabled={busy||workspaceName.trim().length<2} className={`${button} bg-cyan-300 text-slate-950`}><Plus size={14}/>Crear</button></form></div>
      {active && <WorkspaceSummary workspace={active}/>}</section>
    {active && <section aria-labelledby="content-heading" className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={(event)=>{event.preventDefault();if(title.trim()){void act("content.create",{title,body});setTitle("");setBody("");}}} className={card}><h2 id="content-heading" className="flex items-center gap-2 text-sm font-semibold"><FilePlus2 size={16} className="text-violet-300"/>Crear contenido</h2><label className="mt-5 block text-[10px] font-bold uppercase tracking-wider text-slate-500" htmlFor="content-title">Título</label><input id="content-title" value={title} onChange={(event)=>setTitle(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-xs outline-none focus:border-cyan-300/40"/><label className="mt-4 block text-[10px] font-bold uppercase tracking-wider text-slate-500" htmlFor="content-body">Contenido original</label><textarea id="content-body" value={body} onChange={(event)=>setBody(event.target.value)} rows={6} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/20 p-3 text-xs leading-6 outline-none focus:border-cyan-300/40"/><button disabled={busy||!title.trim()} className={`${button} mt-4 w-full bg-gradient-to-r from-cyan-300 to-violet-400 text-slate-950`}><FilePlus2 size={14}/>Guardar borrador</button></form><div className={`${card} overflow-hidden`}><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Biblioteca editorial</h2><button disabled={busy} onClick={load} aria-label="Actualizar contenidos" className="text-slate-500 hover:text-cyan-300"><RefreshCw size={15}/></button></div><div className="mt-4 space-y-3">{active.contents.length===0?<Empty/>:active.contents.map((content)=><ContentRow key={content.id} content={content} busy={busy} onAction={(action,payload)=>void act(action,{contentId:content.id,...payload})}/>)}</div></div></section>}
    {active && <section className="mt-4 grid gap-4 lg:grid-cols-3"><Metric icon={<BarChart3/>} label="Impacto proyectado" value="284.9K" note="Alcance proyectado"/><Metric icon={<Activity/>} label="Actividad auditable" value={String(active.audit.length)} note="Eventos del Workspace"/><Metric icon={<BookOpen/>} label="Aprendizaje" value="5 min" note="Recorrido repetible"/></section>}
    {busy&&<div role="status" className="fixed bottom-24 right-5 z-[90] flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-bold text-slate-950 shadow-2xl"><LoaderCircle size={14} className="animate-spin"/>Guardando operación…</div>}
  </main>;
}

function WorkspaceSummary({workspace}:{workspace:ProductWorkspace}) { return <div className={card}><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Workspace activo</span><h2 className="mt-2 text-2xl font-semibold">{workspace.name}</h2><p className="mt-2 text-xs text-slate-400">{workspace.description}</p></div><span className="rounded-full border border-emerald-300/20 px-3 py-1 text-[9px] font-bold text-emerald-300">{workspace.status}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Audiencia",workspace.audience],["Tono",workspace.tone],["Zona horaria",workspace.timezone]].map(([label,value])=><div key={label} className="rounded-xl bg-white/[0.025] p-3"><small className="text-[9px] text-slate-600">{label}</small><b className="mt-1 block text-xs">{value}</b></div>)}</div><div className="mt-5 border-t border-white/[0.06] pt-4"><span className="text-[9px] font-bold text-cyan-300">Aislamiento visible</span><p className="mt-1 text-[10px] leading-5 text-slate-500">Al cambiar de Workspace, contenidos, campañas, miembros, canales y auditoría se reemplazan como una sola frontera.</p></div></div>}
function ContentRow({content,busy,onAction}:{content:ProductContent;busy:boolean;onAction:(action:string,payload:Record<string,unknown>)=>void}) { return <article className="rounded-xl border border-white/[0.07] bg-black/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-[9px] font-bold uppercase tracking-wider text-violet-300">{content.status.replaceAll("_"," ")}</span><h3 className="mt-1 text-sm font-semibold">{content.title}</h3><small className="text-[9px] text-slate-600">v{content.versions.at(-1)?.number} · Confianza simulada {content.confidence}%</small></div>{content.approvedVersion&&<span className="text-[9px] font-bold text-emerald-300">VERSIÓN {content.approvedVersion} APROBADA</span>}</div>{content.risks.map((risk)=><p key={risk} className="mt-3 text-[10px] text-amber-200">⚠ {risk}</p>)}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>onAction("content.analyze",{})} className={`${button} border border-violet-300/20 bg-violet-300/5 text-violet-200`}><Sparkles size={13}/>Analizar IA simulada</button><button disabled={busy||content.status==="approved"} onClick={()=>onAction("content.transition",{status:"in_review"})} className={`${button} border border-white/10 text-slate-300`}>Enviar a revisión</button><button disabled={busy||content.status!=="in_review"} onClick={()=>onAction("content.transition",{status:"approved"})} className={`${button} bg-emerald-300 text-slate-950`}><ShieldCheck size={13}/>Aprobar</button></div></article>}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}) { return <div className={card}><span className="text-cyan-300">{icon}</span><small className="mt-4 block text-[9px] font-bold uppercase tracking-wider text-slate-600">{label}</small><b className="mt-1 block text-3xl">{value}</b><p className="mt-2 text-[10px] text-slate-500">{note} · Simulado</p></div>}
function Empty(){return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center"><FilePlus2 className="mx-auto text-slate-700"/><p className="mt-3 text-xs text-slate-500">Crea el primer contenido de este Workspace.</p></div>}

