import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, BookOpen, Database, ShieldCheck } from "lucide-react";
import { assets } from "@/lab-market-intelligence/data";
import { EvidenceLabel, MarketTerminal, ScoreCard } from "@/modules/market-intelligence/components";

export function generateStaticParams(){return assets.map(asset=>({slug:asset.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const asset=assets.find(item=>item.slug===slug);if(!asset)return{};return{title:`${asset.name} (${asset.symbol}) | LAEX Market Intelligence`,description:`Precio simulado, liquidez, riesgo y análisis independiente de ${asset.name}.`,alternates:{canonical:`/market/${slug}`}};}
const money=(value:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"USD",maximumFractionDigits:value<1?4:0}).format(value);
export default async function AssetPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const asset=assets.find(item=>item.slug===slug);if(!asset)notFound();const m=asset.metric;return <main className="mx-auto w-[min(100%-2rem,92rem)] py-12 lg:py-18"><Link href="/market" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-cyan-200"><ArrowLeft size={14}/>Volver al mercado</Link>
  <section className="mt-8 grid gap-8 lg:grid-cols-[1fr_.42fr]"><div><div className="flex flex-wrap gap-2"><EvidenceLabel kind="market"/><span className="rounded-full border border-amber-200/15 px-3 py-1.5 text-[10px] font-bold text-amber-200">DATOS SIMULADOS</span></div><div className="mt-6 flex flex-wrap items-end gap-4"><h1 className="laex-display text-5xl sm:text-7xl">{asset.name}</h1><span className="pb-2 text-xl text-slate-500">{asset.symbol}</span></div><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-400">{asset.summary}</p></div><div className="laex-instrument rounded-3xl p-6"><span className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-500">Precio actual simulado</span><strong className="mt-3 block text-4xl tracking-[-.05em]">{m.price?money(m.price):"No disponible"}</strong><span className={`mt-3 block text-sm ${m.change24h>=0?"text-emerald-300":"text-rose-300"}`}>{m.change24h>=0?"+":""}{m.change24h}% · 24 h</span></div></section>
  {asset.conflicts.ecosystemLinked&&<div className="mt-7 rounded-2xl border border-amber-200/15 bg-amber-300/[.04] p-5"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-amber-200" size={18}/><div><b className="text-sm text-amber-100">Activo vinculado al ecosistema LAEX</b><p className="mt-2 text-sm leading-7 text-slate-400">{asset.conflicts.statement}</p></div></div></div>}
  <section className="mt-8"><MarketTerminal initialSlug={asset.slug}/></section>
  <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Cambio 1 h",`${m.change1h}%`],["Cambio 7 días",`${m.change7d}%`],["Volumen 24 h",money(m.volume24h)],["Liquidez",money(m.liquidity)],["Máximo 24 h",money(m.high24h)],["Mínimo 24 h",money(m.low24h)],["Capitalización",m.marketCap?money(m.marketCap):"No disponible"],["Oferta circulante",m.circulatingSupply?.toLocaleString("es-ES")??"No disponible"]].map(([label,value])=><div key={label} className="laex-card rounded-2xl p-5"><span className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-600">{label}</span><b className="mt-3 block text-lg">{value}</b></div>)}</section>
  <section className="mt-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><EvidenceLabel kind="analysis"/><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Inteligencia LAEX explicable</h2></div><Link href="/methodology" className="flex items-center gap-2 text-xs font-bold text-cyan-200"><BookOpen size={14}/>Consultar metodología</Link></div><div className="mt-7 grid gap-4 lg:grid-cols-3"><ScoreCard label="LAEX Trust Score" score={asset.trust} tone="emerald"/><ScoreCard label="Riesgo" score={asset.risk} tone="amber"/><ScoreCard label="Liquidez" score={asset.liquidityScore}/></div></section>
  <section className="mt-16 grid gap-5 lg:grid-cols-2"><article className="laex-surface rounded-3xl p-7"><EvidenceLabel kind="project"/><h2 className="mt-5 text-2xl font-semibold">Identidad del activo</h2><dl className="mt-6 space-y-4 text-sm">{[["Asset ID",asset.assetId],["Blockchain",asset.blockchain],["Contrato",asset.contractAddress??"No aplica / no disponible"],["Proveedor",asset.providerId],["Pares",asset.pairs.join(", ")||"Sin pares disponibles"],["Verificación",asset.verification]].map(([term,value])=><div key={term} className="flex flex-col gap-1 border-b border-white/[.06] pb-3 sm:flex-row sm:justify-between"><dt className="text-slate-500">{term}</dt><dd className="break-all text-slate-200">{value}</dd></div>)}</dl></article><article className="laex-surface rounded-3xl p-7"><div className="flex items-center gap-3 text-cyan-200"><Database size={18}/><EvidenceLabel kind="market"/></div><h2 className="mt-5 text-2xl font-semibold">Fuente y limitaciones</h2><p className="mt-5 text-sm leading-7 text-slate-400">Fuente: {m.source}. Actualización: {new Date(m.updatedAt).toLocaleString("es-CL")}. Esta ficha usa un dataset controlado para demostrar estados de carga, retraso y ausencia de datos.</p><div className="mt-5 flex gap-3 rounded-2xl bg-black/20 p-4"><ShieldCheck size={17} className="shrink-0 text-emerald-300"/><p className="text-xs leading-6 text-slate-500">La verificación confirma identidad o documentación específica. No constituye recomendación, solvencia ni ausencia de riesgo.</p></div></article></section>
  <section className="mt-10 rounded-3xl border border-white/[.08] bg-black/10 p-6"><EvidenceLabel kind="community"/><p className="mt-4 text-sm text-slate-500">Las opiniones comunitarias estarán separadas del score y no están habilitadas en este laboratorio.</p></section>
</main>;}
