"use client";

import { useState } from "react";
import { parseUnits } from "./demo-model";
import { ArrowLeft, ArrowRight, Check, ChevronRight, Globe, Plus, ShieldCheck, Trash2 } from "lucide-react";

export type ExtraScreen = "networks" | "add-network" | "tokens" | "add-token" | "token-detail" | "swap" | "web3" | "browser" | "connect" | "permission" | "settings" | "contacts" | "restore" | "lock";
type Network = { id: string; name: string; symbol: string; rpc: string; explorer: string; custom?: boolean };
type CustomToken = { network: string; address: string; name: string; symbol: string; decimals: number; preset?: boolean };
const initialNetworks: Network[] = [
  { id: "56", name: "BNB Chain", symbol: "BNB", rpc: "", explorer: "" },
  { id: "1", name: "Ethereum", symbol: "ETH", rpc: "", explorer: "" },
  { id: "9580", name: "OMDBlockchain", symbol: "OMDB", rpc: "https://rpc.omdbscan.com", explorer: "https://omdbscan.com" },
];
const initialTokens: CustomToken[] = [{ network: "56", address: "0xA7670e2e6742a18029436E262b01F7C50A863C40", name: "OMD", symbol: "OMD", decimals: 8, preset: true }];
export function useWalletExtras() {
  const [networks, setNetworks] = useState<Network[]>(initialNetworks);
  const [network, setNetwork] = useState("56");
  const [tokens, setTokens] = useState<CustomToken[]>(initialTokens);
  const [sessions, setSessions] = useState<string[]>([]);
  const [events, setEvents] = useState<string[]>([]);
  const [contacts, setContacts] = useState([{ name: "Ana", address: "LAEX-DEMO-002" }, { name: "Luis", address: "LAEX-DEMO-003" }]);
  const [biometric, setBiometric] = useState(false);
  const [autoLock, setAutoLock] = useState("1 minuto");
  const [walletName, setWalletName] = useState("Mi wallet");
  function reset() { setNetworks(initialNetworks); setNetwork("56"); setTokens(initialTokens); setSessions([]); setEvents([]); setContacts([{name:"Ana",address:"LAEX-DEMO-002"},{name:"Luis",address:"LAEX-DEMO-003"}]); setBiometric(false); setAutoLock("1 minuto"); setWalletName("Mi wallet"); }
  return { networks, setNetworks, network, setNetwork, tokens, setTokens, sessions, setSessions, events, setEvents, contacts, setContacts, biometric, setBiometric, autoLock, setAutoLock, walletName, setWalletName, reset };
}
type Extras = ReturnType<typeof useWalletExtras>;
export function WalletExtensions({ screen, go, extras: e, swap, available, balanceBNB }: {
  screen: ExtraScreen; go: (screen: ExtraScreen | "home" | "security") => void; extras: Extras;
  swap: (amount: string) => string | null; available: string; balanceBNB: string;
}) {
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [name, setName] = useState("");
  const [symbol, setSymbol] = useState("");
  const [chain, setChain] = useState("");
  const [rpc, setRpc] = useState("");
  const [explorer, setExplorer] = useState("");
  const [address, setAddress] = useState("");
  const [decimals, setDecimals] = useState("18");
  const [amount, setAmount] = useState("");
  const [review, setReview] = useState(false);
  const [slippage, setSlippage] = useState("0.5");
  const [url, setUrl] = useState("https://jardin.example");
  const [origin, setOrigin] = useState("https://jardin.example");
  const [consent, setConsent] = useState(false);
  const [selected, setSelected] = useState<CustomToken | null>(null);
  const [permissionDone, setPermissionDone] = useState(false);
  const current=e.networks.find(n=>n.id===e.network)!;
  const isBNB=e.network==="56";
  const move=(next: ExtraScreen | "home" | "security")=>{setError("");setNotice("");setReview(false);setConsent(false);go(next);};
  const heading=(title:string,copy:string)=><div className="lw-heading"><h1 tabIndex={-1}>{title}</h1><p>{copy}</p></div>;
  const note=(text:string)=><div className="lw-inline-note"><ShieldCheck size={20}/><p>{text}</p></div>;
  const field=(label:string,value:string,set:(value:string)=>void,placeholder="")=><label className="lw-extra-field"><span>{label}</span><input value={value} onChange={event=>{set(event.target.value);setError("");}} placeholder={placeholder} autoComplete="off" maxLength={200}/></label>;
  const row=(title:string,copy:string,click:()=>void)=><button className="lw-menu-row" onClick={click}><div><b>{title}</b><small>{copy}</small></div><ChevronRight size={19}/></button>;
  function validURL(value:string) { try { const parsed=new URL(value); return parsed.protocol==="https:" && !parsed.username && !parsed.password && !!parsed.hostname; } catch { return false; } }
  function addNetwork() {
    if(!name.trim() || !/^[A-Za-z0-9]{2,12}$/.test(symbol)) return setError("Escribe un nombre y un símbolo de 2 a 12 letras o números.");
    if(!/^[1-9]\d{0,14}$/.test(chain))return setError("El identificador de cadena debe ser un entero positivo de hasta 15 dígitos.");
    if(e.networks.some(n=>n.id===chain))return setError("Ya tienes una red con ese identificador.");
    if(!validURL(rpc)||(explorer&&!validURL(explorer)))return setError("Usa direcciones HTTPS completas, sin usuario ni contraseña.");
    e.setNetworks([...e.networks,{id:chain,name:name.trim(),symbol:symbol.toUpperCase(),rpc,explorer,custom:true}]);e.setNetwork(chain);move("networks");setNotice("Red añadida a la demo. No se ha consultado el RPC.");
  }
  function addToken() {
    if(!/^0x[0-9a-fA-F]{40}$/.test(address)||/^0x0{40}$/i.test(address))return setError("El contrato EVM debe comenzar con 0x y tener 40 caracteres hexadecimales; no puede ser la dirección cero.");
    if(!name.trim()||!/^[A-Za-z0-9]{2,12}$/.test(symbol))return setError("Completa nombre y símbolo del token.");
    if(!/^\d{1,3}$/.test(decimals)||Number(decimals)>255)return setError("Los decimales deben ser un entero entre 0 y 255.");
    if(e.tokens.some(t=>t.network===e.network&&t.address.toLowerCase()===address.toLowerCase()))return setError("Este contrato ya está añadido en esta red.");
    e.setTokens([...e.tokens,{network:e.network,address,name:name.trim(),symbol:symbol.toUpperCase(),decimals:Number(decimals)}]);move("tokens");setNotice("Token añadido con saldo 0. Sus datos no han sido verificados en blockchain.");
  }
  const numeric=Number(amount.replace(",","."));
  const parsed = parseUnits(amount, "USDT");
  const output=parsed ? Number(BigInt(parsed) / BigInt(6)) / 1e8 : 0;
  return <section className="lw-extensions">
    {screen!=="lock"&&<button className="lw-back" onClick={()=>move(["add-network"].includes(screen)?"networks":["add-token","token-detail"].includes(screen)?"tokens":["browser","connect","permission"].includes(screen)?"web3":["contacts","restore"].includes(screen)?"settings":"home")}><ArrowLeft size={19}/>Volver</button>}
    {screen==="networks"&&<>{heading("Tus redes","Elige dónde ver tus activos. Cada red mantiene su propio saldo.")}{e.networks.map(n=><div key={n.id} className="lw-network-entry"><button className="lw-menu-row" onClick={()=>{e.setNetwork(n.id);move("home");}}><span className="lw-network-letter">{n.symbol.slice(0,1)}</span><div><b>{n.name}</b><small>{`Cadena ${n.id} · ${n.symbol} · Demo`}</small></div>{e.network===n.id?<Check/>:<ChevronRight/>}</button>{n.custom&&<button className="lw-icon-button" aria-label={`Eliminar red ${n.name}`} onClick={()=>{e.setNetworks(e.networks.filter(item=>item.id!==n.id));e.setTokens(e.tokens.filter(t=>t.network!==n.id));if(e.network===n.id)e.setNetwork("56");}}><Trash2 size={18}/></button>}</div>)}{e.network==="9580"&&<dl className="lw-details"><div><dt>RPC configurado</dt><dd>https://rpc.omdbscan.com</dd></div><div><dt>Explorador</dt><dd>https://omdbscan.com</dd></div><div><dt>Moneda nativa</dt><dd>OMDB</dd></div></dl>}<button className="lw-primary" onClick={()=>{setName("");setSymbol("");setChain("");setRpc("");setExplorer("");move("add-network");}}><Plus/>Añadir red manualmente</button>{note("Esta demo no se conecta a ninguna red. Añadir una configuración no demuestra compatibilidad.")}</>}
    {screen==="add-network"&&<>{heading("Añadir una red","Introduce los datos de una red EVM. En esta demo solo guardaremos la configuración durante la sesión.")}<form onSubmit={event=>{event.preventDefault();addNetwork();}}>{field("Nombre de la red",name,setName,"Mi red de prueba")}{field("URL RPC (HTTPS)",rpc,setRpc,"https://rpc.example")}{field("Identificador de cadena",chain,setChain,"12345")}{field("Símbolo de la moneda",symbol,setSymbol,"TEST")}{field("Explorador (opcional)",explorer,setExplorer,"https://explorer.example")}<button className="lw-primary">Guardar red de prueba</button></form></>}
    {screen==="tokens"&&<>{heading("Gestionar monedas",`Activos en ${current.name}. Añadir un token no crea una moneda ni le asigna valor.`)}{e.network==="9580"&&<div className="lw-menu-row"><div><b>OMDB</b><small>Moneda nativa · Saldo de demo: 0</small></div></div>}{isBNB&&<><div className="lw-menu-row"><div><b>USDT · Tether</b><small>Activo de ejemplo · {available} USDT</small></div></div><div className="lw-menu-row"><div><b>BNB</b><small>Moneda para comisiones · {balanceBNB} BNB de ejemplo</small></div></div></>}{e.tokens.filter(t=>t.network===e.network).map(t=><div className="lw-network-entry" key={t.address}>{row(t.symbol,`${t.name} · Saldo 0`,()=>{setSelected(t);move("token-detail");})}<button className="lw-icon-button" aria-label={`Ocultar ${t.symbol}`} onClick={()=>e.setTokens(e.tokens.filter(item=>item!==t))}><Trash2 size={18}/></button></div>)}{!isBNB&&!e.tokens.some(t=>t.network===e.network)&&<p className="lw-footnote">Todavía no tienes tokens añadidos en esta red.</p>}<button className="lw-primary" onClick={()=>{setName("");setSymbol("");setAddress("");setDecimals("18");move("add-token");}}><Plus/>Añadir token por contrato</button>{row("Cambiar red",current.name,()=>move("networks"))}</>}
    {screen==="add-token"&&<>{heading("Añadir un token",`Red seleccionada: ${current.name}. Comprueba que el contrato corresponda a esta red.`)}<form onSubmit={event=>{event.preventDefault();addToken();}}>{field("Contrato del token",address,setAddress,"0x…")}{field("Nombre del token",name,setName,"Token de ejemplo")}{field("Símbolo del token",symbol,setSymbol,"DEMO")}{field("Decimales",decimals,setDecimals)}{note("Sin conexión no podemos consultar los datos del contrato. Estos campos son manuales y no están verificados.")}<button className="lw-primary">Añadir a mis monedas</button></form></>}
    {screen==="token-detail"&&selected&&<>{heading(selected.name,`${selected.symbol} · ${current.name}`)}<div className="lw-review-amount"><h2>0 {selected.symbol}</h2><p>Sin cotización ni fondos reales</p></div><dl className="lw-details"><div><dt>Contrato</dt><dd>{selected.address}</dd></div><div><dt>Decimales</dt><dd>{selected.decimals}</dd></div><div><dt>Verificación</dt><dd>{selected.preset ? "Metadatos consultados por RPC · No auditado" : "Datos manuales"}</dd></div></dl>{note("Este token está añadido para probar su gestión. Los ejemplos de envío y recepción usan USDT y BNB en BNB Chain.")}<button className="lw-primary" onClick={()=>{e.setNetwork("56");move("home");}}>Ir a los activos de ejemplo</button></>}
    {screen==="swap"&&<>{heading(review?"Revisa tu intercambio":"Intercambiar monedas", "Ejemplo en BNB Chain. Precio fijo ficticio: 1 BNB = 600 USDT.")}{!review?<><label className="lw-extra-field"><span>Entregas USDT</span><input inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setError("");}} placeholder="0.00"/></label><p className="lw-footnote">Disponible: {available} USDT</p><div className="lw-details"><div><dt>Recibes, de ejemplo</dt><dd>{output.toFixed(8)} BNB</dd></div></div><label className="lw-extra-field"><span>Tolerancia de deslizamiento</span><select value={slippage} onChange={event=>setSlippage(event.target.value)}><option value="0.5">0.5 %</option><option value="1">1 %</option></select></label><button className="lw-primary" onClick={()=>{if(!/^\d+(?:[.,]\d{1,6})?$/.test(amount)||numeric<=0||numeric>Number(available.replaceAll(",",""))||output<=0)return setError("Introduce una cantidad válida de USDT, sin superar tu saldo.");setReview(true);}}>Revisar intercambio<ArrowRight size={20}/></button></>:<><dl className="lw-details"><div><dt>Entregas</dt><dd>{amount} USDT</dd></div><div><dt>Recibes</dt><dd>{output.toFixed(8)} BNB</dd></div><div><dt>Mínimo ilustrativo</dt><dd>{(output*(1-Number(slippage)/100)).toFixed(8)} BNB</dd></div><div><dt>Comisión de red simulada</dt><dd>0.00005 BNB</dd></div><div><dt>Proveedor</dt><dd>Simulador local LAEX</dd></div></dl>{note("No hay cotización de mercado ni aprobación de contrato. Esta simulación actualizará los saldos USDT/BNB y registrará ambos movimientos.")}<button className="lw-primary" onClick={()=>{const problem=swap(amount);if(problem){setError(problem);return;}e.setNetwork("56");setReview(false);setAmount("");setNotice("Intercambio simulado completado. Consulta tu saldo y actividad.");}}>Confirmar intercambio demo</button><button className="lw-secondary" onClick={()=>setReview(false)}>Editar importe</button></>}{notice&&<button className="lw-secondary" onClick={()=>move("home")}>Ver mi saldo</button>}</>}
    {screen==="web3"&&<>{heading("Explora Web3","Aprende a conectar una aplicación y revisar sus solicitudes, sin exponer claves.")}<button className="lw-primary" onClick={()=>move("browser")}><Globe size={20}/>Abrir navegador demo</button><div className="lw-section-title"><h2>Aplicaciones de ejemplo</h2></div>{row("Jardín Web3","Aplicación ficticia · Conexión y permisos",()=>{setOrigin("https://jardin.example");setPermissionDone(false);move("browser");})}{row("Conectar con QR","Simulación de emparejamiento; no usa la cámara",()=>{setOrigin("https://conexion.example");move("connect");})}<div className="lw-section-title"><h2>Sesiones conectadas</h2></div>{!e.sessions.length&&<p className="lw-footnote">Ninguna aplicación conectada.</p>}{e.sessions.map(site=><div className="lw-network-entry" key={site}><div className="lw-menu-row"><div><b>{site}</b><small>Sesión local de prueba</small></div></div><button className="lw-icon-button" aria-label={`Desconectar ${site}`} onClick={()=>e.setSessions(e.sessions.filter(s=>s!==site))}><Trash2 size={18}/></button></div>)}{!!e.events.length&&<details className="lw-help"><summary>Actividad Web3 simulada</summary>{e.events.map((item,index)=><p key={index}>{item}</p>)}</details>}{note("Ninguna web externa se carga ni recibe datos. Conectar una aplicación nunca debe autorizar automáticamente a gastar tus monedas.")}</>}
    {screen==="browser"&&<>{heading("Navegador Web3","Vista de práctica: escribir una URL no abre internet.")}<form onSubmit={event=>{event.preventDefault();if(!validURL(url))return setError("Introduce una URL HTTPS válida, sin credenciales.");setOrigin(new URL(url).origin);setNotice("Dominio preparado para una simulación. No se ha visitado el sitio.");}}>{field("Dirección web",url,setUrl,"https://jardin.example")}<button className="lw-secondary">Preparar vista de prueba</button></form><div className="lw-dapp-card"><Globe size={32}/><h2>Aplicación de práctica</h2><p>{origin}</p><span className="lw-eyebrow">CONTENIDO FICTICIO DE LAEX</span><p>Conecta tu cuenta de ejemplo y prueba una solicitud de permiso.</p>{e.sessions.includes(origin)?<><div className="lw-detail-status"><Check size={18}/>Cuenta demo conectada</div><button className="lw-primary" onClick={()=>{setPermissionDone(false);move("permission");}}>Probar solicitud de contrato</button></>:<button className="lw-primary" onClick={()=>move("connect")}>Conectar wallet demo</button>}</div></>}
    {screen==="connect"&&<>{heading("Revisa la conexión","Comprueba quién solicita acceso antes de aceptar.")}<dl className="lw-details"><div><dt>Sitio</dt><dd>{origin}</dd></div><div><dt>Red de ejemplo</dt><dd>BNB Chain</dd></div><div><dt>Cuenta</dt><dd>LAEX-DEMO-001</dd></div><div><dt>Permiso</dt><dd>Ver la cuenta de ejemplo y solicitar acciones</dd></div></dl>{note("Tu frase nunca se comparte. Cada firma o gasto requiere una revisión aparte. Esta conexión solo existe dentro de la demo.")}<button className="lw-primary" onClick={()=>{if(!e.sessions.includes(origin))e.setSessions([...e.sessions,origin]);e.setEvents([`Conexión de prueba: ${origin}`,...e.events]);move("browser");}}>Aceptar conexión demo</button><button className="lw-secondary" onClick={()=>move("web3")}>Rechazar conexión</button></>}
    {screen==="permission"&&<>{heading(permissionDone?"Solicitud simulada":"Permiso de un contrato",permissionDone?"No se ha firmado nada ni se han movido monedas.":"Lee el límite que estás autorizando.")}{!permissionDone?<><dl className="lw-details"><div><dt>Solicitante</dt><dd>{origin}</dd></div><div><dt>Acción de ejemplo</dt><dd>Aprobar hasta 10 USDT</dd></div><div><dt>Contrato ficticio</dt><dd>CONTRATO-DEMO-JARDIN</dd></div><div><dt>Red</dt><dd>BNB Chain</dd></div><div><dt>Comisión ilustrativa</dt><dd>0.00005 BNB</dd></div></dl>{note("En una wallet real este permiso permitiría al contrato gastar hasta ese límite. Aquí no se firma ni se descuenta comisión.")}<label className="lw-checkbox"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>Entiendo el límite de este permiso de ejemplo.</span></label><button className="lw-primary" disabled={!consent||!e.sessions.includes(origin)} onClick={()=>{e.setEvents([`Permiso simulado: 10 USDT · ${origin}`,...e.events]);setPermissionDone(true);}}>Simular autorización</button><button className="lw-secondary" onClick={()=>{e.setEvents([`Solicitud rechazada · ${origin}`,...e.events]);move("web3");}}>Rechazar solicitud</button></>:<button className="lw-primary" onClick={()=>move("web3")}>Ver conexiones</button>}</>}
    {screen==="settings"&&<>{heading("A tu manera","Preferencias de esta sesión de demostración.")}{field("Nombre de tu wallet",e.walletName,value=>e.setWalletName(value.slice(0,30)))}{row("Contactos","Guarda destinatarios ficticios",()=>move("contacts"))}{row("Recuperar una wallet","Recorre el proceso sin introducir una frase",()=>move("restore"))}{row("Redes y tokens",`${e.networks.length} redes en la maqueta`,()=>move("networks"))}{row("Conexiones Web3",`${e.sessions.length} sesiones de prueba`,()=>move("web3"))}{row("Seguridad y respaldo","Aprende a cuidar tus claves",()=>move("security"))}<label className="lw-checkbox"><input type="checkbox" checked={e.biometric} onChange={event=>e.setBiometric(event.target.checked)}/><span>Preferir huella en Android (preferencia de demo, no activa el sensor).</span></label><label className="lw-extra-field"><span>Bloqueo automático propuesto</span><select value={e.autoLock} onChange={event=>e.setAutoLock(event.target.value)}><option>1 minuto</option><option>5 minutos</option><option>Al salir de la app</option></select></label><p className="lw-footnote">El temporizador y la huella se implementarán en Android. Idioma: español. Moneda de referencia: USD.</p><button className="lw-secondary" onClick={()=>move("lock")}>Probar pantalla de bloqueo</button><details className="lw-help"><summary>Ayuda: lo que debes recordar</summary><p>La comisión se paga con la moneda nativa de cada red. Un token y su copia en otra cadena son activos distintos.</p><p>LAEX nunca te pedirá una frase secreta. Si se pierde el respaldo de una wallet real, soporte no podrá recuperarlo.</p><p>Esta demo se reinicia al recargar. No genera claves, no se conecta a bancos y no guarda tus formularios en servidores.</p></details></>}
    {screen==="contacts"&&<>{heading("Tus contactos","Solo identificadores ficticios de esta demo.")}{e.contacts.map(c=><div className="lw-network-entry" key={c.address}><div className="lw-menu-row"><div><b>{c.name}</b><small>{c.address}</small></div></div><button className="lw-icon-button" aria-label={`Eliminar contacto ${c.name}`} onClick={()=>e.setContacts(e.contacts.filter(item=>item.address!==c.address))}><Trash2 size={18}/></button></div>)}<form onSubmit={event=>{event.preventDefault();if(!name.trim()||!/^LAEX-DEMO-00[23]$/.test(address))return setError("Usa un nombre y LAEX-DEMO-002 o LAEX-DEMO-003. No introduzcas direcciones reales.");if(e.contacts.some(c=>c.address===address))return setError("Ese identificador ya está guardado. Elimínalo antes de cambiar su nombre.");e.setContacts([...e.contacts,{name:name.trim().slice(0,30),address}]);setName("");setAddress("");setNotice("Contacto de prueba guardado.");}}>{field("Nombre del contacto",name,setName)}{field("Identificador ficticio",address,setAddress,"LAEX-DEMO-002")}<button className="lw-primary">Guardar contacto demo</button></form></>}
    {screen==="restore"&&<>{heading(review?"Restauración de ejemplo lista":"Recuperar tu wallet",review?"En una wallet real comprobaríamos que el respaldo devuelve las mismas cuentas.":"En Android podrás recuperar tu cuenta con tu respaldo. Aquí no escribas ninguna frase real.")}{!review?<><ol className="lw-lessons"><li><span>01</span><div><h2>Ten tu respaldo a mano</h2><p>La aplicación real comprobará las palabras y su orden en tu dispositivo.</p></div></li><li><span>02</span><div><h2>Protege el acceso</h2><p>Configurarás un bloqueo local antes de consultar tus cuentas.</p></div></li></ol><label className="lw-checkbox"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>Usar un respaldo ficticio. No se recuperará ninguna wallet real.</span></label><button className="lw-primary" disabled={!consent} onClick={()=>setReview(true)}>Simular recuperación</button></>:<><div className="lw-detail-status"><Check/>Recorrido completado</div><p className="lw-footnote">Conservamos el saldo de tu sesión para que sigas explorando.</p><button className="lw-primary" onClick={()=>move("home")}>Ir a mi wallet demo</button></>}</>}
    {screen==="lock"&&<div className="lw-lock-screen"><ShieldCheck size={55}/>{heading("Tu wallet, en privado","Vista de bloqueo de ejemplo. No protege fondos ni utiliza huella o contraseña.")}<button className="lw-primary" onClick={()=>move("home")}>Desbloquear demostración</button></div>}
    {error&&<p className="lw-error" role="alert">{error}</p>}{notice&&<p className="lw-extra-notice" role="status">{notice}</p>}
  </section>;
}
