"use client";
import { useMemo,useState } from "react";
import { AlertTriangle,ArrowLeft,Check,ShieldCheck,Upload } from "lucide-react";
import { createPendingVerification } from "../application/create-verification";
import type { PaymentMethodProfile,PaymentVerification } from "../domain/types";

export function PaymentCenter({methods,projectName}:{methods:readonly PaymentMethodProfile[];projectName:string}){
 const available=useMemo(()=>methods.filter(method=>method.enabled),[methods]); const[selectedId,setSelectedId]=useState(available[0]?.id??""); const[sent,setSent]=useState<PaymentVerification|null>(null); const selected=available.find(method=>method.id===selectedId);
 if(sent)return <div className="p-7 sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-emerald-400/15 text-emerald-300"><Check/></span><p className="mt-6 text-[10px] font-black uppercase tracking-[.22em] text-emerald-300">Solicitud recibida</p><h2 className="mt-2 text-2xl font-black">Pendiente de verificación</h2><p className="mt-3 text-sm leading-6 text-slate-400">No se aprobará automáticamente. El equipo administrativo revisará el Hash y el comprobante.</p><div className="mt-6 rounded-xl border border-white/10 bg-white/[.04] p-4 text-xs text-slate-300"><b>Referencia:</b> {sent.id}</div><button type="button" onClick={()=>setSent(null)} className="mt-6 flex items-center gap-2 text-xs font-bold text-cyan-300"><ArrowLeft size={14}/> Registrar otro pago</button></div>;
 return <div className="p-6 sm:p-8"><div className="pr-10"><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-300">Centro de Pagos LAEX</p><h2 className="mt-2 text-2xl font-black">Verificar un pago</h2><p className="mt-2 text-xs leading-5 text-slate-400">Selecciona el método, revisa las instrucciones y registra la transferencia.</p></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2 scrollbar-hide">{available.map(method=><button type="button" key={method.id} onClick={()=>setSelectedId(method.id)} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-bold transition ${selectedId===method.id?"border-cyan-300 bg-cyan-300 text-black":"border-white/10 bg-white/[.04] text-slate-300 hover:border-white/25"}`}>{method.name}</button>)}</div>{selected&&<><div className="mt-4 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.045] p-4"><p className="text-xs font-black text-cyan-200">{selected.destinationLabel}</p><p className="mt-2 text-xs text-slate-300">{selected.destinationValue}</p><ol className="mt-4 space-y-2 text-[11px] leading-5 text-slate-400">{selected.instructions.map((instruction,index)=><li key={instruction}>{index+1}. {instruction}</li>)}</ol></div><div className="mt-4 flex gap-3 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-[11px] leading-5 text-amber-100"><AlertTriangle size={18} className="shrink-0"/><p>Toda transferencia deberá incluir obligatoriamente el Hash (ID) de la transacción y la captura del comprobante. Sin esta información no será posible verificar el pago y la solicitud permanecerá pendiente.</p></div><VerificationForm method={selected} projectName={projectName} onSent={setSent}/></>}</div>;
}
function VerificationForm({method,projectName,onSent}:{method:PaymentMethodProfile;projectName:string;onSent:(payment:PaymentVerification)=>void}){
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const receipt=form.get("receipt") as File;onSent(createPendingVerification({customerName:String(form.get("name")),email:String(form.get("email")),phone:String(form.get("phone")),project:String(form.get("project")),amount:Number(form.get("amount")),currency:String(form.get("currency")),paidAt:String(form.get("paidAt")),methodId:method.id,transactionHash:String(form.get("hash")),receiptName:receipt.name}));}
 const field="w-full rounded-xl border border-white/10 bg-white/[.045] px-3 py-3 text-xs text-white outline-none transition focus:border-cyan-300/50";
 return <form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Nombre completo"><input name="name" required className={`${field} mt-1`} autoComplete="name"/></Field><Field label="Correo electrónico"><input name="email" type="email" required className={`${field} mt-1`} autoComplete="email"/></Field><Field label="Teléfono"><input name="phone" type="tel" required className={`${field} mt-1`} autoComplete="tel"/></Field><Field label="Proyecto o servicio"><input name="project" defaultValue={projectName} required className={`${field} mt-1`}/></Field><Field label="Monto pagado"><input name="amount" type="number" min="0.01" step="0.01" required className={`${field} mt-1`}/></Field><Field label="Moneda"><select name="currency" required className={`${field} mt-1`}>{method.currencies.map(currency=><option key={currency} className="bg-[#07111b]">{currency}</option>)}</select></Field><Field label="Fecha del pago"><input name="paidAt" type="date" required className={`${field} mt-1`}/></Field><Field label="Método utilizado"><input value={method.name} readOnly className={`${field} mt-1 opacity-70`}/></Field><label className="text-[11px] text-slate-400 sm:col-span-2">Hash o ID de transacción<input name="hash" required minLength={4} className={`${field} mt-1 font-mono`} placeholder="ID único de la operación"/></label><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-white/15 p-4 text-xs text-slate-400 transition hover:border-cyan-300/40 sm:col-span-2"><Upload size={18} className="text-cyan-300"/><span>Captura del comprobante <b className="text-white">(obligatoria)</b></span><input name="receipt" type="file" accept="image/png,image/jpeg,image/webp" required className="ml-auto max-w-36 text-[10px] file:hidden"/></label><button type="submit" className="flex items-center justify-center gap-2 rounded-xl bg-cyan-300 px-5 py-3.5 text-xs font-black text-black transition hover:bg-cyan-200 sm:col-span-2"><ShieldCheck size={16}/> Enviar para verificación humana</button></form>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-[11px] text-slate-400">{label}{children}</label>}
