import type{LearningPath}from"../domain/types";
const refs={btc:[{type:"market",label:"Bitcoin en Market Intelligence",href:"/market/bitcoin"},{type:"news",label:"Evento de liquidez",href:"/noticias/bitcoin-liquidez-institucional"},{type:"community",label:"Síntesis comunitaria",href:"/comunidad?context=bitcoin"}],sol:[{type:"market",label:"Solana en Market Intelligence",href:"/market/solana"},{type:"news",label:"Actualización de red",href:"/noticias/solana-estabilidad-red"}],media:[{type:"media",label:"Media Intelligence",href:"/media-intelligence"},{type:"community",label:"Conocimiento colaborativo",href:"/comunidad"}]} as const;
export const learningPaths:LearningPath[]=[
 {id:"path-01",slug:"fundamentos-del-ecosistema",title:"Fundamentos del ecosistema digital",description:"Construye criterio para interpretar blockchain, activos, redes y evidencia sin depender del ruido.",level:"Inicial",status:"Disponible",accent:"cyan",skills:["Blockchain","Riesgo","Evidencia"],ai:{reason:"Base recomendada para comprender señales de Market y News Intelligence.",confidence:94},lessons:[{id:"l-01",title:"Cómo leer una red blockchain",duration:12,summary:"Conceptos esenciales: consenso, bloques, validadores y finalidad.",objectives:["Distinguir red, token y aplicación","Reconocer límites técnicos"],references:[...refs.sol]},{id:"l-02",title:"Precio no es valor",duration:14,summary:"Aprende a separar cotización, liquidez, volumen y narrativa.",objectives:["Interpretar datos básicos","Evitar conclusiones sin evidencia"],references:[...refs.btc]}]},
 {id:"path-02",slug:"inteligencia-de-mercado",title:"Inteligencia de mercado con evidencia",description:"Lee movimientos, fuentes y riesgos con la metodología neutral de LAEX.",level:"Intermedio",status:"Disponible",accent:"violet",skills:["Mercados","Liquidez","Metodología"],ai:{reason:"Conecta tus intereses en Bitcoin con preguntas frecuentes de Comunidad.",confidence:89},lessons:[{id:"l-03",title:"Liquidez y profundidad",duration:18,summary:"Qué revelan y qué no revelan las ventanas de mercado.",objectives:["Leer profundidad","Identificar falsas certezas"],references:[...refs.btc]},{id:"l-04",title:"Fuentes y confianza",duration:16,summary:"Evalúa procedencia, actualidad y limitaciones de un análisis.",objectives:["Auditar fuentes","Diferenciar hecho e interpretación"],references:[...refs.btc]}]},
 {id:"path-03",slug:"crear-con-conocimiento",title:"Crear con conocimiento trazable",description:"Transforma aprendizaje y conversación validada en contenido útil sin perder autoría ni procedencia.",level:"Intermedio",status:"Disponible",accent:"green",skills:["Creación","Síntesis","Procedencia"],ai:{reason:"Ruta sugerida para conectar Academy, Comunidad y Media Intelligence.",confidence:92},lessons:[{id:"l-05",title:"De pregunta a brief",duration:20,summary:"Organiza evidencia antes de producir una pieza editorial.",objectives:["Construir un brief","Conservar procedencia"],references:[...refs.media]},{id:"l-06",title:"IA con supervisión humana",duration:17,summary:"Usa IA para asistir, no para sustituir criterio y responsabilidad.",objectives:["Reconocer contenido IA","Aplicar revisión humana"],references:[...refs.media]}]},
 {id:"path-04",slug:"evaluacion-de-proyectos",title:"Evaluación independiente de proyectos",description:"Marco neutral para estudiar identidad, documentación, riesgos y comunidad.",level:"Avanzado",status:"Próximamente",accent:"orange",skills:["Due diligence","Proyectos","Riesgo"],ai:{reason:"Se habilitará tras consolidar metodología y casos auditados.",confidence:97},lessons:[]}
];
export const findLearningPath=(slug:string)=>learningPaths.find(p=>p.slug===slug);
