plugins { id 'com.android.application' }
android {
    namespace 'com.laexwallet.testnet'
    compileSdk 35
    defaultConfig {
        applicationId 'com.laexwallet.testnet'
        minSdk 30
        targetSdk 35
        versionCode 5
        versionName '0.1.4-testnet'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
    buildTypes { release { minifyEnabled false } }
    packaging { resources { excludes += ['META-INF/LICENSE*', 'META-INF/NOTICE*', 'META-INF/DISCLAIMER', 'META-INF/DEPENDENCIES', 'META-INF/versions/9/OSGI-INF/MANIFEST.MF'] } }
    testOptions { unitTests.returnDefaultValues = true; unitTests.includeAndroidResources = true
        unitTests.all { systemProperty 'robolectric.dependency.repo.url', 'https://repo.maven.apache.org/maven2' }
    }
}
dependencies {
    implementation 'org.web3j:crypto:4.12.3'
    implementation 'com.google.zxing:core:3.5.3'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.14.1'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
