import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { MarketDataOrchestrator } from "../../modules/market-intelligence/application/MarketDataOrchestrator";
import { buildMarketNarrative } from "../../modules/market-intelligence/application/MarketNarrative";
import { findMarketAsset, marketCatalog } from "../../modules/market-intelligence/domain/catalog";
import type { AssetIdentity, MarketDataBundle, MarketDataProvider, MarketInterval } from "../../modules/market-intelligence/domain/market-data";

const bitcoin=findMarketAsset("bitcoin")!;
function data(asset:AssetIdentity,provider:string,price=100):Omit<MarketDataBundle,"cache"|"fallbackUsed"|"errors">{const at=new Date().toISOString();return{identity:asset,quote:{assetId:asset.assetId,price,change24h:2,volume24h:1000,marketCap:10000,high24h:105,low24h:95,circulatingSupply:100,totalSupply:200,observedAt:at,provider,state:"live",staleAfterSeconds:60},candles:[{timestamp:1,open:99,high:102,low:98,close:100,volume:10}],venues:[{name:"Venue A",pair:"BTC/USD",price,volume:10,spread:.1,observedAt:at,quality:"high",provider}],provenance:[`${provider}:quote`],generatedAt:at}}
class FakeProvider implements MarketDataProvider{calls=0;constructor(readonly id:string,private behavior:(asset:AssetIdentity)=>Omit<MarketDataBundle,"cache"|"fallbackUsed"|"errors">|Error){}supports(){return true}async fetchBundle(asset:AssetIdentity,_interval:MarketInterval,_signal:AbortSignal){this.calls++;const result=this.behavior(asset);if(result instanceof Error)throw result;return result}}

describe("identidad y catálogo",()=>{it("usa identidades internas únicas y no depende del símbolo",()=>{assert.equal(new Set(marketCatalog.map(a=>a.assetId)).size,marketCatalog.length);assert.ok(marketCatalog.every(a=>a.assetId&&a.networkId&&a.symbol));assert.equal(findMarketAsset("solana")?.providerId,"solana")});it("mantiene OMD pendiente y LAEX conceptual",()=>{assert.equal(findMarketAsset("omd")?.status,"identity-pending");assert.equal(findMarketAsset("laex")?.status,"conceptual")})});
describe("orquestación resiliente",()=>{it("cachea y deduplica lecturas",async()=>{const provider=new FakeProvider("primary",asset=>data(asset,"primary")),service=new MarketDataOrchestrator([provider],10_000);const[first,second]=await Promise.all([service.get(bitcoin,"1h"),service.get(bitcoin,"1h")]);assert.equal(provider.calls,1);assert.equal(first.quote.price,second.quote.price);assert.equal((await service.get(bitcoin,"1h")).cache,"hit")});it("activa proveedor secundario sin mezclar procedencia",async()=>{const primary=new FakeProvider("primary",()=>new Error("down")),secondary=new FakeProvider("secondary",asset=>data(asset,"secondary",101)),service=new MarketDataOrchestrator([primary,secondary]);const result=await service.get(bitcoin,"1h");assert.equal(result.fallbackUsed,true);assert.equal(result.quote.provider,"secondary");assert.deepEqual(result.provenance,["secondary:quote"])});it("sirve caché retrasada cuando todos fallan",async()=>{let fail=false;const provider=new FakeProvider("primary",asset=>fail?new Error("down"):data(asset,"primary")),service=new MarketDataOrchestrator([provider],0,60_000);await service.get(bitcoin,"1h");fail=true;const result=await service.get(bitcoin,"1h");assert.equal(result.cache,"stale");assert.equal(result.quote.state,"delayed")});it("abre el circuito después de fallos repetidos",async()=>{const provider=new FakeProvider("primary",()=>new Error("down")),service=new MarketDataOrchestrator([provider]);await service.get(bitcoin,"1h");await service.get(bitcoin,"1h");await service.get(bitcoin,"1h");await service.get(bitcoin,"1h");assert.equal(provider.calls,6)})});
describe("narrativa",()=>{it("reduce confianza cuando no hay datos",()=>{const unavailable={...data(bitcoin,"none"),quote:{...data(bitcoin,"none").quote,price:null,state:"unavailable" as const},venues:[],cache:"miss" as const,fallbackUsed:false,errors:["down"]};const story=buildMarketNarrative(unavailable,"1h");assert.equal(story.confidence,0);assert.match(story.text,/No evaluable/)});it("describe divergencia como inferencia y no causalidad",()=>{const base=data(bitcoin,"primary"),bundle:MarketDataBundle={...base,venues:[...base.venues,{...base.venues[0],name:"Venue B",price:103}],cache:"miss",fallbackUsed:false,errors:[]};const story=buildMarketNarrative(bundle,"1h");assert.match(story.text,/puede relacionarse/i);assert.match(story.text,/no permiten afirmar causalidad/i)})});
