import type { CommunityDigest,KnowledgeItem } from "../domain/types";
const evidence=(id:string,kind:"market-data"|"official-source"|"news-source"|"academy"|"project-record",label:string,source:string)=>({id,kind,label,source,capturedAt:"2026-08-03T14:20:00-04:00"});
export const knowledgeItems:KnowledgeItem[]=[
 {id:"k-001",kind:"synthesis",status:"ai-organized",title:"Liquidez de Bitcoin: qué cambió y qué no",summary:"LAEX agrupó preguntas repetidas sobre volumen, profundidad y riesgo de interpretar una sola ventana de mercado.",entities:[{type:"market",id:"bitcoin",label:"Bitcoin · BTC",href:"/market/bitcoin"},{type:"news",id:"bitcoin-liquidez-institucional",label:"Evento de liquidez",href:"/noticias/bitcoin-liquidez-institucional"}],evidence:[evidence("ev-1","market-data","Snapshot de mercado","Market Intelligence"),evidence("ev-2","news-source","5 fuentes agrupadas","News Intelligence")],contributors:18,updatedAt:"2026-08-03T14:20:00-04:00",ai:{summary:"Mayor profundidad reduce impacto de órdenes, pero no predice dirección.",confidence:89,duplicates:12,related:7}},
 {id:"k-002",kind:"question",status:"open",title:"¿Cómo validar la estabilidad de una blockchain bajo carga?",summary:"Pregunta abierta conectada con la actualización de Solana y una ruta introductoria de Academy.",entities:[{type:"news",id:"solana-estabilidad-red",label:"Actualización de Solana",href:"/noticias/solana-estabilidad-red"},{type:"academy",id:"blockchain",label:"Fundamentos de blockchain",href:"/academia"}],evidence:[evidence("ev-3","official-source","Actualización coordinada","Registro oficial"),evidence("ev-4","academy","Lección relacionada","LAEX Academy")],contributors:9,updatedAt:"2026-08-03T12:05:00-04:00",ai:{summary:"La comunidad compara disponibilidad, latencia, congestión y recuperación.",confidence:84,duplicates:4,related:5}},
 {id:"k-003",kind:"signal",status:"verified",title:"Consulta regional sobre stablecoins: límites del análisis",summary:"Síntesis neutral: la consulta no es una norma vigente y LAEX no recomienda comprar, vender o invertir.",entities:[{type:"news",id:"marco-stablecoins-latam",label:"Marco regional",href:"/noticias/marco-stablecoins-latam"}],evidence:[evidence("ev-5","official-source","Documento de consulta","Regulador regional")],contributors:6,updatedAt:"2026-08-03T10:30:00-04:00",ai:{summary:"El debate se concentra en reservas, transparencia y protección al usuario.",confidence:93,duplicates:8,related:4}},
 {id:"k-004",kind:"resource",status:"ai-organized",title:"Del debate al brief: flujo trazable para creadores",summary:"Recurso que conecta una conversación validada con Media Intelligence sin duplicar fuentes ni mezclar opinión y promoción.",entities:[{type:"media",id:"workflow",label:"Media Intelligence",href:"/media-intelligence"},{type:"project",id:"omd",label:"Proyecto OMD",href:"/proyectos/omd"}],evidence:[evidence("ev-6","project-record","Identidad del proyecto","Registro LAEX")],contributors:14,updatedAt:"2026-08-02T19:10:00-04:00",ai:{summary:"Un identificador estable conserva procedencia desde la conversación hasta el contenido.",confidence:95,duplicates:3,related:9}}
];
export const communityDigest:CommunityDigest={generatedAt:"2026-08-03T14:30:00-04:00",topicsDetected:24,duplicatesGrouped:31,answersOrganized:46,connectionsCreated:68,highlights:["Aumentan las preguntas sobre liquidez y profundidad de mercado.","Regulación de stablecoins concentra nuevas fuentes oficiales.","Academy recibió dos rutas sugeridas desde conversaciones abiertas."]};
