import {CheckCircle2,Coins,Download,ExternalLink,LoaderCircle,Pickaxe,Search,ShieldCheck,Store,WalletCards} from "lucide-react";
import type {Guide} from "./domain";

import {oneMillionMinerRealSteps} from "./onemillionminers";
export const oneMillionMinerActivationGuide:Guide={slug:"onemillionminers-activar",title:"Activa tu OneMillionMiner",shortTitle:"Cómo activar OneMillionMiner",description:"Te guiaremos paso a paso. No necesitas experiencia previa.",project:"OneMillionMiners",difficulty:"Inicial",requirements:["SafePal","Fondos requeridos"],version:"1.0",updatedAt:"4 sept. 2026",status:"verified",href:"/guias/onemillionminers/activar",projectHref:"/proyectos/onemillionminers",steps:[
{id:"preparar-wallet",number:1,title:"Prepara tu wallet",instruction:"Abre SafePal en tu teléfono.",explanation:"Ten tu wallet lista antes de comenzar. No compartas información privada.",media:{kind:"prototype",alt:"Vista provisional para abrir SafePal"},hotspot:{x:50,y:57,label:"Abre tu wallet"},icon:WalletCards,warning:"Nunca compartas tu frase de recuperación o clave privada."},
{id:"comprobar-requisitos",number:2,title:"Comprueba lo necesario",instruction:"Verifica que tienes lo necesario para continuar.",explanation:"La red, moneda y monto se añadirán cuando sean confirmados oficialmente.",media:{kind:"prototype",alt:"Lista provisional de requisitos"},hotspot:{x:72,y:41,label:"Revisa aquí"},icon:Coins,warning:"Verifica red, moneda y monto antes de confirmar."},
{id:"abrir-proyecto",number:3,title:"Abre OneMillionMiners",instruction:"Entra mediante el acceso oficial verificado.",explanation:"Aquí mostraremos el enlace o acceso correcto tras la activación real.",media:{kind:"prototype",alt:"Acceso provisional a OneMillionMiners"},hotspot:{x:50,y:67,label:"Acceso oficial"},icon:ExternalLink},
{id:"conectar-wallet",number:4,title:"Conecta tu wallet",instruction:"Pulsa aquí para conectar tu wallet.",explanation:"El nombre y la posición exactos se marcarán sobre la captura oficial.",media:{kind:"prototype",alt:"Demostración provisional de un botón señalado"},hotspot:{x:72,y:23,label:"Toca aquí"},icon:ShieldCheck},
{id:"activar-miner",number:5,title:"Inicia la activación",instruction:"Elige la opción verificada y continúa.",explanation:"No mostraremos opciones ni cantidades hasta validarlas en el proceso real.",media:{kind:"prototype",alt:"Opciones provisionales de activación"},hotspot:{x:50,y:69,label:"Continúa aquí"},icon:Pickaxe,warning:"Verifica red, moneda y monto antes de confirmar."},
{id:"confirmar-resultado",number:6,title:"Confirma el resultado",instruction:"Comprueba que la activación terminó correctamente.",explanation:"Sustituiremos este estado por la confirmación oficial verificada.",media:{kind:"prototype",alt:"Estado final provisional de la activación"},hotspot:{x:50,y:47,label:"Estado final"},icon:CheckCircle2}]};
export const safePalDownloadGuide:Guide={slug:"safepal-descargar-android",title:"Vamos a instalar tu wallet SafePal",shortTitle:"Descargar SafePal en Android",description:"Encuentra, identifica e instala la aplicación correcta desde Google Play.",project:"Wallets",difficulty:"Inicial",requirements:["Celular Android","Acceso a Google Play"],version:"1.0",updatedAt:"4 sept. 2026",status:"verified",href:"/guias/safepal/descargar",projectHref:"https://www.safepal.com/es/download",steps:[{id:"abrir-play-store",number:1,title:"Abre Google Play Store",instruction:"Busca Play Store en tu celular y tócala.",explanation:"",media:{kind:"prototype",alt:"Teléfono Android con Google Play Store resaltado"},icon:Store},{id:"buscar-safepal",number:2,title:"Busca SafePal",instruction:"Toca aquí y escribe SafePal.",explanation:"",media:{kind:"prototype",alt:"Barra de búsqueda de Google Play"},icon:Search},{id:"identificar-app",number:3,title:"Elige la aplicación correcta",instruction:"Comprueba el nombre y el desarrollador.",explanation:"",media:{kind:"image",src:"/guides/safepal/app-icon.webp",alt:"Ficha oficial de SafePal"},icon:ShieldCheck},{id:"instalar",number:4,title:"Instala SafePal",instruction:"Pulsa Instalar.",explanation:"",media:{kind:"prototype",alt:"Botón Instalar"},icon:Download},{id:"esperar",number:5,title:"Espera un momento",instruction:"Deja que termine la instalación.",explanation:"",media:{kind:"prototype",alt:"SafePal instalándose"},icon:LoaderCircle},{id:"lista",number:6,title:"SafePal ya está instalada",instruction:"¡Listo! No la abras todavía.",explanation:"",media:{kind:"image",src:"/guides/safepal/app-icon.webp",alt:"SafePal instalada"},icon:CheckCircle2}]};

export const oneMillionMinerRealGuide:Guide={...oneMillionMinerActivationGuide,version:"1.0",updatedAt:"4 sept. 2026",steps:oneMillionMinerRealSteps};

export const guides:Guide[]=[safePalDownloadGuide,oneMillionMinerRealGuide];