import type {GuideStep} from "./domain";
import {CircleCheckBig,Copy,ExternalLink,Globe2,Network,Plus,Search,ShieldCheck,WalletCards} from "lucide-react";

export type GuidedCaptureStep=GuideStep&{
 stage:string;
 actionLabel?:string;
 expectedState:string;
 hotspot:{x:number;y:number;label:string};
 copyFields?:Array<{label:string;value:string}>;
};
const media=(n:number,alt:string)=>({kind:"image" as const,src:"/guides/onemillionminers/steps/"+String(n).padStart(2,"0")+".webp",alt});
export const oneMillionMinerRealSteps:GuidedCaptureStep[]=[
{id:"redes",number:1,stage:"Configurar OMDBlockchain",title:"Entra a las redes",instruction:"Toca aquí.",explanation:"Abre el selector de redes.",media:media(1,"Pantalla principal de SafePal con selector de redes señalado"),hotspot:{x:75,y:42,label:"TOCA AQUÍ"},expectedState:"Verás la lista de redes.",icon:Network},
{id:"nueva-red",number:2,stage:"Configurar OMDBlockchain",title:"Añade una red",instruction:"Ahora toca el signo +.",explanation:"",media:media(2,"Lista de redes con signo más señalado"),hotspot:{x:88,y:14,label:"TOCA +"},expectedState:"Aparecerán las opciones para añadir una red.",icon:Plus},
{id:"manual",number:3,stage:"Configurar OMDBlockchain",title:"Elige añadir manualmente",instruction:"Toca AÑADIR MANUALMENTE.",explanation:"",media:media(3,"Opción Añadir manualmente señalada"),hotspot:{x:42,y:17,label:"TOCA AQUÍ"},expectedState:"Se abrirá el formulario de red.",icon:Plus},
{id:"datos-red",number:4,stage:"Configurar OMDBlockchain",title:"Copia los datos de la red",instruction:"Copia cada dato y colócalo en su campo.",explanation:"No necesitas memorizar nada.",media:media(4,"Formulario OMDBlockchain completado"),hotspot:{x:50,y:48,label:"COMPLETA AQUÍ"},expectedState:"Todos los campos quedarán completos.",icon:Copy,copyFields:[{label:"Nombre",value:"OMDBlockchain"},{label:"Símbolo",value:"OMDB"},{label:"RPC",value:"https://rpc.omdbscan.com"},{label:"Explorer",value:"https://omdbscan.com"},{label:"Chain ID",value:"9580"}]},
{id:"anadir-red",number:5,stage:"Configurar OMDBlockchain",title:"Guarda la red",instruction:"Perfecto. Ahora toca AÑADIR.",explanation:"",media:media(5,"Botón Añadir señalado en SafePal"),hotspot:{x:47,y:84,label:"AÑADIR"},expectedState:"OMDBlockchain quedará guardada.",icon:CircleCheckBig},
{id:"volver",number:6,stage:"Configurar OMDBlockchain",title:"Vuelve a la pantalla principal",instruction:"Toca la flecha para volver.",explanation:"",media:media(6,"Flecha de regreso señalada"),hotspot:{x:6,y:4,label:"VOLVER"},expectedState:"Regresarás a tu wallet.",icon:ExternalLink},
{id:"menu-monedas",number:7,stage:"Agregar OMD",title:"Abre el menú de monedas",instruction:"Toca los tres puntos.",explanation:"",media:media(7,"Menú de tres puntos señalado"),hotspot:{x:90,y:42,label:"TOCA AQUÍ"},expectedState:"Se abrirá un menú.",icon:ExternalLink},
{id:"gestion-monedas",number:8,stage:"Agregar OMD",title:"Entra a Gestión de monedas",instruction:"Toca Gestión de monedas.",explanation:"",media:media(8,"Gestión de monedas señalada"),hotspot:{x:54,y:55,label:"TOCA AQUÍ"},expectedState:"Verás la lista de monedas.",icon:WalletCards},
{id:"buscar-omd",number:9,stage:"Agregar OMD",title:"Busca OMD",instruction:"Copia el contrato y pégalo en el buscador.",explanation:"",media:media(9,"Pantalla Gestión de monedas"),hotspot:{x:18,y:14,label:"PEGA AQUÍ"},expectedState:"Aparecerá OMD en el resultado.",icon:Search,copyFields:[{label:"Contrato OMD",value:"0xA7670e2e6742a18029436E262b01F7C50A863C40"}]},
{id:"sumar-omd",number:10,stage:"Agregar OMD",title:"Añade OMD",instruction:"Toca el signo + junto a OMD.",explanation:"",media:media(10,"Resultado OMD con signo más señalado"),hotspot:{x:88,y:25,label:"TOCA +"},expectedState:"OMD se añadirá a la lista.",icon:Plus},
{id:"omd-listo",number:11,stage:"Agregar OMD",title:"Comprueba que está activado",instruction:"Mira que OMD esté encendido.",explanation:"¡Listo! OMD ya está agregado.",media:media(11,"OMD activado en Gestión de monedas"),hotspot:{x:90,y:18,label:"ENCENDIDO"},expectedState:"El interruptor de OMD aparecerá encendido.",icon:CircleCheckBig},
{id:"recibir",number:12,stage:"Recibir los fondos",title:"Abre Recibir",instruction:"Toca Recibir.",explanation:"",media:media(12,"Botón Recibir señalado"),hotspot:{x:35,y:35,label:"RECIBIR"},expectedState:"SafePal te pedirá elegir una moneda.",icon:WalletCards},
{id:"moneda-recepcion",number:13,stage:"Recibir los fondos",title:"Elige la moneda indicada",instruction:"Toca la moneda que te indicó la persona que te guía.",explanation:"Confirma con tu líder cuál corresponde.",media:media(13,"Lista de monedas para recibir"),hotspot:{x:31,y:75,label:"ELIGE AQUÍ"},expectedState:"Verás la dirección de recepción de esa moneda.",icon:WalletCards},
{id:"copiar-direccion",number:14,stage:"Recibir los fondos",title:"Copia tu dirección",instruction:"Toca Copiar.",explanation:"Envíala solamente a la persona que te está guiando.",media:media(14,"Dirección y QR sanitizados con botón Copiar señalado"),hotspot:{x:74,y:72,label:"COPIAR"},expectedState:"Tu dirección quedará copiada. Espera la transferencia.",icon:Copy,warning:"Nunca envíes tu frase secreta, contraseña ni clave privada."},
{id:"fondos",number:15,stage:"Entrar a OneMillionMiners",title:"Comprueba que recibiste los fondos",instruction:"Mira que el saldo ya aparezca.",explanation:"La cantidad de la captura es solo un ejemplo.",media:media(15,"Saldo disponible en SafePal"),hotspot:{x:50,y:12,label:"SALDO RECIBIDO"},expectedState:"El saldo estará visible en la wallet.",icon:CircleCheckBig},
{id:"dapp",number:16,stage:"Entrar a OneMillionMiners",title:"Abre el navegador Web3",instruction:"Toca DApp.",explanation:"",media:media(16,"Navegador DApp de SafePal señalado"),hotspot:{x:48,y:89,label:"DApp"},expectedState:"Se abrirá el navegador de SafePal.",icon:Globe2},
{id:"continuar-dapp",number:17,stage:"Entrar a OneMillionMiners",title:"Continúa al navegador",instruction:"Toca para continuar.",explanation:"Lee el aviso antes de seguir.",media:media(17,"Aviso de DApp con acción señalada"),hotspot:{x:50,y:84,label:"CONTINUAR"},expectedState:"Verás el buscador de DApps.",icon:ShieldCheck},
{id:"enlace-personal",number:18,stage:"Entrar a OneMillionMiners",title:"Pega tu enlace personal",instruction:"Toca arriba y pega el enlace que te enviaron.",explanation:"Cada líder utiliza su propio enlace. LAEX no proporciona uno global.",media:media(18,"Navegador DApp con barra de dirección señalada"),hotspot:{x:34,y:15,label:"PEGA AQUÍ"},expectedState:"Se abrirá el sitio oficial desde tu enlace personal.",icon:Globe2},
{id:"bnb-chain",number:19,stage:"Entrar a OneMillionMiners",title:"Selecciona BNB Chain",instruction:"Toca BNB Chain.",explanation:"",media:media(19,"BNB Chain señalada en la lista"),hotspot:{x:35,y:43,label:"BNB CHAIN"},expectedState:"La DApp se abrirá en la red seleccionada.",icon:Network},
{id:"advertencia",number:20,stage:"Entrar a OneMillionMiners",title:"Revisa el aviso",instruction:"Confirma solamente si el dominio es correcto.",explanation:"No continúes si la dirección no corresponde al sitio oficial.",media:media(20,"Aviso de seguridad de SafePal"),hotspot:{x:18,y:58,label:"CONFIRMAR"},expectedState:"OneMillionMiners cargará dentro de SafePal.",icon:ShieldCheck},
{id:"opcion",number:21,stage:"Activar el Miner",title:"Elige una opción",instruction:"Elige la opción que deseas activar.",explanation:"Los precios visibles pertenecen al momento de la captura y pueden cambiar.",media:media(21,"Opciones OM Miners y Turbo Miner"),hotspot:{x:69,y:22,label:"ELIGE AQUÍ"},expectedState:"La opción elegida quedará marcada.",icon:WalletCards},
{id:"conectar",number:22,stage:"Activar el Miner",title:"Conecta SafePal",instruction:"Toca SafePal.",explanation:"",media:media(22,"Selector Conectar Wallet con SafePal señalado"),hotspot:{x:41,y:51,label:"SAFEPAL"},expectedState:"La página mostrará tu wallet conectada.",icon:WalletCards},
{id:"comprar",number:23,stage:"Activar el Miner",title:"Continúa con la compra",instruction:"Comprueba que la wallet está conectada y toca COMPRAR.",explanation:"Revisa la opción seleccionada antes de seguir.",media:media(23,"Wallet conectada y botón Comprar señalado"),hotspot:{x:47,y:63,label:"COMPRAR"},expectedState:"SafePal mostrará el detalle de la transacción.",icon:WalletCards},
{id:"confirmar",number:24,stage:"Activar el Miner",title:"Revisa y confirma",instruction:"Revisa los datos y toca CONFIRMAR.",explanation:"Si algo no coincide, cancela y pide ayuda.",media:media(24,"Transacción sanitizada con botón Confirmar"),hotspot:{x:74,y:89,label:"CONFIRMAR"},expectedState:"La transacción comenzará a procesarse.",icon:ShieldCheck,warning:"Si aparece un error, no continúes a ciegas. Envía una captura al soporte."},
{id:"activado",number:25,stage:"¡Lo lograste!",title:"Comprueba que tu cuenta está activa",instruction:"Busca esta pantalla de confirmación.",explanation:"La captura está sanitizada y no promete rendimientos.",media:media(25,"Cuenta activada con datos personales ocultos"),hotspot:{x:78,y:15,label:"WALLET CONECTADA"},expectedState:"Tu cuenta aparecerá activa.",icon:CircleCheckBig},
{id:"herramientas",number:26,stage:"Conoce tus herramientas",title:"Conoce tus datos y tu enlace",instruction:"Mira tu ID y dónde copiar tu enlace personal.",explanation:"Tu ID de patrocinador identifica a quien te invitó. Tu enlace personal sirve para invitar.",media:media(26,"ID de usuario, patrocinador y enlace personal señalados"),hotspot:{x:34,y:52,label:"TU ID"},expectedState:"Sabrás localizar tu ID y tu enlace personal.",icon:Copy}
];