"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Check,ChevronLeft,Copy,ShieldAlert} from "lucide-react";
import {useEffect,useState} from "react";
import {GuideHeader} from "./GuideHeader";
import "./guide-readability.css";
import {SafePalDownloadGuide} from "./SafePalDownloadGuide";
import {oneMillionMinerRealSteps,type GuidedCaptureStep} from "./onemillionminers";

const GUIDE_ID="onemillionminers-activar-real-v1";

export function OneMillionMinerRealGuide(){
 const [screen,setScreen]=useState(-1),[resume,setResume]=useState<number|null>(null),[leader,setLeader]=useState(false),[copied,setCopied]=useState("");
 useEffect(()=>{const stored=localStorage.getItem("laex-guide:"+GUIDE_ID);if(stored===null)return;const saved=Number(stored);if(!Number.isInteger(saved)||saved<0||saved>=oneMillionMinerRealSteps.length)return;const timer=window.setTimeout(()=>setResume(saved),0);return()=>clearTimeout(timer)},[]);
 const go=(n:number)=>{const next=Math.max(-1,Math.min(n,oneMillionMinerRealSteps.length));if(screen===13&&next===14){setLeader(true);return}setScreen(next);setCopied("");window.scrollTo({top:0,behavior:"instant"});if(next>=0&&next<oneMillionMinerRealSteps.length)localStorage.setItem("laex-guide:"+GUIDE_ID,String(next));if(next===oneMillionMinerRealSteps.length)localStorage.removeItem("laex-guide:"+GUIDE_ID)};
 const continueAfterLeader=()=>{setLeader(false);setScreen(14);window.scrollTo({top:0,behavior:"instant"});localStorage.setItem("laex-guide:"+GUIDE_ID,"14")};
 const copy=async(label:string,value:string)=>{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(""),1800)};
 if(screen===-2)return <SafePalDownloadGuide onComplete={()=>go(0)}/>;
 if(screen===-1)return <Intro resume={resume} start={()=>go(0)} download={()=>setScreen(-2)} resumeAt={()=>resume!==null&&go(resume)}/>;
 if(screen===oneMillionMinerRealSteps.length)return <Complete restart={()=>go(-1)}/>;
 const step=oneMillionMinerRealSteps[screen];
 return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Ambient/><GuideHeader/><div className="relative z-10 mx-auto guide-step-layout flex h-[calc(100dvh-4rem)] min-h-0 w-[min(100%-1rem,88rem)] flex-col py-2 sm:w-[min(100%-1.25rem,88rem)] lg:h-auto lg:min-h-[calc(100dvh-4rem)] lg:w-[min(100%-2rem,88rem)] lg:py-7">
  <Progress current={screen}/>
  <section key={step.id} className="guide-step-grid guide-step-enter mx-auto mt-2 grid min-h-0 w-full max-w-6xl flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 overflow-hidden lg:mt-4 lg:grid-cols-[minmax(19rem,.62fr)_minmax(0,1.38fr)] lg:grid-rows-none lg:items-center lg:gap-5 lg:overflow-visible">
   <Capture step={step}/>
   <div className="order-1 min-h-0 px-1 lg:pr-7"><p className="text-sm font-bold uppercase tracking-[.1em] text-amber-300">{step.stage}</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.045em] lg:mt-3 lg:text-4xl">{step.title}</h1><div className="mt-2 rounded-2xl border border-amber-200/20 bg-amber-300/[.065] p-3 lg:mt-5 lg:rounded-[1.6rem] lg:p-5"><p className="guide-instruction font-bold text-white lg:text-2xl">{step.instruction}</p>{<p className="guide-explanation mt-3 lg:mt-2 lg:text-xs lg:leading-6">{step.explanation||step.expectedState}</p>}</div>
   {step.copyFields&&<div className="guide-copy-fields mt-3 grid grid-cols-2 gap-1.5 lg:mt-4 lg:grid-cols-1 lg:gap-2">{step.copyFields.map(field=><button key={field.label} onClick={()=>void copy(field.label,field.value)} className="group flex min-h-10 items-center justify-between gap-1 rounded-xl border border-white/[.08] bg-white/[.035] px-2 text-left lg:min-h-14 lg:gap-3 lg:rounded-2xl lg:px-4"><span className="min-w-0"><small className="block text-[9px] font-bold uppercase tracking-widest text-slate-500">{field.label}</small><code className="block max-w-[5.5rem] truncate pt-0.5 text-[9px] text-slate-200 sm:max-w-[8rem] lg:max-w-xs lg:pt-1 lg:text-[11px]">{field.value}</code></span><span className="inline-flex shrink-0 items-center gap-1 rounded-lg bg-cyan-300 px-2 py-1.5 text-[9px] font-black text-slate-950 lg:gap-2 lg:rounded-xl lg:px-3 lg:py-2 lg:text-[10px]">{copied===field.label?<Check size={14}/>:<Copy size={14}/>} {copied===field.label?"COPIADO":"COPIAR"}</span></button>)}</div>}
   {step.warning&&<div className="guide-warning mt-3 flex gap-2 rounded-xl border border-amber-200/15 bg-amber-300/[.06] p-2.5 text-[10px] leading-4 text-amber-100 lg:mt-4 lg:gap-3 lg:rounded-2xl lg:p-4 lg:text-xs lg:leading-5"><ShieldAlert size={18} className="shrink-0 text-amber-300"/>{step.warning}</div>}
   </div>
  </section>
  <div className="guide-navigation mx-auto mt-2 flex w-full max-w-6xl gap-2 lg:mt-4 lg:gap-3"><button onClick={()=>go(screen-1)} aria-label="Paso anterior" className="grid size-12 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-slate-300 lg:size-16 lg:rounded-2xl"><ChevronLeft size={24}/></button><button onClick={()=>go(screen+1)} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-amber-300 to-yellow-400 px-4 text-xs font-black tracking-[.12em] text-[#171006] shadow-[0_18px_45px_rgba(245,183,47,.22)] lg:min-h-16 lg:gap-3 lg:rounded-2xl lg:px-5 lg:text-sm">YA LO HICE <ArrowRight size={19}/></button></div>
 </div>{leader&&<LeaderInterlude next={continueAfterLeader}/>}</main>
}
function Ambient(){return <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_-10%,rgba(245,183,47,.16),transparent_38rem),radial-gradient(circle_at_100%_70%,rgba(34,211,238,.07),transparent_32rem),linear-gradient(135deg,rgba(234,179,53,.025),transparent_45%)]"/>}
function Progress({current}:{current:number}){const percent=((current+1)/oneMillionMinerRealSteps.length)*100;return <div className="mx-auto w-full max-w-6xl"><div className="flex items-center justify-between text-sm font-bold uppercase tracking-[.06em]"><span className="text-cyan-300">Paso {current+1} de {oneMillionMinerRealSteps.length}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 via-amber-300 to-yellow-400 transition-[width] duration-500" style={{width:percent+"%"}}/></div></div>}
function Capture({step}:{step:GuidedCaptureStep}){return <figure className="guide-capture order-2 mx-auto w-full overflow-hidden rounded-2xl border border-white/15 bg-[#07111d]"><Image src={step.media.src!} alt={step.media.alt} width={720} height={1440} sizes="(max-width: 544px) 100vw, 512px" priority={step.number<=2}/></figure>}
function Intro({resume,start,download,resumeAt}:{resume:number|null;start:()=>void;download:()=>void;resumeAt:()=>void}){return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Ambient/><GuideHeader/><section className="relative z-10 mx-auto grid min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,72rem)] items-center gap-10 py-10 lg:grid-cols-[1fr_.78fr]"><div><span className="laex-eyebrow">Guía real · 26 pasos</span><h1 className="laex-display mt-6 text-[clamp(3rem,7vw,6rem)]">Vamos a hacerlo <span className="text-cyan-300">juntos.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-400">Lee cada instrucción y busca el botón indicado en tu SafePal. Usa la captura como referencia y vuelve aquí para tocar “Ya lo hice”.</p>{resume!==null&&<button onClick={resumeAt} className="mt-6 flex items-center gap-3 rounded-2xl border border-cyan-200/20 bg-cyan-300/[.07] px-5 py-4 text-left text-sm"><span className="grid size-9 place-items-center rounded-full bg-cyan-300 font-black text-slate-950">{resume+1}</span><span><b className="block">Continuar donde lo dejaste</b><small className="text-slate-400">Paso {resume+1} de 26</small></span></button>}<button onClick={start} className="mt-8 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-7 text-sm font-black tracking-[.12em] text-[#171006] sm:w-auto">YA TENGO SAFEPAL · CONTINUAR <ArrowRight size={19}/></button></div><div className="laex-surface overflow-hidden rounded-[2rem] p-6 sm:p-8"><div className="relative mb-5 aspect-[3/2] overflow-hidden rounded-2xl border border-amber-200/15"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros de OneMillionMiners" fill sizes="520px" className="object-cover"/></div><div className="space-y-3 rounded-2xl bg-[#07101b] p-5 text-sm leading-6"><p className="max-w-[85%] rounded-2xl rounded-bl-md bg-white/[.07] p-4"> ¿Te gustaría conocer cómo funciona este recorrido desde tu celular?</p><p className="ml-auto max-w-[55%] rounded-2xl rounded-br-md bg-amber-300 p-4 font-black text-[#171006]">¿CÓMO?</p><p className="max-w-[88%] rounded-2xl rounded-bl-md bg-white/[.07] p-4"> Perfecto. Vamos con el primer paso.</p></div><p className="mt-5 text-center text-xs font-bold uppercase tracking-[.12em] text-amber-200">¿Todavía no tienes SafePal?</p><button onClick={download} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-cyan-300/25 bg-cyan-300/[.06] text-xs font-bold text-cyan-300">DESCARGAR SAFEPAL <ArrowRight size={14}/></button><p className="mt-2 text-center text-xs leading-5 text-slate-400">Completa la instalación y el capítulo para guardar tu frase de recuperación antes de continuar.</p><p className="mt-5 flex gap-2 text-xs leading-5 text-amber-100"><ShieldAlert size={16} className="shrink-0 text-amber-300"/>Nunca envíes tu frase secreta, contraseña ni claves privadas.</p></div></section></main>}
function LeaderInterlude({next}:{next:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#03070d]/95 p-4 backdrop-blur-xl"><div className="laex-surface guide-step-enter my-6 w-full max-w-2xl rounded-[2rem] p-7 text-center sm:p-10"><div className="relative mx-auto aspect-[3/2] w-full max-w-sm overflow-hidden rounded-2xl border border-amber-200/15"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros acompañando el progreso" fill sizes="384px" className="object-cover"/></div><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Pausa de acompañamiento</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">¡Perfecto! Ya podemos continuar.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-slate-200">Ahora tu meta es aprender este mismo proceso para poder enseñárselo a otras personas con claridad y responsabilidad.</p><p className="mx-auto mt-4 max-w-xl text-lg leading-8 text-slate-200">Explora, aprende y conoce cómo funciona antes de tomar tus propias decisiones.</p><p className="mt-6 font-black text-amber-200">⛏️ Aprende → participa → comprende → decide.</p><button onClick={next} className="mt-8 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-6 text-xs font-black text-[#171006] sm:w-auto">CONTINUAR A ONEMILLIONMINERS <ArrowRight size={17}/></button></div></div>}
function Complete({restart}:{restart:()=>void}){return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Ambient/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,56rem)] items-center py-10 text-center"><div className="w-full"><div className="relative mx-auto aspect-[3/2] w-full max-w-xl overflow-hidden rounded-[2rem] border border-amber-200/20 shadow-[0_0_70px_rgba(245,183,47,.16)]"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros de OneMillionMiners celebrando" fill sizes="576px" className="object-cover"/></div><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-emerald-300">¡Felicidades!</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Llegaste al final de tu activación.</h1><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-slate-200">Ya diste el primer paso para conocer este nuevo sistema. Ahora comienza la parte más importante: aprender a utilizarlo.</p><div className="mx-auto mt-7 max-w-xl rounded-2xl border border-amber-200/15 bg-amber-300/[.05] p-5 text-sm leading-7 text-amber-100">La meta no es registrar por registrar. Aprende, enseña y ayuda a otros a comprender para que puedan decidir por sí mismos.</div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/guias" className="grid min-h-14 place-items-center rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-6 text-xs font-black text-[#171006]">VOLVER A GUÍAS</Link><button onClick={restart} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-white/10 px-6 text-xs font-black"><ArrowLeft size={16}/> REPETIR GUÍA</button></div></div></section></main>}
