"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowUpRight,ArrowLeft,ArrowRight,Check,ChevronLeft,Copy,ShieldAlert} from "lucide-react";
import {useEffect,useState} from "react";
import {GuideHeader} from "./GuideHeader";
import {SafePalDownloadGuide} from "./SafePalDownloadGuide";
import {oneMillionMinerRealSteps,type GuidedCaptureStep} from "./onemillionminers";

const GUIDE_ID="onemillionminers-activar-real-v1";

export function OneMillionMinerRealGuide(){
 const [screen,setScreen]=useState(-1),[resume,setResume]=useState<number|null>(null),[leader,setLeader]=useState(false),[copied,setCopied]=useState("");
 useEffect(()=>{const saved=Number(localStorage.getItem("laex-guide:"+GUIDE_ID));if(!Number.isInteger(saved)||saved<0||saved>=oneMillionMinerRealSteps.length)return;const timer=window.setTimeout(()=>setResume(saved),0);return()=>clearTimeout(timer)},[]);
 const go=(n:number)=>{const next=Math.max(-1,Math.min(n,oneMillionMinerRealSteps.length));if(screen===13&&next===14){setLeader(true);return}setScreen(next);setCopied("");if(next>=0&&next<oneMillionMinerRealSteps.length)localStorage.setItem("laex-guide:"+GUIDE_ID,String(next));if(next===oneMillionMinerRealSteps.length)localStorage.removeItem("laex-guide:"+GUIDE_ID)};
 const continueAfterLeader=()=>{setLeader(false);setScreen(14);localStorage.setItem("laex-guide:"+GUIDE_ID,"14")};
 const copy=async(label:string,value:string)=>{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(""),1800)};
 if(screen===-2)return <SafePalDownloadGuide onComplete={()=>go(0)}/>;
 if(screen===-1)return <Intro resume={resume} start={()=>go(0)} download={()=>setScreen(-2)} resumeAt={()=>resume!==null&&go(resume)}/>;
 if(screen===oneMillionMinerRealSteps.length)return <Complete restart={()=>go(-1)}/>;
 const step=oneMillionMinerRealSteps[screen];
 return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Ambient/><GuideHeader/><div className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-1.25rem,88rem)] flex-col py-4 sm:w-[min(100%-2rem,88rem)] sm:py-7">
  <Progress current={screen}/>
  <section key={step.id} className="guide-step-enter mx-auto mt-4 grid w-full max-w-6xl flex-1 gap-5 lg:grid-cols-[minmax(19rem,.62fr)_minmax(0,1.38fr)] lg:items-center">
   <Capture step={step}/>
   <div className="order-1 px-1 sm:px-0 lg:pr-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">{step.stage}</p><p className="mt-2 text-xs font-bold text-slate-500">PASO {step.number} DE {oneMillionMinerRealSteps.length}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">{step.title}</h1><div className="mt-5 rounded-[1.6rem] border border-amber-200/20 bg-amber-300/[.065] p-5"><p className="text-xl font-black leading-snug text-white sm:text-2xl">➜ {step.instruction}</p>{step.explanation&&<p className="mt-2 text-xs leading-6 text-slate-400">{step.explanation}</p>}</div>
   {step.copyFields&&<div className="mt-4 grid gap-2">{step.copyFields.map(field=><button key={field.label} onClick={()=>void copy(field.label,field.value)} className="group flex min-h-14 items-center justify-between gap-3 rounded-2xl border border-white/[.08] bg-white/[.035] px-4 text-left"><span className="min-w-0"><small className="block text-[9px] font-bold uppercase tracking-widest text-slate-500">{field.label}</small><code className="block max-w-[16rem] truncate pt-1 text-[11px] text-slate-200 sm:max-w-xs">{field.value}</code></span><span className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-cyan-300 px-3 py-2 text-[10px] font-black text-slate-950">{copied===field.label?<Check size={14}/>:<Copy size={14}/>} {copied===field.label?"COPIADO":"COPIAR"}</span></button>)}</div>}
   {step.warning&&<div className="mt-4 flex gap-3 rounded-2xl border border-amber-200/15 bg-amber-300/[.06] p-4 text-xs leading-5 text-amber-100"><ShieldAlert size={18} className="shrink-0 text-amber-300"/>{step.warning}</div>}
   </div>
  </section>
  <div className="mx-auto mt-4 flex w-full max-w-6xl gap-3"><button onClick={()=>go(screen-1)} aria-label="Paso anterior" className="grid size-16 shrink-0 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-slate-300"><ChevronLeft size={24}/></button><button onClick={()=>go(screen+1)} className="inline-flex min-h-16 flex-1 items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-5 text-sm font-black tracking-[.12em] text-[#171006] shadow-[0_18px_45px_rgba(245,183,47,.22)]">YA LO HICE <ArrowRight size={19}/></button></div>
 </div>{leader&&<LeaderInterlude next={continueAfterLeader}/>}</main>
}
function Ambient(){return <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_-10%,rgba(245,183,47,.16),transparent_38rem),radial-gradient(circle_at_100%_70%,rgba(34,211,238,.07),transparent_32rem),linear-gradient(135deg,rgba(234,179,53,.025),transparent_45%)]"/>}
function Progress({current}:{current:number}){const percent=((current+1)/oneMillionMinerRealSteps.length)*100;return <div className="mx-auto w-full max-w-6xl"><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[.16em]"><span className="text-cyan-300">Paso {current+1} de {oneMillionMinerRealSteps.length}</span><span className="text-slate-600">{Math.round(percent)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 via-amber-300 to-yellow-400 transition-[width] duration-500" style={{width:percent+"%"}}/></div></div>}
function SignalMarker({x,y}:{x:number;y:number}){return <div className="guide-signal pointer-events-none absolute -translate-x-1/2 -translate-y-1/2" style={{left:x+"%",top:y+"%"}} aria-hidden="true"><span className="guide-signal-pulse absolute left-1/2 top-1/2 size-14 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-amber-300/90 bg-transparent shadow-[0_0_28px_rgba(245,183,47,.72)]"/><span className="guide-signal-arrow absolute -left-8 top-2 text-amber-300 drop-shadow-[0_0_10px_rgba(245,183,47,.85)]"><ArrowUpRight size={30} strokeWidth={2.4}/></span></div>}
function Capture({step}:{step:GuidedCaptureStep}){return <div className="order-2 mx-auto w-full max-w-[46rem]"><div className="relative aspect-[9/18] max-h-[74dvh] min-h-[30rem] overflow-hidden rounded-[2rem] border border-white/10 bg-[#07111d] shadow-[0_30px_100px_rgba(0,0,0,.55)]"><Image src={step.media.src!} alt={step.media.alt} fill sizes="(max-width:1024px) 100vw,544px" className="object-contain" priority={step.number<=2}/><div className="pointer-events-none absolute inset-0 bg-black/20 [mask-image:radial-gradient(circle_104px_at_var(--x)_var(--y),transparent_0,transparent_68px,#000_106px)]" style={{"--x":step.hotspot.x+"%","--y":step.hotspot.y+"%"} as React.CSSProperties}/><SignalMarker x={step.hotspot.x} y={step.hotspot.y}/><span className="absolute left-3 top-3 rounded-full border border-white/10 bg-black/75 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.14em] text-white backdrop-blur">Captura real · datos sanitizados cuando corresponde</span></div><p className="mt-3 text-center text-[10px] text-slate-600">Lo que verás puede variar ligeramente según la versión de SafePal.</p></div>}
function Intro({resume,start,download,resumeAt}:{resume:number|null;start:()=>void;download:()=>void;resumeAt:()=>void}){return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Ambient/><GuideHeader/><section className="relative z-10 mx-auto grid min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,72rem)] items-center gap-10 py-10 lg:grid-cols-[1fr_.78fr]"><div><span className="laex-eyebrow">Guía real · 26 pasos</span><h1 className="laex-display mt-6 text-[clamp(3rem,7vw,6rem)]">Vamos a hacerlo <span className="text-cyan-300">juntos.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-400">Mira la imagen, toca donde apunta la flecha y pulsa “Ya lo hice”. No necesitas memorizar datos técnicos.</p>{resume!==null&&<button onClick={resumeAt} className="mt-6 flex items-center gap-3 rounded-2xl border border-cyan-200/20 bg-cyan-300/[.07] px-5 py-4 text-left text-sm"><span className="grid size-9 place-items-center rounded-full bg-cyan-300 font-black text-slate-950">{resume+1}</span><span><b className="block">Continuar donde lo dejaste</b><small className="text-slate-400">Paso {resume+1} de 26</small></span></button>}<button onClick={start} className="mt-8 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-7 text-sm font-black tracking-[.12em] text-[#171006] sm:w-auto">YA TENGO SAFEPAL · CONTINUAR <ArrowRight size={19}/></button></div><div className="laex-surface overflow-hidden rounded-[2rem] p-6 sm:p-8"><div className="relative mb-5 aspect-[3/2] overflow-hidden rounded-2xl border border-amber-200/15"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros de OneMillionMiners" fill sizes="520px" className="object-cover"/></div><div className="space-y-3 rounded-2xl bg-[#07101b] p-5 text-sm leading-6"><p className="max-w-[85%] rounded-2xl rounded-bl-md bg-white/[.07] p-4"> ¿Te gustaría conocer cómo funciona este recorrido desde tu celular?</p><p className="ml-auto max-w-[55%] rounded-2xl rounded-br-md bg-amber-300 p-4 font-black text-[#171006]">¿CÓMO?</p><p className="max-w-[88%] rounded-2xl rounded-bl-md bg-white/[.07] p-4"> Perfecto. Vamos con el primer paso.</p></div><p className="mt-5 text-center text-xs font-bold uppercase tracking-[.12em] text-amber-200">¿Todavía no tienes SafePal?</p><button onClick={download} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-cyan-300/25 bg-cyan-300/[.06] text-xs font-bold text-cyan-300">DESCARGAR SAFEPAL <ArrowRight size={14}/></button><p className="mt-2 text-center text-xs leading-5 text-slate-400">Instálala, vuelve a esta pantalla y pulsa «Ya tengo SafePal».</p><p className="mt-5 flex gap-2 text-xs leading-5 text-amber-100"><ShieldAlert size={16} className="shrink-0 text-amber-300"/>Nunca envíes tu frase secreta, contraseña ni claves privadas.</p></div></section></main>}
function LeaderInterlude({next}:{next:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#03070d]/95 p-4 backdrop-blur-xl"><div className="laex-surface guide-step-enter my-6 w-full max-w-2xl rounded-[2rem] p-7 text-center sm:p-10"><div className="relative mx-auto aspect-[3/2] w-full max-w-sm overflow-hidden rounded-2xl border border-amber-200/15"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros acompañando el progreso" fill sizes="384px" className="object-cover"/></div><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Pausa de acompañamiento</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">¡Perfecto! Ya podemos continuar.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-slate-300">Ahora tu meta es aprender este mismo proceso para poder enseñárselo a otras personas con claridad y responsabilidad.</p><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-400">Explora, aprende y conoce cómo funciona antes de tomar tus propias decisiones.</p><p className="mt-6 font-black text-amber-200">⛏️ Aprende → participa → comprende → decide.</p><button onClick={next} className="mt-8 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-6 text-xs font-black text-[#171006] sm:w-auto">CONTINUAR A ONEMILLIONMINERS <ArrowRight size={17}/></button></div></div>}
function Complete({restart}:{restart:()=>void}){return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Ambient/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,56rem)] items-center py-10 text-center"><div className="w-full"><div className="relative mx-auto aspect-[3/2] w-full max-w-xl overflow-hidden rounded-[2rem] border border-amber-200/20 shadow-[0_0_70px_rgba(245,183,47,.16)]"><Image src="/guides/onemillionminers/brand-companions-v1.png" alt="Mineros de OneMillionMiners celebrando" fill sizes="576px" className="object-cover"/></div><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-emerald-300">¡Felicidades!</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Llegaste al final de tu activación.</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-slate-400">Ya diste el primer paso para conocer este nuevo sistema. Ahora comienza la parte más importante: aprender a utilizarlo.</p><div className="mx-auto mt-7 max-w-xl rounded-2xl border border-amber-200/15 bg-amber-300/[.05] p-5 text-sm leading-7 text-amber-100">La meta no es registrar por registrar. Aprende, enseña y ayuda a otros a comprender para que puedan decidir por sí mismos.</div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/guias" className="grid min-h-14 place-items-center rounded-2xl bg-gradient-to-r from-amber-300 to-yellow-400 px-6 text-xs font-black text-[#171006]">VOLVER A GUÍAS</Link><button onClick={restart} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-white/10 px-6 text-xs font-black"><ArrowLeft size={16}/> REPETIR GUÍA</button></div></div></section></main>}
