"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight,Check,ChevronLeft,Download,ExternalLink,Search,ShieldCheck} from "lucide-react";
import {useEffect,useState} from "react";
import {GuideHeader} from "./GuideHeader";
import {SafePalRecoveryGuide} from "./SafePalRecoveryGuide";
import "./guide-readability.css";

const PLAY_URL="https://play.google.com/store/apps/details?hl=es-419&id=io.safepal.wallet";
const GUIDE_ID="safepal-descargar-android";
const steps=[
 {id:"abrir-play-store",title:"Abre Google Play Store",instruction:"Busca el icono del triángulo de colores llamado Play Store y tócalo para abrirlo.",scene:"home",target:"Play Store"},
 {id:"buscar-safepal",title:"Busca SafePal",instruction:"Toca la barra Buscar apps y juegos, escribe SafePal y pulsa buscar en el teclado.",scene:"search",target:"Buscar apps"},
 {id:"identificar-app",title:"Elige la aplicación correcta",instruction:"Busca SafePal y comprueba que el desarrollador sea SafePal Wallet antes de elegirla.",scene:"results",target:"SafePal Wallet"},
 {id:"instalar",title:"Instala SafePal",instruction:"En la ficha de SafePal, toca el botón Instalar.",scene:"install",target:"Instalar"},
 {id:"esperar",title:"Espera un momento",instruction:"Espera hasta que el botón cambie de Instalando a Abrir.",scene:"waiting",target:"Instalando…"},
 {id:"lista",title:"SafePal ya está instalada",instruction:"Si ves el botón Abrir, la instalación terminó. Toca Terminar en esta guía para seguir con el respaldo de tu wallet.",scene:"done",target:"Abrir"},
] as const;

export function SafePalDownloadGuide({onComplete}:{onComplete?:()=>void}={}){
 const [recovery,setRecovery]=useState(false),[screen,setScreen]=useState(-1),[resume,setResume]=useState<number|null>(null);
 useEffect(()=>{const stored=localStorage.getItem("laex-guide:"+GUIDE_ID);if(stored===null)return;const saved=Number(stored);if(!Number.isInteger(saved)||saved<0||saved>=steps.length)return;const timer=window.setTimeout(()=>setResume(saved),0);return()=>window.clearTimeout(timer)},[]);
 const go=(n:number)=>{const next=Math.max(-1,Math.min(n,steps.length));setScreen(next);window.scrollTo({top:0,behavior:"instant"});if(next>=0&&next<steps.length)localStorage.setItem("laex-guide:"+GUIDE_ID,String(next));if(next===steps.length)localStorage.removeItem("laex-guide:"+GUIDE_ID)};
 if(recovery)return <SafePalRecoveryGuide onComplete={onComplete} onBack={()=>{setRecovery(false);window.scrollTo({top:0,behavior:"instant"})}}/>;
 if(screen===-1)return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Glow/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,68rem)] items-center py-10"><div className="grid w-full gap-10 lg:grid-cols-[1fr_.72fr] lg:items-center"><div><span className="laex-eyebrow">Capítulo 1 · Android</span><h1 className="laex-display mt-6 text-[clamp(3.2rem,8vw,6.5rem)]">Vamos a instalar tu wallet <span className="text-cyan-300">SafePal.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-400">Te mostraremos una sola acción por pantalla. Este capítulo termina cuando la aplicación queda instalada.</p>{resume!==null&&<button onClick={()=>go(resume)} className="mt-6 flex items-center gap-3 rounded-2xl border border-cyan-200/20 bg-cyan-300/[.07] px-5 py-4 text-left text-sm"><span className="grid size-9 place-items-center rounded-full bg-cyan-300 font-black text-slate-950">{resume+1}</span><span><b className="block">Continuar donde lo dejaste</b><small className="text-slate-400">Paso {resume+1} de {steps.length}</small></span></button>}<button onClick={()=>go(0)} className="mt-8 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-cyan-300 px-8 text-sm font-black tracking-[.1em] text-slate-950 shadow-[0_20px_50px_rgba(34,211,238,.2)] sm:w-auto"><Download size={19}/> COMENZAR CAPÍTULO</button></div><Phone scene="intro"/><p className="lg:col-start-2 text-center text-[10px] text-slate-600">Referencia Android · La apariencia puede variar según el dispositivo.</p></div></section></main>;
 if(screen===steps.length)return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Glow/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,52rem)] items-center py-10 text-center"><div className="w-full"><span className="mx-auto grid size-24 place-items-center rounded-full border border-emerald-300/30 bg-emerald-300/10 text-emerald-300 shadow-[0_0_60px_rgba(74,222,128,.16)]"><Check size={50}/></span><p className="mt-7 text-[10px] font-black uppercase tracking-[.22em] text-emerald-300">Capítulo 1 completado</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">¡Listo! SafePal ya está instalada.</h1><p className="mx-auto mt-5 max-w-lg text-lg leading-8 text-slate-200">Todavía falta proteger tu wallet. Continúa con el capítulo 2 y sigue con cuidado los pasos para guardar tu frase secreta de recuperación.</p><div className="mx-auto mt-6 max-w-lg rounded-2xl border border-amber-300/40 bg-amber-300/10 p-5 text-left"><h2 className="text-xl font-bold text-amber-200">Guarda tu frase secreta de recuperación</h2><p className="mt-3 text-lg leading-8 text-amber-50">Anótala en el orden correcto y guárdala en un lugar seguro. No la pierdas y nunca la compartas con nadie, ni con quien te ayuda.</p></div><button onClick={()=>{setRecovery(true);window.scrollTo({top:0,behavior:"instant"})}} className="mt-9 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-cyan-300 px-6 text-base font-black tracking-[.04em] text-slate-950 sm:w-auto">CONTINUAR AL CAPÍTULO 2 <ArrowRight size={17}/></button><Link href="/guias" className="mx-auto mt-5 block w-fit py-3 text-base font-semibold text-slate-300">Volver al Centro de Guías</Link></div></section></main>;
 const step=steps[screen];
 return <main className="guide-readable relative min-h-dvh bg-[#03070d] text-white"><Glow/><GuideHeader/><div className="relative z-10 mx-auto guide-step-layout flex h-[calc(100dvh-4rem)] min-h-0 w-[min(100%-1rem,72rem)] flex-col py-2 lg:h-auto lg:min-h-[calc(100dvh-4rem)] lg:w-[min(100%-2rem,72rem)] lg:py-8"><Progress current={screen} go={go}/><section key={step.id} className="guide-step-grid guide-step-enter mx-auto mt-2 grid min-h-0 w-full max-w-5xl flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 overflow-hidden lg:mt-5 lg:grid-cols-[.92fr_1fr] lg:grid-rows-none lg:items-center lg:gap-7 lg:overflow-visible"><Phone scene={step.scene}/><div className="order-1 min-h-0"><p className="text-sm font-bold uppercase tracking-[.12em] text-cyan-300">Paso {screen+1} de {steps.length}</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.045em] lg:mt-3 lg:text-5xl">{step.title}</h1><p className="guide-instruction mt-3 font-bold lg:mt-7 lg:text-3xl">{step.instruction}</p>{step.scene==="results"&&<div className="mt-2 rounded-xl border border-emerald-300/15 bg-emerald-300/[.06] p-2.5 text-base leading-7 text-slate-200 lg:mt-6 lg:rounded-2xl lg:p-4 lg:text-base lg:leading-7"><ShieldCheck size={17} className="mb-2 text-emerald-300"/><b className="text-white">Verifica estas 3 señales:</b><br/>Nombre: SafePal: Crypto Wallet BTC NFT<br/>Desarrollador: SafePal Wallet<br/>Identificador: io.safepal.wallet</div>}{step.scene==="install"&&<a href={PLAY_URL} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 text-base font-semibold text-cyan-300 lg:mt-5 lg:min-h-11 lg:text-xs">Abrir ficha oficial real <ExternalLink size={15}/></a>}</div></section><div className="guide-navigation mx-auto mt-2 flex w-full max-w-5xl gap-2 lg:mt-5 lg:gap-3"><button onClick={()=>go(screen-1)} aria-label="Anterior" className="grid size-12 place-items-center rounded-xl border border-white/10 bg-white/[.04] lg:size-14 lg:rounded-2xl"><ChevronLeft/></button><button onClick={()=>go(screen+1)} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-300 text-xs font-black tracking-[.12em] text-slate-950 lg:min-h-14 lg:gap-3 lg:rounded-2xl lg:text-sm">{screen===steps.length-1?"TERMINAR":"YA LO HICE"}<ArrowRight size={18}/></button></div></div></main>
}
function Glow(){return <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_-10%,rgba(34,211,238,.14),transparent_35rem),radial-gradient(circle_at_100%_70%,rgba(94,140,255,.09),transparent_32rem)]"/>}
function Progress({current,go}:{current:number;go:(n:number)=>void}){return <nav aria-label="Progreso" className="mx-auto flex w-full max-w-xl items-center">{steps.map((s,i)=><div className="contents" key={s.id}><button onClick={()=>go(i)} aria-current={current===i?"step":undefined} aria-label={"Paso "+(i+1)} className={`grid size-8 shrink-0 place-items-center rounded-full border text-[11px] font-black sm:size-10 ${i<=current?"border-cyan-300 bg-cyan-300 text-slate-950":"border-white/15 bg-white/[.04] text-slate-300"}`}>{i<current?<Check size={14}/>:i+1}</button>{i<steps.length-1&&<i className={`h-px flex-1 ${i<current?"bg-cyan-300":"bg-white/15"}`}/>}</div>)}</nav>}
function Phone({scene}:{scene:string}){return <figure className="order-2 mx-auto w-full max-w-[23rem]"><div className="guide-phone relative overflow-hidden rounded-[2rem] border-[5px] border-[#64748b] bg-[#f7f9fc] shadow-2xl"><div className="absolute left-1/2 top-2 z-10 size-3 -translate-x-1/2 rounded-full bg-[#111a25]"/><div className="absolute inset-0 text-[#202124]">{scene==="home"||scene==="intro"?<Home/>:<Store scene={scene}/>}</div></div></figure>}
function Home(){return <div className="flex h-full flex-col bg-[linear-gradient(155deg,#c7e9ff,#e5efff_55%,#baf3ec)] px-6 pb-5 pt-12"><div className="text-right text-sm">10:24</div><div className="flex flex-1 flex-col items-center justify-center"><div className="rounded-[1.75rem] bg-white p-5 shadow-lg"><Image src="/guides/safepal/google-play-store.png" alt="Icono oficial de Google Play Store: triángulo verde, azul, rojo y amarillo" width={120} height={120} priority/></div><b className="mt-4 text-2xl">Play Store</b><p className="mt-8 rounded-xl bg-white/90 px-4 py-3 text-center text-lg leading-7">Busca este icono en las aplicaciones de tu celular.</p></div><div className="mx-auto h-1 w-24 rounded-full bg-slate-700"/></div>}
function Store({scene}:{scene:string}){const waiting=scene==="waiting";return <div className="h-full bg-white px-5 pt-12"><div className="flex h-12 items-center gap-3 rounded-full bg-[#edf2f7] px-4 shadow-sm"><Search size={18}/><span className="text-base text-slate-700">{scene==="search"?"Buscar apps y juegos":"SafePal"}</span></div>{scene==="search"?<div className="mt-8 text-lg leading-7 text-slate-700">Toca la barra superior y escribe el nombre.</div>:<div className="mt-9"><div className="flex gap-4"><Image src="/guides/safepal/app-icon.webp" alt="Icono oficial de SafePal" width={82} height={82} className="size-[82px] rounded-2xl"/><div><h3 className="text-lg font-medium leading-6">SafePal: Crypto Wallet BTC NFT</h3><p className="mt-1 text-sm font-medium text-[#087f5b]">SafePal Wallet</p></div></div><button className={`mt-8 h-12 w-full rounded-full font-bold ${waiting?"border border-[#087f5b] text-[#087f5b]":"bg-[#087f5b] text-white"}`}>{waiting?"Instalando…":scene==="done"?"Abrir":"Instalar"}</button>{waiting&&<div className="mt-3 h-1 overflow-hidden rounded-full bg-slate-200"><i className="block h-full w-2/3 animate-pulse bg-[#087f5b]"/></div>}<h4 className="mt-9 text-base font-medium">Acerca de esta app</h4><p className="mt-3 text-base leading-7 text-slate-700">Wallet de criptomonedas sin custodia.</p></div>}</div>}
