"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowUpRight,ArrowRight,Check,ChevronLeft,CircleHelp,Download,ExternalLink,Search,ShieldCheck,X} from "lucide-react";
import {useEffect,useState} from "react";
import {GuideHeader} from "./GuideHeader";

const PLAY_URL="https://play.google.com/store/apps/details?hl=es-419&id=io.safepal.wallet";
const GUIDE_ID="safepal-descargar-android";
const steps=[
 {id:"abrir-play-store",title:"Abre Google Play Store",instruction:"Busca Play Store en tu celular y tócala.",scene:"home",target:"Play Store"},
 {id:"buscar-safepal",title:"Busca SafePal",instruction:"Toca aquí y escribe SafePal.",scene:"search",target:"Buscar apps"},
 {id:"identificar-app",title:"Elige la aplicación correcta",instruction:"Comprueba el nombre y el desarrollador.",scene:"results",target:"SafePal Wallet"},
 {id:"instalar",title:"Instala SafePal",instruction:"Pulsa Instalar.",scene:"install",target:"Instalar"},
 {id:"esperar",title:"Espera un momento",instruction:"Deja que termine la instalación.",scene:"waiting",target:"Instalando…"},
 {id:"lista",title:"SafePal ya está instalada",instruction:"¡Listo! No la abras todavía.",scene:"done",target:"Abrir"},
] as const;

export function SafePalDownloadGuide({onComplete}:{onComplete?:()=>void}={}){
 const [screen,setScreen]=useState(-1),[help,setHelp]=useState<"help"|"missing"|"next"|null>(null),[resume,setResume]=useState<number|null>(null);
 useEffect(()=>{const saved=Number(localStorage.getItem("laex-guide:"+GUIDE_ID));if(!Number.isInteger(saved)||saved<0||saved>=steps.length)return;const timer=window.setTimeout(()=>setResume(saved),0);return()=>window.clearTimeout(timer)},[]);
 const go=(n:number)=>{const next=Math.max(-1,Math.min(n,steps.length));setScreen(next);setHelp(null);if(next>=0&&next<steps.length)localStorage.setItem("laex-guide:"+GUIDE_ID,String(next));if(next===steps.length)localStorage.removeItem("laex-guide:"+GUIDE_ID)};
 if(screen===-1)return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Glow/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,68rem)] items-center py-10"><div className="grid w-full gap-10 lg:grid-cols-[1fr_.72fr] lg:items-center"><div><span className="laex-eyebrow">Capítulo 1 · Android</span><h1 className="laex-display mt-6 text-[clamp(3.2rem,8vw,6.5rem)]">Vamos a instalar tu wallet <span className="text-cyan-300">SafePal.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-400">Te mostraremos una sola acción por pantalla. Este capítulo termina cuando la aplicación queda instalada.</p>{resume!==null&&<button onClick={()=>go(resume)} className="mt-6 flex items-center gap-3 rounded-2xl border border-cyan-200/20 bg-cyan-300/[.07] px-5 py-4 text-left text-sm"><span className="grid size-9 place-items-center rounded-full bg-cyan-300 font-black text-slate-950">{resume+1}</span><span><b className="block">Continuar donde lo dejaste</b><small className="text-slate-400">Paso {resume+1} de {steps.length}</small></span></button>}<button onClick={()=>go(0)} className="mt-8 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-cyan-300 px-8 text-sm font-black tracking-[.1em] text-slate-950 shadow-[0_20px_50px_rgba(34,211,238,.2)] sm:w-auto"><Download size={19}/> COMENZAR CAPÍTULO</button></div><Phone scene="intro"/><p className="lg:col-start-2 text-center text-[10px] text-slate-600">Referencia Android · La apariencia puede variar según el dispositivo.</p></div></section></main>;
 if(screen===steps.length)return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Glow/><GuideHeader/><section className="relative z-10 mx-auto flex min-h-[calc(100dvh-4rem)] w-[min(100%-2rem,52rem)] items-center py-10 text-center"><div className="w-full"><span className="mx-auto grid size-24 place-items-center rounded-full border border-emerald-300/30 bg-emerald-300/10 text-emerald-300 shadow-[0_0_60px_rgba(74,222,128,.16)]"><Check size={50}/></span><p className="mt-7 text-[10px] font-black uppercase tracking-[.22em] text-emerald-300">Capítulo 1 completado</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">¡Listo! SafePal ya está instalada.</h1><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-slate-400">SafePal ya está instalada. Ahora puedes continuar con el siguiente capítulo.</p><button onClick={()=>onComplete?onComplete():setHelp("next")} className="mt-9 inline-flex min-h-16 w-full items-center justify-center gap-3 rounded-2xl bg-cyan-300 px-6 text-xs font-black tracking-[.1em] text-slate-950 sm:w-auto">CONTINUAR CON EL SIGUIENTE CAPÍTULO <ArrowRight size={17}/></button><Link href="/guias" className="mx-auto mt-5 block w-fit py-3 text-xs font-semibold text-slate-500">Volver al Centro de Guías</Link></div></section>{help&&<Modal kind={help} step={null} close={()=>setHelp(null)}/>}</main>;
 const step=steps[screen];
 return <main className="relative min-h-dvh overflow-hidden bg-[#03070d] text-white"><Glow/><GuideHeader/><div className="relative z-10 mx-auto flex h-[calc(100dvh-4rem)] min-h-0 w-[min(100%-1rem,72rem)] flex-col py-2 lg:h-auto lg:min-h-[calc(100dvh-4rem)] lg:w-[min(100%-2rem,72rem)] lg:py-8"><Progress current={screen} go={go}/><section key={step.id} className="guide-step-enter mx-auto mt-2 grid min-h-0 w-full max-w-5xl flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 overflow-hidden lg:mt-5 lg:grid-cols-[.92fr_1fr] lg:grid-rows-none lg:items-center lg:gap-7 lg:overflow-visible"><Phone scene={step.scene}/><div className="order-1 min-h-0"><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-300">Paso {screen+1} de {steps.length}</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.045em] lg:mt-3 lg:text-5xl">{step.title}</h1><p className="mt-2 text-base font-black leading-snug lg:mt-7 lg:text-3xl">➜ {step.instruction}</p>{step.scene==="results"&&<div className="mt-2 rounded-xl border border-emerald-300/15 bg-emerald-300/[.06] p-2.5 text-[10px] leading-4 text-slate-300 lg:mt-6 lg:rounded-2xl lg:p-4 lg:text-xs lg:leading-6"><ShieldCheck size={17} className="mb-2 text-emerald-300"/><b className="text-white">Verifica estas 3 señales:</b><br/>Nombre: SafePal: Crypto Wallet BTC NFT<br/>Desarrollador: SafePal Wallet<br/>Identificador: io.safepal.wallet</div>}{step.scene==="install"&&<a href={PLAY_URL} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-9 items-center gap-2 text-[10px] font-semibold text-cyan-300 lg:mt-5 lg:min-h-11 lg:text-xs">Abrir ficha oficial real <ExternalLink size={15}/></a>}</div></section><div className="mx-auto mt-2 flex w-full max-w-5xl gap-2 lg:mt-5 lg:gap-3"><button onClick={()=>go(screen-1)} aria-label="Anterior" className="grid size-12 place-items-center rounded-xl border border-white/10 bg-white/[.04] lg:size-14 lg:rounded-2xl"><ChevronLeft/></button><button onClick={()=>go(screen+1)} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-300 text-xs font-black tracking-[.12em] text-slate-950 lg:min-h-14 lg:gap-3 lg:rounded-2xl lg:text-sm">{screen===steps.length-1?"TERMINAR":"YA LO HICE"}<ArrowRight size={18}/></button></div></div>{help&&<Modal kind={help} step={step} close={()=>setHelp(null)}/>}</main>
}
function Glow(){return <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_-10%,rgba(34,211,238,.14),transparent_35rem),radial-gradient(circle_at_100%_70%,rgba(94,140,255,.09),transparent_32rem)]"/>}
function Progress({current,go}:{current:number;go:(n:number)=>void}){return <nav aria-label="Progreso" className="mx-auto flex w-full max-w-xl items-center">{steps.map((s,i)=><div className="contents" key={s.id}><button onClick={()=>go(i)} aria-current={current===i?"step":undefined} aria-label={"Paso "+(i+1)} className={`grid size-8 shrink-0 place-items-center rounded-full border text-[11px] font-black sm:size-10 ${i<=current?"border-cyan-300 bg-cyan-300 text-slate-950":"border-white/15 bg-white/[.04] text-slate-500"}`}>{i<current?<Check size={14}/>:i+1}</button>{i<steps.length-1&&<i className={`h-px flex-1 ${i<current?"bg-cyan-300":"bg-white/15"}`}/>}</div>)}</nav>}
function Phone({scene}:{scene:string}){const spot=scene==="home"?{x:50,y:62}:scene==="search"?{x:50,y:18}:scene==="results"?{x:52,y:42}:scene==="install"?{x:74,y:55}:scene==="waiting"?{x:72,y:55}:scene==="done"?{x:73,y:55}:{x:50,y:50};return <div className="order-2 mx-auto h-full min-h-0 w-full max-w-[23rem] lg:h-auto"><div className="relative h-full min-h-0 overflow-hidden rounded-2xl border-[5px] border-[#182332] bg-[#f7f9fc] shadow-[0_35px_100px_rgba(0,0,0,.55)] lg:aspect-[9/18.5] lg:h-auto lg:rounded-[2.8rem] lg:border-[7px]"><div className="absolute left-1/2 top-2 z-30 h-5 w-24 -translate-x-1/2 rounded-full bg-[#111a25]"/><div className="absolute inset-0 text-[#202124]">{scene==="home"||scene==="intro"?<Home/>:<Store scene={scene}/>}</div>{scene!=="intro"&&<><div className="pointer-events-none absolute inset-0 z-10 bg-black/20 [mask-image:radial-gradient(circle_88px_at_var(--x)_var(--y),transparent_0,transparent_58px,#000_90px)]" style={{"--x":spot.x+"%","--y":spot.y+"%"} as React.CSSProperties}/><div className="guide-signal pointer-events-none absolute z-20 -translate-x-1/2 -translate-y-1/2" style={{left:spot.x+"%",top:spot.y+"%"}} aria-hidden="true"><i className="guide-signal-pulse absolute left-1/2 top-1/2 size-14 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-cyan-300 bg-transparent shadow-[0_0_24px_rgba(34,211,238,.8)]"/><ArrowUpRight className="guide-signal-arrow absolute -left-8 top-2 text-cyan-300 drop-shadow-[0_0_8px_#22d3ee]" size={27}/></div></>}</div><p className="hidden text-center text-[9px] uppercase tracking-[.16em] text-slate-600 lg:mt-4 lg:block">Referencia guiada basada en la ficha oficial actual</p></div>}
function Home(){return <div className="flex h-full flex-col bg-[linear-gradient(160deg,#b8e0ff,#ede8ff_55%,#d4fff3)] p-7 pt-16"><div className="text-right text-[10px]">10:24</div><div className="flex flex-1 items-center justify-center"><div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-[1.4rem] bg-white shadow-lg"><span className="text-4xl">▶</span></div><b className="mt-3 block text-xs">Play Store</b></div></div><div className="mb-5 h-1 rounded-full bg-black/70"/></div>}
function Store({scene}:{scene:string}){const waiting=scene==="waiting";return <div className="h-full bg-white px-5 pt-12"><div className="flex h-12 items-center gap-3 rounded-full bg-[#edf2f7] px-4 shadow-sm"><Search size={18}/><span className="text-sm text-slate-600">{scene==="search"?"Buscar apps y juegos":"SafePal"}</span></div>{scene==="search"?<div className="mt-8 text-sm text-slate-500">Toca la barra superior y escribe el nombre.</div>:<div className="mt-9"><div className="flex gap-4"><Image src="/guides/safepal/app-icon.webp" alt="Icono oficial de SafePal" width={82} height={82} className="size-[82px] rounded-2xl"/><div><h3 className="text-lg font-medium leading-6">SafePal: Crypto Wallet BTC NFT</h3><p className="mt-1 text-sm font-medium text-[#087f5b]">SafePal Wallet</p><p className="mt-2 text-[11px] text-slate-500">Compras directas desde la app</p></div></div><div className="mt-7 grid grid-cols-3 text-center text-xs"><span><b className="block">4.5★</b>Calificación</span><span className="border-x"><b className="block">5 M+</b>Descargas</span><span><b className="block">Todos</b>Edad</span></div><button className={`mt-8 h-12 w-full rounded-full font-bold ${waiting?"border border-[#087f5b] text-[#087f5b]":"bg-[#087f5b] text-white"}`}>{waiting?"Instalando…":scene==="done"?"Abrir":"Instalar"}</button>{waiting&&<div className="mt-3 h-1 overflow-hidden rounded-full bg-slate-200"><i className="block h-full w-2/3 animate-pulse bg-[#087f5b]"/></div>}<h4 className="mt-9 text-base font-medium">Acerca de esta app</h4><p className="mt-3 text-xs leading-5 text-slate-500">Wallet de criptomonedas sin custodia.</p></div>}</div>}
function Modal({kind,step,close}:{kind:"help"|"missing"|"next";step:typeof steps[number]|null;close:()=>void}){const title=kind==="next"?"El Capítulo 2 será el próximo":kind==="missing"?"¿Tu pantalla se ve diferente?":"Ayuda para este paso";return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm sm:items-center" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-[#0a1421] p-7"><button onClick={close} className="float-right grid size-11 place-items-center rounded-full bg-white/5"><X/></button><CircleHelp className="text-cyan-300"/><h2 className="mt-6 text-2xl font-semibold">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-400">{kind==="next"?"Todavía no enseñaremos a crear ni importar una wallet. Prepararemos ese capítulo después de aprobar esta presentación.":kind==="missing"?"La tienda puede cambiar ligeramente según tu celular o país. Comprueba que estás en Google Play y usa la ficha oficial.":"Lía recibirá el capítulo y el paso exacto para ayudarte sin pedir datos sensibles."}</p>{step&&<p className="mt-4 rounded-xl bg-white/[.04] p-3 text-xs text-slate-300">Capítulo 1 · Paso {steps.indexOf(step)+1}/{steps.length} · {step.title}</p>}<a href={PLAY_URL} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-cyan-300">Abrir ficha oficial <ExternalLink size={14}/></a><button onClick={close} className="mt-6 min-h-12 w-full rounded-xl bg-white text-xs font-black text-slate-950">ENTENDIDO</button></div></div>}
