import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MediaProductState, ProductWorkspace } from "../../domain/product";
const dataDirectory = path.join(process.cwd(), ".data", "media-intelligence"), dataFile = path.join(dataDirectory, "product.json");
let transaction = Promise.resolve();
const now = () => new Date().toISOString();
const owner = { id: "dev_user", name: "Arquitecta LAEX", email: "dev@laex.local", role: "owner" as const, status: "active" as const, overrides: {} };
function workspace(id: string, name: string, kind: ProductWorkspace["kind"], color: string): ProductWorkspace { return { id, name, kind, color, description: `Centro editorial independiente de ${name}.`, audience: "Comunidad LAEX", objectives: ["Educar", "Aumentar alcance"], tone: "Claro y visionario", locale: "es", timezone: "America/Santiago", status: "active", members: [owner], invitations: [], contents: [{ id: `${id}_content_1`, title: "Todo comienza con una decisión", description: "Pieza base para demostrar el flujo editorial.", sourceType: "manual", status: "in_review", authorId: owner.id, confidence: 92, risks: ["Validar cifras antes de publicar"], keywords: ["decisión", "LAEX", "futuro"], categories: ["Educación"], versions: [{ number: 1, title: "Todo comienza con una decisión", body: "Cada avance sostenible comienza con una decisión informada.", author: owner.name, createdAt: now(), note: "Versión inicial" }], approvedVersion: null, reviewReason: null, updatedAt: now() }], campaigns: [{ id: `${id}_campaign_1`, title: "Decisiones que construyen futuro", objective: "Educación", audience: "Emprendedores", contentIds: [`${id}_content_1`], platforms: ["youtube", "instagram"], status: "in_review", scheduledAt: null, publicationStatus: "idle", idempotencyKey: null }], channels: ["youtube", "instagram", "facebook", "tiktok"].map((platform) => ({ id: `${id}_${platform}`, platform: platform as ProductWorkspace["channels"][number]["platform"], status: "simulated" as const, label: `${platform} · Simulación`, lastSyncAt: null })), audit: [{ id: randomUUID(), workspaceId: id, actorId: owner.id, action: "workspace.seeded", resource: "workspace", outcome: "success", at: now(), detail: "Datos locales demostrativos" }] }; }
function seed(): MediaProductState { const workspaces = [workspace("ws_laex", "LAEX Media Lab", "company", "#67E8F9"), workspace("ws_academy", "Academia Global", "academy", "#A78BFA")]; return { revision: 1, activeWorkspaceId: workspaces[0].id, workspaces }; }
async function persist(state: MediaProductState) { await mkdir(dataDirectory, { recursive: true }); const temporary = `${dataFile}.${process.pid}.tmp`; await writeFile(temporary, JSON.stringify(state, null, 2), "utf8"); await rename(temporary, dataFile); }
async function readState(): Promise<MediaProductState> { try { return JSON.parse(await readFile(dataFile, "utf8")) as MediaProductState; } catch { const initial = seed(); await persist(initial); return initial; } }
export async function getLocalProductState() { return structuredClone(await readState()); }
export function updateLocalProductState(expectedRevision: number, mutate: (state: MediaProductState) => void): Promise<MediaProductState> { const result = transaction.then(async () => { const state = await readState(); if (state.revision !== expectedRevision) throw new Error("revision_conflict"); mutate(state); state.revision += 1; await persist(state); return structuredClone(state); }); transaction = result.then(() => undefined, () => undefined); return result; }
