import type{CatalogItem,InventoryParticipation,LabIdea}from"../domain/types";
export const catalog:CatalogItem[]=[
{id:"epson-l4260",brand:"Epson",model:"EcoTank L4260",category:"Multifuncional",technology:"Tanque de tinta",useCase:"Hogar y oficina",features:["Imprime, copia y escanea","Wi‑Fi","Dúplex automático"],status:"Catálogo demostrativo",sourceUrl:"https://epson.cl/Soporte/Impresoras/Impresoras-multifuncionales/Epson-L/Epson-L4260/s/SPT_C11CJ63301"},
{id:"canon-g3170",brand:"Canon",model:"PIXMA G3170",category:"Multifuncional",technology:"Tanque de tinta",useCase:"Hogar y emprendimiento",features:["Imprime, copia y escanea","Conectividad inalámbrica","Sistema de tinta continua"],status:"Catálogo demostrativo",sourceUrl:"https://www.canon.cl/comunicado-de-producto/pixma-g3170"},
{id:"hp-smart-tank-580",brand:"HP",model:"Smart Tank 580",category:"Multifuncional",technology:"Tanque de tinta",useCase:"Estudio y hogar",features:["Imprime, copia y escanea","Wi‑Fi","USB"],status:"Catálogo demostrativo",sourceUrl:"https://www.hp.com/cl-es/printers/smart-tank.html"},
{id:"hp-laserjet-1602w",brand:"HP",model:"LaserJet Tank MFP 1602w",category:"Multifuncional",technology:"Láser monocromática",useCase:"Oficina",features:["Hasta 22 ppm","Wi‑Fi doble banda","Tóner recargable"],status:"Catálogo demostrativo",sourceUrl:"https://www.hp.com/cl-es/printers/laserjet-tank.html"},
{id:"brother-t530dw",brand:"Brother",model:"DCP‑T530DW",category:"Multifuncional",technology:"Tanque de tinta",useCase:"Hogar y pequeña oficina",features:["Dúplex automático","Wi‑Fi doble banda","Bandeja de 150 hojas"],status:"Catálogo demostrativo",sourceUrl:"https://www.brother.cl/-/media/brother/product-catalog-media/documents/2025/06/09/19/00/ficha-tcnica-dcp-t530dw-1.pdf"}
];
export const participations:InventoryParticipation[]=[{id:"inv-demo-01",itemId:"hp-laserjet-1602w",itemLabel:"HP LaserJet Tank MFP 1602w",currency:"CLP",requiredAmount:285000,offeredPercentage:8,status:"En revisión",disclosures:["Ejemplo de experiencia; no constituye una oferta vigente.","LF-PRINTER y LAEX no reciben fondos mediante esta interfaz.","Toda liberación de capital o rendimiento exige revisión humana administrativa."],history:[{at:"2026-08-03",action:"Ficha creada para evaluación interna",actorRole:"Administrador"},{at:"2026-08-04",action:"Enviada a revisión documental",actorRole:"Revisor"}]}];
export const labIdeas:LabIdea[]=[{id:"lab-001",title:"Pasaporte técnico de equipos",problem:"El historial de mantenimiento suele fragmentarse entre documentos y mensajes.",hypothesis:"Un registro portable puede mejorar diagnóstico, confianza y valor de reventa.",status:"Documentación",owners:["CEO","Arquitecta","Ingeniero"],decisionLog:[{at:"2026-08-04",decision:"Documentar alcance antes de prototipar."}]}];
