import type{CatalogItem,InventoryParticipation,LabIdea}from'../domain/types';
const common={brand:'Epson' as const,category:'Multifuncional' as const,status:'Disponible' as const};
const product=(id:string,family:CatalogItem['family'],model:string,technology:string,useCase:string,features:string[],sourceUrl:string,systemInstalled=true):CatalogItem=>({...common,id,family,model,technology,useCase,features,sourceUrl,systemInstalled,imageUrl:`/assets/lf-printer/official/printers/${id}-hero.webp`,imageAlt:`Impresora Epson ${family} ${model}`});
export const catalog:CatalogItem[]=[
product('wf-4830','WorkForce Pro','WF-4830','PrecisionCore Heat-Free','oficinas de alto volumen',['Impresión, copia, escaneo y fax dúplex','ADF de 50 hojas','Doble bandeja: 500 hojas'],'https://epson.com/For-Work/Printers/Inkjet/WorkForce-Pro-WF-4830-Wireless-All-in-One-Printer/p/C11CJ05201'),
product('wf-4833','WorkForce Pro','WF-4833','PrecisionCore Heat-Free','oficinas y equipos de trabajo',['Impresión de alto rendimiento','Dúplex automático','Wi-Fi y pantalla táctil'],'https://epson.com/Support/Printers/All-In-Ones/WorkForce-Series/Epson-WorkForce-Pro-WF-4833/s/SPT_C11CJ05203'),
product('wf-4834','WorkForce Pro','WF-4834','PrecisionCore Heat-Free','negocios con flujo documental continuo',['Impresión rápida a color','Alimentador automático','Wi-Fi y Ethernet'],'https://epson.com/Support/Printers/All-In-Ones/WorkForce-Series/Epson-WorkForce-Pro-WF-4834/s/SPT_C11CJ05204'),
product('wf-7820','WorkForce Pro','WF-7820','Formato ancho PrecisionCore','estudios creativos y documentos de gran tamaño',['Impresión hasta 13 × 19 pulgadas','Escaneo hasta 11 × 17 pulgadas','Dúplex y ADF automáticos'],'https://epson.com/For-Work/Printers/Inkjet/WorkForce-Pro-WF-7820-Wireless-Wide-format-All-in-One-Printer/p/C11CH78201'),
product('wf-7840','WorkForce Pro','WF-7840','Formato ancho PrecisionCore','producción empresarial de gran formato',['Impresión hasta 13 × 19 pulgadas','Dos bandejas de 250 hojas','Pantalla táctil de 4.3 pulgadas'],'https://epson.com/For-Work/Printers/Inkjet/WorkForce-Pro-WF-7840-Wireless-Wide-format-All-in-One-Printer/p/C11CH67201'),
product('xp-4200','Expression Home','XP-4200','Micro Piezo Heat-Free','hogar, estudios y tareas diarias',['Impresión, copia y escaneo','Dúplex automático','Wi-Fi y pantalla a color'],'https://epson.com/For-Home/Printers/Inkjet/Expression-Home-XP-4200-Wireless-Color-Inkjet-All-in-One-Printer-with-Scan-and-Copy/p/C11CK65201'),
product('xp-4205','Expression Home','XP-4205','Micro Piezo Heat-Free','hogar y pequeños espacios',['Diseño compacto multifuncional','Impresión móvil inalámbrica','Fotografías sin bordes'],'https://epson.com/Support/Printers/All-In-Ones/XP-Series/Epson-XP-4205/s/SPT_C11CK65205'),
{...product('l3250','EcoTank','L3250','EcoTank de fábrica','hogar, estudio y emprendimientos',['Tanques frontales de alta capacidad','Impresión, copia y escaneo','Wi-Fi Direct y Smart Panel'],'https://epson.com/Support/Printers/All-In-Ones/L-Series/Epson-L3250/s/SPT_C11CJ67301',false),status:'Consultar disponibilidad'}
];
export const participations:InventoryParticipation[]=[{id:'inv-demo-01',itemId:'wf-4830',itemLabel:'Epson WorkForce Pro WF-4830',currency:'CLP',requiredAmount:285000,offeredPercentage:8,status:'En revisión',disclosures:['Ejemplo conceptual'],history:[{at:'2026-08-03',action:'Ficha creada',actorRole:'Administrador'}]}];
export const labIdeas:LabIdea[]=[{id:'lab-001',title:'Pasaporte técnico de equipos',problem:'El historial suele fragmentarse.',hypothesis:'Un registro portable mejora diagnóstico y confianza.',status:'Documentación',owners:['CEO','Arquitecta','Ingeniero'],decisionLog:[{at:'2026-08-04',decision:'Documentar alcance.'}]}];
