import { createHash,randomUUID } from "node:crypto";
import { copyFileSync,mkdirSync,readFileSync,statSync,writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CompanyId,UserId } from "../domain/types";
import type { ChapterTwoState,ChapterTwoStore } from "../chapter-two/types";
import type { BusinessIdentity } from "../server/BusinessIdentity";

type ObservableStore=ChapterTwoStore&{operationalStatus?:()=>Promise<{database:Record<string,unknown>;migrations:unknown[];backups:unknown[]}>};
export class PlatformOperationsService{
  constructor(private readonly store:ChapterTwoStore,private readonly identity:BusinessIdentity,private readonly now:()=>Date=()=>new Date(),private readonly id:()=>string=randomUUID){}
  async health(companyId:CompanyId){const state=await this.store.snapshot(),company=state.platformCompanies.find(c=>c.id===companyId);if(!company)throw new Error("company_not_found");const sessions=state.businessSessions.filter(s=>s.companyId===companyId),active=sessions.filter(s=>s.status==="active"&&new Date(s.expiresAt).getTime()>Date.now()),live=await (this.store as ObservableStore).operationalStatus?.();return{company:{id:company.id,name:company.name,status:company.status,version:company.version??"1.0.0",lastAccessAt:company.lastAccessAt??null,modules:company.enabledModules,domains:state.platformDomains.filter(d=>d.companyId===companyId)},users:{total:state.memberships.filter(m=>m.companyId===companyId).length,active:state.memberships.filter(m=>m.companyId===companyId&&m.status==="active").length},sessions:{active:active.length,total:sessions.length},database:live?.database??{status:"healthy",engine:"sqlite-durable",isolation:"tenant-company"},migrations:live?.migrations??state.migrationRecords,backups:live?.backups??state.backupRecords.filter(b=>b.companyId===companyId||!b.companyId),integrations:{dgii:"disabled",externalAi:"not-configured",payments:"not-configured",commerce:"not-configured"},errors:state.platformErrors.filter(e=>e.companyId===companyId).slice(-10),services:{businessEngine:"healthy",identity:"healthy",audit:"healthy",assistants:"demonstrative-local"},storage:{status:"healthy",provider:process.env.BUSINESS_DATABASE_URL?"postgresql":"local-durable",usedBytes:"not-configured"},support:state.supportGrants.filter(g=>g.companyId===companyId).slice(-10)}}
  async createBackup(companyId?:CompanyId){const at=this.now(),id=this.id(),directory=process.env.BUSINESS_BACKUP_DIRECTORY??join(process.cwd(),".data",process.env.BUSINESS_DATABASE_URL?"postgres-backups":"backups");mkdirSync(directory,{recursive:true});if(process.env.BUSINESS_DATABASE_URL){const state=await this.store.snapshot(),company=companyId?state.platformCompanies.find(c=>c.id===companyId):undefined;if(companyId&&!company)throw new Error("company_not_found");const scoped=company?Object.fromEntries(Object.entries(state).map(([key,value])=>[key,Array.isArray(value)?value.filter(item=>!(item&&typeof item==="object"&&"companyId" in item)||(item as {companyId?:string}).companyId===company.id):value])):state,body=JSON.stringify({format:"laex-company-logical-v1",createdAt:at.toISOString(),tenantId:company?.tenantId,companyId,payload:scoped}),target=join(directory,`${at.toISOString().replace(/[:.]/g,"-")}-${companyId??"platform"}.json`);writeFileSync(target,body,{encoding:"utf8",mode:0o600});const checksum=createHash("sha256").update(body).digest("hex"),record:ChapterTwoState["backupRecords"][number]={id,tenantId:company?.tenantId,companyId,kind:"manual",status:"completed",createdAt:at.toISOString(),completedAt:this.now().toISOString(),location:target,sizeBytes:Buffer.byteLength(body),checksum,restoreTestStatus:"not-tested"};await this.store.transact(s=>s.backupRecords.push(record));return record}const source=process.env.BUSINESS_DATABASE_PATH??join(process.cwd(),".data","business-engine.sqlite"),target=join(directory,`${at.toISOString().replace(/[:.]/g,"-")}-${companyId??"platform"}.sqlite`);return this.store.transact(state=>{const company=companyId?state.platformCompanies.find(c=>c.id===companyId):undefined;if(companyId&&!company)throw new Error("company_not_found");const record:ChapterTwoState["backupRecords"][number]={id,tenantId:company?.tenantId,companyId,kind:"manual",status:"pending",createdAt:at.toISOString(),restoreTestStatus:"not-tested"};state.backupRecords.push(record);try{copyFileSync(source,target);Object.assign(record,{status:"completed" as const,completedAt:this.now().toISOString(),location:target,sizeBytes:statSync(target).size,checksum:createHash("sha256").update(readFileSync(target)).digest("hex")})}catch{record.status="failed"}return record})}
  async issueSupport(companyId:CompanyId,input:{reason:string;durationMinutes:number;issuedBy:string}){if(!input.reason.trim())throw new Error("support_reason_required");const minutes=Math.min(Math.max(input.durationMinutes,5),60),now=this.now(),state=await this.store.snapshot(),company=state.platformCompanies.find(c=>c.id===companyId);if(!company)throw new Error("company_not_found");const grant={id:this.id(),tenantId:company.tenantId,companyId:company.id,reason:input.reason.trim(),capabilities:["dashboard.view","support.diagnose"] as const,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+minutes*60000).toISOString(),status:"active" as const,issuedBy:input.issuedBy,sensitiveActionsEnabled:false};await this.store.transact(s=>{s.supportGrants.push(grant);s.audit.push({id:this.id(),tenantId:company.tenantId,companyId:company.id,userId:input.issuedBy as UserId,action:"support.granted",entityId:grant.id,traceId:this.id(),at:now.toISOString()})});const token=await this.identity.issueSupportSession({tenantId:company.tenantId,companyId:company.id,grantId:grant.id,expiresAt:grant.expiresAt});return{grant,token,slug:company.slug}}
  async revokeSupport(grantId:string,revokedBy:string){return this.store.transact(state=>{const grant=state.supportGrants.find(g=>g.id===grantId);if(!grant)throw new Error("support_grant_not_found");grant.status="revoked";grant.revokedAt=this.now().toISOString();state.audit.push({id:this.id(),tenantId:grant.tenantId,companyId:grant.companyId,userId:revokedBy as UserId,action:"support.revoked",entityId:grant.id,traceId:this.id(),at:this.now().toISOString()});for(const session of state.businessSessions)if(session.supportGrantId===grantId&&session.status==="active"){session.status="revoked";session.revokedAt=this.now().toISOString();session.revokedBy=revokedBy;session.revokeReason="support_revoked"}return{revoked:true}})}
}
