import "server-only";
import { getBusinessRuntime } from "../../server/runtime";
import { CompanyProvisioningService } from "../../platform/CompanyProvisioningService";
import { ROLE_POLICIES, type BusinessRoleName } from "../../chapter-five/RolePolicy";
import { LF_PRINTER_PILOT } from "./runtime";
import type { CompanyId, TenantId, UserId, WarehouseId } from "../../domain/types";

let ready: Promise<void> | undefined;
export const CHAPTER_FOUR_ACCESS={lfPrinter:{slug:"lf-printer",email:"owner@lfprinter.local",password:"LF-Owner-2026!"},demoB:{slug:"empresa-demo-b",email:"owner@demob.local",password:"DemoB-Owner-2026!"},demoCashier:{email:"cashier@demob.local",password:"DemoB-Cashier-2026!"},demoInventory:{email:"inventory@demob.local",password:"DemoB-Inventory-2026!"},demoWorkshop:{email:"workshop@demob.local",password:"DemoB-Workshop-2026!"}}as const;

export function ensureChapterFourAuditCompanies(){ready??=(async()=>{const runtime=getBusinessRuntime(),service=new CompanyProvisioningService(runtime.store,runtime.businessIdentity);await service.provision({tenantId:LF_PRINTER_PILOT.tenantId,companyId:LF_PRINTER_PILOT.companyId,ownerUserId:"user-lf-business-owner" as UserId,warehouseId:LF_PRINTER_PILOT.warehouseId,name:"LF-PRINTER",legalName:"LF Printer, S.R.L.",slug:CHAPTER_FOUR_ACCESS.lfPrinter.slug,hostname:"lf-printer.localhost",ownerEmail:CHAPTER_FOUR_ACCESS.lfPrinter.email,ownerPassword:CHAPTER_FOUR_ACCESS.lfPrinter.password,phone:"849-526-1212",currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#0b7285",enabledModules:["dashboard","customers","reception","workshop","inventory","purchases","quotes","invoices","pos","cash","history","assistants","settings"],branchName:"Sucursal principal",warehouseName:"Almacén principal"});await service.provision({tenantId:"tenant-demo-b" as TenantId,companyId:"company-demo-b" as CompanyId,ownerUserId:"user-demo-b-owner" as UserId,warehouseId:"warehouse-demo-b-main" as WarehouseId,name:"Empresa Demo B",legalName:"Empresa Demo B, S.R.L.",slug:CHAPTER_FOUR_ACCESS.demoB.slug,hostname:"empresa-demo-b.localhost",ownerEmail:CHAPTER_FOUR_ACCESS.demoB.email,ownerPassword:CHAPTER_FOUR_ACCESS.demoB.password,currency:"DOP",timezone:"America/Santo_Domingo",primaryColor:"#6d4aff",enabledModules:["dashboard","customers","reception","workshop","inventory","purchases","quotes","invoices","pos","cash","history","assistants","settings"],branchName:"Oficina principal",warehouseName:"Almacén Demo B"});
const roleIds={}as Record<string,string>;await runtime.store.transact(state=>{for(const[name,capabilities]of Object.entries(ROLE_POLICIES)){let role=state.roles.find(r=>r.companyId==="company-demo-b"&&r.name===name);if(!role){role={id:`role-demo-b-${name.toLowerCase()}`,tenantId:"tenant-demo-b" as TenantId,companyId:"company-demo-b" as CompanyId,name,capabilities,system:true,status:"active"};state.roles.push(role);}else role.capabilities=capabilities;roleIds[name]=role.id;}if(!state.products.some(p=>p.id===LF_PRINTER_PILOT.productId))state.products.push({id:LF_PRINTER_PILOT.productId,tenantId:LF_PRINTER_PILOT.tenantId,companyId:LF_PRINTER_PILOT.companyId,sku:"T544-BK",barcode:"7861234567890",name:"Tinta Epson T544 Negro",priceMinor:65000,costMinor:40000,taxRate:18,taxIncluded:true,unit:"unidad",minimumStock:10,status:"active",publishable:false,visibility:"hidden",commerceStatus:"available"});if(!state.inventory.some(i=>i.companyId===LF_PRINTER_PILOT.companyId&&i.sourceId==="pilot-opening"))state.inventory.push({id:"inventory-lf-business-opening",tenantId:LF_PRINTER_PILOT.tenantId,companyId:LF_PRINTER_PILOT.companyId,warehouseId:LF_PRINTER_PILOT.warehouseId,productId:LF_PRINTER_PILOT.productId,delta:100,kind:"purchase",sourceId:"pilot-opening"});if(!state.products.some(p=>p.id==="product-demo-b-paper"))state.products.push({id:"product-demo-b-paper",tenantId:"tenant-demo-b" as TenantId,companyId:"company-demo-b" as CompanyId,sku:"PAPER-A4-B",barcode:"7400000000002",name:"Papel A4 Empresa B",priceMinor:35000,costMinor:25000,taxRate:18,taxIncluded:true,unit:"resma",minimumStock:5,status:"active",publishable:false,visibility:"hidden",commerceStatus:"available"});if(!state.inventory.some(i=>i.companyId==="company-demo-b"&&i.sourceId==="demo-b-opening"))state.inventory.push({id:"inventory-demo-b-opening",tenantId:"tenant-demo-b" as TenantId,companyId:"company-demo-b" as CompanyId,warehouseId:"warehouse-demo-b-main" as WarehouseId,productId:"product-demo-b-paper",delta:25,kind:"purchase",sourceId:"demo-b-opening"});if(!state.migrationRecords.some(m=>m.version==="0001_saas_core"))state.migrationRecords.push({version:"0001_saas_core",appliedAt:new Date().toISOString(),status:"applied"});});
const branchIds=["branch-demo-b-main"];const accounts:Array<{key:"demoCashier"|"demoInventory"|"demoWorkshop";name:string;role:BusinessRoleName}>=[{key:"demoCashier",name:"Caja Demo",role:"Cajero"},{key:"demoInventory",name:"Inventario Demo",role:"Inventario"},{key:"demoWorkshop",name:"Taller Demo",role:"Taller"}];const state=await runtime.store.snapshot(),branch=state.branches.find(b=>b.companyId==="company-demo-b");for(const account of accounts)await runtime.businessIdentity.provisionAccount({email:CHAPTER_FOUR_ACCESS[account.key].email,password:CHAPTER_FOUR_ACCESS[account.key].password,tenantId:"tenant-demo-b" as TenantId,companyId:"company-demo-b" as CompanyId,capabilities:ROLE_POLICIES[account.role],name:account.name,roleId:roleIds[account.role],branchIds:branch?[branch.id]:branchIds});})();return ready;}
